### ISSUE TITLE
Stats stopped updating

### ISSUE THREAD

**Issue by didier91380** [Codewars/codewars.com#1329] opened 2018-03-15 16:29 UTC
My stats stopped updating for some time now. My user name is didierj.

**Comment by anter69** [comment] 2018-03-15 20:04
Same issues: #1326 #1330

**Comment by kazk** [comment] 2018-03-16 18:01
This was caused by the queue for the background jobs being backed up. I've let @jhoffner know about this yesterday and he increased the number of servers processing the jobs. It may take some time to catch up.

**Comment by kazk** [comment] 2018-03-16 18:52
Closing this as the queue is no longer backed up.

**Closed by kazk** 2018-03-16 18:52 UTC
Labels: kind/bug
