### ISSUE TITLE
Array has no method .find

### ISSUE THREAD

**Issue by umar-muneer** [Codewars/codewars.com#204] opened 2015-11-08 08:59 UTC
Whenever i try to call .find method on an array, i get the following error 

TypeError: Object has no method 'find'

**Comment by hyukchan** [comment] 2016-05-10 13:40
I have the same issue as well

**Comment by kazk** [comment] 2017-03-28 01:02
Confirmed this using Node v0.10.33/Babel, but closing because Node v6 is available now.
We should also start looking into removing Node v0.10.x as it reached end-of-life status on 2016-10-31. [nodejs/LTS](https://github.com/nodejs/LTS)

**Closed by kazk** 2017-03-28 01:02 UTC
Labels: enhancement
