### ISSUE TITLE
Duplicated kata in My Profile -> Kata sections

### ISSUE THREAD

**Issue by davemus** [codewars/codewars.com#2235] opened 2020-08-24 13:13 UTC
#### Describe the bug

I have a kata with the same name twice in different kata sections in My Profile - both 'Completed' and 'Unfinished'. Opening both links leads me to completed one.

#### How To Reproduce

On my account it is reproduced very simply: Open 'View Profile' -> 'Kata' check 'Completed' and 'Unfinished' parts.

Not sure how to reproduce situation like this. I would rather try a few combinations of starting kata on few languages, then completing; having few windows open with same kata, while completing kata in one; updating kata with issue, while somebody is completing and other race condition dependent situations.

#### Expected Behavior

I expect that completed kata won't be shown in 'Unfinished' section.

#### Contexts

- Codewars username: davemus
- OS: Reproduced both on Windows 10 Home and Ubuntu 18 - not OS related
- Browser: reproduced on mobile Chrome, Ubuntu 18 Chrome and Win10 Mozilla Firefox - not browser related

#### Screenshoots

Watch to Simple Cluster Analysis task

![bug1](https://user-images.githubusercontent.com/36568373/91047941-8d794400-e623-11ea-9cc1-ed7312cbe13c.png)

![bug2](https://user-images.githubusercontent.com/36568373/91047958-9407bb80-e623-11ea-870c-23d47d415d76.png)

![bug4](https://user-images.githubusercontent.com/36568373/91048990-29f01600-e625-11ea-8433-8b9fba9c4e00.png)

#### BTW

I am okay with trying to fix it by myself, if somebody link repository here and give me access.

**Comment by kazk** [comment] 2020-08-25 20:25
Closing as duplicate of #1966.

**Closed by kazk** 2020-08-25 20:25 UTC

**Comment by davemus** [comment] 2020-08-27 20:19
Sry for duplicate
