### ISSUE TITLE
Serious bugs with accumulation of honour

### ISSUE THREAD

**Issue by DmitryPrusov** [Codewars/codewars.com#1875] opened 2019-07-12 09:48 UTC
1) I remember that some time ago power users wrote that they have got momentary increase of an honour by several thousand of points. I also encountered this: at the current moment my honour is by  several thousand points more than it should be. You can check it on my site events: https://www.codewars.com/users/dileader/site-events
The reason is looks that at some point I have completed a kata without voting it. Then some time later (couple of months) I again encountered it - voted - and got sudden increase of honour in the number of ALL voted katas at the moment of first completion of kata couple of months ago.

2) Second problem which the reason of getting extra honour is that currently something like after completion of every 10-20 kata, instead of getting redirected to the solutions page you a) get the points of completed kata 2)  being redirected to the page which shows that 
"Solutions have been withheld
Since you have not yet solved this kata we have hidden the solutions from you. If you choose to view the solutions you will forfeit your eligibility to earn honor/rank progress for this kata."

So you just again submit that kata and get thus 2*x points

**Comment by error256** [comment] 2019-07-12 12:08
1. #1715
2. #1683 / #1592

**Comment by kazk** [comment] 2019-07-12 21:20
Closing as duplicate of issues mentioned above.

**Closed by kazk** 2019-07-12 21:20 UTC
Labels: duplicate
