### ISSUE TITLE
I can't submit any katas I have done

### ISSUE THREAD

**Issue by SoftwareCreator** [Codewars/codewars.com#589] opened 2016-09-21 07:15 UTC
I have a Problem with every kata I tried. when I write the Code everything works testing also works but as soon as I want to submit nothing happens the submit Tests and random Tests are completed and correct but I can only press submit again to repeat the Tests but I won't get Points for this and it won't Count as passed help me please....

**Comment by tachyonlabs** [comment] 2016-09-26 06:02
Sometimes that happens to me, and then I copy my code, reload the page, paste my code back in, and then after I submit I get the message and the final submit button.

**Comment by drstonebraker** [comment] 2017-04-14 03:07
I've tried closing reloading, clearing cache, and reopening browser window entirely.  I still don't get the submit button... it just stays the "attempt" button, even when I pass everything.  I've used codewars for a while with my current browser (Chrome 57.0.2987.133), but this is the first day it has happened to me, and it happens every time

**Comment by crabtester** [comment] 2017-04-14 07:49
> Same issue here, chrome-dev 59 on 10.12.4

>  even when I pass everything.

do you guys also have borders of results section colored in red too?

**Comment by jojobando** [comment] 2017-04-14 08:09
> do you guys also have borders of results section colored in red too?

Yes, I get all "Test Passed" and red border.

**Comment by czechue** [comment] 2017-05-09 15:43
Hello,
same situation here.
Any possible solution?

**Comment by SoftwareCreator** [comment] 2017-05-09 15:57
@czechue well I solved it by using a different browser thats all or actually it might have been that it was blocked in our school network try chanign your network maybe

**Comment by kazk** [comment] 2017-05-31 05:32
Closing because the original issue seems to be resolved.
For those who had issues recently (2017-04), see #893.

Please let me know if the problem still exists.

**Closed by kazk** 2017-05-31 05:32 UTC
Labels: bug

**Comment by piotr276** [comment] 2018-06-14 20:52
I have this issue :/

**Comment by Kalyalev** [comment] 2018-06-29 14:38
Any chance anyone know how to resolve this problem? Using Firefox. Missing submit buttons on all katas

**Comment by kazk** [comment] 2018-06-29 17:15
@Kalyalev can you open a new issue describing your situation?

**Comment by WybeTuring** [comment] 2018-12-11 12:55
I keep having this situation where my tests are all validated and I can't even find the submit button.

**Comment by WybeTuring** [comment] 2018-12-11 13:01
I tried copying the code, refreshing the page and pasting it. It gave me the submit button. An alternative can be to code in your browser and only put in your final answer in the CodeWars editor.

**Comment by DominicYonce22** [comment] 2023-08-19 13:48
has anyone solved this issue, this is what i'm having now

_EDIT (hobovsky): hidden as a duplicate of https://github.com/codewars/codewars.com/issues/2010#issuecomment-1684948745_
