### ISSUE TITLE
The language dropdown in the kata editor may be too narrow to properly contain a long language name and a cross

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2521] opened 2021-11-05 17:00 UTC
![image](https://user-images.githubusercontent.com/31668662/140548468-9988e21e-b782-41ca-8c7e-97c1a681a7d9.png)

The `div` element takes up as much space as it is needed for the selected item with the `min_width` being set to `160px`. But that is not enough for other items in the dropdown which need more space than the `div` element provides. Either the `min_width` should be increased, or the `div` should have the same width as the widest item in the dropdown.

**Comment by Voileexperiments** [comment] 2022-01-07 09:03
This is a duplicate of #1310

**Comment by kazk** [comment] 2022-01-07 09:08
Thanks

**Closed by kazk** 2022-01-07 09:08 UTC
Labels: kind/bug, area/kata-editor
