### ISSUE TITLE
Unexpected filter behaivor

### ISSUE THREAD

**Issue by vladlozzi** [codewars/codewars.com#2804] opened 2022-09-10 05:29 UTC
[https://www.codewars.com/kata/57036f007fd72e3b77000023/discuss/ruby](url)

I have completed this kata in Ruby twice already more than one month ago, but it is placed in my "not trained on" list. Why?

**Comment by kazk** [comment] 2022-09-10 06:44
Closing as duplicate of #2748. I've fixed your data for that kata.

**Closed by kazk** 2022-09-10 06:44 UTC
