### ISSUE TITLE
/kata/:id/solutions/javascript returns 500 error "undefined method `user_id' for nil:NilClass"

### ISSUE THREAD

**Issue by YakovLittle** [Codewars/codewars.com#829] opened 2017-02-15 08:47 UTC
Hi I've catch 500 error after submitted my final version for kata https://www.codewars.com/kata/583989556754d6f4c700018e/solutions/javascript

![screen shot 2017-02-15 at 10 46 48](https://cloud.githubusercontent.com/assets/10956273/22966719/255897e8-f36c-11e6-9ba5-a7dcbee3173a.png)

**Comment by YakovLittle** [comment] 2017-02-15 09:10
but OK for https://www.codewars.com/kata/583989556754d6f4c700018e/solutions/python

**Comment by plasticbottle** [comment] 2017-05-04 11:24
#944 I should have googled better :( I have the same issue exactly as here

**Comment by luisgc91** [comment] 2017-05-25 00:34
I've experience the same problem with this kata https://www.codewars.com/kata/show-multiples-of-2-numbers-within-a-range
![github](https://cloud.githubusercontent.com/assets/7572760/26431119/b25af414-40f2-11e7-9ec3-2621a22f867f.JPG)

**Comment by kazk** [comment] 2020-03-13 02:48
Closing because a lot have changed since this issue was reported.
Please open a new issue if the problem is not fixed.

**Closed by kazk** 2020-03-13 02:48 UTC
Labels: issue/server-error-nil, kind/bug
