### ISSUE TITLE
Duplicate kata in resolved tab

### ISSUE THREAD

**Issue by side2** [Codewars/codewars.com#1691] opened 2019-01-23 07:48 UTC
#### Duplicate kata in completed tab
On user profile page in kata -> completed tab same kata appear twice and number of resolved point are doubled(for that kata).

#### To Reproduce

This issue pop up some times after i click on final submit button, but not always.

#### Expected Behavior

Expect to go on solutions page and list solutions, but show that "you did not resolved kata and can't view solutions" . On profile page kata is in resolved list, but when go on kata page seems that is not and train button is present.

#### Screenshots

![screenshot_2019-01-23 side2 codewars](https://user-images.githubusercontent.com/16884974/51590584-25b4c180-1ef3-11e9-919f-6d0921a85404.png)

#### Contexts
- OS: Debian
- Browser: Firefox 
- Browser Version: 60.4.0esr (64-bit)

**Comment by kazk** [comment] 2019-01-23 07:53
Closing as duplicate of #1592.

**Closed by kazk** 2019-01-23 07:53 UTC
Labels: duplicate, kind/bug
