### ISSUE TITLE
Kata author changed to someone else for no reasons!!!!!

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1539] opened 2018-08-22 09:16 UTC
Okay, so this _is_ my kata:

https://www.codewars.com/kata/multi-line-task-plus-plus-hello-world

But I just discovered that the kata author has changed to [someone else](https://www.codewars.com/users/Thang) for some reason. What's happening there?

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1bzn) by [Unito](https://www.unito.io)

**Comment by FArekkusu** [comment] 2018-08-22 09:42
Also happened with [this kata](https://www.codewars.com/kata/mumbling/discuss). The most recent comment says the user suddenly "became the author".

**Comment by g964** [comment] 2018-08-22 13:34
CW is becoming more and more weird!

**Comment by kazk** [comment] 2018-08-22 18:09
Thanks for reporting. We're looking into this. Please let us know if you find other affected kata.
Currently we have:
- [Multi Line Task++: Hello World](https://www.codewars.com/kata/multi-line-task-plus-plus-hello-world): author changed from `Voile` to `Thang`
- [Mumbling](https://www.codewars.com/kata/mumbling): author changed from `g964` to `mcneal`

**Comment by kazk** [comment] 2018-08-24 01:51
Thanks @Voileexperiments.
Your method found two more:

- [Alphabetized](https://codewars.com/kata/5970df092ef474680a0000c9): author changed from [kop](https://codewars.com/users/kop) to non existent user id
- [Highest and Lowest](https://codewars.com/kata/554b4ac871d6813a03000035): author changed from [Deantwo](https://codewars.com/users/Deantwo) to non existent user id

**Comment by Voileexperiments** [comment] 2018-10-21 02:51
Has this been investigated and has the cause been found? Weird bugs, manual errors, deliberate attacks (since *somebody* took that kata of mine and asked it directly on [codegolf.SE](https://codegolf.stackexchange.com)), or whatever?

If anything please at least fix these katas to point to their original authors first. (Also please make the honor is properly accounted for during the process.)

**Comment by kazk** [comment] 2018-10-21 19:11
We investigated but the cause was not found. There shouldn't be a way to change the kata author and it's most likely a weird bug.

I'll ask Jake about fixing the data since I'm still not familiar with how everything works together.

**Comment by jhoffner** [comment] 2018-10-22 21:15
I've updated the authors of these challenges. 

I have no idea yet what caused this. Codewars is stuck on a very old db driver which we are slowly making our way towards upgrading. I'm assuming it's an odd hiccup due to this, because no where except record creation does the author ever get modified AFAIKT. 

We will keep this bug open and continue to investigate. The priority is for us to try to get the codebase upgraded as resources become available.

**Comment by Voileexperiments** [comment] 2018-11-15 01:31
Apparently there are more katas that are affected by this:

https://www.codewars.com/kata/short-long-short

Also trying to visit the revisions page gives error `undefined method `username' for nil:NilClass`.

**Comment by kazk** [comment] 2018-11-15 01:33
That's Jake's kata when he originally made Codewars during a Hackathon. There's 3 more kata without authors and I'm assuming it's all his.

**Comment by kazk** [comment] 2022-12-13 07:25
Closing since the data is fixed and honor points got recalculated. Kata without authors are unrelated to this.

**Closed by kazk** 2022-12-13 07:25 UTC
Labels: kind/bug
