### ISSUE TITLE
Allies on dashboard doesn't list the logged in user

### ISSUE THREAD

**Issue by MarisaKirisame** [Codewars/codewars.com#1243] opened 2017-12-02 04:51 UTC
![_0oc f_1ypa9 m l f6w sh](https://user-images.githubusercontent.com/3397377/33511891-5d01fee0-d6d9-11e7-93ab-5084748d10ce.png)
![4w 6dv5 a q6sv1hwrz8u](https://user-images.githubusercontent.com/3397377/33511892-5d28d218-d6d9-11e7-9448-9617227deae4.png)

So I had disappeared from my clan! What happend? I am not ready to have my superpower yet!

**Comment by dhogeland** [comment] 2017-12-02 13:49
<img width="348" alt="untitled" src="https://user-images.githubusercontent.com/26265447/33516242-21ba0ea2-d735-11e7-93ec-8d828c848a13.png">
Same thing happened to me. This is a grab from the Home / Dashboard page, been like this for a couple of days now.

**Comment by MarisaKirisame** [comment] 2017-12-02 15:01
Wow, finally some sign of civilization! I have been alone for entire 10 hours...
Joking aside, I hate this change. Please at least give a setting to revert it.

**Comment by MagneticRegulus** [comment] 2017-12-04 04:12
Hi there,

Same thing happening to me:

![image](https://user-images.githubusercontent.com/21271865/33535992-1b3e759e-d916-11e7-9a20-6f4c4eaec531.png)

Is this actually a change?

**Note:** The 194 in the list is not me.

**Comment by Voileexperiments** [comment] 2017-12-04 04:39
This seems to be happening for *everyone*.

**Comment by anthony-crisp** [comment] 2017-12-04 15:30
Same here.

![2017-12-04](https://user-images.githubusercontent.com/20952384/33560549-f827d45a-d907-11e7-9302-51e5e9451834.png)

Any word on why this is happening?

**Comment by kazk** [comment] 2017-12-04 18:24
@jhoffner This is probably caused by changes made to fix #1220. See https://github.com/Codewars/codewars.com/issues/1220#issuecomment-345203852

**Comment by anter69** [comment] 2018-03-15 10:51
Seems to be totally legit: the list has the title **"Allies"** which implies that *you are not part of your allies*. 

Did you ever complain to Facebook that you do not appear on your "Friends" list?!

**Comment by Voileexperiments** [comment] 2018-03-15 11:01
The key point is, it wasn't like this before and this is an *unintended, breaking* change.

**Comment by anter69** [comment] 2018-03-15 11:54
I understand that it was different before, but probably *that* was wrong (or just different). Now it's clearly labeled as a list of allies, not the list of members of your clan.

**Comment by Voileexperiments** [comment] 2018-04-18 08:14
Still needs feedback from @jhoffner ;-)

**Comment by 1nF0rmed** [comment] 2018-05-06 16:27
Can we have a leader board for each clan @anter69, it would essentially compensate for the new change showing only all the allies.

**Comment by bradenstaudacher** [comment] 2018-12-23 20:13
Any feedback on the above @jhoffner?

**Comment by kazk** [comment] 2018-12-23 21:06
@bradenstaudacher I don't know if Jake intended or not, but it looks like a bug to me after looking at the code.
I'll look into it.

**Comment by kazk** [comment] 2018-12-23 22:41
Got this fixed on staging. I'll deploy it to `preview.codewars.com` later. Deploying to production will be after the holiday, maybe Wednesday. I'll close this issue when I do.

- "Allies" on `/dashboard` will include yourself. Think of this as mini leader board for honor points. You'll be always included, but if you have more than 100 allies then only the top 100 (excluding yourself) will be there. I'm assuming this limit was added to fix #1220 so I left it as is.
- `/users/:username/allies` lists users you follow that follows you and users with same clan name.

**Comment by kazk** [comment] 2018-12-28 19:39
The fix is deployed.

**Closed by kazk** 2018-12-28 19:39 UTC
Labels: kind/bug
