### ISSUE TITLE
Cannot delete my own kata

### ISSUE THREAD

**Issue by vlukyanets** [Codewars/codewars.com#1513] opened 2018-07-20 06:52 UTC
![image](https://user-images.githubusercontent.com/7885242/42987607-81167aca-8c02-11e8-9bb3-74de34bb4bed.png)

1. I created new kata
2. Made some changes, saved it
3. Try to delete

ER: Kata is deleted
AR: Kata deleting process is stuck

**Comment by FiveCrayFish973** [comment] 2018-07-21 09:05
CW server is usually too slow, try again a bit later and it ought to work out.

**Comment by vlukyanets** [comment] 2018-07-21 10:06
I tried five times, but always deleting process is stucked on the end of progress bar.
Could you find more information in server logs?

**Comment by vlukyanets** [comment] 2018-07-25 06:37
I didn't published my kata, just save

**Comment by kazk** [comment] 2018-08-24 08:18
Closing as duplicate of #1043

**Closed by kazk** 2018-08-24 08:18 UTC
