### ISSUE TITLE
I can't comment and give votes

### ISSUE THREAD

**Issue by wisniaboss2** [codewars/codewars.com#2297] opened 2021-01-09 10:33 UTC
**Describe the bug**
I can't add comments below kata's and also I can't give votes etc.
I can write it in textbox but when I am pressing "post" button nothing happen.
I checked that my account it's confirmed and for sure it is.

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by XRFXLP** [comment] 2021-01-09 10:38
Which kata?

**Comment by Blind4Basics** [comment] 2021-01-09 10:43
#2263 ?

**Comment by wisniaboss2** [comment] 2021-01-11 10:06
Unfortunatly in all of kata's. Whole comment panel it's not working. Like it's visible but when I want to give vote or post comment, nothing happens.

**Comment by kazk** [comment] 2021-01-11 10:27
Hi @wisniaboss2, can you list few kata you had the issue with? Even if it happened with "all" the ones you tried, knowing few specific ones can help to narrow the issue down.

**Comment by kazk** [comment] 2021-01-13 21:26
Closing as (assumed) duplicate of #2263.

**Closed by kazk** 2021-01-13 21:26 UTC
