### ISSUE TITLE
Codewars IDE does not show ATTEMPT button

### ISSUE THREAD

**Issue by javacommons** [Codewars/codewars.com#1735] opened 2019-02-16 21:15 UTC
#### Describe the bug
When PC monitor's resolution is 1280x1024 or 1280x720, within Codewars IDE "ATTEMPT" button cannot be or is hard to be pressed.
This problem occurs when the browser's window is maximized.
The workaround of this problem is not to maximize browser window; howver, if this problem is fixed even when a browser is maximized, it's nice.
The problem's screenshot is https://qiita-image-store.s3.amazonaws.com/0/140610/9437940f-e313-5bb4-6b89-6d39745ef756.png

#### To Reproduce

1. Set PC's monitor resolution to 1280x1024 or 1280x720
2. Maximize the browser's window (REQUIRED!)
3. Go to a kata page
4. Click on 'TRAIN' (or 'TRAIN AGAIN')

#### Expected Behavior

The ATTEMPT/SUBMIT FINAL button is shown on IDE correctly.

#### Screenshots

The problem's screenshot is https://qiita-image-store.s3.amazonaws.com/0/140610/9437940f-e313-5bb4-6b89-6d39745ef756.png

#### Contexts

- OS: Windows10 64bit
- Browser: chrome & firefox
- Browser Version:  chrome 72.0.3626.109 (Official Build) 32bit & firefox 65.0.1 64bit

![image](https://user-images.githubusercontent.com/21975837/52905256-f2a7e880-327a-11e9-9401-9378e52791db.png)

**Comment by Blind4Basics** [comment] 2019-02-17 09:40
Hi,

It's a known bug. The button can actually can be pressed (unless you're using a tactile device... x) ), it's just cumbersome. For your convenience: `ctrl+s`.

**Comment by Bubbler-4** [comment] 2019-02-17 12:49
Run sample tests = `ctrl+'`
Attempt/Submit final = `ctrl+Enter` (IIRC `ctrl+s` does this too)

**Comment by javacommons** [comment] 2019-02-17 14:14
If the browser window is not maximized those buttons could be shown.  This problems should be easy to be solved:

![image](https://user-images.githubusercontent.com/21975837/52914267-a9eb4080-3309-11e9-8c70-207badb1d9fb.png)

**Comment by javacommons** [comment] 2019-02-17 14:19
Blind4Basics & Bubbler-4, thanks for teaching me the keyboard shortcuts.
In the other hand, monitor resolution of 1280 pixel is popular even in 2019, so that I hope this problem to be fixed by Codewars.

**Comment by kazk** [comment] 2019-02-18 03:27
Yeah, this is a duplicate of #1214.

Looks like this happens when the width is between around 1280 and 1310 :man_facepalming: 

![peek 2019-02-17 19-18](https://user-images.githubusercontent.com/639336/52926226-bc558200-32e9-11e9-8b6e-e6babf0d41ce.gif)

**Comment by kazk** [comment] 2019-02-23 03:07
This should be fixed. I've adjusted few things and can't reproduce anymore, but please let me know if it's not.

**Closed by kazk** 2019-02-23 03:07 UTC
Labels: duplicate

**Comment by javacommons** [comment] 2019-02-24 11:40
I also can't reproduce this problem any more (1280x720 and 1280x1024 monitor reaolution, browser window maximized).
Thank you for fixing the problem so quickly, kazk.
