### ISSUE TITLE
You should prevent Kata names that resemble to some existing path [BUG]

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#1473] opened 2018-06-07 10:26 UTC
You can take this Kata as an example, you will never be able to get to it.

![image](https://user-images.githubusercontent.com/1063901/41094224-2c8f60e0-6a13-11e8-8273-5cf2a76d9c1e.png)

**Comment by Voileexperiments** [comment] 2018-06-07 11:06
Duplicate of #1086

**Closed** 2018-06-07 19:39 UTC
Labels: duplicate
