### ISSUE TITLE
kata confusion

### ISSUE THREAD

**Issue by kelihansen** [Codewars/codewars.com#1321] opened 2018-03-11 04:50 UTC
I had 60 kata, and I completed a yellow [challenge](https://www.codewars.com/kata/find-the-parity-outlier), which I though was worth 8. Now my total kata is displaying as 62, but my breakdown shows 40 + 20. Something isn't adding up.

**Comment by anter69** [comment] 2018-03-15 11:00
By "kata" I believe you refer to "honor". Anyway, there may be a delay sometimes before the values is updated. If you find that the problem is solved and doesn't reappear, you may close this issue.

**Comment by kazk** [comment] 2018-03-15 23:14
Closing as duplicate of #1329

**Closed by kazk** 2018-03-15 23:14 UTC
Labels: duplicate

**Comment by kelihansen** [comment] 2018-06-06 06:03
Ugh, yes "honor". Apologies!
