### ISSUE TITLE
Bug with getting additional honor

### ISSUE THREAD

**Issue by Elmavis** [Codewars/codewars.com#1779] opened 2019-03-23 21:02 UTC
Hello! I got a bug with the kata: https://www.codewars.com/kata/52bef5e3588c56132c0003bc After finishing and getting some honor, I couldn't see solutions, like I didn't post my solution earlier. I press button "train again", then publish my previous solution and get some more honor for the kata. So, good luck.

**Comment by kazk** [comment] 2019-03-23 21:15
Closing as duplicate of #1683

**Closed by kazk** 2019-03-23 21:15 UTC
Labels: duplicate
