### ISSUE TITLE
Prolog: Some kata translations doesn't appear when you want to (re)edit them

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#2017] opened 2020-01-28 08:04 UTC
For example it happens with:
<https://www.codewars.com/kata/5a057ec846d843c81a0000ad/edit/prolog>
<https://www.codewars.com/kata/5b1cd19fcd206af728000056/edit/prolog>

**Comment by kazk** [comment] 2020-01-28 18:56
Can you clarify what you mean by "doesn't appear"? Both of them shows the code when I try.

**Comment by g964** [comment] 2020-01-29 07:10
"Complete Solution", "Initial Solution", "Test Cases", "Example Test Cases" tabs are completely empty.
![2020-01-29 (2)](https://user-images.githubusercontent.com/12381126/73335077-aa58bf00-426e-11ea-841e-dcc18e09f9b3.png)

**Comment by kazk** [comment] 2020-01-29 19:01
Thanks, that's odd. I can't reproduce this and don't see anything in the error tracker.

Is anything printed to the browser console?

**Comment by kazk** [comment] 2020-01-29 19:02
Is it only Prolog?

**Comment by g964** [comment] 2020-01-30 07:53
As far as I can say, it is only Prolog.
For <https://www.codewars.com/kata/5a057ec846d843c81a0000ad/edit/prolog> 
I get:
```
Uncaught TypeError: ns.GetCommandSrc is not a function
    at GetCommandUrl (main.js?attr=tt_V9LNxkL39YmT-2R_EtAZcq15lfmSNYaHZLkcMEruBB4sCnhJCKrBlajDL3WJgXXKAh3_3CYq3VjfdfWbP1HvkgP8JSKDJHnIKtTk2LUjOFhWSrV0LZJpm3izeMWXl:988)
    at XMLHttpRequest.window.XMLHttpRequest.open (main.js?attr=tt_V9LNxkL39YmT-2R_EtAZcq15lfmSNYaHZLkcMEruBB4sCnhJCKrBlajDL3WJgXXKAh3_3CYq3VjfdfWbP1HvkgP8JSKDJHnIKtTk2LUjOFhWSrV0LZJpm3izeMWXl:1023)
    at XMLHttpRequest.open (breadcrumbs.ts:415)
    at d.exec (ably.min-0.8.js:272)
    at Function.w.Request (ably.min-0.8.js:276)
    at Function.f.postUri (ably.min-0.8.js:53)
    at h (ably.min-0.8.js:52)
    at Function.f.post (ably.min-0.8.js:52)
    at K (ably.min-0.8.js:208)
    at ably.min-0.8.js:209
    at ably.min-0.8.js:211
    at ably.min-0.8.js:211
    at b.getTimestamp (ably.min-0.8.js:212)
    at ably.min-0.8.js:211
    at b.createTokenRequest (ably.min-0.8.js:211)
    at n (ably.min-0.8.js:207)
    at b.requestToken (ably.min-0.8.js:209)
    at d (ably.min-0.8.js:214)
    at b._ensureValidAuthCredentials (ably.min-0.8.js:215)
    at b.authorise (ably.min-0.8.js:203)
    at b.startConnect (ably.min-0.8.js:153)
    at ably.min-0.8.js:152
    at sentryWrapped (helpers.ts:85)
sentry.io/api/116947/store/?sentry_key=dc778a04207f4100809dddc5f47d43fb&sentry_version=7:1 Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```
For the other kata there is nothing.
These things happen in Chrome, not with Firefox.

**Comment by Steffan153** [comment] 2020-01-30 13:30
I have Chrome too, and the editor for 1/n- Cycle in Prolog shows everything fine...
Still strange that you can't access it :/

**Comment by g964** [comment] 2020-01-30 13:59
I can access but the panels are empty:-(

**Comment by g964** [comment] 2020-02-10 16:15
Another Prolog Kata with blank tabs:
<https://www.codewars.com/kata/5539fecef69c483c5a000015/edit/prolog>

**Comment by kazk** [comment] 2020-04-01 22:03
@g964 I think I've found the root cause of all of your issues that others can't reproduce.

`Uncaught TypeError: ns.GetCommandSrc is not a function` is from Kaspersky that you mentioned in https://github.com/codewars/codewars.com/issues/2072#issuecomment-603282607.

https://stackoverflow.com/questions/59411562/kaspersky-internet-security-blocks-ajax-requests

It seems to do stuff depending on the URL so maybe `prolog` is causing something.

Can you try changing some settings? I don't know anything about it, so I have no idea what to do, but maybe https://stackoverflow.com/a/59945988

**Comment by kazk** [comment] 2020-07-28 03:15
Closing because it's not reproducible and it's most likely related to the Kaspersky (https://github.com/codewars/codewars.com/issues/2017#issuecomment-607512316).

**Closed by kazk** 2020-07-28 03:15 UTC
Labels: kind/bug, unreproducible
