### ISSUE TITLE
Redirect from codewars.com to www.codewars.com or vice versa

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#166] opened 2015-08-13 18:31 UTC
One gets redirected to www.codewars.com during sign-in. However, if one visits codewars.com afterwards, they won't be logged in anymore. An automatic redirection from codewars.com to www.codewars.com should fix this.

**Comment by brendanvos** [comment] 2017-03-29 19:19
According to
```curl -Uri "codewars.com" -MaximumRedirection 0``` on powershell
and
```curl -I codewars.com``` on linux bash
codewars.com correctly redirects to www.codewars.com

Looks like the issue is resolved and can be closed.

**Comment by jhoffner** [comment] 2017-03-29 19:20
Thanks

**Comment by bkaestner** [comment] 2017-03-30 08:11
Won't redirect with HTTPS, see #97.

**Comment by bkaestner** [comment] 2017-03-30 15:58
Still does not work. For example, if you open http://codewars.com/users/bkaes/followers, you won't get redirected to http://www.codewars.com/users/bkaes/followers

**Comment by bkaestner** [comment] 2017-03-30 15:59
Still does not work. For example, if you open http://codewars.com/users/bkaes/followers, you won't get redirected to http://www.codewars.com/users/bkaes/followers

@jhoffner should get reopened.

**Comment by kazk** [comment] 2017-03-30 16:21
Also, I found that when I visit non-www, I'm not logged in.

**Comment by jhoffner** [comment] 2017-03-30 16:21
Should be fixed now.

**Closed by jhoffner** 2017-03-30 16:21 UTC
