### ISSUE TITLE
"Final solution invalid. The solution should pass the provided test cases" but solution did pass the example tests

### ISSUE THREAD

**Issue by dpleshkov** [Codewars/codewars.com#771] opened 2017-01-11 00:02 UTC
I was fixing an issue on my <a href='https://www.codewars.com/kata/alien-accent'>Alien Accent</a> kata, but when I clicked the Re-Publish button, a message showed up saying my solution is invalid. I validated my solution and ran the example tests and it passed them though. Am I missing something?

**Comment by jhoffner** [comment] 2017-01-11 00:04
Duplicate of #770. I'm working on it now.

**Comment by DonaldKellett** [comment] 2017-01-11 00:04
#770

**Comment by brendanvos** [comment] 2017-04-03 00:42
@dpleshkov @jhoffner @kazk Can likely be closed as duplicate #770 was stated as fixed and closed by jhoffner.

**Comment by kazk** [comment] 2017-04-03 01:22
Closing this because this is a duplicate of #770 and it has been fixed.

**Closed by kazk** 2017-04-03 01:22 UTC
Labels: duplicate
