### ISSUE TITLE
Deleting a translation causing problem 

### ISSUE THREAD

**Issue by FiveCrayFish973** [Codewars/codewars.com#1542] opened 2018-08-23 12:22 UTC
Dunno if it's just me or what ever. But when I deleted a translation on my Kata (I was also translator) It wouldn't let me save or publish another translation I had been working on (on the same Kata) and neither will it let me create a new translation. It just keeps giving me an error whenever I try it.

**Comment by kazk** [comment] 2018-08-24 08:17
Closing as duplicate of #1268

**Closed by kazk** 2018-08-24 08:17 UTC
