### ISSUE TITLE
highlight.js: Some C# keywords are not highlighted

### ISSUE THREAD

**Issue by SlyBeetle** [Codewars/codewars.com#779] opened 2017-01-16 19:32 UTC
https://www.codewars.com/kata/reviews/5739964ef14baceffa0000c0/groups/587d19f3436f3c0f68001cba

Why?

**Comment by kazk** [comment] 2017-05-29 19:41
Duplicate of #206.

**Comment by kazk** [comment] 2017-09-13 17:55
Reopening this because #206 is the editor (CodeMirror) and this one is hilight.js issue.

**Comment by kazk** [comment] 2020-03-12 03:32
Fixed by replacing with CodeMirror (#1778)

**Closed by kazk** 2020-03-12 03:32 UTC
Labels: kind/bug
