### ISSUE TITLE
Firefox and Chrome get Crashed

### ISSUE THREAD

**Issue by Elite-stay** [Codewars/codewars.com#1599] opened 2018-10-18 04:02 UTC
#### Describe the bug
Some pages (e.g training setup) or sometimes when I click next kata, it crashes.

#### To Reproduce

1. Click on Training Setup
2. Crashed

#### Expected Behavior

Just open it.

#### Screenshots

![x7t6 15szxwmp_vuu6axbd](https://user-images.githubusercontent.com/9249009/47130722-8f5a7980-d2cd-11e8-881a-8b9f91ace671.png)

#### Contexts

Please complete the following information:

- OS: Windows 7
- Browser: Firefox and Chrome
- Browser Version: Lastest

**Comment by kazk** [comment] 2018-10-18 16:47
_Some_ Windows users are having this issue.
Closing as duplicate of #1157.

**Closed by kazk** 2018-10-18 16:47 UTC
Labels: duplicate
