### ISSUE TITLE
Users with < 300 honor can publish katas

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1532] opened 2018-08-16 08:44 UTC
In the last 2 days the user [ongp1347](https://www.codewars.com/users/ongp1347) managed to publish 2 katas despite having 10 and around 20 honor at the moment of publishing.

This happened because users can freely convert kumite to kata no matter what their current honor is. I've tested it out myself by [creating an account](https://www.codewars.com/users/123xyz123), starting a kumite and pressing `convert to kata` button freely, without any warning or errors. At the moment of publishing I had only 4 honor (before checking out the existence of this hole I completed another task except "multiply" to see if completing more katas unlocks `create kata` button).

Here's the [link to the kata](https://www.codewars.com/kata/5b7535031db5ce1ad400012e) I've made for quick access to it.

Related to #1457 .

**Comment by kazk** [comment] 2018-08-16 17:11
Thanks so much for this! I was trying to look into why this was happening yesterday and overlooked "convert to kata".

**Comment by kazk** [comment] 2018-08-18 00:13
This is fixed now. Thanks again for looking into the cause.

**Closed by kazk** 2018-08-18 00:13 UTC
Labels: kind/bug
