### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Leumas47-code** [Codewars/codewars.com#3229] opened 2024-05-27 19:13 UTC
**Describe the bug**
When I submitted my code for a kata, it gave the error. 

**To Reproduce**
def create_phone_number(n):
    if len(n) != 10:
        raise ValueError("List must contain exactly 10 numbers.")
    numbers_str = ''.join(map(str, n))
    formatted_phone_number = f"({numbers_str[:3]}) {numbers_str[3:6]}-{numbers_str[6:]}"
    return formatted_phone_number

**Expected behavior**
I expected it to say "code submitted!" or something similar then take me to the discussions page. 

**Screenshots**
![image](https://github.com/codewars/codewars.com/assets/139003339/7fc048c3-42da-4d78-8b18-670c9edbd14c)

**Browser**
I am on Chrome. 

**Additional context**
This has not happened for any other Kata I have done, ever.

**Comment by hobovsky** [comment] 2024-05-27 19:26
Duplicate of #3209

**Closed as completed by hobovsky** 2024-05-27 19:26 UTC
Labels: duplicate
