### ISSUE TITLE
Ability to Change Profile Picture

### ISSUE THREAD

**Issue by shli3** [Codewars/codewars.com#1821] opened 2019-05-16 00:06 UTC
#### Is your feature request related to a problem? Please describe.
I don't want my profile picture to be the same one I use for GitHub, but there doesn't seem to be an option to actually upload a picture

#### Describe the solution you'd like
I would like to be able to upload a picture as my profile.

#### Describe alternatives you've considered
...

#### Additional context
There is no button to add a profile picture, we should change that.

**Comment by anter69** [comment] 2019-05-24 20:52
same as #1398

**Comment by kazk** [comment] 2020-02-25 20:17
Closing as duplicate of #1398

**Closed by kazk** 2020-02-25 20:17 UTC
Labels: duplicate, kind/feature-request
