### ISSUE TITLE
Negative number of collections in one kata

### ISSUE THREAD

**Issue by canyone2015** [codewars/codewars.com#2308] opened 2021-01-18 16:26 UTC
Negative number of collections (`-1`) in one kata
https://www.codewars.com/kata/5912ded3f9f87fd271000120 (Guess the Word: Count Matching Letters, 7 kyu)
<img src="https://i.imgur.com/SMudXZf.png"></img>

**Comment by hobovsky** [comment] 2021-01-18 16:39
Duplicate of #2185

**Closed by hobovsky** 2021-01-18 16:39 UTC
