### ISSUE TITLE
Notification links return server error if the kata name is changed

### ISSUE THREAD

**Issue by aryan-firouzian** [Codewars/codewars.com#1074] opened 2017-08-14 13:09 UTC
Kata pages are accessible by links which include name of the kata in the url. When kata name changes (lets say after a suggestion) the previous notification still refers to previous address which returns server error.

**Comment by Voileexperiments** [comment] 2017-09-04 00:43
This is by design.

To post a link which wouldn't be broken by kata name change, you should post the object id link and not the slug link (i.e the link that resembles the title).

**Comment by jhoffner** [comment] 2017-09-06 22:55
The system is supposed to remember old slugs, so that's a bug.

**Comment by kazk** [comment] 2020-02-12 19:16
I've changed the notifications to use the ids instead so this should be fixed now.

**Closed by kazk** 2020-02-12 19:16 UTC
Labels: area/notification, kind/bug
