### ISSUE TITLE
Submission timeout

### ISSUE THREAD

**Issue by VladimirZD** [Codewars/codewars.com#65] opened 2015-05-11 20:12 UTC
Trying to sole few katas.
Getting "Submission timed out. Please try again." error..

I am trying to submit kata http://www.codewars.com/kata/54598e89cbae2ac001001135/train/javascript

**Comment by XcrossD** [comment] 2015-05-22 03:16
Got the same error here. I am sure my code is correct because I ran it on my local machine and it worked perfectly. Also, just to be sure I forfeited and inserted other people's solution code into the question, but got the error.
UPDATE:
I was going back and forth in my browser and the page refreshed for me (it didn't record my previous code). And then I tried again, but this time it worked. This is clearly a bug or a server issue.

**Comment by bkaes** [comment] 2015-05-22 10:37
Duplicate of #18

**Closed** 2015-05-22 21:48 UTC
