### ISSUE TITLE
Impossible to publish a translation : Publish button never appears

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#2072] opened 2020-03-18 14:07 UTC
#### Describe the bug
Impossible to publish a translation : Publish button never appears
#### To Reproduce

1. Go to a translation that you want to publish, fill all the tabs: solution, solution setup, test cases, sample test cases
2. Click on 'Save'
3. It says it saves
No publish button
#### Expected Behavior
Be able to publish

Please complete the following information:

- Codewars username (if account related): g964
- OS: win 10
- Browser: Chrome(Version 80.0.3987.149 (Build officiel) (64 bits)
 Firefox: 74.0 (64 bits)

**Comment by FArekkusu** [comment] 2020-03-18 14:22
A few translations were published today. You should probably mention the kata you couldn't translate.

**Comment by g964** [comment] 2020-03-18 14:39
Thanks for your post! It was a Fortran translation for "k-Primes".

**Comment by Steffan153** [comment] 2020-03-18 23:49
I see publish button for Fortran translation in k-Primes. Strange...

**Comment by g964** [comment] 2020-03-19 07:27
How can you see a publish button for Fortran translation when in <https://www.codewars.com/kata/5726f813c8dcebf5ed000a6b/translations> there is no Fortran translation? Please could you tell me how you can do that?

**Comment by g964** [comment] 2020-03-19 08:06
Another strange fact:
Usually if you "SAVE" without having filled the "Solution Setup" tab you have a warning saying that this tab can't be "blank" but now you have no such warning, only something (bottom left) saying "Saving...".

**Comment by g964** [comment] 2020-03-19 13:05
At last I have succeeded to do the translation of "k-primes"  with MS Edge (usually I don't use it; can it be I have a problem with Chrome and Firefox?)

**Comment by kazk** [comment] 2020-03-19 18:57
@g964 Do you have any browser extensions? Can you try without them?

I'm surprised that Chrome/Firefox doesn't work and MS Edge does. Maybe it's Windows only.

**Comment by Steffan153** [comment] 2020-03-19 19:03
@g964 I just made my own spam Fortran translation without actually publishing it.

**Comment by Blind4Basics** [comment] 2020-03-19 19:23
Hi,

Seems I just ran into the same kin of troubles...

Just published (tried to) a [translation ](https://www.codewars.com/kumite/5e726c7f4a04e4001ab3faaa?sel=5e726c7f4a04e4001ab3faaa) to the [switch bulbs kata](https://www.codewars.com/kata/5a96064cfd57777828000187/). got the tests runnig when cliking "publish", tests passed, then waiting... (note: cw's icon does never roll, today...), still wiating... nothing happens. Finally, some time after that: "kumite published with failed tests" appears (-> wut!!!?? :o ). 
When going to the translation itself, I see the edit button but not the other ones...

Using FF 74.0 on windows 7

cheers

**Comment by kazk** [comment] 2020-03-19 19:53
@Blind4Basics Do you remember when was the last time it worked?

> When going to the translation itself (outside of the edit panel), I see the edit button but not the other ones...

This is because your translation is in "draft" state. I'm not sure what happened yet.

> note: cw's icon does never roll, today..

No spinning logo since March 9th.
I've been updating the frontend stack and updated to use [Turbolinks](https://github.com/turbolinks/turbolinks) from a custom implementation based on [jquery-pjax](https://github.com/defunkt/jquery-pjax). The navigation is more efficient now, but the logo often just twitched so I decided to remove.

**Comment by Blind4Basics** [comment] 2020-03-19 20:17
> Do you remember when was the last time it worked?

no idea, since it's the first translation I published in months... :/

>No spinning logo since March 9th.

Ok, good to know. Tho, the thin red bar is showing up for some operations, but not when trying to publish the translation. Weird? (if that's intended, I'd say it would be nice to have something telling the user that work is in progress x) )

**Comment by Blind4Basics** [comment] 2020-03-19 20:31
@kazk: ok, I found the problem!

I'm printing shit tons of stuff to the console (I'm actually pretty close of the buffer limit error, when the tests succeed). I deactivated the canvas code and could publish normally. I'll reactivate the code later from the edit panel.

Tho, what's weird is that the tests execute perfectly in time (less than 7s, usually). Any idea why that makes the publication fail?

**Comment by kazk** [comment] 2020-03-19 20:35
> the thin red bar is showing up for some operations, but not when trying to publish the translation. Weird? (if that's intended, I'd say it would be nice to have something telling the user that work is in progress x) )

The progress bar is from Turbolinks so it currently only shows on navigation. I'll add something for other operations.

> god... :o I tried with internet explorer: I cannot see the translation or even display the discourse sections of a kata

IE support is not considered so that's not surprising. I can make Babel transpile to support it once I'm done migrating to the modern stack though.

> Tho, what's weird is that the tests execute perfectly in time (less than 7s, usually). Any idea why that makes the publication fail?

Maybe the payload is exceeding the maximum allowed size set by the server since it includes the test output in JSON format and the code.

**Comment by g964** [comment] 2020-03-20 09:15
@kazk : I have no browser extensions; neither Chrome nor Firefox... nor MS Edge.
I am surprised like you that MS Edge works so well:-)

**Comment by g964** [comment] 2020-03-20 10:05
Another Fortran translation that I have not been able to publish with Chrome:
<https://www.codewars.com/kata/5ce399e0047a45001c853c2b>
This time the "PUBLISH" button appears but when you push it, the kata validates but you can't "approve" it because this "APPROVE" button never appears.
I publish it with MS Edge.

**Comment by g964** [comment] 2020-03-20 16:19
Another Fortran translation that I have not been able to publish with Chrome:
<https://www.codewars.com/kata/5613d06cee1e7da6d5000055>
When I save, the page doesn't refresh and no "PUBLISH" button.
Used MS Edge once more.

**Comment by docgunthrop** [comment] 2020-03-24 05:24
I've run into an issue with publishing a kata translation. It's saved (so, in *Draft*), but when I click publish, I get the message "Something went wrong, please try republishing again". Tried this a few times, and clearing the browser cache didn't appear to make a difference.

This is for an Elixir translation to the "Alternate Capitalization" kata.

![failed to publish](https://user-images.githubusercontent.com/17622328/77390794-ea2fb480-6d8e-11ea-854e-a8078f5bdbca.png)

**Comment by Blind4Basics** [comment] 2020-03-24 09:03
I've the same problem for publications of forks of solutions too.

Seems generalized to kumites in general (yet, I didn't try with a "kumite" kumite) and due to a recent change.

**Comment by g964** [comment] 2020-03-24 10:48
Using Chrome or Firefox:
- unable to publish translations,
- clicking "up vote" or "down vote" or "View Solution" or "Spoiler" does nothing... unless you refresh the page one or several times,
- On the discourse page there is a mix of "https" and "http" implying warnings in Chrome and Firefox.

**Comment by FArekkusu** [comment] 2020-03-24 11:04
That's weird. I'm using Chrome v80.0.3987.149 (latest version as of now) on 64-bit Win 7 and having no issues: published a translation a couple days ago, all buttons are working correctly, and there're no errors/warning in the console.

**Comment by Blind4Basics** [comment] 2020-03-24 11:16
cw is "acting" since a bunch of hours only.

**Comment by g964** [comment] 2020-03-24 14:47
OS: win 10
Browser: Chrome(Version 80.0.3987.149 (Build officiel) (64 bits)
Firefox: 74.0 (64 bits)
Antivirus: Kaspersky

This has been happening for a few days.
Example of warning by Chrome on the console:

```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.
discuss#5e79c943c1baac0033937f84:1 Mixed Content: The page at 'https://www.codewars.com/kata/56a5d994ac971f1ac500003e/discuss#5e79c943c1baac0033937f84' was loaded over HTTPS, but requested an insecure image 'http://graph.facebook.com/10155057140168426/picture?type=square'. This content should also be served over HTTPS.
```

In Firefox the lock in the address bar has a warning.
In discourses page only the "reply" button works (sometimes) without refreshing.
When trying to publish a new translation the "Run" or "Validate" button works but when I "save" nothing happens, no refresh of the page, no "Publish" button!
Annoying because I can't get any more Chrome or Firefox to work... I have to use MS Edge...

**Comment by kazk** [comment] 2020-03-24 18:18
@docgunthrop

I believe it's different from @g964's issue, but I was able to reproduce yours and found the cause. I should be able to deploy the fix soon.
This is a bug that was introduced yesterday. 

---

I was expecting some bugs to appear since I refactored the entire frontend and deployed that yesterday. The change is mostly refactoring all the code to ES modules and using Webpack to bundle them instead of file concatenation by Rails' asset pipeline. This improves the maintainability significantly and allows the use of modern tools.

**Comment by kazk** [comment] 2020-03-24 18:36
@docgunthrop @Blind4Basics can you try again? I just deployed a fix for a bug that was causing publishing kumite to fail.

I can't reproduce @g964's original issue.

**Comment by Blind4Basics** [comment] 2020-03-24 18:45
:+1: working perfectly on my side (and Doc just published his translation) :+1:

**Comment by docgunthrop** [comment] 2020-03-24 18:47
@kazk yep, looks like it's fixed now. Just published the translation that was bugging out as well as another one I just wrote today.

**Comment by kazk** [comment] 2020-07-28 03:16
Closing because it's not reproducible. Maybe related to https://github.com/codewars/codewars.com/issues/2017#issuecomment-607512316

**Closed by kazk** 2020-07-28 03:16 UTC
Labels: browser/chrome, browser/firefox, kind/bug?, platform/windows, unreproducible
