### ISSUE TITLE
Kumite claims CoffeeScript is not supported

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#327] opened 2016-05-24 16:07 UTC
I was trying to fork a CoffeeScript translation [here](http://www.codewars.com/kumite/new?parent=5588627fcc02d4cde9000081).  To my surprise, I could not run the test cases.  The tooltip said:

> We do not currently support the ability to run the language you have selected.

![screenshot](https://cloud.githubusercontent.com/assets/5090280/15510463/5dda2a76-21a5-11e6-9225-5485be42f473.png)

**Comment by paul-calvelage** [comment] 2016-05-24 16:12
I just tried this again after trying to fork some other Kumite and now it is working.  Good thing I took a screenshot the first time, or I'd think I was going crazy.
![screenshot2](https://cloud.githubusercontent.com/assets/5090280/15511119/37bf983c-21a8-11e6-807d-d20a3173c799.png)

I still think this is a bug, since it shouldn't have happened in the first place.  But now I can't reproduce it.

**Comment by kazk** [comment] 2017-08-26 01:55
Closing this because we can't reproduce and too much time has passed.

**Closed by kazk** 2017-08-26 01:55 UTC
