### ISSUE TITLE
Can't login via github

### ISSUE THREAD

**Issue by kuchaguangjie** [codewars/codewars.com#2929] opened 2023-02-02 03:37 UTC
**Describe the bug**
When login via github, it always fail and back to the index page without login.

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: Linux mint mate 20
- Browser: chrome
- Version: 109.0.5414.119

**Additional context**
In virtual machine.

**Comment by kuchaguangjie** [comment] 2023-02-02 04:00
![a](https://user-images.githubusercontent.com/4230959/216228394-f0c7f49c-74e5-4394-b38e-3d46c681e357.jpg)
It can't find my account, but my account is here: https://www.codewars.com/users/kuchaguangjie

There is some serious bug here !

**Comment by kuchaguangjie** [comment] 2023-02-02 04:05
When try to sign up via github again:
![b](https://user-images.githubusercontent.com/4230959/216229087-b0ac1ff0-e2c8-43e4-9f63-8fef9e8e61d4.jpg)

It should just let me login, since my github is already login..

**Comment by kuchaguangjie** [comment] 2023-02-02 04:09
And, when click `forget password`, it simply jump to index, ......

**Comment by kazk** [comment] 2023-02-02 04:25
Calm down. Posting many comments to multiple issues won't help anyone.

I know some people are having trouble signing up and signing in with GitHub account, but I've never been able to reproduce the issue, and it's been working for most users.

https://www.codewars.com/users/kuchaguangjie doesn't seem to have GitHub account associated with it, so you need to reset password. Try again in Incognito/Private window or a different browser, which worked for some people.

**Comment by kuchaguangjie** [comment] 2023-02-02 06:10
Same result in private window. I just comment in the similar issue that's not fixed, and that helps with the feed back I think.
You can' repeat it, or it works for most people isn't a proper execuse.

**Comment by kazk** [comment] 2023-02-02 06:19
I hope you can imagine it's extremely difficult to fix something when you can't see it broken. That's all.

Closing this as a duplicate.

**Closed by kazk** 2023-02-02 06:19 UTC

**Comment by kuchaguangjie** [comment] 2023-02-02 15:56
And, even on my original laptop on which I can already login to codewars, I still can't set the password, because it's login via github, there is no password yet, but to set a new password, the old password can't be empty, this is deadlock ... can't believe this .

**Comment by kazk** [comment] 2023-02-02 18:30
Looks like https://www.codewars.com/users/kuchaguangjie is now linked with your account. Try signing in with GitHub again.

**Comment by kuchaguangjie** [comment] 2023-02-03 01:06
Because I went back home, and fixed it on my laptop which is already login, yesterday I was trying to login on another pc at office.
I tried to login again 10 seconds ago at office, it succeed now.

**Comment by IamUnranked** [comment] 2023-05-24 18:00
Hello, i have same problem. How i can fix this bag?)
