### ISSUE TITLE
Sudden inexplicable increase in honor

### ISSUE THREAD

**Issue by matthewmoppett** [Codewars/codewars.com#739] opened 2016-12-22 23:25 UTC
I have just received a huge increase in honor points -- from 508 to 2125. The extra honor points all came from completed kata, according to my stats page, although my rank has not changed at all. I think this must be due to a bug. 

My Codewars account is matthewmoppett.

**Comment by saimeeh** [comment] 2016-12-23 08:44
Hi, same here I went from 119 to 262 when I completed a single 6kyu kata

**Comment by suic86** [comment] 2016-12-23 09:38
Duplicate of #738

**Comment by BornaKavcic93** [comment] 2016-12-23 14:05
Greetings, same here went from 366 to 1224 when I was solving 5 Kyu kata.

Codewars account is Borna_Kavcic93

**Comment by OFFLlNE** [comment] 2016-12-23 17:20
Also got like 100 point boost. And today it seems to be gone :'(

**Comment by jhoffner** [comment] 2016-12-23 17:49
Some changes were deployed prematurely. A change to the honor system is coming but its not ready yet. Everyone's honor should be reverted now.

**Closed by jhoffner** 2016-12-23 17:49 UTC
