### ISSUE TITLE
Kata code load error

### ISSUE THREAD

**Issue by Mike667** [Codewars/codewars.com#1916] opened 2019-08-22 09:17 UTC
Hi, last 2 days i have error **Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)** in page kata console. Code editor and test editor empty, but i assured it must be with some example. (as before)

I thinks its high load and waiting, but problem still exist. And some times site work very slow, if upgrade account to red, its will be work faster?

**Comment by jhoffner** [comment] 2019-08-22 19:59
What kata is this for? Please provide reproduction steps

**Comment by Mike667** [comment] 2019-08-22 20:08
https://www.codewars.com/users/mike667 - my profile

Bug #1
I complete Additionless addition(you can see in my completed solutions). But i cant see another people solutions, system say i dont complete kata. I try refactor kata and submit new solution. In my profile solutions duplicate and when i try refactor they - i have issue from first post.

Bug #2
When i submit kata 2 times i get 2 times ~10 honor. (~20 honor for same kata)


![image](https://user-images.githubusercontent.com/9371245/63546116-ad1dee00-c531-11e9-8629-a5672b68be41.png)
![image](https://user-images.githubusercontent.com/9371245/63546139-b9a24680-c531-11e9-9f47-e8b9276b7c05.png)

**Comment by jhoffner** [comment] 2019-08-22 20:42
Closing as the issues you seem to be reporting are already filled.

**Closed by jhoffner** 2019-08-22 20:42 UTC
Labels: needs more info

**Comment by andrew-qio** [comment] 2019-08-22 21:23
Per [kazk on performance](https://github.com/Codewars/codewars.com/issues/1891#issuecomment-519203468):
> The recent performance issue is most likely caused by the increased traffic. For some reason, Codewars had the highest number of new users per month last month (20% more than previous highest), especially towards the end of the month.

Duplicate of #1683
