### ISSUE TITLE
update Keyboard Shortcuts page

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#355] opened 2016-06-07 22:09 UTC
`Ctrl + Enter` doesn't submit on windows `Ctrl + S` does. Please test on major platforms and update the docs and the trainning pages.

**Comment by javatlacati** [comment] 2016-06-09 17:46
related to #24

**Comment by kazk** [comment] 2017-04-11 01:40
Closing this because this is a duplicate of #212. I'm going to include the updated information in #881 once tests are done.
Also, this is not related #24 which is about enabling shortcuts without focus.

**Closed by kazk** 2017-04-11 01:40 UTC
Labels: documentation issue
