### ISSUE TITLE
Translated kata wasn't moved to the top of the kata list

### ISSUE THREAD

**Issue by suic86** [codewars/codewars.com#1514] opened 2018-07-23 11:26 UTC
I've created and published a Ruby translation of [this kata](https://www.codewars.com/kata/mixbonacci) but it wasn't moved to the top of kata list. AFAIK, this should have happened.

Update: I've translated other two of my katas. [This kata](https://www.codewars.com/kata/build-a-trie) was moved to the top but [the other one](https://www.codewars.com/kata/57c18a16c82ce75f4b000020) wasn't. This behavior is confusing.

Update 2: <s>It happened again with [this translation](https://www.codewars.com/kumite/5b899ac5cc7c03b4a5000167?sel=5b899ac5cc7c03b4a5000167).</s> The kata was moved but with some delay and not to the top of the list.

**Comment by anter69** [comment] 2018-07-26 21:41
I noticed the same, but it seems to happen only when you publish a new translation to **your own kata**.

**Comment by suic86** [comment] 2018-07-30 07:52
@anter69 thanks, that would explained this. However, this is still rather a bug that a future :)

**Comment by Voileexperiments** [comment] 2018-09-03 01:54
Maybe it's to prevent people bumping their katas constantly? :wink:

**Comment by suic86** [comment] 2018-09-03 07:16
@Voileexperiments, could be, but this doesn't seem to work very well as some people bump their katas constantly :) Also, this behavior seems to be inconsistent. I've noticed 3 different behaviors:

1. The kata is moved instantaneously after publishing the translation.
2. It't not moved at all.
3. It's moved after some delay and not to the top of the list.

If this isn't a bug, then this behavior should be explicitly documented.

**Comment by kazk** [comment] 2018-09-05 21:19
I don't know if this is a bug or not, but I'll try my best to explain what I _think_ is going on after reading some of the related code.

When "Sort By" is set to "Newest", the kata list sorts by the latest of following timestamps associated with a kata:

- approved at
- last published at
- created at

Maybe it should also consider when the kata was updated (e.g., new language was added). I'm not sure if approving translations affects those timestamps. Maybe it's also affected by how the translation was added (kata editor vs kumite).
I don't think the sorting is affected by who made the changes, but maybe I missed something.

I hope this explains 1 and 2.

> 3. It's moved after some delay and not to the top of the list.

I'm guessing it wasn't moved to the top after the delay because other kata was also updated during the delay.

> If this isn't a bug, then this behavior should be explicitly documented.

I really wish it was. I'll be leading Codewars rewrite soon and I've been struggling to infer the expected behaviors :(

**Comment by suic86** [comment] 2018-09-06 15:50
@kazk thanks for this. The logic behind this thing is apparently quite complicated and from outside it looks "buggy/magical". Is the resorting of the list 1) done periodically (e.g. in every x minutes) or 2) is it event driven (e.g. triggered by translation approval)? No. 1 would explain some of the behavior.

**Addtional info:** I've added a Python version to [this](https://www.codewars.com/kata/encrypt-this) via Kata editor (== not a translation ergo no honor points) and it was put on the top.

This leads me the following consideration: As the author has the opportunity to add new version via translation (=> with honor points) or via kata editor (=> without honor points), the behavior on approval of author's own translation on his own kata can be somehow penalized. IMO this should happen and probably it isn't the case as [this translation](https://www.codewars.com/kumite/5b8f2f4aa6ece8036500001f?sel=5b8f2f4aa6ece8036500001f) wasn't move to the top either.

**Comment by kazk** [comment] 2018-09-07 01:59
> Is the resorting of the list 1) done periodically (e.g. in every x minutes) or 2) is it event driven (e.g. triggered by translation approval)?

As far as I can tell, it's event driven. The background job to update the search data is triggered whenever a kata is saved/updated/published. The job is low priority so it can be delayed if there're other jobs to be completed.

**Comment by error256** [comment] 2019-03-19 07:27
Both moving and not moving to the top when a translation is approved happen often these days and it's about 50/50 split without any apparent pattern.

**Comment by kazk** [comment] 2019-03-19 20:21
@error256 there was a bug that made the order within each request messed up (https://github.com/Codewars/codewars.com/issues/1773#issuecomment-474534196). I just deployed the fix so hopefully this makes the behavior more consistent.

**Comment by kazk** [comment] 2021-11-22 09:08
This shouldn't happen anymore. Both republishing and merging a translation should update the timestamp used to sort by `Newest`.

Let me know if this happens again.

**Closed by kazk** 2021-11-22 09:08 UTC
Labels: enhancement, area/search, area/translation
