### ISSUE TITLE
undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1294] opened 2018-01-26 07:57 UTC
kata: https://www.codewars.com/kata/561e9c843a2ef5a40c0000a4/translation/new

Unable to re-publish the Scala translation because it always times out, I deleted it and wanted to redo it. All I get is:
```
Looks like there was a server error! (500)
We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `name' for nil:NilClass
```
It seems that it is impossible to re-publish Scala translations maybe because CW Scala is very very slow.
Similar : #851 #1090

**Comment by kazk** [comment] 2018-04-19 07:16
> Unable to re-publish the Scala translation because it always times out, I deleted it and wanted to redo it. 

This is a duplicate of #1268, so I'm closing this one.

**Closed by kazk** 2018-04-19 07:16 UTC
Labels: duplicate
