### ISSUE TITLE
Site doesnt work in Google chrome

### ISSUE THREAD

**Issue by Serveladik** [Codewars/codewars.com#1181] opened 2017-10-16 18:42 UTC
The site not opening in google chrome
What to do?>>

**Comment by kazk** [comment] 2017-11-10 19:44
Closing because there's not enough information. Maybe duplicate of #1157.

**Closed by kazk** 2017-11-10 19:44 UTC
Labels: browser/chrome, more info needed

**Comment by kabantejay** [comment] 2018-01-17 06:05
the same problem i have - its just not opens... it shows on 0.5 sec some page elements and then google chrome just show error grey screen - Page Crash

**Comment by kabantejay** [comment] 2018-01-17 06:06
i am win 7

**Comment by mouchin777** [comment] 2018-09-12 06:49
same stuff over there

**Comment by kabantejay** [comment] 2018-09-12 06:55
are you kiddin me?? you answered after several month!!!
and it STILL dont work!

https://pastenow.ru/f047a6a80d0d32d89945579103609ff5

[image: image.png]

ср, 12 сент. 2018 г. в 9:50, mouchin777 <notifications@github.com>:
