### ISSUE TITLE
Logging me out every few minutes, in the middle doing katas

### ISSUE THREAD

**Issue by iggirex** [Codewars/codewars.com#762] opened 2017-01-04 22:25 UTC
I'm not sure how to reproduce this issue, it happens constantly to me. I used to not have to sign in to CodeWars everyday, but now I do. After I sign in, I get automatically signed out after a period of time, could be 10 minutes or 3 hours. It will do it when I'm actively on the site doing katas, sometimes it'll happen like 10 minutes after the last time I signed in.

**Comment by kazk** [comment] 2017-05-29 00:01
Duplicate of #1.

**Closed by kazk** 2017-05-29 00:01 UTC
Labels: duplicate
