### ISSUE TITLE
ApplicationController::AccessDeniedError for signing up

### ISSUE THREAD

**Issue by deegeebee** [Codewars/codewars.com#1593] opened 2018-10-14 09:01 UTC
#### Describe the bug
Filled in information to enlist.
Next I got timeouts, now 'ApplicationController::AccessDeniedError'

#### To Reproduce

Don't know.

#### Expected Behavior

Expected to get a login.

#### Contexts

Please complete the following information:

- Codewars username (if account related): deegeebee
- OS: Ubuntu 16.04LTS
- Browser: Firefox
- Browser Version: 62.0.3

**Comment by kazk** [comment] 2018-10-14 19:09
Sorry about this. Can you try signing up again? User `deegeebee` doesn't exist yet.
Signup is known to timeout often and we know the cause, but it needs some database rework and we're unable to fix at the moment.
Closing as duplicate of #1516.

**Closed by kazk** 2018-10-14 19:09 UTC
