### ISSUE TITLE
Publicly visible solutions?

### ISSUE THREAD

**Issue by bhgalloway** [Codewars/codewars.com#1442] opened 2018-05-23 14:18 UTC
I'd like a way to allow solutions to be publicly visible on my profile.  Whenever I'm out job-hunting, potential employers request to see samples of my code.  It sure would be nice if I could point them to my CW profile as a portfolio.

Even if it were a subscriber-only feature to go along with the other enhanced profile stats, that might be a compelling reason to subscribe.

**Comment by DonaldKellett** [comment] 2018-05-23 14:27
This has been suggested countless times but won't ever happen because otherwise plagiarism on CW would be much more rampant (there is already more plagiarism than we want on CW **\***).  If you want to show off your programming skills to your employers, consider sharing one or two of your most remarkable solutions with them in private (by sifting through your own solutions and copy/pasting them manually).

@kazk Would you mind closing this Issue?  Cheers :smile:

**\*** All confirmed rampant cheaters are "banned" permanently (rank locked to 8 kyu and honor locked to 0) once caught.

**Closed** 2018-05-23 17:22 UTC
