### ISSUE TITLE
Beta kata becomes approvable even when there are open issues

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2041] opened 2020-02-21 01:44 UTC
I raised an issue in this kata yesterday:

https://www.codewars.com/kata/5e4bb05b698ef0001e3344bc/discuss

I don't remember if the kata has become unapprovable after that, but when I check it at this moment apparently it's approvable now even though the issue hasn't been closed yet. Open, unresolved issues should prevent a kata from becoming approvable.

**Comment by kazk** [comment] 2020-02-21 01:52
Some kind of data issue. I triggered to recheck the state so it's unapprovable now.

**Comment by Voileexperiments** [comment] 2020-02-21 01:56
Okay, so I just saw it become unapprovable and resolved my issue, which should make the kata approvable again, but apparently it's not updated again? :thinking:

**Comment by kazk** [comment] 2020-02-21 02:00
Looks like opening/resolving issue is not affecting the kata status. I just updated the status for this one and will look into it.

**Comment by kazk** [comment] 2020-02-21 02:01
The status didn't get updated :/ I'm not sure what's going on.

**Comment by kazk** [comment] 2020-02-21 02:07
OK, I was able to fix the status for that kata.

**Comment by Voileexperiments** [comment] 2020-03-27 09:57
@kazk This is happening again in another kata:

https://www.codewars.com/kata/5e6fac5bed561b0027161ba2/discuss/agda

It was approvable, I raised an issue and it's still approvable after that.

**Comment by kazk** [comment] 2020-03-27 18:09
I fixed the state of the kata.
And I think I found the cause. I'll close this when it's deployed.

**Comment by kazk** [comment] 2020-03-27 20:36
Just deployed the fix. Please let me know if this happens again.

**Closed by kazk** 2020-03-27 20:36 UTC
Labels: kind/bug
