### ISSUE TITLE
internal server error for all katas

### ISSUE THREAD

**Issue by kuldeepgajera** [Codewars/codewars.com#1844] opened 2019-06-14 09:37 UTC

**Comment by Christoph-Harms** [comment] 2019-06-14 09:49
This issue contains no information at all, don't be so disrespectful. ;) But based on the heading, I'd say this is a dupe of #1842

**Comment by kazk** [comment] 2019-06-14 10:14
Closing as duplicate of #1842.

The outage was caused by Redis service going down. I'm deploying the changes right now so it should go back up soon. See https://status.codewars.com/

**Closed by kazk** 2019-06-14 10:14 UTC
