### ISSUE TITLE
Re-publish C kata

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#832] opened 2017-02-19 11:05 UTC
1) When re-publishing a C kata the "Example Tests:" part is NOT re-published with the modifications. This part is kept as it was *before* the modifications.

2) When running only the "Example Tests:" ALL "Test Cases" are run so it is impossible to validate separately "Example Tests:"  and  "Test Cases"

kata: <https://www.codewars.com/kata/55e2adece53b4cdcb900006c/edit/c>

**Comment by g964** [comment] 2017-02-19 17:14
1) Fixed: updated hours later.

**Comment by kazk** [comment] 2018-04-19 07:52
Closing because 2 is duplicate of #103

**Closed by kazk** 2018-04-19 07:52 UTC
