### ISSUE TITLE
Invalid link to kata when kata name equals language name

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#1242] opened 2017-12-01 18:54 UTC
There's a kata called "NIM": https://www.codewars.com/kata/54120de842dff35232000195
When it appears in search results, the link is https://www.codewars.com/kata/nim and leads to the list of katas in the Nim language. (Other links like https://www.codewars.com/kata/nim/javascript work correctly.)

**Comment by kazk** [comment] 2017-12-01 19:10
Closing as duplicate of #1086

**Closed by kazk** 2017-12-01 19:10 UTC
