### ISSUE TITLE
Whenever I try to login to CodeWars, I get brought to the enlist screen.

### ISSUE THREAD

**Issue by PietroLinguini** [codewars/codewars.com#2449] opened 2021-08-11 00:20 UTC
**Describe the bug**
Whenever I try to login to CodeWars through the login screen, I get brought to the enlist screen. After I press either the "Sign in with Github" button, the "Sign in" button (even if I don't enter any credentials), or the underlined "Sign up" button, I am brought to the enlist screen. Pressing the "Forgot your password?" button also brings me to the enlist screen, with the added info that I am already signed in. I am also brought straight to the enlist screen after going to www.codewars.com.

**To Reproduce**
1. Go to the CodeWars login screen.
2. Press either the "Sign in with Github", "Sign in", "Sign up", or "Forgot your password?" button.
3. Be brought to the enlist screen.

**Expected behavior**
After pressing the "Sign in with GitHub" button, I expected to be logged into CodeWars, not brought to the enlist screen.

**Screenshots**
CodeWars login screen:
![image](https://user-images.githubusercontent.com/87112370/128951130-6ce442f0-a986-4828-84f9-3f308c6b77a6.png)
The enlist screen:
![image](https://user-images.githubusercontent.com/87112370/128950865-023327b6-9daa-4080-afbd-8e8aeeca1df4.png)
The enlist screen after pressing the "Forgot your password?" button:
![image](https://user-images.githubusercontent.com/87112370/128950890-57fca4b2-7e7e-4dd9-ad50-6ab1ecf8eb06.png)

**Browser**
- OS: Windows
- Browser: Opera GX, Firefox, Microsoft Edge
- Version: LVL3 (core: 77.0.4054.298), 91.0 (64-bit), Version 92.0.902.6

**Additional context**
I have recently cleared all my browser cookies, as well as my cached images and files on Opera GX, my main browser. However, I have also run into the same problem using Firefox and Microsoft Edge.

**Comment by kazk** [comment] 2021-08-11 00:36
Sounds very similar to #2447. A few users also emailed us with similar issue. I can never reproduce, none of our heavy users have this issue either as far as I know, and I honestly have no idea. Thanks for the detailed issue.

Do you have any extensions enabled? Have you tried in Incognito/Private? If that doesn't work, can you try looking at the Network tab in Developer tools? You should see something like this:

- `POST https://www.codewars.com/users/auth/github` 302
- `GET https://github.com/login/oauth/authorize` 302
- `GET https://www.codewars.com/users/auth/github/callback` 302
- `GET https://www.codewars.com/dashboard` 200

**Comment by PietroLinguini** [comment] 2021-08-11 02:36
Could you send a screenshot showing where that information shows up. Sorry, I'm just having some trouble finding it. And yes, I've tried using incognito, unfortunately to no avail.

**Comment by kazk** [comment] 2021-08-11 03:06
On https://www.codewars.com/users/sign_in open Developer Tools (`Ctrl+Shift+I` on Firefox, `Ctrl+Shift+J` on Chrome), then open `Network` tab.

![image](https://user-images.githubusercontent.com/639336/128962937-73c34099-6e0f-4c2c-8f97-3c6d3283cea4.png)

Then click "Sign in with GitHub".

You should see requests like these:
![image](https://user-images.githubusercontent.com/639336/128963219-1ebb87b9-f347-465c-9ec7-6144c015dd4d.png)

**Comment by PietroLinguini** [comment] 2021-08-11 04:36
Again, I'm using Opera GX, which I'm pretty sure uses Chrome as a base or at least has Chrome's Develop Tools' design, so mine looks a bit different from yours, most notably it has many more entries. This is what they look like:
I did catch the 200 GET, but I didn't see the rest of them.
![image](https://user-images.githubusercontent.com/87112370/128970219-0863fe13-46be-4798-9c55-e106c61ce707.png)
![image](https://user-images.githubusercontent.com/87112370/128970287-dc7cfdd0-a765-4734-b2ea-2e1171fa7ae1.png)

**Comment by kazk** [comment] 2021-08-11 04:41
Can you clear (:no_entry_sign:) the entries before clicking sign in? That should make the relevant entries first.

**Comment by PietroLinguini** [comment] 2021-08-11 05:13
It seems to have worked, now I see those four requests that you mentioned, or at least requests that look similar to them.
![image](https://user-images.githubusercontent.com/87112370/128973060-1d44fa79-fbdc-43e5-ab43-4bb7f9372de3.png)

**Comment by PietroLinguini** [comment] 2021-08-11 20:20
I'm going to try the solution that is in [#2447](https://github.com/codewars/codewars.com/issues/2447), unless it would be better to wait for a solution instead of using a work around?

**Comment by kazk** [comment] 2021-08-11 20:24
You can try it. I don't know why that makes it work, and clearing cookies doesn't.

**Comment by kazk** [comment] 2021-08-11 20:35
I think #2447 was fixed by signing up with a new account (enlist), so you should be able to do the same if you want (create a new account, sign out, try old account). Or are you saying you can't sign up either?

> What would happen to my old account if I went this route?

You shouldn't be able to. You should get an error saying GitHub user is already associated with another user.

**Comment by kazk** [comment] 2021-08-11 21:38
You're no longer redirected? Did signing up with another account fix the redirect in all of your browsers?

> I'm only able to sign in with my GItHub as Peeepo

How are you testing this? CW user `Peeepo` is linked to @PietroLinguini, and `YerlyYear` is linked to @Peeepo.

> Another thing to note is that PietroLinguini is no longer associated with my GitHub account.

This shouldn't happen because there's no code to update other user when signing up, only the new user is persisted. The only thing I can think of is that your original user didn't have GitHub linked properly for some reason. To log in to your original account, you can request a password reset.

**Comment by PietroLinguini** [comment] 2021-08-11 22:49
So I've fixed the issue. I signed out of my GitHub and pressed the "Forgot your password?" button and reset it, which subsequently logged me into my account. Also, you were right about my GitHub not being linked to my CodeWars account, so I've now linked it properly after deleting the CodeWars Peeepo account. Thank you for the help!

**Comment by kazk** [comment] 2021-08-11 23:38
No problem. Don't forget to delete `YearlyYear` as well.

**Closed by kazk** 2021-08-11 23:38 UTC
Labels: kind/bug

**Comment by DianaAndreeva** [comment] 2022-09-08 20:23
Guys i have the same problem what should i do????

**Comment by WeHaveBOOST** [comment] 2023-02-09 08:25
Same problem. Can't log in, he says i'm already log in but it's wrong.
When i try to reset a password or relogin, he redirect me on main page.
-
![image](https://user-images.githubusercontent.com/80750542/217756787-f6a79a48-3287-4182-9f60-da8762b28f83.png)

**Comment by rscharfer** [comment] 2023-02-18 22:51
If you have attempted to log in with GitHub, delete your cookies.  Now try logging in directly (not using Github).  It seems logging / attempting to log in with GitHub sets a cookie that is screwing things up.

**Comment by jfvillablanca** [comment] 2023-04-19 03:05
This is still an issue and I hope this issue gets reopened.
I have tried to login via Firefox, and then cleared the cache and cookies. I also tried Incognito (no extensions) and then to Google Chrome. Sign in redirects to homepage (I even tried on another computer running another distro, just to see it fail also)
I am posting a screenshot of the console warnings after clicking Sign In with GitHub and then getting redirected to index page

![image](https://user-images.githubusercontent.com/31008330/232955562-ad5df5c7-3fa0-46e6-ac9e-f6afee54e087.png)

Firefox 112.0
OS: NixOS

This is my [codewars account](https://www.codewars.com/users/jfvillablanca) if that helps.

**Comment by iTzVoko** [comment] 2023-05-31 14:19
> If you have attempted to log in with GitHub, delete your cookies. Now try logging in directly (not using Github). It seems logging / attempting to log in with GitHub sets a cookie that is screwing things up.

Yes, this solution solve the issue successfully.

**Comment by israelnazareth** [comment] 2024-10-29 21:44
> If you have attempted to log in with GitHub, delete your cookies. Now try logging in directly (not using Github). It seems logging / attempting to log in with GitHub sets a cookie that is screwing things up.

thanks, man! worked here!
