### ISSUE TITLE
Unable to edit published (PHP) Kumite

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#370] opened 2016-06-11 07:02 UTC
Again, I'm not sure if this bug is specific to PHP only or appears in Kumite of all languages but when I try to edit a PHP Kumite that was already published the code window and the description simply won't show up for some reason no matter how many times I reload the page:

![2016-06-11 2 57 37](https://cloud.githubusercontent.com/assets/7777884/15983790/56288842-2fe5-11e6-8636-cc2724b34054.png)

**Comment by kazk** [comment] 2018-12-31 22:51
Closing since this is old and I can't reproduce. Please let me know if this is still happening.

**Closed by kazk** 2018-12-31 22:51 UTC
Labels: area/kumite, kind/bug
