### ISSUE TITLE
Unable to log into Codewars due to 5XX: Server Error

### ISSUE THREAD

**Issue by BorisPro** [Codewars/codewars.com#1868] opened 2019-07-05 15:29 UTC
Accessing https://www.codewars.com/ gives me the "5xx: Server Error" :(
I believe my username is: BananaTraider.
I tried private Firefox mode but can access the login screen. Thats why I can't try to reset my password.
![grafik](https://user-images.githubusercontent.com/7208367/60732781-3b6eee00-9f4b-11e9-8e7b-1c29fbf720d7.png)

How can I solve this problem? :)

**Comment by bdoremus** [comment] 2019-07-05 15:35
Duplicate of https://github.com/Codewars/codewars.com/issues/1867

**Comment by BorisPro** [comment] 2019-07-05 15:41
Ok, thanks 👍

**Closed** 2019-07-05 15:41 UTC
