### ISSUE TITLE
Save button redirects to login page, deleting all changes.

### ISSUE THREAD

**Issue by CursedFlames** [Codewars/codewars.com#462] opened 2016-07-17 23:21 UTC
Occasionally, you get spontaneously logged out, and when you click on a link or some of the buttons you get redirected to the login page.
The Save button is one of the buttons that does this, which takes you away from the page without saving and thus deletes all your modifications.
To prevent this, changes should either save locally, or the page should not redirect and should instead tell you that you are not logged in, and allow you to log in in another tab and copy-paste your changes to the version of the page that is logged in.

**Comment by kazk** [comment] 2017-05-29 00:02
Duplicate of #1.

**Closed by kazk** 2017-05-29 00:02 UTC
Labels: bug, duplicate
