### ISSUE TITLE
Search for kata that were completed or not-completed by language

### ISSUE THREAD

**Issue by jlb071** [codewars/codewars.com#2376] opened 2021-05-10 03:45 UTC
Who knows if this has been requested before -- I spent 20min looking through but certainly couldn't check all previous posts -- It would be great if you could search for kata that were completed or not-completed BY LANGUAGE. Now you can search for kata by language, and if that kata is completed IN ANY LANGUAGE but not IN A SPECIFIC LANGUAGE. For example: I am learning a new language, and I want a list of available kata that I have not completed in the new language, but if I search for NOT COMPLETED then it will exclude any kata that I may have previously completed in another language

EDIT (hobovsky): Moved long title to the post

**Comment by XRFXLP** [comment] 2021-05-10 03:48
What is this?

**Comment by Voileexperiments** [comment] 2021-05-10 03:59
This is a duplicate of #790

**Comment by hobovsky** [comment] 2021-05-10 08:57
Duplicate of #790, #1642, and a couple of other issues.

You can check #1758 for some possible work-arounds.

**Closed by hobovsky** 2021-05-10 08:57 UTC
