### ISSUE TITLE
Number of satisfaction votes below 0

### ISSUE THREAD

**Issue by docgunthrop** [Codewars/codewars.com#1953] opened 2019-10-06 18:28 UTC
I haven't seen this bug with other katas yet, so I'm not certain if it only affects this particular kata.

**Kata:** https://www.codewars.com/kata/5b62e33c51f0b36fe70000bc

**Issue:** the number of "somewhat satisfied" votes is `-2`

![kata error](https://user-images.githubusercontent.com/17622328/66273802-dfc44180-e866-11e9-9a46-944314ab600c.png)

**Comment by hobovsky** [comment] 2019-10-07 11:55
I think it might be related to things like #1660 or #1833. Or Voile having fun and casting votes through API endpoints ;)

**Comment by kazk** [comment] 2019-10-08 02:14
I'm pretty sure this is a duplicate of #1660 that just went the opposite direction. I've fixed the data for this kata.

**Closed by kazk** 2019-10-08 02:14 UTC
Labels: duplicate
