### ISSUE TITLE
Submit button rendering off screen, no scroll, can't submit.

### ISSUE THREAD

**Issue by obscure-shadow** [Codewars/codewars.com#1526] opened 2018-08-12 17:16 UTC
hey,
 first off thanks for providing a page like this where people can practice up on their skills!
so the issue that i'm having is that when i go to a kata, the screen renders larger than my screen, and there's no scroll, and though I can barely see the top of the submit button, it won't let me click on it.
while there might be a way to get there by keyboard shortcut, I could not figure that out either (but hey maybe i'm a n00b and this is the real challenge) 
I'm on a MacBook Pro (13-inch, Early 2011) (yeah i know it's a dinosaur but it's still chuggin)
2.3ghz intel i5
8 gb ram
intel hd graphics 3000 512mb

google chrome Version 68.0.3440.106

i tried resizing the window but that didn't seem to help

![image](https://user-images.githubusercontent.com/35914606/44004537-8654c94a-9e29-11e8-9d98-432e027385f3.png)

you can barely see it peeking out at the bottom right there.... that's what i got..

**Comment by obscure-shadow** [comment] 2018-08-12 18:35
i was able to zoom out the screen, and get it to show, so it works for now.. but perhaps this can be avoided some kinda way...

**Comment by kazk** [comment] 2018-08-12 19:30
Closing as duplicate of #1214

**Closed by kazk** 2018-08-12 19:30 UTC
