### ISSUE TITLE
Translation approval buttons have no effect?

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1116] opened 2017-09-06 16:33 UTC
Hello,

I recently noticed that I see translation Approval and Reject buttons (hoorah!),
but when I tried to approve a translation, and confirmed that I really knew what I was doing,
it seemed like nothing happened, and the translation was not approved.

Is this a known issue, or are there some conditions which were not met? In the latter case, it would help to get an appropriate error message.

**Comment by thetamind** [comment] 2017-10-10 06:58
Yes, it appears the buttons show even when the action is unavailable.

Duplicate of #1093

**Comment by kazk** [comment] 2018-06-05 21:11
Closing as duplicate of #1093

**Closed by kazk** 2018-06-05 21:11 UTC
