### ISSUE TITLE
Bookmark Star Design issue

### ISSUE THREAD

**Issue by Programmer245** [codewars/codewars.com#2103] opened 2020-04-19 09:23 UTC
#### Describe the bug
Whenever i bookmark a kata, the bookmark star is filled in to indicate that the kata has been bookmarked, however, if i exit the kata and re-enter it, the bookmark star will return to its default hollow state

#### To Reproduce

1. Bookmark a kata
2. Click on the kata from the bookmaks
3. Click 'train again'
4. Bookmark star will now be hollow instead of filled in

#### Expected Behavior

Whenever bookmarked, a kata should display a grey-filled bookmark star

#### Screenshots

![BookmarkIssue](https://user-images.githubusercontent.com/38455578/79684233-0a11a580-8273-11ea-971d-63f69acdcc8b.png)

(As you can see, although bookmarked, the star is still hollow as if it wasn't bookmarked)

#### Contexts

Please complete the following information:

- Codewars: Ninja45
- OS: Windows
- Browser: Firefox
- Browser Version: Version 75.0

**Comment by kazk** [comment] 2020-04-20 00:01
Closing as duplicate of #1011.

**Closed by kazk** 2020-04-20 00:01 UTC
