### ISSUE TITLE
No kata can be attempted in chrome or firefox

### ISSUE THREAD

**Issue by dennisgit42** [Codewars/codewars.com#952] opened 2017-05-05 02:52 UTC
A few things to check first:

I am trying to submit my answer for the remove duplicates kata in both chrome and firefox, but I see that whenever I hit the Attempt button to run my tests and save my code, I get nothing but a blank white screen where I should see the output and results of the tests. This is happening for multiple katas, I have also tried http://www.codewars.com/kata/5526fc09a1bbd946250002dc/train/ruby and get the exact same issue. Looks like site wide issue with either chrome or firefox.

**Comment by rylandtikes** [comment] 2017-05-05 04:04
Same issue

**Comment by denizgenc** [comment] 2017-05-05 04:46
I am getting this exact same problem . I am using Firefox 53.0, on Windows 7.

**Comment by Voileexperiments** [comment] 2017-05-05 04:47
Duplicate of #928

**Closed** 2017-05-05 16:57 UTC
