### ISSUE TITLE
Unfinished kata appear unfinished list up to four times

### ISSUE THREAD

**Issue by samsamson33** [Codewars/codewars.com#1981] opened 2019-12-04 21:19 UTC
#### Describe the bug
Many of the kata in my "unfinished kata" list appear twice, at different points on the list. [One kata](https://www.codewars.com/kata/5c879811bc562909bf65c8e6) appeared twice in a row, then twice again further down the list.

#### Screenshots
![image](https://user-images.githubusercontent.com/35579293/70182008-01984400-16b1-11ea-8c85-69662ea1f216.png)

#### Contexts
- Codewars username: Samsamson33
- OS: Windows 10
- Browser: Firefox Dev
- Browser Version: Currently 72.0b2

When changing the browser to chrome, the kata were not duplicated at other points on the list (but the one in the screenshot still appeared twice in a row).

**Comment by kazk** [comment] 2019-12-05 19:21
Closing as a duplicate of issues like #1529 and #1966. This is caused by old bug that was creating multiple records for user for a kata. The bug itself was fixed, but the affected data is not yet cleaned up. See https://github.com/Codewars/codewars.com/issues/1683 for more details if interested.

**Closed by kazk** 2019-12-05 19:21 UTC
Labels: duplicate
