### ISSUE TITLE
Server Execution Error: [4th Kyu]Next bigger number with the same digits

### ISSUE THREAD

**Issue by SanderLy** [Codewars/codewars.com#477] opened 2016-07-27 09:20 UTC
Whenever I submit my code this happens... I've ran the test cases and they're all correct. What's the cause of this error?

![image](https://cloud.githubusercontent.com/assets/11423702/17170341/26320ad4-541e-11e6-8622-b31d531c7ab7.png)

**Comment by jhoffner** [comment] 2016-07-28 14:17
Is this still happening?

**Comment by SanderLy** [comment] 2016-07-28 23:36
It still is but I already solved this kata using a different approach.

**Comment by erickstm87** [comment] 2016-10-22 18:45
Hey I'm getting the same error. I run it on my local machine and it solves no problem. This is also for next biggest number with same digits
<img width="564" alt="screen shot 2016-10-22 at 12 44 53 pm" src="https://cloud.githubusercontent.com/assets/7424828/19621729/63f5900e-9855-11e6-9d88-eacb5e795d09.png">

**Comment by erickstm87** [comment] 2016-10-22 18:46
<img width="532" alt="screen shot 2016-10-22 at 12 45 58 pm" src="https://cloud.githubusercontent.com/assets/7424828/19621734/84dcfd16-9855-11e6-81aa-ac15cb433dcb.png">

**Comment by syltluwe** [comment] 2016-10-22 18:52
Got the same!

**Comment by kazk** [comment] 2017-05-31 16:40
> It still is but I already solved this kata using a different approach.

I'm closing this because this sounds like the issue was caused by the original approach. Please let me know if this is incorrect or the issue is still there.

**Closed by kazk** 2017-05-31 16:40 UTC
