### ISSUE TITLE
" String " doesn't containta definition for " Count "

### ISSUE THREAD

**Issue by RiperFish** [Codewars/codewars.com#1879] opened 2019-07-18 12:48 UTC
#### Describe the bug
" String " doesn't contain a definition for " Count "
#### Screenshots

![Untitled](https://user-images.githubusercontent.com/17910065/61458524-07dc8c80-a96b-11e9-9c09-bca2ac0d2760.png)

**Comment by DonaldKellett** [comment] 2019-07-18 16:28
That's a bug with your solution, not the Codewars site itself.

**Comment by RiperFish** [comment] 2019-07-18 17:01
> That's a bug with your solution, not the Codewars site itself.

the same code works just fine on VS 19 :)

**Comment by kazk** [comment] 2019-07-18 18:19
What's the C# version you have configured for your VS 19? It might be a newer version. Codewars has C# 7.3 support as it says above the editor. Also, it uses .Net Core 2.1 on Linux so there might be a difference from your local environment.

Closing because it's not a bug. If this is because of C# version, you can make a request to add support on https://github.com/Codewars/codewars-runner-cli

**Closed by kazk** 2019-07-18 18:19 UTC

**Comment by RiperFish** [comment] 2019-07-18 22:11
> What's the C# version you have configured for your VS 19? It might be a newer version. Codewars has C# 7.3 support as it says above the editor. Also, it uses .Net Core 2.1 on Linux so there might be a difference from your local environment.
> 
> Closing because it's not a bug. If this is because of C# version, you can make a request to add support on https://github.com/Codewars/codewars-runner-cli

it is the version, im not posting this as it's bug, i just posted so that the team might work to update the version that's all :)

**Comment by Voileexperiments** [comment] 2019-07-19 08:59
No, it's your issue: you're using the wrong method to get the length of the string, and you forgot to `using` the namespaces before trying to use the extension method.

String length is in `Length` property, not `Count`; that's the Linq method, so you need to import Linq before that's available. Again, your code's problem, not sure why you're blaming others for your own mistake.
