### ISSUE TITLE
Testing suite is frequently broken by rebuilds

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#928] opened 2017-04-29 08:18 UTC
Yesterday we've encountered a situation where the css stylesheet fetching return 404 error some of the time, resulting in unformatted test output (the horror!). And today it happens again with manifest.js, which causes entire test screen to go white, breaking test suite as well as the code autosave functionality:

![image](https://cloud.githubusercontent.com/assets/14909989/25553980/9542cb02-2cf4-11e7-8612-5a3d518018ed.png)

![image](https://cloud.githubusercontent.com/assets/14909989/25553979/911b13e0-2cf4-11e7-9a42-1f99902c8158.png)

Both occurrences happen at roughly the same time period. Are there any explanations to them? The same thing happening for half an hour or so every day is pretty inconvenient (especially for power users).

**Comment by troggzor** [comment] 2017-04-29 12:44
I confirm I have the same issue

![image](https://cloud.githubusercontent.com/assets/889997/25555568/ac88cb7e-2cf2-11e7-969a-93afd0f87d8a.png)

**Comment by Voileexperiments** [comment] 2017-04-29 13:42
@troggzor The problem will inevitably solve itself some of the times after refreshes because it just happens some of the times.

**Comment by Shizenfism** [comment] 2017-04-29 15:08
I assume I am having the same issue, as trying to submit test code doesn't appear to do anything most of the time. For me, I was able to do a few kata on one browser, then it seemed to stop working. I changed to a different browser, was able to complete a couple more kata, and then the same issue. I am getting 404 errors on a couple of .js files.

**Comment by jhoffner** [comment] 2017-04-29 18:23
This is super frustrating. It seems like a deployment goes well and things are ok. I check the system repeatedly and all is well, then at some point these links randomly start breaking. Oddly when I hit the endpoint from different places (like reloading the iframe vs just loading the URL directly) I seem to get different ratios of success/fail.

I've taken a shot in the dark and removed a few things in the build process (like pre-gzipping) and pushed a new build to see if that resolves the issue.

**Comment by jhoffner** [comment] 2017-04-29 18:44
I think the gzipping was the issue, seems to be stable now. Please let me know if this happens again. Otherwise I'll close this task if things go well.

**Comment by Shizenfism** [comment] 2017-04-29 19:19
I honestly can't say if what I have going on has anything to do with this particular issue; I just don't have the insight. I can say that I cleared my browser cache, refreshed, and am still having the same (or similar) issue: can't submit test code or perform attempts. Here's a screen capture if it helps.

![capture17607](https://cloud.githubusercontent.com/assets/24981432/25558183/1a14c598-2cd6-11e7-840b-578f6bdff792.png)

**Comment by jhoffner** [comment] 2017-04-29 19:59
This issue is that the output frame doesn't load at all. If you click output and it's all white, then you have this issue.

**Comment by Shizenfism** [comment] 2017-04-29 20:32
Sorry, my bad. My output frame is loading correctly. I'll stop now before I confuse things further.

**Comment by Voileexperiments** [comment] 2017-05-02 02:59
The problem seems to have mostly disappeared. I haven't encountered any of them these two days (note that I'm clearing up 6kyu katas so I'm doing like 100+ katas per day) except once earlier:

![image](https://cloud.githubusercontent.com/assets/14909989/25599696/c7bd5aca-2f10-11e7-80b9-9372db4b9331.png)

**Comment by Voileexperiments** [comment] 2017-05-02 06:49
Apparently the problem is getting more and more frequent the last few hours.

**Comment by jhoffner** [comment] 2017-05-03 02:18
OK I think I can put this issue to bed. It was crazy how eventually a successful deployment would just stop serving files, the cloudflare CDN should have been serving them even if the server wasn't - but I've moved everything over to an explicit CDN and if that doesn't solve the problem for good my head might implode. This was a weird one.

**Closed by jhoffner** 2017-05-03 02:18 UTC
Labels: bug, high priority

**Comment by NeonWizard** [comment] 2017-05-04 23:58
I'm having this problem with the 404 errors in console

**Comment by hyojeongson** [comment] 2017-05-05 03:08
It happens to me as well with a webpackJsonp is not defined error..

**Comment by Amit232** [comment] 2017-05-05 12:48
I am facing the same issue again on Chrome browser.
Clicking on "Run Sample TestS" and "Attempt" doesn't do anything.

**Comment by Voileexperiments** [comment] 2017-05-10 07:39
![image](https://cloud.githubusercontent.com/assets/14909989/25887945/c19ef0c2-3596-11e7-8bd0-0c3ba03deba4.png)

This is happening again.

**Comment by kazk** [comment] 2017-05-10 08:16
@Voileexperiments can you go to preview.codewars.com and see if it requests the same URLs? 
On my browser, both loads following URLs and works fine.

- https://crcdn.qualified.io/static/js/manifest.21f0ef3028a775441ecc.js
- https://crcdn.qualified.io/static/js/vendor.1ce33a870a09e5d4dc94.js
- https://crcdn.qualified.io/static/js/app.f949cb47b8629e1b1e3c.js

**Comment by kazk** [comment] 2017-05-10 08:42
`manifest.21f0ef3028a775441ecc.js`

<details>
<summary>Request Headers</summary>
<pre>
:authority:crcdn.qualified.io
:method:GET
:path:/static/js/manifest.21f0ef3028a775441ecc.js
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8,ja;q=0.6
cache-control:no-cache
dnt:1
pragma:no-cache
referer:https://runner.codewars.com/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
</pre>
</details>


<details>
<summary>Response  Headers</summary>
<pre>
accept-ranges:bytes
cache-control:max-age=7200000
content-encoding:gzip
content-length:857
content-type:application/javascript; charset=utf-8
date:Wed, 10 May 2017 07:58:30 GMT
etag:"4b3af8061203c3e8f5a08d90530e5951"
last-modified:Wed, 10 May 2017 04:47:49 GMT
status:200
strict-transport-security:max-age=31556926
vary:Accept-Encoding
via:1.1 varnish
x-cache:HIT
x-cache-hits:2
x-powered-by:Express
x-served-by:cache-lax8649-LAX
x-timer:S1494403111.780235,VS0,VE0
</pre>
</details>


---

I reloaded the page and now it's requesting the same URLs as @Voileexperiments.

`manifest.a706d3c57447ec65d411.js`

<details>
<summary>Request Headers</summary>
<pre>
:authority:crcdn.qualified.io
:method:GET
:path:/static/js/manifest.a706d3c57447ec65d411.js
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8,ja;q=0.6
cache-control:no-cache
dnt:1
pragma:no-cache
referer:https://runner.codewars.com/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
</pre>
</details>


<details>
<summary>Response  Headers</summary>
<pre>
accept-ranges:bytes
cache-control:max-age=7200000
content-encoding:gzip
content-length:6963
content-type:text/html; charset=utf-8
date:Wed, 10 May 2017 08:28:17 GMT
status:404
strict-transport-security:max-age=31556926
vary:Accept-Encoding
via:1.1 varnish
x-cache:HIT
x-cache-hits:1
x-powered-by:Express
x-served-by:cache-lax8647-LAX
x-timer:S1494404898.506252,VS0,VE0
</pre>
</details>

**Comment by kazk** [comment] 2017-05-10 09:36
@jhoffner
Cloudflare seems to be serving `runner.codewars.com` and I noticed two `last-modified` dates.
JavaScript fails to load when it's `Wed, 10 May 2017 05:02:27 GMT` and succeeds for `Tue, 09 May 2017 20:07:04 GMT` version. These two versions are requesting different sets of JavaScript files and Firebase CDN only allows one set (according to your comment in #937).

<details>
<summary>Response Headers</summary>
<pre>
access-control-allow-headers:Origin, X-Requested-With, Content-Type, Accept
access-control-allow-methods:POST, GET, OPTIONS
access-control-allow-origin:*
cache-control:public, max-age=0
cf-ray:35cbd046cc7c1e71-SJC
content-encoding:gzip
content-type:text/html; charset=UTF-8
date:Wed, 10 May 2017 09:18:52 GMT
etag:W/"31c-15beed27e40"
last-modified:Tue, 09 May 2017 20:07:04 GMT
server:cloudflare-nginx
status:200
x-powered-by:Express
</pre>
</details>

<details>
<summary>Response Headers when the page is white</summary>
<pre>
access-control-allow-headers:Origin, X-Requested-With, Content-Type, Accept
access-control-allow-methods:POST, GET, OPTIONS
access-control-allow-origin:*
cache-control:public, max-age=0
cf-ray:35cbd2f588571e71-SJC
content-encoding:gzip
content-type:text/html; charset=UTF-8
date:Wed, 10 May 2017 09:20:42 GMT
etag:W/"31c-15bf0bca6b8"
last-modified:Wed, 10 May 2017 05:02:27 GMT
server:cloudflare-nginx
status:200
x-powered-by:Express
</pre>
</details>

**Comment by smiks** [comment] 2017-05-10 11:18
https://i.snag.gy/udUlWh.jpg
https://i.snag.gy/qlmoM1.jpg

**Comment by jhoffner** [comment] 2017-05-10 21:55
This issue likely partially caused by me moving deployments over to a new CI environment. I think the issue might be the same as it has been, it's just that sometimes deployments go well and sometimes they don't, with whatever the fundamental issue here is. In this case everything seemed fine and I tested like crazy but things eventually feel apart after a few hours. I really would love to spend the time to dig into this and understand what happened for my own curiosity and for sanity's sake, but I just don't have anymore time right now before I leave. I've just changed how everything is deployed to what is a better model anyway. 

Firebase now serves the entire site, including the index.html. The run requests are handled by a different sub-domain where the Node server is hosted. This removes both Express/Node and Cloudflare from the UI equation, and we now have proper/separate environments for staging and production assets. It also allows me to deploy client vs server side changes independently and I no longer have to monitor 25+ servers when a new client side deployment goes out. 

Now that I'm writing this the only thing left for me to do is to make sure index.html has a `max-age=0` to ensure that cached indexes don't try to load older content that may no longer be there. 

I feel like this issue is now truly behind us.

**Comment by kazk** [comment] 2017-05-11 23:04
@jhoffner I got a white output panel again in Kumite :(

![image](https://cloud.githubusercontent.com/assets/639336/25975437/1ac47cae-3663-11e7-8428-62447b447619.png)


This time the logged error looks different.

![image](https://cloud.githubusercontent.com/assets/639336/25975382/d807eaf4-3662-11e7-9c3a-99facbef99f1.png)

```
Failed to load resource: the server responded with a status of 404 () vendor.2646ba21e87879fdfc24.js

Uncaught TypeError: Cannot read property 'call' of undefined
    at n (manifest.6197db5efe3a3ac87bcd.js:1)
    at Object.<anonymous> (app.33838d7e686f5ee6f8da.js:1)
    at n (manifest.6197db5efe3a3ac87bcd.js:1)
    at window.webpackJsonp (manifest.6197db5efe3a3ac87bcd.js:1)
    at app.33838d7e686f5ee6f8da.js:1
```


`manifest.6197db5efe3a3ac87bcd.js` is loaded by failing to load `vendor.2646ba21e87879fdfc24.js`.

![image](https://cloud.githubusercontent.com/assets/639336/25975486/5c71d976-3663-11e7-8242-827581b3f988.png)

**Comment by jhoffner** [comment] 2017-05-11 23:44
runner.codewars.com shouldn't be the URL. I bet kumite isnt using the right config setting. 

I'm out prepping to leave but I should be able to push a fix for this tonight.

**Comment by kazk** [comment] 2017-05-12 00:12
Is it supposed to be `cr-red.codewars.com`?

When I reload <https://www.codewars.com/kumite/new>, I get one of

- `runner.codewars.com` with errors (failed to load all, one, few; different hashes)
- `runner.codewars.com` without error
- `cr-red.codewars.com`

![image](https://cloud.githubusercontent.com/assets/639336/25976702/7765aea8-366b-11e7-9d9d-d715023cdf70.png)

![image](https://cloud.githubusercontent.com/assets/639336/25976716/91787244-366b-11e7-8041-9c5661b86509.png)

![image](https://cloud.githubusercontent.com/assets/639336/25976755/c77e63e4-366b-11e7-9ce4-b54c7fe999ab.png)

![image](https://cloud.githubusercontent.com/assets/639336/25976739/afd59d7a-366b-11e7-91a0-5f2824b7b7ba.png)

![image](https://cloud.githubusercontent.com/assets/639336/25976767/ecb02c4c-366b-11e7-9a3b-24a4f8a058a7.png)

**Comment by jhoffner** [comment] 2017-05-12 00:42
OK that's odd. The code is using the correct config value now that I am able to look at it. I could see this being an issue with maybe the rails cache possibly delivering old content somehow, but not if its the same url being reloaded, giving you mixed results. 

Interesting how now Rails is having some kind of weird caching issue...

Back to the original issue with the CR Node app. This is interesting:

![image](https://cloud.githubusercontent.com/assets/579835/25977370/12b5aaee-3670-11e7-8c99-5b3134902f4e.png)

Reloading runner.codewars.com multiple times results in different assets sometimes loading or not loading, and in this case it tried loading app.338.....js, it failed, but succeeded on the retry. So clearly the assets are loaded on the server it's just that it's hit or miss if it will actually deliver them. 

```
app.use(require('connect-history-api-fallback')());
app.use(express.static('public'));
```

I'm betting it's the connect-history-api-fallback. I haven't gotten a chance to comb through its internals yet but that's the only new piece to the Node server puzzle that I can think of. I think I might be done blaming WebPack for now. I probably should have taken that out to begin with.

Anyway I cleared the Rails cache again, @kazk have you still able to reproduce the issue? I haven't been able to after reloading about 20 times (always cr-red.codewars.com, as it should be).

**Comment by kazk** [comment] 2017-05-12 00:51
>  have you still able to reproduce the issue?

No, it's always loading `cr-red.codewars.com` :) Tried about 10 times.

**Comment by ggorlen** [comment] 2019-06-21 15:50
Apologies for pulling up this old issue, but this appears to still be happening:

![whitescreen](https://user-images.githubusercontent.com/17895165/59934847-5563e900-9401-11e9-814a-e63e724416da.png)
