### ISSUE TITLE
404 when accessing solutions

### ISSUE THREAD

**Issue by Zelatrix** [Codewars/codewars.com#1901] opened 2019-08-06 16:11 UTC
I tried to access my account page, and I was greeted with a 404 error message when I tried to get to the solutions list on my account. I'm not sure what caused it, but the page advised me to file an issue on the GitHub about it. 

My CodeWars username is: 
Zelatrix

**Comment by Steffan153** [comment] 2019-08-07 00:34
What URL does it try to go to when you click the link?

**Comment by kazk** [comment] 2019-08-20 01:06
Closing because I don't think this is happening every time and there's not enough information to reproduce. One cause that I can think of is username was changed and some of the page had outdated URL.

Please let me know if this happens again.

**Closed by kazk** 2019-08-20 01:06 UTC
