### ISSUE TITLE
Navigation broken from Edit account to Leaderboard

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#275] opened 2016-04-03 07:15 UTC
Just try to navigate from https://www.codewars.com/users/edit to http://www.codewars.com/users/leaderboard

you will see:

>    http://www.codewars.com/users/{:protocol=>"http"}

**Comment by kazk** [comment] 2018-04-23 02:49
Closing this because I can't reproduce and it's been 2 years. Let me know if this is still happening.

**Closed by kazk** 2018-04-23 02:49 UTC

**Comment by javatlacati** [comment] 2018-04-23 15:02
Fixed thank you
