### ISSUE TITLE
Show your completed check mark when viewing authored or completed kata on others' profiles

### ISSUE THREAD

**Issue by barbaralaw** [codewars/codewars.com#2315] opened 2021-02-03 18:51 UTC
Pretty self-explanatory, but would like to see the completed check-mark (similar to when browsing kata) when viewing others' authored or completed katas. Sometimes our clan likes to compete with each other on similar kata, and not having to click into the kata to see if you've previously completed it would be fantastic.

**Comment by hobovsky** [comment] 2021-02-03 19:50
I am not sure if it's exactly what you mean, so could you please tell me whether it is a duplicate of any of #727, #752, or #790, #1162, #1272, or #1641 ?

**Comment by barbaralaw** [comment] 2021-02-03 19:57
I suppose #752 includes it.

**Comment by hobovsky** [comment] 2021-02-13 04:49
Closing as a duplicate of #752 then.

**Closed by hobovsky** 2021-02-13 04:49 UTC
Labels: enhancement
