### ISSUE TITLE
Internal Server Error while reaching the solutions

### ISSUE THREAD

**Issue by laiiith** [Codewars/codewars.com#3223] opened 2024-05-22 13:25 UTC
Internal Server Error while reaching the solutions

**Comment by Insertingthedisk** [comment] 2024-05-22 13:31
as well...

**Comment by Insertingthedisk** [comment] 2024-05-22 13:32
No, I'd say I have another problem I cannot even open the Home page :D

**Comment by hobovsky** [comment] 2024-05-22 13:38
Duplicate of #3216  #3220 #3221

**Closed as completed by hobovsky** 2024-05-22 13:38 UTC
Labels: duplicate
