### ISSUE TITLE
Delete draft translation

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#817] opened 2017-02-04 22:13 UTC
When editing translations, I noticed that sometimes multiple drafts get saved, even while you've published one. What I miss is a way to clean up unwanted drafts by deleting them. I could not find a delete button,
please add.

**Comment by javatlacati** [comment] 2017-03-07 19:41
I think this is an enhacement proposal 😄

**Comment by kazk** [comment] 2017-05-29 20:09
Duplicate of #81.

**Closed by kazk** 2017-05-29 20:09 UTC
Labels: area/contents, duplicate, enhancement
