### ISSUE TITLE
Can not view profile server error

### ISSUE THREAD

**Issue by KPH3082** [Codewars/codewars.com#1665] opened 2019-01-03 00:21 UTC
This has been happening for about the past week. I am getting a server error when I try to "View Profile" I have tried this on Firefox Version 64 and Safari Version 12.0.2 but I'm getting the same error. I am on MacOS, Macbook Pro, Username KPH3802. I finish a Kata and click on "View Profile" to see my score update and it just tries to load for a long time and times out.

See screenshot below.

<img width="1108" alt="screen shot 2019-01-02 at 6 12 13 pm" src="https://user-images.githubusercontent.com/33405945/50618809-c565cd80-0eba-11e9-8fea-1d3dfcfb6bf9.png">

**Comment by kazk** [comment] 2019-01-03 00:38
This is most likely a duplicate of #1657.

I can view both g964's and your profile.

Are you able to view other pages like him?

**Comment by KPH3082** [comment] 2019-01-03 00:55
No, I can't find his page but I don't know how to search for others. I am just interested in seeing my profile and my stats which I still cannot do. I don't need to see it on GitHub I am trying to go to the "View Profile" page on CodeWars.

**Comment by kazk** [comment] 2019-01-03 00:57
? I'm just saying both you and @g964 are having the same issue.

**Comment by kazk** [comment] 2019-01-04 09:41
Closing as fixed. Please let me know if this is still happening.

**Closed by kazk** 2019-01-04 09:41 UTC
Labels: kind/bug
