### ISSUE TITLE
Clojure has problem too?

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#180] opened 2015-09-04 15:48 UTC
I want to publish a new translation of my kata
<http://www.codewars.com/kata/55e86e212fce2aae75000060>
I "Save" and "Validate" without any problems but when I push "Publish" nothing happens.

**Comment by jhoffner** [comment] 2015-09-06 18:47
Thanks for reporting. This is a duplicate of #178.

**Closed by jhoffner** 2015-09-06 18:47 UTC
Labels: duplicate
