### ISSUE TITLE
Remove duplicates from "Completed" kata section in profile

### ISSUE THREAD

**Issue by zhaluza** [Codewars/codewars.com#1890] opened 2019-07-30 02:43 UTC
#### Describe the bug
The same completed kata appears 3 times in the Kata -> Completed section of my profile. 

This may have happened because I submitted the same solution 3 times, receiving a "you do not have access to the solution" message the first two times.

I only received a "successful" message after submitting my solution the third time.

#### To Reproduce

1. Go to my profile.
2. Click on "Kata" menu button
3. Click "Completed" (if it isn't already selected)

#### Expected Behavior

The menu should display two completed kata. 

Instead, it shows four: the same one three times, and then the second.

#### Screenshots

<img width="695" alt="Screen Shot 2019-07-29 at 10 37 53 PM" src="https://user-images.githubusercontent.com/45137225/62096525-f12f1300-b251-11e9-90d6-bca339464649.png">

#### Contexts

Please complete the following information:

- Codewars username (if account related): zhaluza
- OS: macOS
- Browser: Chrome
- Browser Version: 75.0.3770.142

**Comment by hobovsky** [comment] 2019-07-30 05:59
#1683

**Comment by kazk** [comment] 2019-07-31 21:14
This is one of the symptoms of having multiple records in the database which causes #1683. Details are explained in https://github.com/Codewars/codewars.com/issues/1683#issuecomment-473416159

Closing as duplicate of #1683.

**Closed by kazk** 2019-07-31 21:14 UTC
