### ISSUE TITLE
C# NUnit Framework can be cracked easily

### ISSUE THREAD

**Issue by dgzargo** [Codewars/codewars.com#3204] opened 2024-04-29 01:06 UTC
It's applicable only for C# NUnit. Other environments may not.
This line makes you pass (almost) any test: `NUnit.Framework.Assert.Pass();`
See: https://www.codewars.com/kata/reviews/5d612414344de60001df1e50/groups/662ece960a3f2d0001193e20
It's the reproduction.

Generally, you are not supposed to pass katas with the same line of code.
So, it should not pass and be invalidated.

Way around for Kata developers:
```csharp
Assert.DoesNotThrow<SuccessException>(() => KataTest());
```

**Comment by hobovsky** [comment] 2024-04-29 09:14
It's a duplicate of this issue https://github.com/codewars/codewars.com/issues/2179#issuecomment-644977083 and a couple of similar. I'm going to close this issue as a duplicate, but maybe it would be good to pick up some mentioned topics again, for example _"[...] For banning specific code, we can create a community project for each language if the community is interested. [...]_

**Closed as completed by hobovsky** 2024-04-29 09:14 UTC
