### ISSUE TITLE
Site logs out frequently

### ISSUE THREAD

**Issue by kittyj27** [Codewars/codewars.com#1345] opened 2018-03-27 14:54 UTC
Hi,

I find frequently when using codewars the site logs me out, sometimes 4/5 times in ten minutes, sometimes not for hours or even a couple of days. Cause/behaviour do not seem to be consistent, but most frequently is when I view my own user profile.

Thanks

**Comment by kazk** [comment] 2018-04-21 21:15
Closing as duplicate of #1

**Closed by kazk** 2018-04-21 21:15 UTC
Labels: duplicate
