### ISSUE TITLE
SQL katas fail to match correct results

### ISSUE THREAD

**Issue by rogueqd** [Codewars/codewars.com#732] opened 2016-12-17 18:54 UTC
Often when I get a solution correct for an SQL kata I get an error in the results matching that says:

  should should return the expected results
✘ expected true to respond to `true?` or perhaps you meant `be true` or `be_truthy`

I think this happens more often for katas I have already completed in the past. It may only occur for katas I have completed in the past, I can't say for sure.

**Comment by jhoffner** [comment] 2016-12-21 04:57
Please provide a specific set of reproduction steps. Which kata? Which solution?

**Comment by rogueqd** [comment] 2016-12-21 05:35
Steps to reproduce:
Load an SQL Kata. Press Skip until you find a Kata with a Past Solution. Cut and paste the past solution in to Solution field. Click Run Examples.
Sometimes you don't get an error, but here are three that gave me the error pasted above.

Kata:
https://www.codewars.com/kata/5811501c2d35672d4f000146/train/sql
Solution:
WITH special_sales
AS (
SELECT * FROM sales WHERE price > 90
)

SELECT * FROM departments
WHERE id IN (SELECT department_id AS id FROM special_sales)
ORDER BY id;


kata:
https://www.codewars.com/kata/5811527d9d278b242f000006/train/sql
Solution:
CREATE VIEW members_approved_for_voucher
AS
SELECT q.id, m.name, m.email, q.total_spending
FROM members as m
JOIN (
-- find members with $1000 in purchaes from $1000 depts list
SELECT s.member_id AS id, SUM(p.price) AS total_spending
FROM sales AS s
JOIN members AS m ON m.id = s.member_id
JOIN products AS p ON s.product_id = p.id
JOIN departments as d ON s.department_id = d.id
WHERE d.id IN (
-- Find depts with over $10000 in sales
SELECT s.department_id FROM sales AS s
JOIN products AS p ON s.product_id = p.id
GROUP BY s.department_id
HAVING SUM(p.price) > 10000)
GROUP BY s.member_id
HAVING SUM(p.price) > 1000
ORDER BY s.member_id)
AS q ON m.id = q.id;

SELECT * FROM members_approved_for_voucher


Kata:
https://www.codewars.com/kata/58164ddf890632ce00000220/train/sql
Solution:
SELECT age, COUNT(name) AS total_people
FROM people
GROUP BY age
HAVING COUNT(name) > 9;

**Comment by pmatseykanets** [comment] 2016-12-26 22:36
@jhoffner I second this. All SQL kata's using `compare_with expected` including mine are broken probably because rspec was upgraded.

Hopefully it can be fixed ASAP.

**Comment by jhoffner** [comment] 2016-12-27 16:23
Should be fixed now

**Closed by jhoffner** 2016-12-27 16:23 UTC
Labels: bug, cli issue, high priority

**Comment by pmatseykanets** [comment] 2016-12-28 03:55
@jhoffner Thank you! 👍
