### ISSUE TITLE
Submitted kata solutions aren't displayed

### ISSUE THREAD

**Issue by TheBlackJok3r** [codewars/codewars.com#2469] opened 2021-08-29 23:22 UTC
It appears that some solutions that i made are not displayed correctly. It happens only with some katas, but I can't find regularity in it.

After i submitted kata i wanted to discuss it with my teacher, but he told me that he can't see it. I was trying to find where is the problem, so i clicked on that kata, chose "solutions", sorted them by "My solutions", and then there wasn't any submission.

As far as I know, it should post my solution after i click submit button while doing kata, so i made 2nd submission, but it didn't work as well.

Bug appears in chrome and firefox (i believe that it works on other browsers too).

Some screenshots to prove the statement:
![Screenshot from 2021-08-30 01-15-15](https://user-images.githubusercontent.com/68962009/131268547-ad66d085-3c95-473f-a8f1-0274cbfe41cb.png)
![Screenshot from 2021-08-30 01-14-57](https://user-images.githubusercontent.com/68962009/131268600-dbd56dad-6c88-4b05-85df-6cfa70cef664.png)

**Comment by kazk** [comment] 2021-08-31 23:14
This is a known issue. Closing as duplicate of many. https://github.com/codewars/codewars.com/issues?q=is%3Aissue+is%3Aopen+label%3Aissue%2Fsolution-not-shown

**Closed by kazk** 2021-08-31 23:14 UTC
Labels: duplicate
