### ISSUE TITLE
Python exit(0)

### ISSUE THREAD

**Issue by ishid4** [codewars/codewars.com#2179] opened 2020-06-16 10:11 UTC
#### Describe the bug
When you return the first answer and write exit(0), you're finishing the kata.
(Sorry if this bug reported before)

#### To Reproduce

1. Go to https://www.codewars.com/kata/574e890e296e412a0400149c/train/python
2. Write
`if a == 1:
        return f"24"
    exit(0)`

#### Expected Behavior

exit(0) can be a banned code

#### Contexts

- Codewars username: Macbeth
- OS: Win 10
- Browser: Chrome
- Browser Version: 83.0.4103.97

**Comment by DonaldKellett** [comment] 2020-06-16 11:21
This is a known cheat, don't use it again if you do not wish to get banned.

**Comment by ishid4** [comment] 2020-06-16 12:07
You're funny. You even slandered me with saying "don't use it again".

**Comment by hobovsky** [comment] 2020-06-16 16:22
Kinda duplicate of #2163, https://github.com/codewars/codewars.com/issues/1970#issuecomment-552014145

To summarize: It's a known issue, and users who deliberately abuse it can get banned.

**Comment by ishid4** [comment] 2020-06-16 17:22
> Kinda duplicate of #2163, [#1970 (comment)](https://github.com/codewars/codewars.com/issues/1970#issuecomment-552014145)
> 
> To summarize: It's a known issue, and users who deliberately abuse it can get banned.

Sorry for the duplication. Instead of banning users for coding like this, simply banning that code or fixing it would be better. Because I'm believing in, hacking a system is also about code "wars".

**Comment by kazk** [comment] 2020-06-16 19:49
> Because I'm believing in, hacking a system is also about code "wars".

We disagree.

I mean you can do this to get temporary internet points if you want, but I'd recommend using the time to learn more useful things instead.

> Instead of banning users for coding like this

We ban users that are harmful to the community based on [our rules](https://github.com/codewars/codewars.com/wiki/Community-Code-of-Conduct).

> simply banning that code or fixing it would be better.

In my opinion, it's not worth the effort to _try_ to prevent all the cheats that's possible in our flexible environment. Cheaters will keep looking for workarounds and find them eventually because it's kind of fun to do. However, we don't have the resources or the motivation to keep patching. It's significantly easier if we had more restricted environment, but we don't and won't.
It's a trade-off like anything in software. Our environment takes simplicity, flexibility and natural UX over control. If something for cheaters ruins any of the values we believe in, we won't do it and we'll simply kick the repeated offender out of the community. 99.9% of the users are using Codewars to learn and we obviously care about them more.

That being said, simple early exit cheat like this should be preventable by storing the expected number of passed test cases and only allowing to complete when that matches exactly. There's other cheats so it doesn't really fix anything, but it's possible that we'll add this in the future. This can increase the cost of maintenance since a change in the test output can break existing kata, so I'll look into that and any other drawbacks when I decide to add it.

For banning specific code, we can create a community project for each language if the community is interested. This doesn't mean shifting the blame to the authors for not including this in their tests though. I just thought it can be useful for some kata similar to [`Hidden`](https://github.com/codewars/hspec-codewars#hidden) for Haskell.

**Closed by kazk** 2020-06-16 19:49 UTC

**Comment by Blind4Basics** [comment] 2020-06-17 13:44
> preventable by storing the expected number of passed test cases and only allowing to complete when that matches exactly.

(note: in some katas, the number of assertion might have some randomness too, so... not that simple, I fear.

cheers)
