### ISSUE TITLE
Messages with the spoiler flag are hidden to me too

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#73] opened 2015-05-20 18:50 UTC
I noticed it [here](http://www.codewars.com/kata/geometry-a-1-dot-1-modify-point-location-detector-to-handle-zero-length-vectors-and-precision-errors-dry/discuss?utm_campaign=code_challenge_comment_reply&utm_medium=email&utm_source=notifications#555cbd1fa1304869b000004d).

Of course I can unflag it as a spoiler and then flag it again, but it is not the smoothest way to handle a discussion on CW.

Screen (sorry for the caps lock text, but I feared you could not read well a lower case comment):

![image](https://cloud.githubusercontent.com/assets/4815731/7733779/c3815f3a-ff31-11e4-8902-9c2f358fbdc8.png)

**Comment by Stargator** [comment] 2015-05-28 16:18
I know the spoiler tags seem to be tied to the version you solved the kata. If you solved the kata with a Java solution, then you can read any post under discourse while the Java translation is selected. But if you switch to the C# translations then the posts with spoiler tags will be hidden.

So I would recommend checking that. As there are a few instances where switch to the translation I solved fixed that. (ex. the Sum by Factors for one of my posts).

In further testing, I've seen this occur for me on the Caffeine Script kata. Though I have not submitted a solution for that kata at this time, which may be the reason I cannot view it despite being the author.

**Comment by GiacomoSorbi** [comment] 2015-05-28 16:29
I cannot be 100% sure now, but I am pretty sure that time it was in some language I solved the kata already.

Even so, hiding my own messages is just wrong :D

**Comment by adam-tokarski** [comment] 2015-06-27 19:50
Yes, it's quite easy to replicate this issue. Today I was surprised that my post to the Kata, that I solved, was hidden. It was because I made this in Python, but when opened discourse section, the JS was set. Simply changing this to Python make every post visible. It's the way it should work?

**Comment by kazk** [comment] 2017-03-29 17:35
Closing this because this is a duplicate of #53.

**Closed by kazk** 2017-03-29 17:35 UTC
Labels: duplicate
