### ISSUE TITLE
Kata search broken

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#172] opened 2015-08-23 07:05 UTC
The kata search is currently broken. "There are no items to display":

![No katas](https://cloud.githubusercontent.com/assets/6301773/9427302/dfb60c1c-4975-11e5-8089-ba87684951e4.png)

Searching for a specific tag [like algorithms](http://www.codewars.com/kata/latest?tags=Algorithms) leads to a 500 error.

(Originally filed on [gitter](https://gitter.im/Codewars/codewars.com?at=55d96ea1004c3e375ad05686) by @DivyanshBatham)

**Comment by bkaes** [comment] 2015-08-23 20:53
Seems like the issue resolved itself. Was there something broken in the ES, or a random, not reproducible server hickup?

**Comment by DivyanshBatham** [comment] 2015-08-24 03:14
Yup looks same here ^_^!

**Comment by kazk** [comment] 2017-03-29 17:47
Closing this because "the issue resolved itself" and I think it's hard to answer the question asked in the comment now.

**Closed by kazk** 2017-03-29 17:47 UTC
