### ISSUE TITLE
Re-publishing Java and Clojure translations

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#209] opened 2015-11-20 07:41 UTC
On the 16/11 I posted the following on <https://gitter.im/Codewars/codewars.com>:

>I don't know why but it's always very long, almost impossible, to re-publish a kata translation in Java.
"Please wait while we publish" turns turns turns but nothing else happens.
Unfortunately same thing when trying to re-publish the Clojure translation.

The kata is <http://www.codewars.com/kata/56484848ba95170a8000004d>.

I already had this problem with a Java translation of one of Giacomo's some months ago and never had answers to my posts at that time. What can I do? Suppress first the Java and Clojure translation and then try to publish a new version?

**Comment by bkaestner** [comment] 2015-12-24 13:40
Duplicate of #64.

**Comment by jhoffner** [comment] 2015-12-31 00:08
I'm still on Holiday vacation but I'll look into these issues when I'm back next week. It sounds like these issues are only happening for specific kata?

**Comment by g964** [comment] 2015-12-31 08:09
I have the problem each time I try to re-publish a Java kata and it seems that I'm not the only one. See #64. 
You can easily validate the modifications but when you hit the publish-button it can run for hours without re-publishing. 
If you delete the Java translation you can neither write it anew or write another translation. You get "Uhh, something went wrong, error 500... blah blah". Try with <http://www.codewars.com/kata/easy-wallpaper/translations>. I suppressed the Java translation because it was impossible to re-edit it with modifications. Try hit the "+" button and then "Translate this kata"... you will see error 500...
Once you write a kata in Java you have to have it right at the first shot and it is very anxiety-provoking:-)

**Comment by jhoffner** [comment] 2016-06-27 18:37
This should have been resolved with all of the recent updates

**Closed by jhoffner** 2016-06-27 18:37 UTC
Labels: bug, duplicate, high priority
