### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by Lovejonezin** [Codewars/codewars.com#1547] opened 2018-08-25 16:21 UTC
From the "Training Setup" Page, I clicked on "kyu" (in the top right corner), but received the following error on the next page. 

Server Error (500)

/codewars/app/views/users/stats/_progress.html.slim:20: syntax error, unexpected modifier_rescue, expecting ')' ...miter(user.honor_ranking rescue '?')}"))).to_s)); ... ^ /codewars/app/views/users/stats/_progress.html.slim:20: syntax error, unexpected ')', expecting tSTRING_DEND ...(user.honor_ranking rescue '?')}"))).to_s)); ... ^ /codewars/app/views/users/stats/_progress.html.slim:21: unknown regexp option - b /codewars/app/views/users/stats/_progress.html.slim:24: syntax error, unexpected keyword_end, expecting tSTRING_DEND ...er.safe_concat(("</div>")); end; @output_buffer.safe_concat(... ... ^ /codewars/app/views/users/stats/_progress.html.slim:60: syntax error, unexpected keyword_ensure, expecting tSTRING_DEND /codewars/app/views/users/stats/_progress.html.slim:62: syntax error, unexpected keyword_end, expecting tSTRING_DEND

*** When trying to re-create the error, I was properly directed to my profile page, so the issue is possibly resolved***

**Comment by Blind4Basics** [comment] 2018-08-25 17:03
these are just random problems cw has currently very (too much) often with the servers. Just reload the page (several times if needed)

**Comment by FArekkusu** [comment] 2018-08-25 17:04
Duplicate of #1535.

**Comment by kazk** [comment] 2018-08-25 18:42
Closing as duplicate of #1535

**Closed by kazk** 2018-08-25 18:42 UTC
Labels: duplicate
