### ISSUE TITLE
[short description of the bug]

### ISSUE THREAD

**Issue by AbdullahDahash** [codewars/codewars.com#2808] opened 2022-09-13 08:03 UTC
**Describe the bug**
When I log in, it shows 502 error

**To Reproduce**
Login

**Expected behavior**
Logging in and using the website to train
![codewarsError](https://user-images.githubusercontent.com/107808323/189845845-edd95b58-8410-4213-8e30-9bda0ee4fce5.png)

**Screenshots**

**Browser**
Chrome

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by Madjosz** [comment] 2022-09-13 08:04
Duplicate of #2807
Please look for similar issues before opening a new one.

**Comment by kazk** [comment] 2022-09-13 08:05
Closing as duplicate of #2807

**Closed by kazk** 2022-09-13 08:05 UTC
