### ISSUE TITLE
Website does not work on Mac

### ISSUE THREAD

**Issue by murphyryan1** [Codewars/codewars.com#951] opened 2017-05-05 02:03 UTC
Tried to run a kata, the output tab does not load, the buttons do nothing.  I tried safari and chrome and same results in both.

Getting these browser errors:

2javascript:1 OPTIONS https://www.codewars.com/users/notifications/unread_popups 
javascript:1 XMLHttpRequest cannot load https://www.codewars.com/users/notifications/unread_popups. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.codewars.com' is therefore not allowed access. The response had HTTP status code 500.
ably.min.js:26 The Ably CDN URL you are using is deprecated because it does not contain a version number. Please see https://support.ably.io/solution/articles/3000063698
(anonymous) @ ably.min.js:26
(anonymous) @ ably.min.js:32
runner.codewars.com/:1 GET https://crcdn.qualified.io/static/js/manifest.3168bb31eb870c38e096.js 
runner.codewars.com/:1 GET https://crcdn.qualified.io/static/js/app.70b963111d561c75ba17.js 
vendor.18ea8d2….js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at vendor.18ea8d2….js:1
(anonymous) @ vendor.18ea8d2….js:1
runner.codewars.com/:1 GET https://crcdn.qualified.io/static/js/app.70b963111d561c75ba17.js

**Comment by Voileexperiments** [comment] 2017-05-05 04:47
Duplicate of #928

**Closed** 2017-05-05 16:56 UTC
