### ISSUE TITLE
Language undefined is not supported

### ISSUE THREAD

**Issue by stackcats** [Codewars/codewars.com#849] opened 2017-03-07 05:23 UTC
Golang

**Comment by jhoffner** [comment] 2017-03-07 16:46
Not to be a jerk but for the purpose of learning: Put yourself in my shoes. If I filed this bug report and you were the one who had to look into this. Would this be enough information for you to go on?

**Comment by javatlacati** [comment] 2017-03-07 19:39
I think it's related to [this bug](https://github.com/Codewars/codewars-runner-cli/issues/275) since I always get the same message

**Comment by kazk** [comment] 2017-03-07 23:14
@jhoffner, I just confirmed this for Go translation of "Is this a triangle?" kata. Both `www` and `preview`.

Maybe the form data for `POST` doesn't contain `'language'` field because `#language_dd` and `#language_version` is blank?

![image](https://cloud.githubusercontent.com/assets/639336/23682144/2f7daed0-0347-11e7-9536-b1dd2e05a5fa.png)

![image](https://cloud.githubusercontent.com/assets/639336/23682178/53e73afc-0347-11e7-8d0a-d62a156e45cb.png)

- <https://www.codewars.com/kata/is-this-a-triangle/train/go>
- <https://preview.codewars.com/kata/is-this-a-triangle/train/go>

**Comment by jhoffner** [comment] 2017-03-07 23:15
Now thats a bug report. Thanks. I'll look into it.

**Comment by kazk** [comment] 2017-03-07 23:30
I just completed [To square(root) or not to square(root)](https://www.codewars.com/kata/57f6ad55cca6e045d2000627) kata in Go without any problem. I'll try the other one from the email soon.

**Comment by kazk** [comment] 2017-03-07 23:33
[Floating-point Approximation (I)](https://www.codewars.com/kata/58184387d14fc32f2b0012b2) in Go had no problem either.

**Comment by 10XL** [comment] 2017-03-08 01:44
@kazk check [Multiply](https://www.codewars.com/kata/multiply/train/go). This one has a `Caution: This kata does not currently have any known supported versions for Go...` warning but it doesn't throw any server execution error.

**Comment by kazk** [comment] 2017-03-08 01:55
"Multiply" kata shows the language "Go (Beta)" and language version "1.7.5" correctly, but has the caution :/


I also see a warning from Ably logged.
`The Ably CDN URL you are using is deprecated because it does not contain a version number. Please see https://support.ably.io/solution/articles/3000063698`

**Comment by kazk** [comment] 2017-03-08 03:16
@jhoffner I just made (copy and pasted from the examples) a translation for your [Two Oldest Ages](https://www.codewars.com/kata/511f11d355fe575d2c000001) kata because I couldn't reproduce the problem with other Go translations.

Can you check what happens to this?

**Comment by jhoffner** [comment] 2017-03-08 03:43
Was a data issue. Should be fixed. Hopefully it doesn't pop back up.

**Closed by jhoffner** 2017-03-08 03:43 UTC
Labels: bug, high priority

**Comment by g964** [comment] 2017-03-08 08:08
Is go 1.8 possible?

**Comment by kazk** [comment] 2017-03-08 17:07
@g964 I'll start working on it soon :)
Also, if you notice anything while authoring kata, please let me know.

**Comment by g964** [comment] 2017-03-08 18:58
OK, thanks!

**Comment by groundberry** [comment] 2017-06-13 17:29
I had the same issue today with the "Counting in the Amazon" kata for JavaScript. But found kazk's answer and it works fine now. I had to refresh the page to make sure that it picked the language, though. Thank you!

**Comment by DeadSet13** [comment] 2018-03-08 17:54
I just encountered this error when trying to run an attempt on the "cat years, dog years" kata for c++, it gives error code 500, any help with this would be greatly appreciated.
![capture fpr kata](https://user-images.githubusercontent.com/37094466/37167387-65c60d98-22c7-11e8-9064-a2740aca1752.PNG)
