### ISSUE TITLE
Unable to complete kata

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#893] opened 2017-04-14 01:35 UTC
Having this problem in multiple katas. Both sample tests and final tests. I also see multiple users reporting this issue on the dashboard.

![image](https://cloud.githubusercontent.com/assets/639336/25029977/bd6d02a8-2076-11e7-92cb-0d6a77bef342.png)

![image](https://cloud.githubusercontent.com/assets/639336/25029981/c7122946-2076-11e7-92ee-38a4ccbb928b.png)

![image](https://cloud.githubusercontent.com/assets/639336/25030000/db988d2e-2076-11e7-944f-a22f0a72f226.png)

Even `Test.expect(true)` has red outline.

![image](https://cloud.githubusercontent.com/assets/639336/25030061/3119e568-2077-11e7-8275-12794295528f.png)

`stderr` is empty.
![image](https://cloud.githubusercontent.com/assets/639336/25030109/923384f8-2077-11e7-855a-d86159659ef0.png)

**Comment by scottfister** [comment] 2017-04-14 01:43
I have the same issue -- keep hitting "Attempt", it succeeds, but can't submit.

![image](https://cloud.githubusercontent.com/assets/1707867/25030318/0dae9248-2079-11e7-9ada-aedda0797cac.png)

**Comment by pcast01** [comment] 2017-04-14 02:25
I also am having the same issue.
![azrael7codewars](https://cloud.githubusercontent.com/assets/1172644/25031070/b8c652d6-208f-11e7-9954-1fc13c9146d9.PNG)

**Comment by christopherchateau** [comment] 2017-04-14 02:38
Same here

Tried reloading page, restarting browser, etc.

**Comment by wyattis** [comment] 2017-04-14 02:43
Same thing for me on the 2 different Katas I've tried in the last 30 mins.

**Comment by Incestosaurus** [comment] 2017-04-14 03:09
Same here for every Kata done in the past 2 hours.

**Comment by Voileexperiments** [comment] 2017-04-14 03:21
Looks like even preview.codewars.com is suffering from the same problem. I suspect it has to do with backend server problems.

Currently I'm watching the discourse and responding to new comments that talks about this issue. I hope @jhoffner will take care of the issue quickly :)

**Comment by lqfortytwo** [comment] 2017-04-14 03:23
Same issue

**Comment by bahaha** [comment] 2017-04-14 03:23
Same here
![](https://cloud.githubusercontent.com/assets/7671532/25032181/b53d8074-2104-11e7-8052-561b506f885f.jpeg)

**Comment by koopahi** [comment] 2017-04-14 04:17
same issue.

**Comment by nhouser9** [comment] 2017-04-14 04:41
Same issue - happens on Linux and Windows, and on all browsers.

**Comment by pi-h** [comment] 2017-04-14 05:26
same issue

**Comment by chill37** [comment] 2017-04-14 06:52
same here whether chrome or safari

**Comment by charatobu** [comment] 2017-04-14 07:10
same issue

**Comment by emsnguyen** [comment] 2017-04-14 07:15
I had thought there were some problems with my algorithm. I am not alone!

**Comment by hopkinskong** [comment] 2017-04-14 07:34
Same, please fix it ASAP.

**Comment by wonderay** [comment] 2017-04-14 07:41
same issue
![cannot_submit](https://cloud.githubusercontent.com/assets/4599206/25036827/82cb4ecc-2128-11e7-8e4f-f4ef8ee29ab7.png)
username: wonderay
browser: chrome 57.0.2987.133
login: github

**Comment by s2k** [comment] 2017-04-14 08:06
Happens here as well.
On macOS using Safari.

**Comment by Chava** [comment] 2017-04-14 08:21
Same here

**Comment by Flowersnow** [comment] 2017-04-14 08:25
:(

**Comment by Wmitbrodt** [comment] 2017-04-14 08:33
same here :(

**Comment by salim-dev** [comment] 2017-04-14 08:37
:(

**Comment by duquesnay** [comment] 2017-04-14 08:48
Here also, Mac/Safari, Mac/Chrome, iPad/Safari, reload, log out, cache n cookie flush, etc

**Comment by vkarampinis** [comment] 2017-04-14 09:14
same here

**Comment by BIWhitfield** [comment] 2017-04-14 09:20
Same for me!

**Comment by adieCodes** [comment] 2017-04-14 09:22
+1

**Comment by toniocodo** [comment] 2017-04-14 09:28
+1

**Comment by eastabrooka** [comment] 2017-04-14 09:32
Same Issue. - I am saving them all in Notepad until its fixed.

**Comment by eastabrooka** [comment] 2017-04-14 09:32
+1 - Same problem

**Comment by clifflu** [comment] 2017-04-14 09:48
Could it be Ably CDN ? Got warning message `The Ably CDN URL you are using is deprecated because it does not contain a version number. Please see https://support.ably.io/solution/articles/3000063698` in the console. I'll install mockup proxy for verification.

**Comment by smiks** [comment] 2017-04-14 09:55
Same problem with this kata: https://www.codewars.com/kata/collatz-conjecture-3n-plus-1/train/python
Time: 143ms Passed: 150 Failed: 0
Output window is bordered in red.

notify:
{success: true, data: null}
data:null
success:true

run:
result:{serverError: false, completed: false,…}
assertions:{passed: 4, failed: 0, hidden: {passed: 0, failed: 0}}
completed:false

**Comment by le-minh-mulodo** [comment] 2017-04-14 10:08
+1 same here :(

**Comment by fliptv97** [comment] 2017-04-14 10:18
+1

**Comment by Voileexperiments** [comment] 2017-04-14 10:20
@clifflu: IIRC that was already happening in the past, so it shouldn't be the cause.

**Comment by sjgmr13** [comment] 2017-04-14 10:27
+1

**Comment by wardymate** [comment] 2017-04-14 10:36
+1

**Comment by prathapareddy** [comment] 2017-04-14 10:42
+1

**Comment by AwelEshetu** [comment] 2017-04-14 10:44
+1

**Comment by lynmuldrow** [comment] 2017-04-14 10:54
+1 - I'd really like to sign up and start the challenges! I can't get past the initial sign up test. 

![image](https://cloud.githubusercontent.com/assets/10834210/25041600/f8168b1e-20c5-11e7-888d-da9431961897.png)

**Comment by lelloman** [comment] 2017-04-14 10:56
+1

**Comment by prathapareddy** [comment] 2017-04-14 10:56
+1

**Comment by AwelEshetu** [comment] 2017-04-14 10:57
@lynmuldrow site is suffering from some problems. Try it again later.

**Comment by shnend** [comment] 2017-04-14 11:49
+1 (happy Easter holidays)

**Comment by kkavita92** [comment] 2017-04-14 12:03
+1

**Comment by Dagozba** [comment] 2017-04-14 12:06
+1

**Comment by kikofernandez** [comment] 2017-04-14 12:13
+1

**Comment by Mark-McCracken** [comment] 2017-04-14 13:00
+1

**Comment by intermike** [comment] 2017-04-14 13:05
+1

**Comment by MixalisV** [comment] 2017-04-14 13:08
+1

**Comment by kiririk** [comment] 2017-04-14 13:09
+1

**Comment by Lughino** [comment] 2017-04-14 13:27
+1

**Comment by laszloLaun** [comment] 2017-04-14 13:29
+1

**Comment by heavyfeather** [comment] 2017-04-14 13:34
same :(

**Comment by tonypnode** [comment] 2017-04-14 13:35
+1

**Comment by smahel** [comment] 2017-04-14 13:47
same for me

**Comment by kreafox** [comment] 2017-04-14 14:37
Same issue, can't submit solution.

**Comment by hammenm** [comment] 2017-04-14 14:40
Well I guess, they can put a label : "URGENT NOT WORKING"

**Comment by CharlieNoodles** [comment] 2017-04-14 14:41
It is working again for me

**Comment by Voileexperiments** [comment] 2017-04-14 14:49
It's now fixed! :D

**Comment by hammenm** [comment] 2017-04-14 14:51
I shouldn't have complain then. Good job! 👍

**Comment by shnend** [comment] 2017-04-14 14:54
working for me as well :))

**Closed** 2017-04-14 14:59 UTC

**Comment by siebenschlaefer** [comment] 2017-04-14 15:06
Thank you, @jhoffner!

**Comment by eastabrooka** [comment] 2017-04-14 15:28
[image: Inline images 1]
I am still experiencing problems. I don't think its fully restored yet ?

**Comment by mulveyj** [comment] 2017-04-14 17:16
It was still happening for me but logging out and then logging back in again got it going.

**Comment by jhoffner** [comment] 2017-04-14 17:20
@eastabrooka that looks like a different issue. May have been a server issue. Did you try to submit again?
