### ISSUE TITLE
Can't delete the Kata

### ISSUE THREAD

**Issue by FiveCrayFish973** [Codewars/codewars.com#1543] opened 2018-08-23 12:26 UTC
Alright so after opening #1542. I tried to delete the Kata that was causing the problem. But the best I could do was unpublish it. It won't let me delete the Kata for some reason. No matter what I do, it just gets stuck on the last part and doesn't delete it.

**Comment by kazk** [comment] 2018-08-24 08:19
Closing as duplicate of #1043.

**Closed by kazk** 2018-08-24 08:19 UTC
