### ISSUE TITLE
Unable to bookmark kata

### ISSUE THREAD

**Issue by kmjones77** [Codewars/codewars.com#1417] opened 2018-04-26 09:28 UTC
Hi,

I am unable to bookmark this kata:

http://www.codewars.com/kata/56d93f249c844788bc000002

Is there a reason for this?

EDIT:

This one is fine:
https://www.codewars.com/kata/56d931ecc443d475d5000003
This one doesnt work either:
http://www.codewars.com/kata/56d904db9963e9cf5000037d

Ken

**Comment by kazk** [comment] 2018-04-26 17:24
Probably caused by this:

> There is an issue with this not working on http. We don't force https on all pages due to some users having issues with iframes with the kata editor. For now the workaround should be to use https.
> https://github.com/Codewars/codewars.com/issues/552#issuecomment-243616335

Closing as duplicate.

**Closed by kazk** 2018-04-26 17:24 UTC
Labels: area/bookmark, duplicate

**Comment by kmjones77** [comment] 2018-04-27 07:16
OK thanks
