### ISSUE TITLE
https://www.codewars.com/users/sign_in :)

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#1341] opened 2018-03-26 14:12 UTC
Interesting behaviour:

I've notice that the user's profile page url profile this pattern `https://www.codewars.com/users/<user_name>` and also that the login page has the following url `https://www.codewars.com/users/sign_in`. Just for fun, I've tried to create a user called `sign_in` and surprisingly I could do it. IMO this shouldn't be possible.

The sign in page is not affected by this.

**Comment by Voileexperiments** [comment] 2018-03-26 15:00
IIRC all user-related pages are under `user` (e.g `user/edit`), so...

**Comment by anter69** [comment] 2018-03-28 09:22
Well, now that you have created the user "sign_in", this will not be a problem anymore :laughing:

**Comment by anter69** [comment] 2018-04-19 12:45
Not directly related to this issue, but unicode support for usernames has it's downsides -- see my fake jake account: [https://www.codewars.com/users/jhoffner](https://www.codewars.com/users/%CF%B3hoffner)

Suggested reading:
* https://en.wikipedia.org/wiki/Homoglyph
* https://en.wikipedia.org/wiki/IDN_homograph_attack

ps: I just rocketjumped to 4 kyu, by completing one single kata (cheating :-)

**Comment by kazk** [comment] 2018-04-27 00:46
Closing as duplicate of #150

**Closed by kazk** 2018-04-27 00:46 UTC
