### ISSUE TITLE
Not able to renew Codewars Red

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#1562] opened 2018-09-03 21:19 UTC
I've been trying to renew my Codewars Red membership off and on for over a month now with no success -- no matter which credit card I try, and I have a lot of them, when I click to pay, Stripe gives me a green checkmark, but after a pause Codewars pops up a message saying, "Subscription failure. Your card was declined." I've tried this with both Firefox and Chrome. A couple weeks ago I had posted about this in the Codewars Gitter, explaining the problem and asking if anyone had been able to renew their Codewars Red membership recently, but I didn't get any responses. I had also posted about some of my earlier attempts in comments on #1317 but I don't know if Codewars management sees comments on old issues, so I thought I would create a new issue to see if there's any update on when this may be working again or when there will be other ways to pay or what have you ...

**Comment by kazk** [comment] 2018-09-03 21:42
Sorry for the inconvenience and the lack of responses.

> I don't know if Codewars management sees comments on old issues

I do see comments on old issues, but I cannot help much with this one. I'm not sure if @jhoffner sees them because GitHub notification doesn't seem to work for him for some reason (I also have problems reaching him on GitHub :sweat_smile:).

Looks like you had similar issues before and you were able to resubscribe (https://github.com/Codewars/codewars.com/issues/1261#issuecomment-355779929). Do you have any ideas what was causing it? Are you using the same card?

**Comment by tachyonlabs** [comment] 2018-09-03 22:04
Thanks! What had happened in January -- https://github.com/Codewars/codewars.com/issues/1261#issuecomment-355779929 -- was
> I just made another attempt at resubscribing, using one of the same credit cards that I had tried with yesterday, and this time it worked just fine, and so my Codewars Red is back! But as to why it hadn't autorenewed last month, and why I was getting nothing but errors from Stripe yesterday, who knows ...
but this time, at least so far, the same approach of repeatedly trying different credit cards hasn't succeeded yet. I'm not remembering offhand which card finally worked that time after some rounds of not working -- maybe I will go through records to find out -- but I think I've basically tried all of them at one time or another in the last month, so it would have come up at least once.

**Comment by moonbrv** [comment] 2018-09-26 09:55
I did try 7 cards from different banks in my country, all cards declined...

maybe you know some international online bank which will accept my card and will give me some online card to pay for codewars?

**Comment by tachyonlabs** [comment] 2018-10-04 17:29
I just tried again with no change :-( ... I would do PayPal, send a check, whatever ...

**Comment by kazk** [comment] 2018-10-29 21:09
@tachyonlabs sorry for the delay. I'm currently in the process of taking over the project and just started to look into this issue.

In your case, payments are failing because your bank is declining with `do_not_honor`. Unfortunately, this is generic unknown reason and can be caused by lots of things. I don't think there's anything we (or Stripe) can do.

![image](https://user-images.githubusercontent.com/639336/47680429-03293b80-db84-11e8-80d9-94ab2f3e4017.png)
https://stripe.com/docs/declines/codes

---

I've also found that the card you used to get the subscription in January was expired when the subscription was renewing in July. We retry the transaction 3 days after a failure and cancel the subscription after 3 failures.

Is the card you're trying to use still valid?

**Comment by tachyonlabs** [comment] 2018-10-29 21:29
Thanks for getting back to me! I've got multiple credit cards and have probably tried them all with this at one time or another over the last several months, with no luck. Right now I just tried again with a card that I had used multiple times (in a coffeeshop) on Friday with no problem, which has an expiration date of 04/19, but once again it was declined when I tried to get six months of Codewars Red. If the last card I had successfully subscribed with has since expired, probably they sent me a new card with a new expiration date and security code in the meantime. I should go through my statements later when I have more time (I think I said that before, oops) and figure out which card it was that worked last time.

**Comment by kazk** [comment] 2018-10-29 21:43
> Right now I just tried again with a card that I had used multiple times (in a coffeeshop) on Friday with no problem, which has an expiration date of 04/19

Your most recent transaction failure at 2:19 PM was with a card that expires on 06/18 according to the Stripe dashboard.

**Comment by tachyonlabs** [comment] 2018-10-30 15:31
Well, something's going haywire ... I used that same card again yesterday evening at Trader Joe's with no problem, and it definitely has an expiration date of 04/19. I will try again now and you can see if it again gets reported as 06/18 or as something else. BTW, this is a MasterCard, but in the past I've tried Visa, Discover, and American Express cards also.

**Comment by tachyonlabs** [comment] 2018-10-30 15:39
Once again it was declined, but as you can see (except for the last four digits which I blacked out in my screen capture), when I clicked SUBSCRIBE the payment widget came up pre-filled with the card details I had entered yesterday, including the 04/19. 
![image](https://user-images.githubusercontent.com/2389786/47730373-41276d80-dc1f-11e8-8b83-b83436c7c8fc.png)

**Comment by tachyonlabs** [comment] 2018-10-30 15:41
(Though from what you say I'm not sure if the 06/18 is what Stripe thinks I entered, or what Stripe thinks what I entered should match.)

**Comment by kazk** [comment] 2018-10-30 17:45
This is really odd. It's showing the same info again.

> BTW, this is a MasterCard, but in the past I've tried Visa, Discover, and American Express cards also.

On the Stripe dashboard it's Visa and that's the only card associated with you.
I'll look into it and let you know. Maybe removing the card will help.

**Comment by kazk** [comment] 2018-10-30 18:14
I found the bug. It's ignoring the updated information when a user had a subscription before and using the information stored in Stripe to create a new subscription instead.

So it's failing for you because it's trying to get a subscription with the card you used in the past that's stored in Stripe.

I'll try to fix this soon.

**Comment by tachyonlabs** [comment] 2018-10-30 18:32
Great, thanks!

**Comment by kazk** [comment] 2018-10-30 21:21
@tachyonlabs I've deployed the fix. Can you try again? It shouldn't use the old card anymore at least.

**Comment by tachyonlabs** [comment] 2018-10-30 21:43
It works, yay! My profile looks all cool again! :-)

**Comment by kazk** [comment] 2018-10-30 21:47
Thanks for confirming. I'll close this as fixed.
Sorry for the inconvenience and the delay.

**Closed by kazk** 2018-10-30 21:47 UTC
Labels: area/payment, kind/bug

**Comment by kazk** [comment] 2018-10-30 22:51
@moonbrv 

> I did try 7 cards from different banks in my country(Ukraine), all cards declined...

Can you try again? This bug was preventing users to use different card so it's possible that other 6 works.

**Comment by moonbrv** [comment] 2018-10-31 14:03
@kazk It works, thank you very much!!!

**Comment by kazk** [comment] 2018-10-31 16:20
Great! Sorry for the inconvenience and thanks for your support.
