### ISSUE TITLE
Unknown Server Error

### ISSUE THREAD

**Issue by hilzmax** [Codewars/codewars.com#1959] opened 2019-10-19 09:49 UTC
I get the error for a while now. I tried with multiple browsers (chrome,edge,firefox,ie).

First attempt with a new browser:
I login to codewars with my credentials ==> get redirected to dashboard ==> get 'Unknown Server Error'

Retry with that browser (reproduced every time I tried since):
I go to URL: https://www.codewars.com ==> get redirected to dashboard ==> get 'Unknown Server Error'

My codewars username is "txtsxm".
Please help.

**Comment by kazk** [comment] 2019-10-21 16:47
> I get the error for a while now.

Do you remember when this started?

> I login to codewars with my credentials ==> get redirected to dashboard ==> get 'Unknown Server Error'

Can you tell me what happens if you directly go to other pages (e.g., https://www.codewars.com/users/txtsxm) after getting `Unknown Server Error`? Does the page load? If it does, are you logged in? This will tell me if this error is related to dashboard.

Is this reproducible using incognito/private window? Without any cookies/extensions.

**Comment by hilzmax** [comment] 2019-10-21 19:23
- I do not remember when it started but it must be more than a month ago (I originally replied to #1765 29 days ago and I don't recall playing codewars this year)
- I also get the unknown server error if I go directly to my page or follow a link to a kata from a weekly_coding_challenges mail, e.g.:
https://www.codewars.com/kata/regular-expression-for-binary-numbers-divisible-by-5?utm_source=newsletter&utm_medium=email&utm_campaign=weekly_coding_challenges&utm_term=2019-10-21
- I think I am logged in
- I can go directly to my page and other pages while I am not logged in (and every thing looks fine). But as soon as I log in I get the error regardless from where I log in.
- reproducible in incognito/private window with disabled extensions and disabled plugins (I think cookies are disabled in incognito/private, I might have to check that later)

**Comment by kazk** [comment] 2019-10-21 20:12
Thanks. I found some data issue in your account and fixed it. Can you try again?

**Comment by TheGuy566** [comment] 2019-10-21 21:30
I just started getting a similar error around half an hour ago
"undefined method `username' for nil:NilClass"
My username is theguy678

**Comment by hilzmax** [comment] 2019-10-21 21:33
Thanks. The fix worked. :)
-I will leave the topic open because theguy678 has an open issue now-

**Comment by kazk** [comment] 2019-10-22 01:00
@TheGuy566 I've made some changes. Can you try again?

**Comment by TheGuy566** [comment] 2019-10-22 01:09
I can now assess katas properly but my home section where random kata should be shown says 
"There are no challenges available for the selected language."
even though my selected language is Python which I am currently 4kyu in.

**Comment by kazk** [comment] 2019-10-22 01:20
@TheGuy566 can you open a new issue with a screenshot? I'll close this one because the original issue is resolved.

**Closed by kazk** 2019-10-22 01:20 UTC
Labels: area/account, issue/server-error-nil, kind/bug

**Comment by TheGuy566** [comment] 2019-10-22 02:28
The issue is now resolved. Thanks for your help!
