### ISSUE TITLE
nil can't be coerced into Integer

### ISSUE THREAD

**Issue by Neuly** [Codewars/codewars.com#1802] opened 2019-04-23 06:10 UTC
#### Describe the bug
I am not able to open the page, where I can search for katas. I always get the error message 500 and the message: nil can't be coerced into Integer

#### To Reproduce

1. Go to 'https://www.codewars.com/kata/latest/my-languages'
2. The internal Server error appears

I think this error is dependent on my user, due to the fact that a friend of mine can open this page without any problems.

#### Expected Behavior

Seeing the page to search and choose katas.

#### Contexts

Please complete the following information:

- Codewars username: Neuly
- OS: Win 7
- Browser: IE 11, Chrome 73.0.3683.103

**Comment by ivanji** [comment] 2019-04-23 06:15
Same here. Tested on different browsers.

**Comment by hobovsky** [comment] 2019-04-23 06:34
You're 10 hours late: #1801 ;)

**Comment by mosleymos** [comment] 2019-04-23 07:44
Same here. Can't search any kata.

**Comment by alzca1** [comment] 2019-04-23 09:39
It happens the same to me.

**Comment by robert-dopieralski** [comment] 2019-04-23 10:10
same here

**Comment by IShadowmaNI** [comment] 2019-04-23 10:34
same here actually...

**Comment by EricsonWillians** [comment] 2019-04-23 12:43
Same here! :)

**Comment by dankgen-tobias** [comment] 2019-04-23 13:13
Same for me, too!

**Comment by brudolce** [comment] 2019-04-23 13:14
yup, same issue here

**Comment by Chrono79** [comment] 2019-04-23 13:16
Temporary workaround:

https://www.codewars.com/kata/search/?q=&r%5B%5D=-7&r%5B%5D=-6&r%5B%5D=-5&r%5B%5D=-4&r%5B%5D=-3&r%5B%5D=-2&r%5B%5D=-1

will get you all katas except 8 kyu ones.

**Comment by nomennescio** [comment] 2019-04-23 14:28
Same issue. Chrome browser.

**Comment by kazk** [comment] 2019-04-23 17:19
Closing as duplicate of #1801

**Closed by kazk** 2019-04-23 17:19 UTC
