### ISSUE TITLE
Cannot sign-up using Github

### ISSUE THREAD

**Issue by ehdgua01** [codewars/codewars.com#2396] opened 2021-06-02 05:25 UTC
**Describe the bug**
I faced an `Internal Server Error` when I sign up codewards.com using Github 

**Expected behavior**
Sign up codewars.com

**Screenshots**
![스크린샷 2021-06-02 오후 2 22 35](https://user-images.githubusercontent.com/22000773/120428160-222c8180-c3ae-11eb-8a9c-d29f727c28b5.png)

**Browser**
If applicable, please provide your browser information.

- OS: macOS
- Browser: chrome
- Version 90.0.4430.212

**Comment by kazk** [comment] 2021-06-02 05:55
I just tried signing up and worked fine :/ However, I do see a relatively high number of errors related to this. I'll look into it.

At which point do you get this error page? When you click "Link your GitHub" after solving the challenge? Or when you click "Enlist"?

**Comment by ehdgua01** [comment] 2021-06-02 07:19
I got this error page when I click "Link your Github Account" button
![스크린샷 2021-06-02 오후 4 15 29](https://user-images.githubusercontent.com/22000773/120439754-d71a6a80-c3bd-11eb-893d-7565af207055.png)

So, I tried signing up without Github linking then I got this error messages
![스크린샷 2021-06-02 오후 4 17 00](https://user-images.githubusercontent.com/22000773/120439888-fc0edd80-c3bd-11eb-90be-2ebedcc251ec.png)

**Comment by kazk** [comment] 2021-06-02 07:36
The error occurs when there's already a Codewars user with the same email address as the linked GitHub account (the primary email address). This validation error is not handled and causing internal server error. I'll fix it.

Looks like you already have an account you had created in 2017 https://www.codewars.com/users/ehdgua01
You can sign in and link your GitHub in account settings, or delete the account to create a new one. If you don't remember your password, you can reset from the login page.

**Comment by ehdgua01** [comment] 2021-06-02 15:51
Thank you, I can now log in to my account.
If you want to close this issue you do :)

**Comment by kazk** [comment] 2021-06-16 21:39
I forgot to close this. The error caused by non-unique email was fixed last week.

**Closed by kazk** 2021-06-16 21:39 UTC
Labels: kind/bug
