### ISSUE TITLE
The protocol switches from HTTP to HTTPS if one visits the account settings

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#97] opened 2015-06-08 19:59 UTC
There's something strange going on with the `/^https?:/` links on the settings page. Here are the steps to reproduce the behaviour:
1. Go to the dashboard.
2. Go to your **account settings**.
3. Go to either the kata/kumite editor or your language/account settings.
4. ??? (HTTPS issues, language settings don't load at all, account settings after some time)

**Comment by kazk** [comment] 2017-03-30 01:46
Is this fixed? I couldn't reproduce.

**Comment by bkaestner** [comment] 2017-03-30 05:12
I go with "no", since https://codewars.com won't redirect.

Am 30.03.2017 03:46 schrieb "kazk" <notifications@github.com>:

**Comment by kazk** [comment] 2017-03-30 06:34
Thanks. So the issue is redirection from `https://codewars.com` to `https://www.codewars.com` is not working.

**Comment by kazk** [comment] 2017-03-30 16:24
Closing this because now it redirects. See also #166.

**Closed by kazk** 2017-03-30 16:24 UTC
Labels: bug
