### ISSUE TITLE
Unparsed Markdown in Morse kata

### ISSUE THREAD

**Issue by Ryuno-Ki** [codewars/codewars.com#2092] opened 2020-04-09 16:15 UTC
The link to the previous kata is not parsed properly:

![markdown-morse](https://user-images.githubusercontent.com/3097194/78916604-01a8b600-7a8e-11ea-9ec0-6056595a6533.png)

Please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue.

No idea, where that discourse page shall live. I don't even no about a discourse instance.

**Comment by kazk** [comment] 2020-04-09 17:57
Closing as duplicate of #1927.
I've fixed this one, but please let the kata author know and let them or other contributors fix them by commenting on the kata.

> No idea, where that discourse page shall live. I don't even no about a discourse instance.

It's not a Discourse service. Each kata has discussion page.

Accessible from the kata page:
![image](https://user-images.githubusercontent.com/639336/78925288-11a1a500-7a50-11ea-9ce5-024672434507.png)
Or from the trainer:
![image](https://user-images.githubusercontent.com/639336/78925526-6fce8800-7a50-11ea-9398-88d4cbc6e226.png)
Or just appending `/discuss` to the kata URL.
https://www.codewars.com/kata/54b72c16cd7f5154e9000457/discuss

**Closed by kazk** 2020-04-09 17:57 UTC
