### ISSUE TITLE
Unable to create a kumite

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#543] opened 2016-08-27 12:04 UTC
I'm not sure if it's a duplicate of another issue.
When I try to create a kumite in any language, Save, Publish and Run buttons are disabled. There's the following error message in the console: 
```
TypeError: this.setupCode is undefined
...ditor.setValue(this.fields.code.value),this.setupCode.setValue(this.fields.setup...
https://www.codewars.com/assets/bundles/code_snippets-2cf0a6c83aed77dfd9414a52178a639c.js
```

**Comment by jhoffner** [comment] 2016-08-27 23:47
Not around to verify but this should be resolved now. 

Get Outlook for iOS




On Sat, Aug 27, 2016 at 5:04 AM -0700, "error256" <notifications@github.com> wrote:












I'm not sure if it's a duplicate of another issue.

When I try to create a kumite in any language, Save, Publish and Run buttons are disabled. There's the following error message in the console: 

TypeError: this.setupCode is undefined
...ditor.setValue(this.fields.code.value),this.setupCode.setValue(this.fields.setup...
https://www.codewars.com/assets/bundles/code_snippets-2cf0a6c83aed77dfd9414a52178a639c.js

**Closed** 2016-08-28 02:06 UTC

**Comment by error256** [comment] 2016-08-28 09:15
That error doesn't appear anymore but the buttons are still disabled. Now I get HTTP 200 from `rest.ably.io/.../connect?...` and then aborted connection `from rest.ably.io/.../recv?...`

**Comment by jhoffner** [comment] 2016-08-28 15:53
Did you try adding code? Buttons don't enable until there is something to save

**Comment by error256** [comment] 2016-08-28 17:21
Oh, sorry, I forgot it. It works now.
