### ISSUE TITLE
BUG: Creating Kata: Language undefined is not supported.

### ISSUE THREAD

**Issue by plasticbottle** [codewars/codewars.com#1323] opened 2018-03-12 13:26 UTC
This issue closely resembles issue #849 

I have created a Kata which is supposed to be solved in SQL, and when trying to update Example Test Cases, I encounter an error:

![bug1](https://user-images.githubusercontent.com/28384630/37285948-250775d4-2633-11e8-81bf-89148128af29.jpg)

I am unable to select SQL as a language (or any language for that matter).

If I try to run some code, I get the following error:

![bug2](https://user-images.githubusercontent.com/28384630/37286036-61510b86-2633-11e8-98ef-db5741cb3e0f.jpg)

Link to kata: https://www.codewars.com/kata/5aa3ef1efd5777f3870004f0

These errors persist through different browsers (Firefox, Chrome) and through different platforms (Debian Jessie, Windows 7)

I have added a message to the description to not attempt the Kata, as the bug causes it to be unsolvable.

Please let me know if you need more information.

**Comment by error256** [comment] 2018-03-13 16:18
Did you have available in a language other than SQL at some point?

**Comment by plasticbottle** [comment] 2018-03-13 18:01
@error256 No, the Kata is/was intended to be SQL specific

**Comment by plasticbottle** [comment] 2018-04-23 09:59
@kazk Hi, would you be able to pick this up?
Not that I am in a rush, but I would like to know what went wrong in the end.

**Comment by plasticbottle** [comment] 2018-04-24 10:06
I apologize for the tone in my earlier post, in the internet things seem more rude than intended. I am seeing the issue every time from any browser and any machine or operating system. (Win 7, Debian Jessie, Cent OS 7)

**Comment by Voileexperiments** [comment] 2018-04-24 10:09
It's not a client-side problem, so changing browser/machine wouldn't help.

**Comment by plasticbottle** [comment] 2018-04-29 15:25
That is right, it is why I asked for help from the maintainers of the website. I just don't know what type of information would be helpful for them, if anything.

**Comment by kazk** [comment] 2018-04-29 18:59
@plasticbottle your kata have the language SQL (see the screenshot above) when I open it. I just don't know why this happened or happening because I don't work on Codewars itself.

By the way, The example tests fail because `results` is not defined.

**Comment by plasticbottle** [comment] 2018-04-30 09:39
@kazk 
I don't think that the test is completed because I encountered this error while writing it, and had not had the chance to finish it (not having the language defined prevents me from saving any further changes)

If you have managed to open it, are you able to completely destroy the kata and I can rewrite it again? I hope to add better ones in the future, but wanted to see how the system works.

**Comment by kazk** [comment] 2018-04-30 17:43
@plasticbottle 

> If you have managed to open it

So it still doesn't have language defined when you open it? That's odd :/
Can you try opening the trainer https://www.codewars.com/kata/sql-a-simple-sum-query/train/sql logged out? (after logging out or use incognito window)

> I figure that this must be some kind of one off problem, given that most users don't have any issues with submitting new katas.

Yeah, it's one of the long standing issues and difficult to reproduce.

**Comment by plasticbottle** [comment] 2018-05-01 14:14
@kazk Thanks for looking into the issue, I can open the kata in an incognito window, and I can pass both the "Test Cases" and the "Example Test Cases".

However, once logged in, I get the following...
![bug4](https://user-images.githubusercontent.com/28384630/39475866-2dde4afc-4d84-11e8-99c6-daaa9a383514.jpg)

**Comment by plasticbottle** [comment] 2018-05-01 14:37
Also, there might be some issues with the layout, as it is rapidly changing between "h" and "v". Not sure if this is related to the same error though (I'd guess it is not)

**Comment by kazk** [comment] 2018-05-01 17:53
So this only happens to you when you're logged in :/

Does anything show in the developer console when opening that page (before submitting)? That 422 is not important here because it just means that the request payload is missing language. I'd like to know why the page doesn't have the language set when you open it while logged in.

**Comment by plasticbottle** [comment] 2018-05-01 19:54
:@kazk

Just a warning appears. It is triggered every time I try to select a language for the kata though. (language selector marked by a crudely drawn red arrow)

![bug5](https://user-images.githubusercontent.com/28384630/39490695-d7b60388-4db3-11e8-8974-a5ff79149ad8.jpg)

What appears in the console is the following:

![bug6](https://user-images.githubusercontent.com/28384630/39490734-fe80d5e2-4db3-11e8-901a-d7c3fb6ea533.jpg)

**Comment by kazk** [comment] 2018-05-01 20:09
Hmm, this is really odd. I have no idea what can cause this to happen only to you. That Ably warning should be irrelevant.

---

@jhoffner can you look into this? This is very similar to #849 closed with comment:

> Was a data issue. Should be fixed. Hopefully it doesn't pop back up.
> https://github.com/Codewars/codewars.com/issues/849#issuecomment-284938138

**Comment by kazk** [comment] 2018-08-24 08:37
@plasticbottle I'm sorry no one gave you updates.
Is this still happening? And only reproducible when you're logged in?

**Comment by plasticbottle** [comment] 2018-09-30 20:46
Hey, @kazk thanks for getting back to me about this, yes, the issue is still outstanding, no change from the original situation.

**Comment by kazk** [comment] 2018-10-01 00:41
What do you see in the kata editor? (https://www.codewars.com/kata/5aa3ef1efd5777f3870004f0/edit/sql)
Is the language blank there as well?

It's so weird that this only happens to you and when only you're logged in.

**Comment by plasticbottle** [comment] 2018-10-01 05:28
The language is `SQL` `PostgreSQL 9.6` in the editor. 

But if I send the Kata to preview, I get the same screen as in the opening comment of this thread.

**Comment by kazk** [comment] 2018-10-01 17:35
What happens if you "reset" in the trainer (preview)?

This issue is different from #849 because I see `sql` in the database and it only happens when you're logged in :/

**Comment by plasticbottle** [comment] 2018-10-01 22:43
Hi. @kazk unfortunately no change occurs. Is `sql` the only entry you see in the database for the kata? Is there no second entry with `NULL` values or empty values?

**Comment by kazk** [comment] 2018-10-01 22:56
No, just `sql`. I don't think this is database issue because it's working correctly when I open it, both logged in and logged out.

There might be something stored locally for you that's affecting this.
In Chrome Developer Tools, can you check if you have any local storage with key `5aa3ef1efd5777f3870004f0`? Go to `Storage > Local Storage` under `Applications` tab and entering `5aa3ef1efd5777f3870004f0` to filter:

![image](https://user-images.githubusercontent.com/639336/46320273-6e3a1f00-c592-11e8-8484-cecbb63dc9de.png)

Also, have you tried other browsers? If not, can you try and see if anything changes?

**Comment by plasticbottle** [comment] 2018-10-01 22:58
I tried in the past from three computers, one using Debian Jessie, one using Cent OS 7, and one using Windows 7. Tried Chrome and Firefox on both, issue persists.

**Comment by kazk** [comment] 2018-10-01 23:06
Thanks. I'll check if there's anything is done differently when loading the kata data for the author.

**Comment by plasticbottle** [comment] 2018-10-01 23:07
Checked the storage as you suggested, but this value is not found there.

**Comment by plasticbottle** [comment] 2018-10-01 23:19
@kazk Quite curiously, I was able to access and complete the sample tests on the kata as a non-registered user (but that way it can not be updated/edited)

**Comment by plasticbottle** [comment] 2018-10-01 23:30
Yes the main tests are broken, which was why I made this issue, they cant be updated. If this is too hard to fix, I propose deleting the kata and making a new one, because this is hardly worth your time.

**Comment by plasticbottle** [comment] 2018-10-01 23:32
On my personal account, I cant complete the kata though

**Comment by kazk** [comment] 2018-10-01 23:51
What's preventing you from updating?
You wrote "The language is SQL PostgreSQL 9.6 in the editor." in https://github.com/Codewars/codewars.com/issues/1323#issuecomment-425793391

Can you try saving **without going to preview**? I don't think many users use that and there might be some weird bug there. (I'm assuming you got the confirmation of unsaved changes and continued.)

> If this is too hard to fix, I propose deleting the kata and making a new one,

A kata cannot be deleted after solutions are submitted. This is because it'll affect multiple users' stats and I don't think that's implemented. The closest way at the moment is to retire the kata and create a new one.

> because this is hardly worth your time.

I'm taking over this project and I need to fix/understand all the mess accumulated over the years. So I'm using this as an opportunity to dig into some of the code that I haven't read yet. I'll need to study the code base either way so it's ok.

**Comment by plasticbottle** [comment] 2018-10-02 09:53
@kazk 

> I'm taking over this project and I need to fix/understand all the mess accumulated over the years. 

Well then I'll be glad to try and assist you on figuring this one out :)

When I loaded the page and pressed save, I got the following results:

![image](https://user-images.githubusercontent.com/28384630/46341824-e9a6d980-c641-11e8-82c8-0d3094591d03.png)

However, I dont think that the uncaught type error is relevant, the only response I get strictly at saving is `missing metadata for fortran`.

**Comment by plasticbottle** [comment] 2018-10-02 18:44
Not sure. If I save, and then go to preview the kata

I get this
```ruby
# TODO: replace with your own tests (TDD), these are just how-to examples to get you started.

# Ruby/Rspec/Sequel Example:
# While the code section is pure SQL, for testing we use Ruby & Rspec.
# Sequel (https://github.com/jeremyevans/sequel) is used to setup the database and run queries.
# The connection is already made for you, use DB to access.

DB.create_table :items do
  primary_key :id
  String :name
  Float :price
end

items = DB[:items] # Create a dataset

# Populate the table
items.insert(:name => 'a', :price => 10)
items.insert(:name => 'b', :price => 35)
items.insert(:name => 'c', :price => 20)

# calling run_sql will print the results and return them so that you can test data within them.
# if you want to test different sets of data, then its best to move this code into its own top level describe
# block. If you are only testing one set though, its better to set the results before you enter a describe block
# so that the results are presented at the top of the output.
results = run_sql

describe :items do
   it "should return 3 items" do
    expect(results.count).to eq 3
   end
end

# Other tips about using run_sql:
# The SQL/code section supports multiple statements, seperated of course by a ";".
# When multiple SELECT statements are issued:
#    run_sql will return an array of arrays, unless only one SELECT statement returned results
#    INSERT and UPDATE results will not be included in the list
#    SELECT statements that return no results will not be included in the list
```

Instead of the actual test cases that I wrote.

**Comment by plasticbottle** [comment] 2018-10-02 18:45
Even though in the editor section, the test cases I wrote do appear correctly.

**Comment by kazk** [comment] 2018-10-02 18:51
So the language is selected now? Just the test is not correct?

**Comment by plasticbottle** [comment] 2018-10-02 18:53
No, the language also still looks the same as in comment 1 of this thread. However, I thought this additional information might somehow help.

**Comment by kazk** [comment] 2018-10-02 19:01
I've made some minor formatting changes.

Can you try opening https://www.codewars.com/kata/sql-a-simple-sum-query/train/sql and see what shows up after reset?
When I first opened it, it showed the sample tests before the formatting change and resetting made the new version to show.

**Comment by plasticbottle** [comment] 2018-10-02 19:10
A notification about your edit appeared, but what displays is the same as described in my previous comment.

**Comment by kazk** [comment] 2018-10-02 19:15
Even after you reset in the trainer?

**Comment by plasticbottle** [comment] 2018-10-02 20:01
After reset, the trainer becomes completely blank. No initial solution, no test cases

**Comment by plasticbottle** [comment] 2018-10-02 20:07
![image](https://user-images.githubusercontent.com/28384630/46373867-1d582280-c687-11e8-98a0-6385a8078ffb.png)

**Comment by kazk** [comment] 2018-11-05 03:52
@plasticbottle can you check if anything changed?

I can't think of any reason why this happens only to you at the moment, but Codewars has lots of weirdness so anything is possible. I've fixed many bugs last month so I'm hoping this is also resolved somehow. If not, I'll continue to keep this in mind while digging further.

**Comment by plasticbottle** [comment] 2018-11-05 08:34
Hey @kazk thanks for the update :) Unfortunately no change yet, just checked right now. Issue is exactly in the same state as it has been up to this point.

**Comment by Voileexperiments** [comment] 2018-11-05 08:49
Have you tried a hard refresh (Ctrl+F5)? The javascript files and cached and so might not be updated unless you flush the cache.

**Comment by plasticbottle** [comment] 2018-11-06 13:35
Yep, I did.

**Comment by plasticbottle** [comment] 2018-11-20 08:02
@kazk The issue is still not resolved by this. However, I think you should not focus on this issue for now. I see there are many more urgent things to deal with.

**Comment by kazk** [comment] 2018-11-20 08:10
Yeah, I've been doing a nightmarish task right now :laughing: I sometimes need a break from it so I look into different issues.
My latest guess is that this has something to do with the frontend which I haven't really touched yet. I'll let you know if I find anything, but I have no idea when I'll come back to this at the moment.

**Comment by plasticbottle** [comment] 2019-03-15 11:39
Hey. Was there any update on this one? (No rush, just curious about the status)

**Comment by kazk** [comment] 2019-03-15 20:19
No, sorry. I'll close this when it's fixed.

**Comment by kazk** [comment] 2019-03-22 04:19
@plasticbottle there was some data that looked corrupted so I deleted it. Can you try if anything changed?

**Comment by plasticbottle** [comment] 2019-03-26 15:17
@kazk seems to be still broken

**Comment by kazk** [comment] 2020-01-08 20:34
@plasticbottle 
I think I was able to finally fix this. There was some corrupted data stored.
Sorry it took so long.
Please let me know if this is still happening, so I can reopen.

**Comment by plasticbottle** [comment] 2020-03-06 19:40
@kazk Sorry for the extremely late reply. Just checked, unfortunately the bug persists.

**Comment by kazk** [comment] 2020-03-06 19:41
I guess it's a different issue from #2003 then. Thanks for letting me know.

**Comment by plasticbottle** [comment] 2020-03-09 20:54
Actually I get such an error message too as in the issue you referenced, but I am not sure to what extent are API responses generic. Is it possible to delete and re-create the kata entirely? I suspect that the SQL language itself is fine, just something strange is bugging this particular kata.

**Comment by kazk** [comment] 2022-06-17 21:53
Had a similar data issue as https://github.com/codewars/codewars.com/issues/1291#issuecomment-1159197648

**Closed by kazk** 2022-06-17 21:53 UTC
Labels: kind/bug, area/data
