### ISSUE TITLE
Submit button hide when browser is in maximize size

### ISSUE THREAD

**Issue by Rafellus** [Codewars/codewars.com#1505] opened 2018-07-04 13:11 UTC
When doing a kata training on a maximized (using chrome), the submit button and "run sample test" go all the way down in the page. If I put resized manually, the button fits.

**Comment by anter69** [comment] 2018-07-04 15:33
@kazk same as issue #1214, it should be closed

**Comment by kazk** [comment] 2018-07-04 22:07
Closing as duplicate of #1214

**Closed by kazk** 2018-07-04 22:07 UTC
Labels: duplicate
