### ISSUE TITLE
Handling of nested formatting markup is inconsistent between editor, preview, and final rendering of a comment.

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#1617] opened 2018-11-02 09:46 UTC
#### Description
Handling of nested formatting markup is inconsistent between editor, preview, and final rendering of a comment. Editor and preview seems to handle markup correctly, while submitted comment seems to miss parts of its markup.

#### To Reproduce
Create a large paragraph of text marked as italics. Mark one word of this paragraph as bold. Try different markup variants: "\_text \*bold\* text\_" or "\*text \*\*bold\*\* text\*" or " \_text \*\*bold\*\* text\_" . All of these seem to be handled correctly in editor itself and in editor preview.

#### Expected Behavior
Text formatted as "_text **bold** text_" .

#### Screenshots

For "\_text \*bold\* text\_":
Editor:
![cwsshot31](https://user-images.githubusercontent.com/23709795/47907598-dcbd1600-de8b-11e8-9a63-127a00bc7012.png)

Preview:
![cwsshot32](https://user-images.githubusercontent.com/23709795/47907599-dd55ac80-de8b-11e8-910b-eb47c0e79654.png)

Rendered comment:
![cwsshot33](https://user-images.githubusercontent.com/23709795/47907601-dd55ac80-de8b-11e8-9291-25eb1c988635.png)

For "\*text \*\*bold\*\* text\*":
Preview:
![cwsshot34](https://user-images.githubusercontent.com/23709795/47907602-dd55ac80-de8b-11e8-8088-5f573333b6d1.png)

Rendered comment:
![cwsshot35](https://user-images.githubusercontent.com/23709795/47907604-dd55ac80-de8b-11e8-8b03-516d9e3791c4.png)

#### Contexts
Win 10, Opera browser 56.0.3051.52.

**Comment by Voileexperiments** [comment] 2018-11-02 15:05
#1441?

Also AFAIK lots of Markdown implementations are not up to spec with the GitHub flavor (which makes the most sense IMO). Like the one in StackOverflow...

**Comment by hobovsky** [comment] 2018-11-02 15:20
My intention was to put more impact on the fact that markup itself seems to work for CW, because two on three cases it's handled correctly (or at least it seems so). For discourse editor it works ok, for editor preview it works ok, it's 'just' final result which looks off. That's what leads me to thinking that it's some smaller issue than implementation of markup being incorrect/'underimplemented' in general.

But you are probably right, comment editor and comment display are probably handled in two completely separate ways.

**Comment by kazk** [comment] 2019-01-28 10:53
Closing as duplicate of #1640

**Closed by kazk** 2019-01-28 10:53 UTC
Labels: area/markdown, duplicate, kind/bug
