### ISSUE TITLE
String.prototype.repeat is broken

### ISSUE THREAD

**Issue by N0ps32** [Codewars/codewars.com#195] opened 2015-10-14 00:01 UTC
The ES6 String.prototype.repeat function does not exist when running tests.

```
let ipToInt32 = ip => parseInt(ip
      .split('.')
      .map(n => (n * 1).toString(2))
      .map(s => s.length > 7 ? s : '0'.repeat(8 - s.length) + s)
      .join('')
  ,2)

ipToInt32("128.32.10.1");
```

The code above runs perfectly fine in the latest chrome version but returns

```
TypeError: Object 0 has no method 'repeat'
       at Array.map
    at ipToInt32
```

on the website instead the expected value (2149583361).

**Comment by jhoffner** [comment] 2015-10-18 21:55
Labeled it as an enhancement since babel does not seem to support this out of the box. We may need to include a specific polyfill node package

**Comment by kazk** [comment] 2017-03-28 00:53
Confirmed this using Node v0.10.33/Babel, but closing because Node v6 is available now.
We should also start looking into removing Node v0.10.x as it reached end-of-life status on 2016-10-31. nodejs/LTS.

**Closed by kazk** 2017-03-28 00:53 UTC
Labels: enhancement
