### ISSUE TITLE
"Check the exam" doesn't accept final submit

### ISSUE THREAD

**Issue by wavecycle** [Codewars/codewars.com#1812] opened 2019-05-07 17:46 UTC
I selected the 1st challenge in the email "Check the exam" and completed the initial testing successfully. There after I selected "submit final" and was taken to this dialogue:

> Solutions have been withheld
> Since you have not yet solved this kata we have hidden the solutions from you. If you choose to view the solutions you will forfeit your eligibility to earn honor/rank progress for this kata.

I went back several times to make sure I hadn't made any mistakes. My code below:

`return max(sum([0 if y == '' else 4 if x == y else -1 for x, y in zip(arr1,arr2)]), 0)`

**Comment by kazk** [comment] 2019-05-07 17:48
Closing as a duplicate of #1683. Submitting again _might_ get it accepted.

**Comment by wavecycle** [comment] 2019-05-07 17:49
I went back to try again but 1st reset the code and this time it worked.

**Closed by kazk** 2019-05-07 17:48 UTC
Labels: duplicate
