### ISSUE TITLE
STDOUT broken for newlines / HTML?

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#960] opened 2017-05-09 12:42 UTC
I am authoring a new Java Kata but when I run it the STDOUT test output is not behaving as expected.

```
System.out.println("AAA"); 
System.out.println("\n\n\n");  // doing nothing?
System.out.println("BBB"); 
```

is outputting just as 2 lines in the log

> AAA
> BBB

AND

```
System.out.println("AAA"); 
System.out.println("<hr>");  // not rendering
System.out.println("BBB"); 
```

is outputting without rendering the HTML horizontal line

> AAA
> &lt;hr&gt;BBB

**Comment by jhoffner** [comment] 2017-05-09 17:33
It does look like additional empty new lines are being collapsed, I'll look into that. I'm not sure how to fix it though since the issue is most likely that each line is considered a new "data" item and since it's blank, it's ignored. If I change this so that it works how you would expect then I'm pretty sure the display output will look odd for a lot of challenges. 

The HR tag was not in the whitelist of allowed html auto detect elements. I can add that. However HR's are also not styled so they don't actually do anything. That needs to be fixed as well. 

In the meantime if you need to have multiple line breaks in your logs you can either use HTML `<br>` or our special token for combining multi-line content into one line of data, which is `<:LF:>`.

**Comment by dinglemouse2250** [comment] 2017-05-09 21:05
> If I change this so that it works how you would expect then I'm pretty sure the display output will look odd for a lot of challenges.

Actually I don't know if this is different to before or not... I only tried it because the &lt;hr&gt; was not working like it used to. Really it's only the hr I am missing. TIA

**Comment by kazk** [comment] 2019-02-25 23:24
Closing because `<hr>` is rendered now.
![image](https://user-images.githubusercontent.com/639336/53375899-6ef09a80-3911-11e9-83ae-f935f0817d0e.png)

**Closed by kazk** 2019-02-25 23:24 UTC
Labels: area/test-output, kind/bug
