### ISSUE TITLE
cheats

### ISSUE THREAD

**Issue by mediocrity1** [codewars/codewars.com#2259] opened 2020-10-25 17:41 UTC
this python code passes almost all the kata:
class functname:
    def __init__(self, *args):
        pass
    def __eq__(self, other):
        return True

it's a huge problem, please, fix it

**Comment by hobovsky** [comment] 2020-10-25 17:49
Duplicate of #1970 and a couple of similar issues.

**Closed by hobovsky** 2020-10-25 17:49 UTC
