### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by WinterCore** [Codewars/codewars.com#259] opened 2016-03-17 15:54 UTC
When solving a kata hovering over the submit button shows the tooltip 
"Submit your solution. The kata's test fixture will be used ..... etc"
which makes the horizontal scrollbar visible
**before hovering**
![image](https://cloud.githubusercontent.com/assets/8643036/13851829/5c5b2078-ec68-11e5-8454-0dfbccc8a9ba.png)
**after hovering**
![image](https://cloud.githubusercontent.com/assets/8643036/13851883/8743de56-ec68-11e5-91eb-7e33bacc7f55.png)
Maybe it should be shifted to the left a little if it goes beyond the screen.

**Comment by nathandoctor** [comment] 2016-04-27 02:13
Additional details and solution courtesy of Virzen Virzen: 

Recently, while coding at your page, I noticed that vertical scrollbar appears on editor page, despite it seemingly being intended to be adjusted to the window size. Screenshot 1. ilustrates this issue.

Screenshot 1
Screenshot 1. Editor view with unnecesary scrollbar on the right

This also happens in full-window view, as you can see on Screenshot 2.

Screenshot 2
Screenshot 2. Editor view in full-window mode with unnecesary scrollbar on the right

I call myself a web developer, so I investigated the issue. I arrived at the conclusion that it's the `main` element which is causing the trouble, specificly - its padding.

![unnamed-1](https://cloud.githubusercontent.com/assets/2425507/14839788/b3abf6ec-0be2-11e6-974d-6378d14f03c7.jpg)
Screenshot 3. `main` element highlighted in Firefox DevTools

After fiddling around with padding values, I found the fault and the solution: bottom padding is 5px too large and it can be fixed by (surprisingly) lowering it by 5px.


![unnamed](https://cloud.githubusercontent.com/assets/2425507/14839792/b593e6e0-0be2-11e6-9f6c-3ea041742e1d.jpg)
Screenshot 5. `main` element with bottom padding lowered by 5px (new values in lower right corner)

The issue is present in both Firefox Developer Edition 47.02a and Chrome 50 (at least that's where I have checked for it).

I hope my report is helpful.

Best regards,
Virzen

**Closed** 2018-04-24 17:52 UTC
Labels: area/ui, kind/bug
