### ISSUE TITLE
Using the solutions that were accepted by the kata.

### ISSUE THREAD

**Issue by Sausy21** [Codewars/codewars.com#1914] opened 2019-08-19 13:35 UTC
This is regarding with the katas in 3 kyu. For Python specifically. There is always a problem with my code showing 'Execution timed out'. It works perfectly fine for the sample tests, but not the actual ones. I then forfeited and saw the solutions and grabbed one of those solutions and trained the kata again. Using one of those accepted solutions, when running the actual tests, it is still showing 'Execution timed out'.

**Comment by Voileexperiments** [comment] 2019-08-19 13:38
This is a kata issue so you should leave a isssue at the kata's discourse instead. This repo is for the site itself.

**Comment by kazk** [comment] 2019-08-19 20:46
This is probably caused by some weird performance issue some Python code is having when executed inside a container. Closing as a duplicate of https://github.com/Codewars/codewars-runner-cli/issues/757

**Closed by kazk** 2019-08-19 20:46 UTC
