### ISSUE TITLE
Cannot run/test Kata

### ISSUE THREAD

**Issue by lawnboyy** [Codewars/codewars.com#1058] opened 2017-08-02 13:30 UTC
I attempted 2 different kata today and every time I attempt to run the sample tests I receive the following error:

"This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request."

I retried several times with the same results.

**Comment by incik** [comment] 2017-08-02 13:37
Same here :( Doesn't matter which language I choose, I always end up with this message :(

**Comment by kchwalisz** [comment] 2017-08-02 13:47
Same here :(

**Comment by ChristianECooper** [comment] 2017-08-02 14:03
+1

**Comment by chinesedfan** [comment] 2017-08-02 14:18
Duplicate of #1057. Sad~ No kata can be trained.

**Closed** 2017-08-08 18:31 UTC
