### ISSUE TITLE
Issue when accessing `completed_solutions` after a language was deleted

### ISSUE THREAD

**Issue by reivhax** [Codewars/codewars.com#1627] opened 2018-11-14 08:09 UTC
#### Description
When accessing '/users/reivhax/completed_solutions' I get an error 500 with the message __undefined method `id' for nil:NilClass__

The error does not persist on the other solution pages. For example '/users/reivhax/completed_solutions?page=1' and subsequent pages have no error.

I have recently created a kata which is still in beta state and it is my most recent solution. I had initially created the kata in python but deleted the python version and only preserved a javascript version. This may be the cause of the bug.

#### Context
- Codewars username: reivhax
- OS: Ubuntu 16.04
- Browser: Chromium
- Browser Version: 70.0

**Comment by FArekkusu** [comment] 2018-11-14 14:06
Duplicate of #1268.

**Comment by kazk** [comment] 2018-11-14 18:41
Yeah, documents in Codewars' database often references nonexistent documents because deleting is not cascaded. And the code often lacks the guard for it, so it's causing nil errors like this.
I'll try finding the exact line causing it.

**Comment by kazk** [comment] 2019-01-13 01:35
This should be fixed now. It should show your solution without any links under it instead of throwing error.

**Closed by kazk** 2019-01-13 01:35 UTC
Labels: area/db, kind/bug
