### ISSUE TITLE
Internal Server Error when clicking on attempt or run sample test

### ISSUE THREAD

**Issue by forceofseth** [Codewars/codewars.com#1845] opened 2019-06-14 10:00 UTC
Whenever i klick on attempt or run saple tests i will get this error:
https://imgur.com/a/iCmAzVD

**Comment by kazk** [comment] 2019-06-14 10:15
Closing as duplicate of #1842.

The outage was caused by Redis service going down. I'm deploying the changes right now so it should go back up soon. See https://status.codewars.com/

**Closed by kazk** 2019-06-14 10:15 UTC
