### ISSUE TITLE
Website crash problem

### ISSUE THREAD

**Issue by raunakhajela** [Codewars/codewars.com#1564] opened 2018-09-08 08:19 UTC
It's now more than 6 months and still, this load issue hasn't fixed. When I visit codewars.com in Google Chrome or Firefox, it shows on 0.5 sec some page elements and then website instantly crash. 

![234234](https://user-images.githubusercontent.com/6176598/45251990-26e2b900-b36d-11e8-956f-869404ee0f1a.PNG)
![3432324](https://user-images.githubusercontent.com/6176598/45251991-277b4f80-b36d-11e8-8f54-b6beb403620e.PNG)

**Desktop:**
- OS: Windows 7 64 Bit
- Browser: Chrome, Firefox

To visit a website I have to use the login [link](https://www.codewars.com/users/sign_in) but still the same problem when you try to solve any kata. This is an old problem and it's more than 6 months now. This problem has been reported earlier on Oct 3, 2017, but no action taken so far. I request you to please fix this asap. I think this is the problem with people using the windows machine. 

Similar issue - https://github.com/Codewars/codewars.com/issues/1157

**Comment by anter69** [comment] 2018-09-12 07:05
I'm pretty sure it's not the website's issue: rather a local one, otherwise a big percentage of users would have already complained in the last months. I have the same setup at work (win 7 64bit + chrome/firefox) and I have had no such issues (ever).

Try the usual things: clear your cache and cookies, etc.

**Comment by raunakhajela** [comment] 2018-09-12 07:08
I did everything and it's not working and also checked among my friend's machines.

**Comment by itdeega** [comment] 2018-09-30 21:28
same issue here on win7 both chrome and firefox

**Comment by kazk** [comment] 2018-10-01 00:49
Closing as duplicate of #1157.
This only happens to small percent of Windows users and we're not able to reproduce the issue. Some users reported that it stopped after updating Windows. Please comment there if you have any additional information.

**Closed by kazk** 2018-10-01 00:49 UTC
