### ISSUE TITLE
Can not be approved, error 500

### ISSUE THREAD

**Issue by smile67** [Codewars/codewars.com#427] opened 2016-06-30 12:31 UTC
https://www.codewars.com/kata/especially-joyful-numbers/

https://www.codewars.com/kata/sum-of-array-averages/

Thanks;-)!

**Comment by DonaldKellett** [comment] 2016-06-30 14:51
#316

**Comment by brendanvos** [comment] 2017-04-03 00:37
@smile67 @jhoffner @kazk Can likely be closed as duplicate was closed by jhoffner

**Comment by kazk** [comment] 2017-04-03 01:25
Closing this because this is a duplicate of #316 and it has been fixed.

**Closed by kazk** 2017-04-03 01:25 UTC
Labels: bug, duplicate
