### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by anselmoalves** [Codewars/codewars.com#384] opened 2016-06-13 15:56 UTC
Can't login into Codewars anymore. Getting the following message: "GitHub account is not linked to an existing Codewars user."
Before that, I was seeing the avatar of another user instead of mine.

**Comment by jhoffner** [comment] 2016-06-13 17:17
There was what I thought to be a thread-safety issue caused by a config change. I had reverted that change last night - so I'm troubled to see that you only reported this an hour ago. Have you tried clearing your cache?

**Comment by anselmoalves** [comment] 2016-06-13 17:27
@jhoffner Yes, I have. Also tried incognito window, but no luck so far.

**Comment by jhoffner** [comment] 2016-06-15 03:14
Ok thanks for the info. I'm closing this issue as it is being tracked with #368 and #386

**Closed by jhoffner** 2016-06-15 03:14 UTC
