### ISSUE TITLE
/kata/:id/solutions/javascript returns 500 error "undefined method `user_is_author?' for nil:NilClass"

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#838] opened 2017-02-22 23:49 UTC
The message

> undefined method `user_is_author?' for nil:NilClass

appears.

I'm not the owner, but the method that checks if current iser is the Kata's author seems to be missing.

![cw user is author](https://cloud.githubusercontent.com/assets/1063901/23238348/268c062a-f927-11e6-8f81-cd79d2674c6f.PNG)

**Comment by kazk** [comment] 2019-01-13 01:44
Closing because I wasn't able to reproduce.

Can you try again and let me know if this still happens?

https://www.codewars.com/kata/556cb06665814377d700006d/solutions/javascript

**Closed by kazk** 2019-01-13 01:44 UTC
Labels: issue/server-error-nil, kind/bug

**Comment by javatlacati** [comment] 2019-01-13 18:44
works now! 😄
