### ISSUE TITLE
Cant complete draft kata

### ISSUE THREAD

**Issue by Etoneja** [codewars/codewars.com#2169] opened 2020-06-09 22:37 UTC
#### Describe the bug
The system does not let complete the kata that is in the draft stage.
In the user profile ("kata" and "solutions"), the kata is displayed as "unfinished".
The attempt completes all tests, but does not let confirm solution (screenshot1).
**If you use the "show solution", then nothing changes!**
The edit button in the task itself is available (screenshot1), but there is an access error when clicking on it (screenshot2).

#### To Reproduce
1. Go to [kata](https://www.codewars.com/kata/5d5aa53890b243c1d26e9564)
2. run python task
3. solve kata
4. submit your solution

#### Expected Behavior
The ability to either complete the task or remove from unfinished.

#### Screenshots
a bit later - some troubles with upload
[screenshot1](https://ibb.co/nPpbkBH)
[screenshot2](https://ibb.co/Tmkcvvy)

#### Contexts
- Codewars username (if account related): Etoneja
- OS: any
- Browser: any
- Browser Version: any

**Comment by kazk** [comment] 2020-06-15 21:18
Closing as a duplicate of #1565.

**Closed by kazk** 2020-06-15 21:18 UTC
Labels: duplicate
