### ISSUE TITLE
"Preview your comment" does not accurately reflect comment formatting

### ISSUE THREAD

**Issue by brendanvos** [Codewars/codewars.com#864] opened 2017-03-21 15:26 UTC
Here is a screenshot of an [issue](https://www.codewars.com/kata/how-many-numbers-iii/discuss/python) I recently submitted:
![commentactual](https://cloud.githubusercontent.com/assets/11360165/24154176/d5f76208-0e26-11e7-9c2b-b1da15b55a66.png)

Here is a screenshot of the preview I was able to see prior to posting the issue:
![commentpreview](https://cloud.githubusercontent.com/assets/11360165/24154219/f2b80ffa-0e26-11e7-97dc-94bb8316643e.png)

And here is the comment itself:
```
The description for this kata is not gramatically sound and does a poor job of communicating the problem.
Specifically:
>We want to generate all the numbers of three digits that adding their corresponding ones equals to 10 and being all of them in increasing order (the numbers may have two or more equal contiguous digits)  
They are 118, 127, 136, 145, 226, 235, 244, 334.  
Make a function that receiving the total sum of digits and the number of desired digits, outputs the amount of all these possible numbers with the minimum and the maximum numbers. The case above should be:  
find_all(10, 3) == [8, 118, 334]

This section needs to be heavily reworked. Here is a replacement which may better outline the problem:
_____
Make a list of all numbers _n_ such that:
- _n_ has _num\_digs_ digits
- the digits of _n_ sum to _sum\_dig_
- each digit of _n_ is either equal to or larger than the previous digit (when parsing _n_ from left to right)

find_all will return _a_ list [_a_, _b_, _c_] where:
- _a_ is length of the list of _n_s
- _b_ is the smallest _n_
- _c_ is the largest _n_

For example:
find\_all(10, 3) == [8, 118, 334]

As calculated from the list of _n_s [118, 127, 136, 145, 226, 235, 244, 334]
````

As you can see the 'rendered github-flavored markdown' isn't correctly rendered in the preview. Notable in this example are:
- Missing single line breaks
- Missing bullets

_____

I believe the missing bullets may actually result from the missing single line break, as using a double line break prior to the bullets causes the preview to render the bullets correctly.

**Comment by kazk** [comment] 2018-12-31 03:56
This is because two different markdown engines are used. The server side engine has been updated recently, but they're still inconsistent.

See #1640. That issue is a duplicate of this one, but I'm going to close this one because it's old.

**Closed by kazk** 2018-12-31 03:56 UTC
Labels: area/discourse, area/markdown, kind/bug
