### ISSUE TITLE
Escape characters not interpreted on the home page

### ISSUE THREAD

**Issue by tfKamran** [Codewars/codewars.com#210] opened 2015-11-22 05:57 UTC
![screenshot from 2015-11-22 11-23-35](https://cloud.githubusercontent.com/assets/5621082/11322306/a41ebe00-910b-11e5-93f4-0c1af54188da.png)

In `Your Next Challenge...` section on the home page, the escape keywords are shown as it is in the Kata descriptions. For example it appears as `>` in the Kata description page, but in the home page it appears to be `&gt;` as shown in the screenshot attached.

**Comment by bkaestner** [comment] 2015-11-23 14:41
Duplicate of #15 and #62.

**Comment by tfKamran** [comment] 2015-11-23 15:01
I should probably close it then. :neutral_face:

**Comment by bkaestner** [comment] 2015-11-25 10:09
@tfKamran Well, the other issue was open for 6 months now…

**Comment by tfKamran** [comment] 2015-11-25 10:12
@bkaestner Yeah, I was wondering why is it open since so long, doesn't look like it should take too long to be fixed... :confused:

**Closed** 2015-11-25 10:13 UTC
