### ISSUE TITLE
Impossible to translate : undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1519] opened 2018-07-29 10:05 UTC
Another kata that is impossible to translate:
<https://www.codewars.com/kata/561e9c843a2ef5a40c0000a4/translation/new>

**Comment by g964** [comment] 2018-08-26 09:00
Works since I re-created a translation I had deleted...

**Comment by deadzq** [comment] 2018-08-26 09:07
hi G964, I have a bug with your kata question : 
https://www.codewars.com/kata/5592e3bd57b64d00f3000047

this is my solution : 
`public static long findNb(long m) {

		double x = Math.sqrt(m);
		if (x != (Math.round(x))) {
			return -1;
		}
		long n = (long) (Math.floor(Math.sqrt(x * 2)));
		return n;

	}
`
I think the large number Java can not support it.

**Comment by FArekkusu** [comment] 2018-08-26 09:59
Also a duplicate of #1268.

@deadzq this is not the right place to discuss this.

**Comment by kazk** [comment] 2018-08-26 19:07
Closed as duplicate of #1268

**Closed** 2018-08-26 19:07 UTC
Labels: issue/server-error-nil, kind/bug
