### ISSUE TITLE
https://www.codewars.com/kata/string-repeat/train/scala is broken

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1359] opened 2018-04-04 06:32 UTC
For some reasons, there *is* a Scala version of this kata but when selected it shows like this at the top:

![image](https://user-images.githubusercontent.com/14909989/38292063-e5f3912c-3814-11e8-9939-cf98a25dd542.png)

And this too:

![image](https://user-images.githubusercontent.com/14909989/38292043-d48b9d80-3814-11e8-89fe-d1ef98249ed3.png)

Does it have to do with the newest change by #1336?

**Comment by kazk** [comment] 2018-04-04 17:25
> Does it have to do with the newest change by #1336?

No. But this is happening pretty often recently though. I see requests without language specified in the logs.

**Comment by kazk** [comment] 2018-04-05 07:05
This is probably duplicate of #1291

**Comment by kazk** [comment] 2018-04-19 19:08
https://www.codewars.com/kata/string-repeat/train/scala works now. Maybe because I republished it few days ago.

**Closed by kazk** 2018-04-19 19:08 UTC
Labels: kind/bug
