### ISSUE TITLE
Getting logged out too often

### ISSUE THREAD

**Issue by Laplandia** [Codewars/codewars.com#1524] opened 2018-08-08 08:17 UTC
My account is https://www.codewars.com/users/Laplandia
Lately I am getting logged out every minute or so. When I submit a solution, it redirect to log in screen and the solution is lost.

It might have to do with the fact that I have two codewars tabs open.

**Comment by rajatkantinandi** [comment] 2018-08-30 08:15
@Laplandia 
Same here, frequent log out while submitting a solution & after login can't find I have to rewrite the solution of the problem.
This is so frustrating..

**Comment by Voileexperiments** [comment] 2018-08-30 08:31
#1

**Comment by kazk** [comment] 2018-08-30 17:47
Sorry about this. We're aware but it's been difficult to reproduce. Closing as duplicate of #1.

**Closed by kazk** 2018-08-30 17:47 UTC
