### ISSUE TITLE
Request: on adding new translation, float kata to the top in the list of katas sorted by 'latest'

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#114] opened 2015-07-03 07:28 UTC
Currently, the default kata sorting is by time of first publication ever (for beta katas) or by time of approval (for approved katas).

Katas usually get significant attention only when they are in the top of the list sorted by 'latest'.

Imagine a situation:
1. Kata is written in JS, and gets some attention, but just a bit not enough to make it out of beta.
2. One month later, it gets translated to Python. But the kata remains low in the list sorted by 'latest', so those who seek new katas in Python will hardly notice it (unless they already solved most of Python katas and filter the kata list by 'Kata I have not completed'.
3. By some miracle, somebody newbie solves the python version, fights through the issues, but doesn't mention them on discussion page, only votes up.
4. Kata is now ready for approval and a moderator who knows JS but does not know Python approves it.

We get a broken kata approved!

What I suggest is to pop up katas each time they have another language added to them, either through approval by a kumite, or through adding another language in editing interface. This is crucially important for katas in beta, because that will make new translations much more noticeable.

**Comment by bkaes** [comment] 2015-07-04 10:27
Instead of "latest", a "sort by recent activity" would be handy. That enables you to check on katas you haven't solved and have been changed.

**Comment by bkaestner** [comment] 2017-03-29 15:16
@kazk has this been changed?

**Comment by kazk** [comment] 2017-03-29 16:49
@bkaestner isn't this same as #264 and #859?
Every time a new translation is approved, the kata appears at the top of the list including beta kata.

**Comment by brendanvos** [comment] 2017-03-29 17:00
@kazk The difference I see is that this is asking for it to be updated when a translation is *published*, whereas the others are asking for it to update when a translation is *approved*.

**Comment by bkaestner** [comment] 2017-03-29 17:06
> @bkaestner isn't this same as #264 and #859?

It might be. However, if you close an issue without any further comment, the process gets opaque, and future users will not know whether the issue was

- resolved
- declined
- a duplicate of another one
- replaced by another one
- ...

You should always add a comment _why_ the issue was closed.

**Comment by kazk** [comment] 2017-03-29 17:13
@brendanvos I'm confused.

> What I suggest is to pop up katas each time they have another language added to them, either through approval by a kumite, or through adding another language in editing interface.

@bkaestner I agree, sorry.

**Comment by kazk** [comment] 2017-03-29 17:15
Closing this because I believe this feature has been added (#859).

**Closed by kazk** 2017-03-29 17:15 UTC
