### ISSUE TITLE
Internal Server Error causing no new katas to be available.

### ISSUE THREAD

**Issue by AlexanderC-J** [codewars/codewars.com#2538] opened 2021-11-17 16:51 UTC
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**
![2021-11-17](https://user-images.githubusercontent.com/90320353/142245011-5bdb6258-2c24-4a24-9ff0-dfc5b0c3434f.png)

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by Madjosz** [comment] 2021-11-17 16:58
Because of #2534
Also duplicate of #2535 #2537

**Closed** 2021-11-17 20:59 UTC
