### ISSUE TITLE
VB completion progress is not reflected

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#2011] opened 2020-01-18 14:26 UTC
#### Describe the bug
Perhaps it is related to #1476. If you have provided a solution for a Kata, and also a translation, the new completions will no longer be reflected for the new languages.

#### To Reproduce

1. Go to any previously completed Kata
2. Provide a solution in VB
3. Click compare with my solution and your solution appears
4. Click "My Solutions" link
5. your completion is not reflected

#### Screenshots

![image](https://user-images.githubusercontent.com/1063901/72665186-5971dc80-39cb-11ea-82c4-5488ec610581.png)

![image](https://user-images.githubusercontent.com/1063901/72665203-a48bef80-39cb-11ea-8217-cc788b414d0d.png)

![image](https://user-images.githubusercontent.com/1063901/72665214-bc637380-39cb-11ea-9c7e-6ac1298fc38c.png)

#### Contexts

Please complete the following information:

- Codewars username javatlacati
- OS: Windows 10
- Browser: Firefox
- Browser Version: 71.0 (64-bit)

**Comment by javatlacati** [comment] 2020-01-18 14:28
Also, it's been a couple of days since I completed it and it was the only one I had on VB, however it's not reflected the competion even in the profile.

![image](https://user-images.githubusercontent.com/1063901/72665287-6c38e100-39cc-11ea-8a0f-54ec5d7e6fcc.png)

**Comment by FArekkusu** [comment] 2020-01-18 14:58
* Completions not being shown is an old issue.
* If you translated a kata in the past, you will not progress in any languages which this kata is translated into later.

**Comment by kazk** [comment] 2020-01-18 21:56
The solution not shown in solutions page is a duplicate. See issues labeled with [solution-grouping](https://github.com/Codewars/codewars.com/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aissues%2Fsolution-grouping).

You're most likely not getting progress on VB for Multiply because you've contributed to it in the past. (I don't get any progress for Multiply either for new languages.)
The conditions are really messy and I don't really understand how it works at the moment because I haven't spent much time in that area yet.

I'm going to close this as a duplicate of other issues already reported.

**Closed by kazk** 2020-01-18 21:56 UTC
Labels: duplicate
