### ISSUE TITLE
Elixir: impossible to write or paste in the different edit fields -> Elixir translations are impossible

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1237] opened 2017-11-26 08:28 UTC
I wanted to publish an Elixir translation (<https://www.codewars.com/kata/5629db57620258aa9d000014/translation/new>)
but it is impossible to paste and see **Elixir code**: the code in solution field is not visible.
It is possible to paste  lines of code but you don't see them and if you want the page in full it is impossible to come back to a minimized field, the "Maximize editor (escape key)" doesn't work anymore. 

Nevertheless you can "Validate" the kata without seeing the solution code. Unfortunately when you "Save"  the solution field becomes completely white and the contents of all fields disappear.

I tried Chrome, Edge, Firefox but none  correctly works.

**Comment by parkerjm** [comment] 2018-01-30 19:47
+1, this is likely a duplicate of https://github.com/Codewars/codewars.com/issues/643

**Comment by kazk** [comment] 2018-12-04 19:20
Closing as duplicate of #643 and it should be fixed. Please let me know if it's not.

**Closed by kazk** 2018-12-04 19:20 UTC
Labels: area/editor
