### ISSUE TITLE
Errors in figures from stats profile

### ISSUE THREAD

**Issue by hastly** [Codewars/codewars.com#1989] opened 2019-12-16 16:46 UTC
#### Describe the bug
Numbers of completed tasks in search and in statistics are not equal. Several days have passed from status change.

#### To Reproduce

1. Go to '/kata/search/rust?q=&r[]=-8&xids=not_completed&beta=false'
2. See counter of found numbers
3. Go to '/users/.../stats'
4. Compare counter for language/rank with previous one

#### Expected Behavior

Counter figures should be equal.

#### Screenshots

![cw_stat_err_A](https://user-images.githubusercontent.com/26484889/70925905-2ab7bd80-203d-11ea-8db2-81d327fda375.png)
![cw_stat_err_B](https://user-images.githubusercontent.com/26484889/70925589-8897d580-203c-11ea-95cf-8bd2b132be06.png)

#### Contexts

- Username: hastly
- Browser: firefox 72
- Browser Version: 72

**Comment by kazk** [comment] 2019-12-16 18:52
It's confusing, but the search is showing the challenges you've completed in any languages that have Rust and not the challenges you completed in Rust. So the numbers don't match if you've completed some challenges in some other languages and those had Rust version.

I'm closing as a duplicate of feature requests to improve the search to show the challenges completed per selected language.

**Closed by kazk** 2019-12-16 18:52 UTC
Labels: duplicate

**Comment by hobovsky** [comment] 2019-12-16 19:21
If you are interested in filtering kata by "Solved/Not solved in [language]", you might want to check #1758  out. It's not perfect as it does not update counters, performs only user-side filtering etc. but hey, it's still something! ;)

**Comment by hastly** [comment] 2019-12-17 07:10
@kazk You explanation has shed some light. Now it makes sense and not feel like a bug any more, at least for me. Many thanks for your precious efforts.
@hobovsky Such a wonderful tool, thank you a lot! It helped me to find unsolved problem, and it seems it will be useful in future.
