### ISSUE TITLE
Constant logs coming from raven.js:80

### ISSUE THREAD

**Issue by benjaminben** [Codewars/codewars.com#1601] opened 2018-10-19 21:28 UTC
#### Describe the bug
My computer's fan starting whirring out of control and then I noticed I'm getting an infinite trail of logs in dev tools while looking at a kata. It also appears this only happens when `window` is in portrait orientation

#### To Reproduce

1. Load a kata in train mode, e.g https://www.codewars.com/kata/tap-into-mr-mxyzinjins-toy-safe/train/javascript
2. If you're not already in portrait layout, shrink your browser window to be < 768px wide
3. Open the developer console

#### Expected Behavior

No infinite stream of logs

#### Screenshots

<img width="1552" alt="screen shot 2018-10-19 at 14 16 52" src="https://user-images.githubusercontent.com/12801745/47244608-f4d06800-d3aa-11e8-8574-12602e1896c6.png">

#### Contexts

Please complete the following information:

- Codewars username (if account related): benjaminben
- OS: macOS 10.12.6
- Browser: Chrome
- Browser Version: 69.0.3497.100 (Official Build) (64-bit)

**Comment by kazk** [comment] 2018-10-19 21:43
Thanks for reporting (and using the new issue template!). This is a duplicate of #1397.
I'll close both once I deploy the fix.

**Comment by kazk** [comment] 2018-10-19 22:16
Fixed

**Closed by kazk** 2018-10-19 22:16 UTC
Labels: duplicate

**Comment by benjaminben** [comment] 2018-10-19 22:18
Nice! Np, thank you 👍
