### ISSUE TITLE
After submission, solutions are unlocked, but my solutions has disappeared

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#2241] opened 2020-09-11 09:56 UTC
After submitting a valid solution for
https://www.codewars.com/kata/55911ef14065454c75000062
all solutions were unlocked, but my solution had disappeared!
When using the 'back' button of the browser I landed on the Kata training page again, which was now also showing only the initial setup.

Very annoying. I will be entering my solution again, trying to remember all the details as good as I can...

**Comment by kazk** [comment] 2020-09-11 18:22
Closing as a duplicate of [issues](https://github.com/codewars/codewars.com/labels/issue%2Fsolution-not-shown) about submitted solution not appearing on the solutions page.

> When using the 'back' button of the browser I landed on the Kata training page again, which was now also showing only the initial setup.

This is because the system thought you're retraining after completing.

> Very annoying. I will be entering my solution again, trying to remember all the details as good as I can...

You can still find the solution under your profile even if it's not in solutions page.

**Closed by kazk** 2020-09-11 18:22 UTC
Labels: duplicate
