### ISSUE TITLE
Submitted solution not showing in the list of solutions

### ISSUE THREAD

**Issue by SunMasterXIV** [Codewars/codewars.com#1996] opened 2019-12-28 12:33 UTC
I recently finished https://www.codewars.com/kata/ascii85-encoding-and-decoding/solutions/c

When I want to see my own submitted solution by clicking 'My solutions' codewars states 'There are no solutions yet for this kata.'

However, if I choose to compare my solution to another solution, my solution shows. It's also shown under my profile->solutions->completed, and it's not listed under obsolete.

I can't reproduce this error, but I've seen this happen from time to time.

![cw1](https://user-images.githubusercontent.com/59310204/71543706-80159800-2976-11ea-9c5b-96eaa7f433b1.png)
![cw2](https://user-images.githubusercontent.com/59310204/71543708-8277f200-2976-11ea-81a8-b9e8b15960e6.png)
![cw3](https://user-images.githubusercontent.com/59310204/71543711-8441b580-2976-11ea-8e18-653828188008.png)

**Comment by hobovsky** [comment] 2019-12-28 23:33
Either old problem is back, or you are lucky enough to encounter #1683 after it was fixed/limited. Can you observe also other symptoms, like duplicate solution in "Completed" list after resubmit?

**Comment by kazk** [comment] 2019-12-29 21:28
This is not related to #1683 because you're able to see the solutions page.
It's a duplicate of [issues with solution grouping](https://github.com/Codewars/codewars.com/labels/issues%2Fsolution-grouping) which is responsible for the solutions page.

**Closed by kazk** 2019-12-29 21:28 UTC
Labels: duplicate

**Comment by SunMasterXIV** [comment] 2019-12-31 00:35
Well, I have submitted my code - which I can see in my own profile/solutions a number of time. It will not show among solutions - even when I select 

https://www.codewars.com/kata/5277dc3ff4bfbd9a36000c1c/solutions/c/me/best_practice . Nor  https://www.codewars.com/kata/5277dc3ff4bfbd9a36000c1c/solutions/c/all/newest


Not sure it is the same issue. When I select 'all' solutions, my solution still does not exist, even though it has been submitted 10+ times.

**Comment by kazk** [comment] 2019-12-31 00:45
See [the other issues already reported](https://github.com/Codewars/codewars.com/labels/issues%2Fsolution-grouping) like I wrote above. For example, what you just wrote is #1598.
