### ISSUE TITLE
Kata filtering on languages does not work for 'completed'

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#2020] opened 2020-01-31 03:47 UTC
If you go to the Kata overview, select a specific language, then select 'Katas I have completed'. it will show all your completed Katas in **any** language, not only the completed Katas in the selected language.

**Comment by kazk** [comment] 2020-01-31 03:51
Closing as duplicate of #790

**Closed by kazk** 2020-01-31 03:51 UTC
Labels: duplicate
