### ISSUE TITLE
CW-225: Internal Server Error when changing Red subscription

### ISSUE THREAD

**Issue by menitasa** [Codewars/codewars.com#3139] opened 2024-01-10 09:55 UTC
I've been trying for two weeks to change my payment method for my Red subscription, and it keeps giving an Internal Server Error page.

![image](https://github.com/codewars/codewars.com/assets/25803358/d894c82b-952a-4cda-822e-9f8c8d2300d3)

Please cancel my subscription.

Thanks

**Comment by VanessaGreene** [comment] 2024-01-11 14:11
Hi @menitasa I'm sorry you encountered this error, if you haven't already, please email info@codewars.com for subscription support. I will escalate this issue to our engineering team.

**Comment by VanessaGreene** [comment] 2024-03-29 13:22
Hello everyone,

We apologize for the inconvenience caused by the ongoing issue. Our team has been working on resolving the bug, but the investigation stage took longer than expected. We hope to have a fix in place in the coming weeks.

In the meantime, if you need to make any subscription requests, please send an email to info@codewars.com. Please make sure to include 'Codewars Red management' in the subject line.

Thank you for your patience and understanding.

**Comment by VanessaGreene** [comment] 2024-04-25 10:55
Hi all, we have identified the source of this issue and made the required critical updates and changes. This issue is now resolved. If you encounter any billing issues in the future, please contact our customer support team via info@codewars.com.

**Closed as completed by VanessaGreene** 2024-04-25 10:55 UTC
Labels: kind/bug?, jira-escalated
