### ISSUE TITLE
detect language when sending issue [Enhacenment]

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#1415] opened 2018-04-25 18:45 UTC
As some user proposed when you have done the following:

1. you solved a Kata 
2. you are in the solutions tab and switch to Discourse tab
3. Select comment new type as an issue

then fill with a template text that includes something like:

> Language: PHP
  Version: -specify version here-
  Input: -Write your input here-
  Output: -Write your output here-
  Additional comments: -extra Info here-

since you can get the language from the url

**Comment by kazk** [comment] 2018-04-25 18:47
Duplicate of #124

**Closed by kazk** 2018-04-25 18:47 UTC
Labels: duplicate
