### ISSUE TITLE
Don't have the option to submit passing katas

### ISSUE THREAD

**Issue by shawfire** [Codewars/codewars.com#898] opened 2017-04-14 12:09 UTC
Hi,
My username is shawfire and I have completed the katas below in JavaScript, 
when I attempt the katas they pass all test without any error messages
but I do not get the option to submit the katas.
https://www.codewars.com/kata/equal-sides-of-an-array/train/javascript
https://www.codewars.com/kata/complementary-dna/train/javascript
Thanks
John Shaw

**Comment by DonaldKellett** [comment] 2017-04-14 12:14
Exact duplicate of #893 - please leave a comment there instead.

**Closed** 2017-04-14 14:59 UTC
