### ISSUE TITLE
Possible cheating on a pretty normal solution - list of own solutions marked as "possible cheating"

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#121] opened 2015-07-04 18:33 UTC
I was somehow surprised to read that [this](http://www.codewars.com/kata/reviews/556370811d3348d158000067/groups/556498eff44b1b4103000039) could have been a cheating solution and I wondered if there was some way of getting all the suspect solutions.

IIRC, other than losing points, you could have other consequences (ultimately being blocked/banned from the site?) and I would like to be at least notified before it is too late to appeal such decisions.

**Comment by jhoffner** [comment] 2015-07-06 23:34
I undid the cheat and changed the way the cheat detection system works. There seems to be a bug with how it was working in Python (possibly caused by some sort of whitespace issue) though it might be happening in other languages. 

My fix for this was to stop the system from auto-marking a solution as a cheat and instead sending the solution over to one of our Slack channels for review. If we spot a cheat that actually is a cheat we have a way of marking it through the interface. 

This might also eventually lead to us providing the ability to allow any user to flag a solution as a cheat, where we and possible kata contributors would be notified and given the chance to confirm or deny.

**Closed by jhoffner** 2015-07-06 23:34 UTC

**Comment by GiacomoSorbi** [comment] 2015-07-07 00:30
The crowd-flagged cheat detection seems a really neat idea.

And thanks for the fix :)
