### ISSUE TITLE
Failed to process output. It is possible that too much data was written to STDOUT.

### ISSUE THREAD

**Issue by hoku3859** [Codewars/codewars.com#778] opened 2017-01-16 10:19 UTC
Hello,

My code seems to run fine on the example test, but on "ATTEMPT" I receive a server execution error as written in the subject ("Failed to process output. It is possible that too much data was written to STDOUT.")

I am attaching my code below (in Java).
Any ideas what could cause this?

Waiting to apply me code solution
Thanks!

-------------------------------------------------------------------------------------------------------------------
Code:

public class Decompose {

  public String decompose(long n) {
		  
		int target = (int)n * (int)n;
		int cur = 0;

		String result = "";
		for (int i = ((int)n)-1; i>0; i--){

			if (target >= i*i){
				target -= i*i;
				if (i==((int)n)-1) {
					result = String.valueOf(i) + result;
				} else {
					result = String.valueOf(i) + " " + result;
				}
				cur++;
			}
		}
		
		return result;
	  }
}

**Comment by DonaldKellett** [comment] 2017-01-16 10:43
@hoku3859 ,

This error is thrown whenever too much "content" is printed to the console (i.e. STDOUT) when the tests are running, and that includes the Passed and Failed messages from the assertions themselves.  This could either be caused by you or the Kata author.

Although I do not know much about Java, it does not appear that the solution you posted does any printing itself so we can rule out the possibility of your solution printing out too much to the console; hence, the only possible explanation (provided Codewars is functioning correctly) is that the author of the Kata (at least in the Java version) has included too many test cases in his/her Kata.  As you may realise, the Test Failed message is usually longer than the Test Passed message so if the Kata author included too many tests and your solution fails every test, then a lot may be printed to the console such that Codewars cannot handle the messages.

Hope this answers your question :smile:

Cheers,
DonaldKellett (donaldsebleung on Codewars)

**Comment by g964** [comment] 2017-01-16 10:55
If it is that kata:
<https://www.codewars.com/kata/square-into-squares-protect-trees/train/java>
it prints quite nothing to the console...

**Comment by hoku3859** [comment] 2017-01-16 11:07
Thank you @DonaldKellett for your explanation, it does answer a big part of my question.

**Comment by hoku3859** [comment] 2017-01-16 11:08
@g964 this is the kata I was referring to!
So if it prints almost nothing to the console, what could cause this error?
Have you tried a solution similar to mine? (assuming it isn't completely wrong)
Love to hear a few ideas...

**Comment by g964** [comment] 2017-01-16 17:06
I tried your solution and had the same problem as you had:-( But... changing in the loop your `int i = ((int)n)-1;` and other of the same kind to `long` (instead of int) give outputs like that:
```
 Log
 12
✘ expected:&lt;1 2 [3 7 9]&gt; but was:&lt;1 2 [4 11]&gt;
  test3(DecomposeTest)
 Log
 625
✘ expected:&lt;[2 5 8 34] 624&gt; but was:&lt;[1 2 4 35] 624&gt;
  test4(DecomposeTest)
 Log
 7100
✘ expected:&lt;[2 3 5] 119 7099&gt; but was:&lt;[1 6] 119 7099&gt;
  test5(DecomposeTest)
 Log
 12345
✔ Test Passed
  test6(DecomposeTest)
 Log
 1234567
✘ expected:&lt;[2 8 32 1571 1234566]&gt; but was:&lt;[]&gt;
```
The `log` corresponds to my printing of the input n.
I think you should give a look at your code. The buffer is certainly filled with all the info about your failing tests:-(
Hope that helps. Cheers!

**Comment by hoku3859** [comment] 2017-01-16 18:38
@g964 
Thanks!
That certainly gives me a lead...
I'll check it out and hopefully resolve whatever is faulty in my code.
Cheers!

**Comment by kazk** [comment] 2017-05-31 18:37
Closing this because it appears that the issue is specific to this kata and the solution.
Let me know if this is incorrect.

**Closed by kazk** 2017-05-31 18:37 UTC

**Comment by OdaiAlqohaly** [comment] 2018-03-22 13:21
If you still have this issue check this out:
https://stackoverflow.com/a/49429743/8820190
