### ISSUE TITLE
Can see other solutions before my submitting own code

### ISSUE THREAD

**Issue by SunMasterXIV** [Codewars/codewars.com#1998] opened 2019-12-29 00:14 UTC
I've no idea if this applies to all languages, but it certainly applies to C.

I've just just finished the Kata at https://www.codewars.com/kata/collision-detection/train/c

As you can see on the first image, I have not yet submitted my code.

If I now go (e.g. on a different browser tab) go to the solutions part of the kata, other solutions are available for me to see - before submitting my own.
![cw10](https://user-images.githubusercontent.com/59310204/71550786-89375100-29d8-11ea-85c2-d7e8971ef2e8.png)
![cw11](https://user-images.githubusercontent.com/59310204/71550787-905e5f00-29d8-11ea-8e8f-e766f5148d1b.png)

The code currently *not submitted* is shown under my profile->solutions->completed.

(my codewars username is SunMaster, and I've not yet submitted this code).

**Comment by FArekkusu** [comment] 2019-12-29 00:46
Not an issue. Submitting your code to the solutions list is not mandatory for it to count.

**Comment by kazk** [comment] 2019-12-29 22:47
It's been like this at least since 2015, but apparently this is a bug. Closing as duplicate of #122 and #1104.

#122 was closed because of a comment "should be already the case", but #1104 was opened after that.

**Closed by kazk** 2019-12-29 22:47 UTC
Labels: duplicate
