### ISSUE TITLE
Cannot comment even after verifying account

### ISSUE THREAD

**Issue by jordankittle** [codewars/codewars.com#2284] opened 2020-12-12 05:56 UTC
**Describe the bug**
When I first tried to comment on a solution, it was told I needed to verify my account by clicking the link in my email. I did that and now when I click post nothing happens. In my console there are no errors and I have tried logging out and back in. I have also tried posting on Chrome and Firefox.

**To Reproduce**
Go to https://www.codewars.com/kata/552c028c030765286c00007d/solutions/javascript and try to comment on a solution 

**Expected behavior**
I expected my comment to be posted after clicking post.

**Browser**
Firefox 83.0 64-bit and Chrome Version 87.0.4280.88 (Official Build) (64-bit)

- OS: Windows 7
- Browser Firefox and Chrome
- Firefox Version 83.0 64-bit and Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
I also cannot vote

**Comment by kazk** [comment] 2020-12-12 06:00
Closing as a duplicate of #2263

**Closed by kazk** 2020-12-12 06:00 UTC
Labels: duplicate
