### ISSUE TITLE
No submit final button

### ISSUE THREAD

**Issue by northcoders-chris** [Codewars/codewars.com#897] opened 2017-04-14 08:02 UTC
Am I also experiencing this issue? It has happened twice today. I have a much higher rank than these Katas which may be the reason. I am doing them as I am preparing a course using CodeWars for beginners.
![screen shot 2017-04-14 at 08 54 59](https://cloud.githubusercontent.com/assets/5517662/25037311/60f259b8-20f0-11e7-9d9b-6df98e7bd3f2.png)

I have also done it on this Kata http://www.codewars.com/kata/combine-objects but I clicked 'Show Solutions' in that case as I like to explain the top rated solution to beginners.

I have also commented on a previous issue #337  but thought if this was a bug you would want it pretty high priority!

**Comment by kazk** [comment] 2017-04-14 08:19
Closing because this is exact duplicate of #893.

**Closed by kazk** 2017-04-14 08:19 UTC
