### ISSUE TITLE
Run Sample Tests Fails With Internal Server Error

### ISSUE THREAD

**Issue by sudhz5588** [Codewars/codewars.com#1846] opened 2019-06-14 10:01 UTC
#### Describe the bug
Internal Server Error
Request failed with status code 500
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

#### To Reproduce

1. Go to 'any kata and click on train'
2. Click on 'run sample tests'
3. See error 'Internal Server Error'

The issue is reproducible for irrespective of Kata and language.

#### Expected Behavior

Should show me the result of the test case run.

#### Screenshots

![image](https://user-images.githubusercontent.com/34641965/59501289-d3cc0280-8eb8-11e9-8b0a-38afef8a4424.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): RisingDrago
- OS: Windows 7
- Browser: Chrome
- Browser Version: 73

**Comment by kazk** [comment] 2019-06-14 10:15
Closing as duplicate of #1842.

The outage was caused by Redis service going down. I'm deploying the changes right now so it should go back up soon. See https://status.codewars.com/

**Closed by kazk** 2019-06-14 10:15 UTC
