### ISSUE TITLE
Test and "Attempt" buttons are invisible on many kata's

### ISSUE THREAD

**Issue by Isaxved** [Codewars/codewars.com#1988] opened 2019-12-14 19:05 UTC
#### Describe the bug
Mostly on level 8 and 7 kata's the absence of attempt and test buttons.
#### To Reproduce

1. Go to kyu 8 kata's
2. Click on train or train again
3. Scroll down to see whether the attempt and test buttons are in place
4. See nothing

#### Screenshots

![image](https://user-images.githubusercontent.com/45680036/70853329-97fd0e80-1ed6-11ea-83bd-f247663155f6.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): isaXved
- OS: Windows 10
- Browser: Chrome
- Browser Version: latest

**Comment by hobovsky** [comment] 2019-12-14 20:01
#1839 #1214

**Comment by Isaxved** [comment] 2019-12-15 07:34
> #1839 #1214

Thank you very much, works fine now

**Comment by kazk** [comment] 2019-12-16 18:54
Closing as duplicate of #1839.

**Closed by kazk** 2019-12-16 18:54 UTC
Labels: duplicate
