### ISSUE TITLE
Can't see buttons on Chrome/Sierra

### ISSUE THREAD

**Issue by JaimeGo** [Codewars/codewars.com#1396] opened 2018-04-18 14:01 UTC
Hi! I can barely see the buttons at the end of the screen on Google Chrome in my laptop, with mac OS Sierra. I used to see them a while back, but I came back to the page and now it is impossible to click on them. Obviously I can't scroll down. Taking down the bar on the bottom doesn't help either. Thanks
![captura de pantalla 2018-04-18 a la s 11 00 07](https://user-images.githubusercontent.com/11428830/38936692-b8e11e6e-42f7-11e8-9e73-a0bc2d95dbb8.png)

**Comment by kazk** [comment] 2018-04-18 18:11
Closing as duplicate of #1214

For now, you should be able to use keyboard shortcuts:

- `Cmd`+`'` to run sample tests
- `Cmd`+`Enter` to submit

**Closed by kazk** 2018-04-18 18:11 UTC
Labels: duplicate
