### ISSUE TITLE
Backspace and space on mobile devices

### ISSUE THREAD

**Issue by LadenPopsicle** [Codewars/codewars.com#710] opened 2016-12-07 02:02 UTC
When using CodeWars on my Android tablet and phone, if I press **backspace** in the place to type code, it will **delete the character in front of the cursor and skip a line**. Also, if I press the **spacebar**, it will **skip a line**.

 This is very **annoying** and makes it difficult for a high school student such as myself to use CodeWars without access to a desktop or laptop. As a side note, CodeWars works perfectly on my desktop and laptop.

Please fix it soon, I really like CodeWars otherwise.

**Comment by jhoffner** [comment] 2016-12-07 02:05
This is a duplicate of #693. Unfortunately the only thing that can probably be done is that we provide an option to just turn the code editor into a normal textarea (no syntax highlighting). Codemirror just doesn't work on Android / Chrome. Other mobile browsers have issues as well.

**Closed by jhoffner** 2016-12-07 02:05 UTC
Labels: duplicate
