### ISSUE TITLE
The kata failed to load. Please try reloading the page.

### ISSUE THREAD

**Issue by copperwye** [Codewars/codewars.com#1974] opened 2019-11-12 19:57 UTC
#### Describe the bug
For four days now, I get for every Python kata that I try to train on the message: "The kata failed to load. Please try reloading the page.". I tried chrome and firefox browser as well as different Windows 10 Computer. All with the same negative effect.

#### To Reproduce

Load untrained Python kata and press the >TRAIN button.

#### Expected Behavior

Open the kata in train mode.

#### Screenshots

![kata_failed_to_load](https://user-images.githubusercontent.com/25419449/68697777-d0c86180-057f-11ea-8e7b-121b4a40e4a1.png)

#### Contexts

Please complete the following information:

- Codewars username: CopperWye
- OS: Win10
- Browser:  Chrome: 78.0.3904.97 and Firefox 70.0.1
- Browser Version: see above

**Comment by kazk** [comment] 2019-11-12 20:02
Closing as duplicate of #1973

**Closed by kazk** 2019-11-12 20:02 UTC
Labels: duplicate
