### ISSUE TITLE
Please allow me to edit my .vimrc

### ISSUE THREAD

**Issue by ShakaUVM** [codewars/codewars.com#2294] opened 2020-12-31 20:45 UTC
I've checked the documentation and I don't see anything about how to edit the editor settings in Vim mode.

Since it's clear it's not a stock installation of Vim, there must be a .vimrc config file somewhere on the server that is being used. Could you allow users to edit it on a per-user basis? As a long time Vim user, I have my own settings that I'm used to, and things like the auto-closing of brackets messes up my flow.

Thanks!

**Comment by Steffan153** [comment] 2020-12-31 20:49
There is no vimrc file, it's just using CodeMirror's built-in Vim bindings: https://codemirror.net/demo/vim.html

**Comment by kazk** [comment] 2020-12-31 20:52
There's no `.vimrc`. We use CodeMirro's [Vim mode](https://codemirror.net/demo/vim.html).

> As a long time Vim user, I have my own settings that I'm used to

I totally understand as a long time Vimmer, but we can't have the same experience in browser.

Closing as a duplicate of other issues to make edtiors customizable.

**Closed by kazk** 2020-12-31 20:52 UTC
