### ISSUE TITLE
Make user's own comment marked as spoilers visible to him/her under any condition.

### ISSUE THREAD

**Issue by SavioVolceroKiera** [Codewars/codewars.com#1997] opened 2019-12-28 14:15 UTC
Example:
1. User solves kata in JS, but not in python.
2. User posts comment marked as spoiler in discourse.
3. Depending on chosen language, he can either see (JS) or not (python) his own comment.

**Comment by kazk** [comment] 2019-12-29 22:34
Closing as duplicate of #53.

**Closed by kazk** 2019-12-29 22:34 UTC
Labels: duplicate
