### ISSUE TITLE
Kata completion was not registered

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1592] opened 2018-10-13 09:19 UTC
Yesterday evening (around 10 p.m. GMT+3, I think) I completed [this kata](https://www.codewars.com/kata/5274e122fc75c0943d000148). For some reason after I pressed the `Submit solution` button the completion was not registered: when I was redirected to the solutions page I was told that "I should complete the kata before viewing solutions", `Train` button was shown in the top-right corner instead of `Train again` button. When I opened the trainer again, there was also no `Past Solutions` tab.

While searching for the link to the kata in my profile I found this:
![image](https://user-images.githubusercontent.com/31668662/46903744-f816b000-cee1-11e8-9eb0-b04226f1e807.png)

**Comment by error256** [comment] 2018-10-13 11:43
I've just had the same thing too; looks like some new bug.

**Comment by kazk** [comment] 2018-10-13 23:55
Thanks.
From what's in the database, I think something like the following happened:

1. On first submission, something failed when grouping the solution
3. The solution was stored in the database without a solution group associated
4. Then the saved document was not found/returned for some reason. This probably caused it to consider you haven't completed the kata.
5. When you opened the trainer again, a new record was created. (Database doesn't have unique index set :()
6. The second submission worked as expected

---

I've found multiple data issues while looking into this :man_facepalming:
This might be related to all the ["solution not shown issues"](https://github.com/Codewars/codewars.com/issues?q=label%3Aissue%2Fsolution-not-shown) too.

> I've just had the same thing too; looks like some new bug.

I haven't checked if a user having duplicate kata completion records is new, but a solution finalized without a solution group wasn't new. Recent changes was just adding PureScript so I don't think this is a completely new bug. I'll try looking through the database more.

**Comment by kazk** [comment] 2018-10-17 17:49
Someone experienced this issue on 2017-09-16

> I'm currently unable to see my F# solutions at codewars.com/kata/sort-an-array-by-value-and-index/solutions/fsharp/me/best_practice but at the same time I can see two listed at codewars.com/users/USERNAME/completed_solutions.
> https://github.com/Codewars/codewars.com/issues/1114#issuecomment-329963827

---

All of these seems to be related to code grouping failing and the system not noticing that.

**Comment by error256** [comment] 2018-11-22 13:50
It's just happened again. I haven't resubmitted, this is my only solution:
https://www.codewars.com/kata/reviews/5bf6a24ff8c527c2f0001d96/groups/5bf6b1fbff398675180022e1

**Comment by Voileexperiments** [comment] 2018-11-22 14:59
Does this have to do with #1283 too?

**Comment by kazk** [comment] 2018-11-24 03:44
@error256 is the solutions page still locked? You're able to provide the link so the solution has a solution group (its own). It looks normal in the database as well.
So if it's still not considered as completed then it's a separate bug with the same symptom.

@FArekkusu's first solution doesn't have a solution group even it's marked as finalized. This means the link to the solution doesn't exist and it fails to show up in the list of solutions as well.

#1283 is also same symptom with different cause. That one might be because it's failing something while trying to reference the deleted JS version while updating some fields in the document.

The logic is surprisingly complicated, involving multiple nested documents. Errors seems to result in partial updates instead of failing the process and rolling back. So data is inconsistent depending on when it failed.

**Comment by kazk** [comment] 2018-11-24 21:36
@error256 I think I found the cause for your case and it's now looking similar to the original issue. There's actually two separate records of you with this kata (1. just opened; 2. completed).

On solutions page, Codewars is checking if you've completed the kata by looking up previous attempts. And it's getting the first document so it thinks that you haven't completed it, so the solutions are locked.
On you profile, the list of solutions are generated by the ids of completed challenges which is stored separately. This contains the id of this challenge so it's shown there.

I've removed the first document, can you try going to the solutions page?

---

One of the major problem with Codewars database is data integrity. For this one, there should be a check to disallow the same user having multiple records for the challenge. Rest of the code assumes this condition so the behavior is undefined.

**Comment by error256** [comment] 2018-11-25 10:43
I can see the solution now, the kata is completed.

**Comment by error256** [comment] 2019-01-26 17:54
It happened to me twice today. One time I submitted a solution, but didn't complete the kata. It looks like there's no way to access the saved code because it's not on Solutions page in this case.

**Comment by FArekkusu** [comment] 2019-01-31 14:20
Happened with user [saudahmed-dev](https://www.codewars.com/users/saudahmed-dev) as well, but this time it's more severe. After 3 attempts, he still [can't access](https://www.codewars.com/kata/526571aae218b8ee490006f4/discuss#5c527babb47cdb5decb32e9a) the solutions page.

![image](https://user-images.githubusercontent.com/31668662/52059917-cd756380-2573-11e9-8d95-fb195f94780c.png)

**Comment by Patrykot** [comment] 2019-06-22 08:44
I've encountered similar problem with [this kata] https://www.codewars.com/kata/58c5577d61aefcf3ff000081). But i was working on it from two different places. 
I've start to working on this kata in my job. Did not complete it, and after few hours i've started to work on it in my home. The progress on this kata that i've made in job was not saved. Not even info that I've train it. I had to find it in search and start again from scratch. 
After publishing solution, 3 things have happened:
1. I was not moved to the page with solutions, because i didn't complete this kata [sic!]. 
2. I think i was rewarded - can't remember and don't know if i can check it.
3. The progress that I've made in job was retrieved.

So I've copied my solution from My completed Kata's paste it and republish. And then i was granted to view other solutions and rewarded again.

**Comment by FArekkusu** [comment] 2019-06-22 10:51
I had a similar issue as @Patrykot. I started working on a kata using one PC but had to leave before I could finish it. Some time later I decided to solve it using another computer but:
* there was a `Train` button instead of `Train again`
* the kata trainer was empty when I entered it
* after I submitted the solution the usual "you haven't solved the kata yet" bug occured
* when I entered the trainer to resubmit the solution, some other code showed up in the trainer (it looked like the code from one of the intermediate attempts got saved there somehow) which has never happened before

It seems that when this "wrong DB index" bug occurs an "instance of the trainer" is created for the kata but they are not actually related, and closing the tab will make you lose access to it until you manage to pass the tests(???).

Although, *probably* you can still access this "trainer instance" from the "unfinished kata" list, but it'd be hard to test considering this bug is totally random.

**Comment by kazk** [comment] 2019-11-15 20:40
The issue itself should be fixed (the affected data like duplicates shown in profile is not yet fixed). If this happens again, please let me know by commenting on #1683.

Not having a solution's "Discuss" page (and solution not shown in solutions page) is a separate issue with many issues already opened for so I'm going to close this.

**Closed by kazk** 2019-11-15 20:40 UTC
Labels: area/db, issue/not-marked-as-completed, kind/bug
