### ISSUE TITLE
Display run time/mem usage of solutions listed when you complete a kata

### ISSUE THREAD

**Issue by frgauthi** [codewars/codewars.com#2173] opened 2020-06-12 17:32 UTC
I think that displaying run time and memory usage of others' solutions to a kata would be really helpful. Often there are solutions that look nice but are very inefficient. I noticed I can see what my own run time is when testing my solution that it could easily be shown when you view others' solutions as well. Displaying memory usage might be a little more to ask for, but since programming is a balance of cpu cycles/memory usage it think these metrics would be very important when voting on / adopting the best solutions to a particular problem.

Thanks for considering this feature. I love this site it is a great idea.

**Comment by hobovsky** [comment] 2020-06-12 18:36
You might want to read through #959 to see why it's not as good idea as it sounds.

**Comment by kazk** [comment] 2020-06-15 21:17
Closing as a duplicate of #959.

**Closed by kazk** 2020-06-15 21:17 UTC
Labels: duplicate
