### ISSUE TITLE
A Kata can appear on negative number of collections

### ISSUE THREAD

**Issue by javatlacati** [codewars/codewars.com#2406] opened 2021-06-20 21:10 UTC
**Describe the bug**
I opened a kata that was on negative number of collections

**To Reproduce**
Open this Kata: https://www.codewars.com/kata/57d06663eca260fe630001cc

**Expected behavior**
Should appear on 4 instead of -4

**Screenshots**
![image](https://user-images.githubusercontent.com/1063901/122688454-e1bc6880-d1e1-11eb-84b5-4f9d767e05e9.png)

**Browser**
If applicable, please provide your browser information.

- OS: Windows 10
- Browser firefox
- Version 89.0.1

**Comment by Blind4Basics** [comment] 2021-06-20 21:16
Duplicate of #2185

**Closed by Blind4Basics** 2021-06-20 21:16 UTC
