### ISSUE TITLE
List of kumites?

### ISSUE THREAD

**Issue by ZEDCWT** [Codewars/codewars.com#1137] opened 2017-09-16 04:24 UTC
It says `Kumite:8 (8 Started)` on my [profile page](https://www.codewars.com/users/ZED.CWT). I'm 100 percent sure I have not started any kumites, and found nothing under the `Kumite` tab, neither the `Published` part nor the `Drafts` part.
I have also tried checking the `Show My Kumite Only?` but found nothing.
So what are the 8 started kumites on earth? Where can I view them all?
Please dont blame me if I misunderstood something O_o

**Comment by Voileexperiments** [comment] 2017-09-16 07:50
It's probably #908 again.

**Comment by kazk** [comment] 2019-01-01 01:20
Closing as duplicate of #908

**Closed by kazk** 2019-01-01 01:20 UTC
Labels: duplicate
