### ISSUE TITLE
I was told to talk about this 500 error

### ISSUE THREAD

**Issue by JacobWarners** [Codewars/codewars.com#1358] opened 2018-04-04 02:21 UTC
I had been logged in automatically from a cookie and then I changed my language to python and clicked train and got this message. 

Good luck!

No route matches kata/577a98a6ae28071780000989/train/train

**Comment by Voileexperiments** [comment] 2018-04-04 03:42
Yes, both `kata/577a98a6ae28071780000989/train` and `kata/577a98a6ae28071780000989/train/python` are valid but not `kata/577a98a6ae28071780000989/train/train`.

It's probably not very insightful if we don't know how to reproduce that though.

**Comment by JacobWarners** [comment] 2018-04-04 05:33
I'll see if I can try to mess it up again and get back to you



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by harryyy27** [comment] 2018-04-05 14:45
I'm also getting a server error 500 when I try to open the Javascript Kata editor.

**Comment by kazk** [comment] 2018-04-23 05:38
Closing as duplicate of #596

**Closed by kazk** 2018-04-23 05:38 UTC
