### ISSUE TITLE
"Sign up" page breaks several tabs

### ISSUE THREAD

**Issue by shakhbulatgaz** [Codewars/codewars.com#1252] opened 2017-12-11 19:13 UTC
If i go to https://www.codewars.com/join, page breaks into "Aw Snap" error message.

It doesn't break immediately, you can actually see website loading for half a second and only then it breaks.

It also breaks several other tabs, **not related** any way to Codewars.
You can see that on the screenshots 1-2 below.

![1](https://user-images.githubusercontent.com/22275982/33848519-102e5968-debf-11e7-938a-3b86142765e7.png)
![2](https://user-images.githubusercontent.com/22275982/33848521-104bdaa6-debf-11e7-9114-feb230879b3e.png)
 
If i reload broken tabs and try to click "SignUp" again, Codewars breaks the **same tabs** again.

If i change the websites on these tabs, it will randomly break some of them.

In the screenshot below you can see that **it broke my GitHub issue submit page, if though it didn't on the screenshots above**

![3](https://user-images.githubusercontent.com/22275982/33848745-b0ca53fe-debf-11e7-82c5-2b35298b967f.png)

Browser: Google Chrome 62.0.3202.94
Installed extensions: uBlock, Imagus.

**Comment by kazk** [comment] 2017-12-11 19:26
Thanks for reporting with details.
Are you on Windows 7 or 8? Some Windows users are having issues, for example #1157

**Comment by shakhbulatgaz** [comment] 2017-12-11 19:29
@kazk Windows 8. Seems like issue is the same as #1157

**Comment by kazk** [comment] 2017-12-11 19:46
@shakhbulatgaz Thanks for confirming.
Do you think you can help us by enabling logging (`--enable-logging --v=1`) and posting `chrome_debug.log`? [How to determine what is causing Chrome to show the “Aw, Snap” dialogue](https://superuser.com/a/607564).

**Comment by shakhbulatgaz** [comment] 2017-12-11 20:10
@kazk sure, here you go
[chrome_debug.log](https://github.com/Codewars/codewars.com/files/1549235/chrome_debug.log)

I tried to open just codewars.com ,  since it throws the same error.

**Comment by shakhbulatgaz** [comment] 2017-12-11 20:22
@kazk another observation — page works fine on IE 10.0.1
The console there says "Raven is not defined"

**Comment by kazk** [comment] 2017-12-11 20:38
@shakhbulatgaz Thanks! I'll look into it and see if I can find anything. I'll also remove the file just in case if it contains any personal information.

**Comment by kazk** [comment] 2017-12-11 23:03
@shakhbulatgaz Unfortunately, I couldn't find anything obvious.
Does codewars.com crash without extensions? Extension `mjdepdfccjgcndkmemponafgioodelna` is writing to console few times.

Other lines that might be related, but I don't have the knowledge to understand are:

```
[1588:2248:1212/000800.824:VERBOSE1:policy_loader_win.cc(377)] Reading policy from the registry is disabled.

[1588:1736:1212/000800.918:VERBOSE1:dhcp_proxy_script_adapter_fetcher_win.cc(263)] Error fetching PAC URL from DHCP: 2

[4524:3988:1212/000801.012:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_accelerator_win.cc on line 485
```

---

Adding `--no-sandbox` flag might add more details.

> To enable logging from the render processes on Windows you also need the --no-sandbox command line flag.
> https://www.chromium.org/for-testers/enable-logging

I'm not sure if I can find anything from it because I'm not familiar with browser internals, but I can try. If you don't mind, can you disable extensions and launch with `--enable-logging --v=1 --no-sandbox`? Make sure to remove those flags after collecting logs. If not, don't worry, thanks for all the info.

---

I want to know why only Windows 7 and 8 crashes :/ Windows 10 seems fine.

**Comment by shakhbulatgaz** [comment] 2017-12-12 07:14
@kazk later, once i get home.

Interesting - I tried to open codewars.com from my workplace and it works fine, even though my browser here has even more extenstions. 

Problem obviously is in local machines.

**Comment by shakhbulatgaz** [comment] 2017-12-12 20:04
@kazk here
[chrome_debug.log](https://github.com/Codewars/codewars.com/files/1553116/chrome_debug.log)

**Comment by kazk** [comment] 2017-12-12 20:10
@shakhbulatgaz Thanks, I'll take a look.

**Comment by kazk** [comment] 2017-12-12 21:12
@shakhbulatgaz 

>  I tried to open codewars.com from my workplace (Windows 7) and it works fine

Is your chrome 32 bit version? And maybe 64 bit at your work?

Does it work in Incognito window?

---

Some other observations:

- `chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm` is loaded. This seems to be the builtin Chrome Cast

**Comment by shakhbulatgaz** [comment] 2017-12-13 14:35
@kazk no and no.

Maybe there is some sort of GPU memory problem taking place? 
It could probably explain this:
`[4524:3988:1212/000801.012:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_accelerator_win.cc on line 485`

At work we use distributed network, so maybe that's why it doesn't crash here.
Also the tabs that get crashed alongside codewars are heavily loaded with graphics, (it doesnt' crash text-only pages) so...

**Comment by kazk** [comment] 2017-12-13 20:20
@shakhbulatgaz sorry, I don't think I can help at this point. Thanks for providing us the logs. I'm going to close this as a duplicate of #1157.

**Closed by kazk** 2017-12-13 20:20 UTC
Labels: browser/chrome, platform/windows
