### ISSUE TITLE
  My kata honor doesn't change after kata resolution.

### ISSUE THREAD

**Issue by nikz2710** [Codewars/codewars.com#463] opened 2016-07-18 12:45 UTC
I solved today various katas but my honor doesn't affected at all. Also there is a kata which i solved previously but i still cannot see the solutions because the system tells me, that i must solve it first.

Bugged kata : https://www.codewars.com/kata/5226eb40316b56c8d500030f

Solved today without honor change:
https://www.codewars.com/kata/55c6126177c9441a570000cc
https://www.codewars.com/kata/52a89c2ea8ddc5547a000863
https://www.codewars.com/kata/52f78966747862fc9a0009ae

**Comment by SteffenVogel79** [comment] 2016-07-18 13:00
It is queud and will change after a short time.
No honors are lost!!

**Comment by nikz2710** [comment] 2016-07-18 14:12
Seems strange to me, to update honor over time. But - ok. There is still some bug with the pascal triangle's kata.

**Comment by jhoffner** [comment] 2016-07-18 16:13
Its a Rails app and most logic is moved into the background process. If something has caused background processing to queue then it may take a moment for your honor to show up. Especially on the very next page load since the page was probably loaded before the background task completed.

**Comment by jhoffner** [comment] 2016-07-18 16:14
Just to verify before I close this - did the honor ever end up showing correctly?

**Comment by nikz2710** [comment] 2016-07-18 16:37
Well, passed more than a hour. Now the honor is updated. But still, there is a bugged kata. Please check it.

**Comment by SteffenVogel79** [comment] 2016-07-18 16:37
The duration for the honor-points to arrive increases the last days. Sometimes in a range from minutes to an hour.

**Comment by g964** [comment] 2016-07-18 18:13
Today, this time, <https://www.codewars.com/users/leaderboard> is several hours (13 hrs) late.

**Comment by SteffenVogel79** [comment] 2016-07-18 18:25
But this seems a caching-problem from the cloud-solution!
When you refresh several times, you get often changing results in the leader-table.

**Comment by jhoffner** [comment] 2016-07-18 19:30
The background processing engine went down and I'm assuming these issues are caused by that. This was never an issue before and nothing else has changed. The processing has been restarted and completed. Please let me know if any issues still persist. 

In the meantime there are a number of issues related to background processing (which I am investigating the reason for it crashing) so I will close this one.

**Closed by jhoffner** 2016-07-18 19:30 UTC
Labels: more info needed
