### ISSUE TITLE
undefined method `revised_by' on solutions page

### ISSUE THREAD

**Issue by roborourke** [Codewars/codewars.com#824] opened 2017-02-10 21:31 UTC
I'm not sure if I should add this elsewhere or not, I got the following error when I submitted my final answer for the JS version of this:

URL: https://www.codewars.com/kata/5286d92ec6b5a9045c000087

```
undefined method `revised_by' for #<Array:0x005559b8839de0>
```

![500 error](https://www.dropbox.com/s/atl0fvathu2wzpu/Screenshot%202017-02-10%2021.27.33.png?dl=1)

**Comment by jhoffner** [comment] 2017-02-10 21:33
duplicate of #823 - Fix is being deployed now.

**Comment by roborourke** [comment] 2017-02-10 21:33
@jhoffner thanks! I did search the error message but found nothing :/

**Closed by jhoffner** 2017-02-10 21:33 UTC
Labels: duplicate
