### ISSUE TITLE
Codewars dashboard page broken (for reach user limit user in clan, i guess)

### ISSUE THREAD

**Issue by Pabloin** [Codewars/codewars.com#1220] opened 2017-11-10 08:04 UTC
Hello, 
I would like to report a bug in the codewars platform. My user in codewars is pablo.inchausti and the clan that I belong to is "BBVA"

When I login in codewars with my user I see the dashboard broken with a big error 500 message:  **Looks like there was a server error! (500)** and a detail of the error (I am attaching the screens)

In the dashboard usually show the users ranking in the clan

The error message said at the end:  
` failed with error 17144: "Runner error: Overflow sort stage buffered data usage of 33579417 bytes exceeds internal limit of 33554432 bytes" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error.`

And I guess that the reason is related to the size of the clan in codowars that I belong to. I looks that there are many user in the clan and the querey broke against the database, and the screen from dashboard that show the ranking users in the clan cant be drow. That is just a supposition...

The full error code is
`The operation: #<Moped::Protocol::Query @length=16929 @request_id=6429 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="codewars-production.users" @skip=0 @limit=0 @selector={"$query"=>{"$and"=>[{"_id"=>{"$in"=>["580f24e39..... etc.... etc.... etc....00010d"]}}]}, "$orderby"=>{"points.xp"=>-1}} @fields=nil> failed with error 17144: "Runner error: Overflow sort stage buffered data usage of 33579417 bytes exceeds internal limit of 33554432 bytes" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error.
.....`

And the screens are:

<img width="1199" alt="codewars dashboard broken i" src="https://user-images.githubusercontent.com/21208987/32648347-27600252-c5d4-11e7-86e9-c1d0b7068bb6.png">
<img width="1199" alt="codewars dashboard broken ii" src="https://user-images.githubusercontent.com/21208987/32648348-278b9534-c5d4-11e7-8e88-bc3f59195fe0.png">

I hope you cant fix that
Thanks in advance!
Pablo

**Comment by jhoffner** [comment] 2017-11-10 16:55
Thanks Pablo. I deployed a fix to preview.codewars.com. Can you verify its fixed?

**Comment by Pabloin** [comment] 2017-11-10 17:23
Hello Jake! I verify it in preview.codewars.com and it is working ok (screen atached) 
Thanks

![codewars ok](https://user-images.githubusercontent.com/21208987/32670469-a3de4ffc-c622-11e7-8d86-4c91ebb07ff7.png)

**Comment by jcarmonabbva** [comment] 2017-11-17 10:21
Hello, I have the same problem in the codewars platform and I verify that it´s ok in preview.codewars.com ... but in that preview I´m not in the ranking ... is the ranking different in that preview platform?

**Comment by anter69** [comment] 2018-03-15 10:57
@kazk Shouldn't this issue be closed? It's 5 months old and seems to be fixed...

**Comment by kazk** [comment] 2018-03-15 18:13
Thanks @anter69.
I'll close this but I think this fix caused #1243. Not sure if the change was intended. Got no reply from @jhoffner when I asked about it few months ago.

**Closed by kazk** 2018-03-15 18:13 UTC
Labels: high priority, kind/bug
