### ISSUE TITLE
Double honor for a single kata solution

### ISSUE THREAD

**Issue by aeros167** [Codewars/codewars.com#1850] opened 2019-06-20 02:36 UTC
#### Describe the bug
Similar to issue #1683, however, this may be more severe since I received double the honor for a single solution rather than just the solution not being unlocked after submitting my solution once. Notably, this occurred after submitting a 4kyu solution so the additional honor was somewhat significant.

After solving the following kata: https://www.codewars.com/kata/51eead3461ccf7db04000017 I noticed that I had not unlocked the ability to view the solutions of other users, despite having my solution in the "Completed" section of the "Solutions" page on my profile (https://www.codewars.com/users/Aerros/completed_solutions).  As a result, I attempted to copy my solution and submit it again so that I could unlock the solutions page. However, upon doing this, I received honor for doing the kata again, and in my "Completed" section, the same solution for the same kata appears twice. 

#### To Reproduce

Unsure, not sure if this bug is reproducible on the client end or if it was a server issue. 

#### Expected Behavior
Upon the initial submission of a solution which passed all of the tests, the solutions should have been unlocked and I should have only received credit for a single submission of the kata. Normally when submitting multiple solutions for a kata, additional ones beyond the first do not reward points. Also, the solutions for the same kata are normally grouped together instead of being separated. See screenshots below.

#### Screenshots
Normally after submitting multiple solutions for a single kata, the solutions are grouped together:

![CompletedKataExpected](https://user-images.githubusercontent.com/44193521/59814166-5520fc00-92e2-11e9-9418-05c72cc234f7.png)

Instead of the expected behavior, this occured:
![CompletedKataBug](https://user-images.githubusercontent.com/44193521/59813698-7ed92380-92e0-11e9-823c-2b8f57e1d1c9.png)

#### Contexts

- Codewars username: Aerros
- OS: Arch Linux
- Browser: Firefox
- Browser Version: 67.0.3

**Comment by andrew-qio** [comment] 2019-06-20 17:02
Closing as this is a duplicate of #1683

**Closed by andrew-qio** 2019-06-20 17:02 UTC
Labels: duplicate

**Comment by kazk** [comment] 2019-06-21 18:01
@aeros167 Just to clarify, this is already reported as one of the symptoms of #1683 in the comments.

**Comment by aeros167** [comment] 2019-06-24 22:03
@kazk Oh okay thanks for the clarification, I thought that issue was exclusively just the double appearance issue in "completed kata", as I had only read the initial post. After scrolling through the comments, I see the double honor was also mentioned.

**Comment by suryasiriki4** [comment] 2019-08-13 05:42
It is still not rectified in 2019 Aug.Why the hell ,code wars are not resolving this bug
