### ISSUE TITLE
Suggestion: Notify if Kata solution becomes invalid

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#933] opened 2017-05-02 04:10 UTC
During the Beta process there are always a bunch of early solvers, and often those early solvers have the best solutions....

But because a Kata is Beta (or maybe even not Beta if the author is nasty) it can change in some fundamental way (e.g. a method signature changes case etc) so all those good solutions become invalid though no fault of the solvers.

It might be nice if there is some notification to a user if their once-good solutions becomes invalid to give them a chance to go back and resubmit it - not to get any extra points for it (I know they cannot) - but just to allow their solutions to appear in the "Best Practices" list etc.

It could also trigger discourse like "Hey - you should not have changed that!", which might otherwise go unnoticed.

**Comment by Voileexperiments** [comment] 2017-05-02 04:23
Yes, the "incomplete" and "obsolete" section of solutions page just feels... incomplete (pun intended), as in they just exist there silently without good integration to the whole system, and that they have some bugs (which I might file a issue about some time in the future).

**Comment by kazk** [comment] 2017-05-04 21:41
Duplicate of #57

**Closed** 2017-05-28 21:15 UTC
Labels: duplicate, enhancement
