### ISSUE TITLE
double language version to "path finder 4" after approval of the translation (java)

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1727] opened 2019-02-13 16:51 UTC
Hi,

Troubles while approving my java translation of https://www.codewars.com/kata/path-finder-number-4-where-are-you : there are 2 different versions (both seems to work properly).

cheers

**Comment by kazk** [comment] 2019-02-13 18:16
Closing as duplicate of #1189

**Closed by kazk** 2019-02-13 18:16 UTC
Labels: duplicate

**Comment by Blind4Basics** [comment] 2019-02-13 20:04
woops sorry... x)
