### ISSUE TITLE
Can't add translation after translation removal

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#1537] opened 2018-08-21 12:31 UTC
I've created a JS translation of [this kata](https://www.codewars.com/kata/ordered-count-of-characters/translations) but I had to delete it as there was some weird issues with tests (i.e. even if all tests passed it showed me that tests were failing) as I was logged out during translating.

When I'm trying to add the translation again I got the following error when I press "Translate This Kata":

![image](https://user-images.githubusercontent.com/11985251/44401278-65473e00-a54e-11e8-901d-fdeef70a3e15.png)

**Comment by FiveCrayFish973** [comment] 2018-08-21 12:45
Na, that's not the correct issue. It's just CW servers acting up **again**

**Comment by FArekkusu** [comment] 2018-08-21 13:11
Looks like #1268 to me.

**Comment by kazk** [comment] 2018-08-21 18:18
Closing as duplicate of #1268

**Closed by kazk** 2018-08-21 18:18 UTC
