### ISSUE TITLE
Site not working on mobile Safari (iOS)

### ISSUE THREAD

**Issue by rdlugosz** [codewars/codewars.com#606] opened 2016-10-04 23:45 UTC
Browsed to the site via Safari on iOS 10 (iPad) and could not begin a kata. See screenshot; clicking the "Train" button does nothing. Also tried getting to a kata via my profile & clicking a completed one, but the train buttons there take you to a screen that won't load the editor or other kata details.

![img_0045](https://cloud.githubusercontent.com/assets/402328/19096460/91763d10-8a6a-11e6-8f70-325ac93f1550.PNG)

Content blockers are disabled.

**Comment by rdlugosz** [comment] 2016-10-04 23:55
Seems that you can get the editor working if you hold the refresh icon and select "request desktop site". Then the site mostly works, although the code editor is not great... for example, arrow keys don't work on the iPad keyboard & if you're in Vim mode there's no way to escape to normal.

**Comment by kazk** [comment] 2022-05-20 20:42
Closing because a lot have changed since this issue was reported.
Please open a new issue if the problem is not fixed.

**Closed by kazk** 2022-05-20 20:42 UTC
Labels: area/ui, platform/ios
