### ISSUE TITLE
Completed Kata wont display solutions 

### ISSUE THREAD

**Issue by IKMalik** [Codewars/codewars.com#1755] opened 2019-03-09 20:55 UTC
You have not earned access to this kata's solutions
Solutions are locked for kata ranked far above your rank. Rank up or complete this kata to view the solutions.

I would like to see the alternate solutions to this question, yet it tells me I have to beat it first, which I already have.

**Comment by IKMalik** [comment] 2019-03-09 20:55
its the Ro13 5 kyu question

**Comment by hobovsky** [comment] 2019-03-10 20:50
#1683?

**Comment by kazk** [comment] 2019-03-11 00:09
Closing as duplicate of #1683. See https://github.com/Codewars/codewars.com/issues/1683#issuecomment-456951790

**Closed by kazk** 2019-03-11 00:09 UTC
Labels: duplicate
