### ISSUE TITLE
Login session expires too frequently

### ISSUE THREAD

**Issue by DestyNova** [Codewars/codewars.com#883] opened 2017-04-08 23:16 UTC
I authenticated with Github which was pretty smooth, but now I have to login again once or twice every day. That's kind of annoying and I can't see an option to change it.

Not sure if this is some token expiration thing that Github forces upon us, or if it would go away by me adding a password and email address instead, but if so that should probably be mentioned when setting up the account.

**Comment by DonaldKellett** [comment] 2017-04-09 09:11
I think I also experienced this minor Issue just a few hours ago.  My CW account is linked to this GitHub account but my most recent login was with an ordinary email and password (not GitHub login).  However, after viewing "My Profile" following about 30 minutes of solving Kata, I realised I was (unexpectedly) logged out when I went back to the "Kata" page.  Not that it was a major inconvenience to me at the time but weird nonetheless.

**Comment by brendanvos** [comment] 2017-04-09 20:54
This actually happens to be a duplicate of the first issue #1 (which remains open). It's also likely related to #762, and #462.

Anecdotally I've noticed the frequency of this seems to increase the more codewars tabs I've been using.
If I've got lots of codewars tabs open I tend to need to log in again regularly, which is a pain as after logging in you are not returned to your previous page.

**Comment by DestyNova** [comment] 2017-04-09 21:47
Thanks @DonaldKellett and @brendanvos -- is there a way to mark this as a dupe and close it so it's still referenced by #1? Or should I just close it and add a comment to the other bug? It's not massively encouraging that the very first issue in the tracker is still open, although it's not the worst bug in the world I guess... :bomb:

**Comment by brendanvos** [comment] 2017-04-11 01:26
You can either leave it open or close it. 
Just by referencing the other issue this one shows up as 'referenced by' in the other issue's log.
I usually close my issues if I realize they're duplicates, but seeing as this has been around for so long it might be good to stir up discussion on it again.

Besides, the developers can close it and/or mark this as a duplicate when they come across it.

**Comment by jhoffner** [comment] 2017-04-13 17:02
This issue continues to linger. I've done a lot to try to clean it up and its much better than it was when the issue was originally logged, but unfortunately its a combination of technical debt and our use of PJAX, which seems to make troubleshooting these login issues a lot harder. 

The issue is definitely more reproducible when you use multiple tabs.

**Comment by jhoffner** [comment] 2017-04-22 01:36
Closing due to duplicate.

**Closed by jhoffner** 2017-04-22 01:36 UTC
Labels: bug, duplicate, high priority
