### ISSUE TITLE
Cannot run "test code", only "sample test code" in pending translation review panel?

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#2373] opened 2021-05-04 09:57 UTC
Consider as an example this [pending translation](https://www.codewars.com/kumite/5e776d7fb19cc00033390b0b?sel=5e776d7fb19cc00033390b0b)

When evaluating it for approval, one wants to run both the **sample test cases** as well as the **test cases**. However, when looking at the page, one can use "View Run Output". This will run the **sample test cases** only *once*.

So how is it possible to the **test cases** as well, or to run the example multiple times?
And wouldn't it be more "logical" to run the test cases, *not* the sample test cases?

(It is possible to "Edit" the translation, and do runs from there for your own translation **but not for somebody else's translation**. This question is related to this page)

**Comment by XRFXLP** [comment] 2021-05-04 10:10
You can fork the translation and run it over any test suite.

**Comment by nomennescio** [comment] 2021-05-04 10:35
> You can fork the translation and run it over any test suite.

Forking a translation just to review it for approval is really missing the point, and should not be necessary.

**Comment by kazk** [comment] 2021-05-04 19:17
"View Run Output" doesn't run it. It shows the output from when the translation was last updated.

**Comment by nomennescio** [comment] 2021-05-05 10:02
> "View Run Output" doesn't run it. It shows the output from when the translation was last updated.

And how can I switch views between "Sample Tests" and "Tests"? It seems only "Sample Tests" are shown?

**Comment by kazk** [comment] 2022-05-20 22:28
Closing as a duplicate of #1110

**Closed by kazk** 2022-05-20 22:28 UTC
