### ISSUE TITLE
Deleted Collections Remain Visible

### ISSUE THREAD

**Issue by EmmanuelIsaac** [codewars/codewars.com#2058] opened 2020-03-07 14:26 UTC
#### Description
Two collections I authored and later deleted are still visible, but lead to dead pages . 'Todo Medium' and 'Todo Hard' returning 'https://www.codewars.com/collections/todo-medium' and 'https://www.codewars.com/collections/todo-hard-2'. They can be seen in my authored collection list, when searching public collections via the kata tab (at least from my accounts POV) and also from any problems which used to be a member of either collection, for example:
![image](https://user-images.githubusercontent.com/58617353/76145077-44b3ea00-60da-11ea-99f5-a7f5fcd54932.png)
Clicking remove greys out the buttons and requires the page to be refreshed to access the collections adding again:
![image](https://user-images.githubusercontent.com/58617353/76145099-7927a600-60da-11ea-8b2e-4f27e0521544.png)
Currently no collections can be deleted, and they behave as described above after attempting to delete.

#### To Reproduce
I cannot test easily on my end, but I believe the problem was triggered by my navagating to the collection page as it was in the process of being deleted.

#### Expected Behavior
Collections should disappear entirely when deleted and connected kata should be untied.

#### Contexts
Codewars Username: EmmanuelIsaac
OS: Windows 10 Pro (64-bit)
Browser: Google Chrome
Browser Version: 80.0.3987.132 (Official Build) (64-bit)

**Comment by hobovsky** [comment] 2020-03-07 20:35
I think they will disappear over time and it's just some caching/stale read issue.

**Comment by FArekkusu** [comment] 2020-03-07 21:23
> I think they will disappear over time

The collections are fundamentally broken, so that's *highly* unlikely.

I have a collection (https://www.codewars.com/collections/later-34) which I created 2 years ago and could not delete because it was throwing errors. If you follow the link above, you'll see that another user is it's author now - I think the deletion process partially(?) failed then, somebody created a collection with the same name, and the id of my collection got assigned to his one.

You never know what and how is going to break when using them...

**Comment by MobulaKuhlii** [comment] 2020-08-26 08:02
To add, my own observation, deletion of collection which has more than 1 element works partially (for an empty or with 1 element works properly, same as reducing collection to this state by deleting each entry separately), meaning the visuals show that it disappears from users' collections tab, however after refreshing it's still there but the link gives `404` (I presume this is the cause of #2185). Moreover, it would be better if changes to order of elements were to be submitted manually (or maybe after some short time after last modification) rather than after every single one, also extending to the collections the whole private/public feature from kumites. Completely different approach could be removing collections altogether and moving things over to bookmarks (right now the former seems to be used in such manner most of the time) also with the option of publishing (it would be nice for groups or maybe it could be connected to clans?).

**Comment by XRFXLP** [comment] 2021-06-07 04:48
> I think they will disappear over time and it's just some caching/stale read issue.

I've a collection (https://www.codewars.com/collections/compilers-and-interpreters-1) which I tried deleting 6 months ago, but I still can see it on my profile.

> or with 1 element works properly

Doesn't seems to be the case, I've a collection with just one element : https://www.codewars.com/collections/will-approve, I tried deleting it couple of months ago and yesterday but it is still there.

However, another thing is I see from collections section on my profile page (https://www.codewars.com/users/XRFXLP/authored_collections) there are four collections, however in the contributions section, it is showing collections : 1

![image](https://user-images.githubusercontent.com/23459568/120960506-9d5cb180-c779-11eb-8479-8a06dcb92c17.png)

**Comment by kazk** [comment] 2022-05-20 22:22
Let me know if this is still happening.

**Closed by kazk** 2022-05-20 22:22 UTC
Labels: kind/bug, area/collections
