### ISSUE TITLE
Internal Server Issue

### ISSUE THREAD

**Issue by pranathi-cola** [Codewars/codewars.com#3226] opened 2024-05-23 09:31 UTC
I have been unable to submit my code. It shows that there is an internal server issue.  

This is my code:

function countSheeps(sheep) {
  // TODO
  let count = 0;
  for(let i=0; i<sheep.length; ++i) {
    if(sheep[i]===true) {
      count++;
    }
  }
  return count;
}

The code is supposed to take an array and check if it is true/false and return the number of times true is given as input. My testcases ran perfectly. I passed the "attempt" process but this is being shown if  I try to submit my code:

![Screenshot 2024-05-23 145045](https://github.com/codewars/codewars.com/assets/165368133/5cf55875-ad84-401f-ae46-fd452cd710e7)
![Screenshot 2024-05-23 145045](https://github.com/codewars/codewars.com/assets/165368133/4612b545-3536-491e-9891-b3e34916e082)

I am using google chrome to open the websites.

**Comment by hobovsky** [comment] 2024-05-23 09:37
Duplicate of #3209

**Closed as completed by hobovsky** 2024-05-23 09:37 UTC
Labels: duplicate
