### ISSUE TITLE
Looks like there was a server error! (500)

### ISSUE THREAD

**Issue by Marcin-Kulik** [Codewars/codewars.com#1338] opened 2018-03-22 21:09 UTC
When I go to my profile and then click on Solutions all I get is:
      Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `code_challenge_review' for nil:NilClass

**Comment by anter69** [comment] 2018-03-24 21:02
Same as #1332 so you may close the issue.

**Comment by kazk** [comment] 2018-03-25 02:56
Not exactly a duplicate of #1332 but errors from not handling `nil` have been reported for years so I'm going to close this.

**Closed by kazk** 2018-03-25 02:56 UTC
