### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by veyu0** [Codewars/codewars.com#3238] opened 2024-06-05 13:37 UTC
I just entered main page and cought internal server error

- OS:  macOS
- Browser:  safari
- Version: 17.5

**Comment by veyu0** [comment] 2024-06-05 13:37
<img width="1439" alt="1" src="https://github.com/codewars/codewars.com/assets/50861303/6790de3c-1ad0-4000-98a7-fa2d2e5df677">

**Comment by hobovsky** [comment] 2024-06-05 13:38
Duplicate of #3216

**Closed as completed by hobovsky** 2024-06-05 13:38 UTC
Labels: duplicate
