### ISSUE TITLE
Running kata or seeing unlock solution

### ISSUE THREAD

**Issue by mehran5454** [Codewars/codewars.com#1484] opened 2018-06-17 11:57 UTC
each time I run one kata, it surprises me
sometimes I cannot see "discuss" and "unlock solution" bottoms and sometimes I cannot see  "run sample" and "attend".
Is it possible someone explains to me how can I work with this site? It is really frustrating that couldn't find a simple document to show How should use the site

**Comment by anter69** [comment] 2018-06-18 15:28
@kazk seem to be a duplicate of #1214

**Comment by kazk** [comment] 2018-06-18 19:43
Closing as duplicate of #1214

**Closed by kazk** 2018-06-18 19:43 UTC
