### ISSUE TITLE
Elixir "Error: Cannot find module './runners/elixir'"

### ISSUE THREAD

**Issue by mattcree** [Codewars/codewars.com#1067] opened 2017-08-11 18:36 UTC
When I try to run sample tests or submit for testing on the elixir variant of https://www.codewars.com/kata/irreducible-sum-of-rationals/ I get this error.

```Time: 0ms Errors: 1
STDERR:
module.js:457
    throw err;
    ^

Error: Cannot find module './runners/elixir'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.run (/runner/lib/runner.js:3:10)
    at Object.<anonymous> (/runner/run-json.js:1:87)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
Server Execution Error:
module.js:457
    throw err;
    ^

Error: Cannot find module './runners/elixir'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.run (/runner/lib/runner.js:3:10)
    at Object.<anonymous> (/runner/run-json.js:1:87)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)```

**Comment by kazk** [comment] 2017-08-11 18:41
Duplicate of https://github.com/Codewars/codewars-runner-cli/issues/495

**Closed by kazk** 2017-08-11 18:41 UTC
