### ISSUE TITLE
500 Internal Server Error when vote clever/best practice

### ISSUE THREAD

**Issue by ryanmp19** [codewars/codewars.com#2255] opened 2020-10-17 05:38 UTC
**Describe the bug**
As mentioned on title

**To Reproduce**
Click vote / best practice

**Expected behavior**
post become voted but getting internal server error

**Screenshots**
![image](https://user-images.githubusercontent.com/41146124/96329270-6c5a3000-1075-11eb-8344-eab6ffc442fb.png)

**Browser**
If applicable, please provide your browser information.

- OS: Windows 10
- Browser: Opera
- Version: 71

**Additional context**
In case @kazk see this, I have disable all my Opera extension and the built-in ads and tracker blocker and Tried with my Chrome too but nothing help. And also, I got that 503 error everytime I load any kata.

**Comment by kazk** [comment] 2020-10-17 05:41
Which kata is it? It might be a known issue for old kata with lots of data.

All the avatar 503s are from GitHub and should be unrelated though.

**Comment by ryanmp19** [comment] 2020-10-17 05:54
its this kata: https://www.codewars.com/kata/54da5a58ea159efa38000836/solutions/javascript
and recently just tried in this kata: https://www.codewars.com/kata/54ff3102c1bad923760001f3/solutions/javascript
both come with the same internal server error

**Comment by kazk** [comment] 2020-10-17 06:11
Yeah, unfortunately this is a known issue for some old kata. This is caused by how the solution groups are stored in the database and requires fundamental changes to how things work. I've been doing what I can since I inherited the project, but the database is still a huge mess and needs major rework.

**Comment by ryanmp19** [comment] 2020-10-17 07:04
I see. Sorry I haven't google about this bug yet. I post this once I found the bug. I hope it's not a duplicate bug.
Anyway, perhaps you need some help to fix the bug, you can contact me. Although, I'm still junior at web development.

**Comment by kazk** [comment] 2020-11-22 06:26
Closing because I commented the details on another issue https://github.com/codewars/codewars.com/issues/2263#issuecomment-719997658, and we don't need two issues open.

**Closed by kazk** 2020-11-22 06:26 UTC
Labels: kind/bug
