### ISSUE TITLE
My profile is not displaying in my clan

### ISSUE THREAD

**Issue by micahwierenga** [Codewars/codewars.com#1273] opened 2018-01-07 21:01 UTC
My profile is not longer displaying in the list of clan members (Denver GA). My clan leader said he could see me, but I'm not able to when I log in. He also looked at my profile and it said I was in a clan called shrug, but when I view my own profile and account settings, both say Denver GA.

**Comment by sljohnson32** [comment] 2018-01-17 05:40
I am having the same problem.  Interestingly, I am in the Turing School of Software and Design clan (also in Denver).

**Comment by kazk** [comment] 2018-03-16 18:52
Closing as duplicate of #1243

**Closed by kazk** 2018-03-16 18:52 UTC
Labels: duplicate
