### ISSUE TITLE
Avira extension can prevent posting comments

### ISSUE THREAD

**Issue by ryanmp19** [codewars/codewars.com#2253] opened 2020-10-16 04:17 UTC
**Describe the bug**
I can't post an issue to this kata: https://www.codewars.com/kata/5508249a98b3234f420000fb/discuss

**To Reproduce**
1. Write issue to "leave feedback or ask for help..." textbox
2. click post

**Expected behavior**
Should post the issue but nothing happen, checked browser console and get error, error screenshot below

**Screenshots**
![image](https://user-images.githubusercontent.com/41146124/96212407-069c7400-0fa1-11eb-9496-c9d2636d288e.png)

**Browser**
If applicable, please provide your browser information.

- OS: Windows 10
- Browser Opera
- Version 71.0.3770.228

**Additional context**

**Comment by kazk** [comment] 2020-10-16 04:26
Thanks for reporting. It's weird that you're getting 404.

Can you post to other kata? If not, have you confirmed your email? If you haven't, you can resend the confirmation email from Account Settings. This is unlikely though because the status shouldn't be 404.

Another known cause is some issue with the database but that should return 500 error.

**Comment by FArekkusu** [comment] 2020-10-16 09:50
Post a comment on a random kata, and if it works, just delete it immediately.

**Comment by ryanmp19** [comment] 2020-10-16 10:12
Nope, this is attempt on posting to other kata, still having the same error 😕
![image](https://user-images.githubusercontent.com/41146124/96246289-a0304980-0fd2-11eb-9a24-7ba13d58c714.png)

**Comment by kazk** [comment] 2020-10-16 22:28
@ryanmp19 I just noticed you're using Opera.

Can you try in another browser like Firefox or Chrome to see if it's related to the browser? I'm not sure how it can cause 404 though.

**Comment by hobovsky** [comment] 2020-10-17 00:13
If it helps anything, I use Opera as my only browser and I have no issues with CW. Granted, I do not post issues on kata every day so I might miss something, but I think I have not noticed any browser specific issues.

**Comment by kazk** [comment] 2020-10-17 01:09
Thanks @hobovsky. Glad to know there's no issues with Opera.

@ryanmp19 Can you post the full URL in the error message?

![image](https://user-images.githubusercontent.com/639336/96325121-1ab09780-0fda-11eb-8604-0c7e2d6981a5.png)

I see `/comments/abId0.09208` and that looks suspicious.

Do you have any extensions enabled?

**Comment by ryanmp19** [comment] 2020-10-17 02:38
@kazk here you go: https://www.codewars.com/kata/5508249a98b3234f420000fb/comments/abId0.5423597410875649

And yes, apparently it is caused by 1 of the 3 extension.

Currently I'm trying Opera because I'm tired of Chrome taking all my ram portion -_-
and somehow 3 avira extension was automatically installed:

- Avira Safe Shopping

- Avira Password Manager

- Free Avira Phantom VPN – Unblock Websites

Maybe because I have avira as my antivirus, I don't recall any option to skip the extension when I install this browser.

Tried to disable the safe shopping (it has ad blocker feature in it), but still can't post. Tried to disable all of them and it works now. probably related with the VPN. But, I don't activate the VPN though.

**Comment by kazk** [comment] 2020-10-17 02:50
Thanks for confirming. I'm going to close this because this is not our bug.

**Closed by kazk** 2020-10-17 02:50 UTC
Labels: area/comments, wontfix
