### ISSUE TITLE
Kata auto-retired with 4 "Somewhat Satisfied" and 1 "Not Satisfied" votes

### ISSUE THREAD

**Issue by CliffStamp** [Codewars/codewars.com#1645] opened 2018-12-04 02:33 UTC
It appears that a kata can be retired if there are a string of negatives votes in a row.  I would assume that the intent of this was to retire katas which were so problematic that the negatives heavily outweighed the positive, or a steady stream of issues just caused a pile up of downvotes.

However there there are a group of PU's who are seriously abusing this ability by 

- making a down vote
- calling for mass action in gitter chat
- spamming downvotes

Thus they completely ignore the community feedback / interaction, and have created their own private enforcement militia. Note critically there is NO response time from the author to correct any issues, and there are at times no issues even raised, not even any feedback given. Ex 

https://www.codewars.com/kata/5c001479a7c77ac734000c25

When pressed for why this was retired, one noted likely because it was "uninteresting" to those that downvoted. Note it was a white kata and that group are far from novice programmers. 

Note the kata 

- well written description
- random tests
- one small bug in the test suite

The author had no idea why it happened, no feedback given on the retirement. 

If you wanted to create an elitist and openly hostile environment and about as anti-learning as you could, then this pretty much has achieved it. You have a small group of people who have their own standard of what quality means, which is never documented anywhere and enforced without explanation which is never even explained let alone actually defended. 

Even if a new user somehow had that reception and for some crazy reason wanted to try again, there is no indication at all about what they need to do because no feedback is given, and there is no standard of what makes a quality problem even hinted at let alone documented for someone to try to follow. I seriously doubt that CW actually intended this retirement policy to be used in this way.

**Comment by kazk** [comment] 2018-12-04 02:48
So this kata was retired after 4 "Somewhat Satisfied" and 1 "Not Satisfied".
I don't know if this is a bug or not, but I personally don't like the current behavior.

This happened because the current implementation only cares about the number of votes and the satisfaction percentage which is calculated by `(up_vote + 0.5*ok_vote)/votes`.

I think we should at least consider how many "Not Satisfied" was given or the ratio of it.

**Comment by kazk** [comment] 2018-12-04 02:53
I don't know if this is an abuse though. I'd say it's Codewars' fault not being more clear. I was surprised by this to be honest.

**Comment by kazk** [comment] 2018-12-04 03:10
Also, it's a good idea to give authors some time to fix before auto-retiring. But I'm not sure how to do that with current system's limitation. The votes are permanent in most cases so simply giving a time before retiring would be worse (author spends time to fix and fixes it, but gets retired anyways).


(I'm never on Gitter, but I read them randomly and see discussions about improving Codewars. I wish there's a way to keep track of them and manage the information better.)

**Comment by Voileexperiments** [comment] 2018-12-04 03:49
@CliffStamp 

I'm going to repeat the same arguments I have in *cough* one of the recent beta katas here:

---

> However there there are a group of PU's who are seriously abusing this ability by
> - making a down vote
> - calling for mass action in gitter chat
> - spamming downvotes

For the record, this is not spamming, this is [vote-brigading](https://en.wikipedia.org/wiki/Vote_brigading).

However, even then, your choice of word here is, frankly, disgusting:

- In what sense is this an *abuse*? People can upvote or downvote all they want. What is the problem in downvoting katas that are not up to quality? Why is this suddenly an "abuse"?
- If you're defining this as "abuse", what about instead doing the same *but for upvotes* to quickly make a beta kata approvable? Is this an "abuse"? If it's not, why is downvoting and abuse while upvoting is not?
- In what sense is this "spamming"? @10XL even [has a tool to automatically upvote every kata you've solved](https://github.com/10XL/codewars-voter). Is this spamming? Is "posting some old betas so someone will solve it and finally get enough votes for approval" vote-brigading? Is "bumping my beta kata to the top of the search list every day" spamming?
- Also, as far as I recall, *nobody has actually called for massive action in gitter chat*, so it's highly likely you're imagining things or just making it up.

Your choice of word "spamming" and "abuse" contains hidden agenda and sentiment that, unless you clarify yourself, remains hidden.

---

> When pressed for why this was retired, one noted likely because it was "uninteresting" to those that downvoted. Note it was a white kata and that group are far from novice programmers.

> If you wanted to create an elitist and openly hostile environment and about as anti-learning as you could, then this pretty much has achieved it. You have a small group of people who have their own standard of what quality means, which is never documented anywhere and enforced without explanation which is never even explained let alone actually defended.

Are you trying to pull off the "PUs are all elitists who downvote katas because they are too good for them, blablabla" public-shaming talks again?

**Stop it already.**

There was a time where PUs like me vote like a normal person does: according to how I feel about the kata and how it's written. Then there comes a few... "special" kata authors and users who throws a fit whenever a new beta kata is downvoted and begin to call all kinds of words on PUs who downvoted their katas. Occurrences like [this](https://www.codewars.com/kata/5c01c1525486bf12bd0001cd/discuss) happen literally every few days, and it's a massive annoyance and disappointment to participate in the beta process.

**Eventually we settled to just upvote anything that is acceptable to prevent these "special" kata authors and users throwing tantrums at us again.**

If beta quality gets lower, nobody but the likes of you are responsible for the mess.

***You do not dictate how how people vote*** (if anything, it'd be a standard set up by CW officially), ***nobody owes you an explanation why they downvoted***, and ***you do not simply police other user's votes***. Do I have to fill in a "downvote submission form" filled in a 1000-word essay about why the downvote is justified, and get 5 approvals from 5 different users (which 2 of them must be novice programmers) before I can even cast and downvote and get it applied? (And of course if you upvote, you just upvote and it's applied. Go figure.) Because these constant nagging and shaming is just suggesting this. This is a serious breach of other user's free will and freedom of speech. It's utterly disgusting.

(The same goes to ranking votes as well.)

---

Currently the only way for users to express their opinion *that actually matter* in beta process is to cast their votes. Comments are pointless as some kata authors are *known* to straight out ignore them, and once there are enough votes and satisfaction rating, *someone* can just barge in, resolve all the issues instantly regardless of their validity and approve the kata.

This is the final line of defense in the current beta system. I did not post #1626 for no reasons.

If you don't like how others vote, *use your votes*. Stop calling names and public-shaming whoever downvoted the kata. You're abusing the process more than people posting links to new beta katas in gitter chat.

**Comment by Voileexperiments** [comment] 2018-12-04 03:55
@kazk As far as I can see, the only way to resolve the constant arguments about the same thing on beta katas are to set up a standard ASAP. Then everyone has to be referred to the standard and advised to comment on the standard outside CW.

Well, it's not like I haven't tried (I did posted lots of issues in this repo about various things that *ought to* have a standard), but whenever an issue is set up, the users who were arguing on CW comments almost never give any input, so it leads to nowhere and nothing can be done. Instead we're still stuck at pointless, unproductive arguments on new beta katas every few days, while they should be expression their opinions on the github issues instead. At this point I'm not sure if these arguments are in good faith anymore.

Can we at least set up some issues to talk about these things in specific, and direct users to these issues to continue talking as soon as another argument is about to happen in a beta kata? Otherwise I'm not seeing how the standardization process can proceed.

**Comment by kazk** [comment] 2018-12-04 05:55
@Voileexperiments Let's start by collecting "the constant arguments about the same thing". I'll create an issue about it for discussion and also a wiki page later that summarizes them so the community can reference it.

**Comment by Blind4Basics** [comment] 2018-12-05 15:48
> calling for mass action in gitter chat

@cliff: talking about me?

Did you seriously look at the katas I called this for? All was bad in those: bad description / bad tests / bad design / even done by cheaters, for some of them. Let's rather say I call for an action to be sure that no "casual user" will make a mistake by upvoting it, forbidding a retirement.

You'd say that the author could act on the kata to make it good. Yes. But in most case it requires to actually completely rewrite the thing. And the retirement can be educational for the author, too.

**Comment by Blind4Basics** [comment] 2018-12-05 15:53
(wanted to edit, but firefox versino unsupported where I am, so...)

> And the retirement can be educational for the author, too.

yes because in those cases, the original work is so bad that it clearly shows that the author published without any care about what others do or any sort of "respect" (translation troubles, don't focus your attention on the chosen word) for other users. So it's seems pretty fair to act that way.

**Comment by GiacomoSorbi** [comment] 2019-01-01 02:57
I am sorry, but apparently I was mentioned indirectly in the discussion, as per Voile's habit: nice collection of strawmen up there, but the point is that a bunch of power-users goes around bullying other people, mostly new users, with nasty remarks and/or no feedback at all.

So odd that also it comes from somebody declaring that he just wants to downvote on a whim (like "this kata is too easy for me") and/or without bothering to leave a comment, uh...

Regardless, I think the correct solution would be to ponder the user story: somebody just blindly approving or downvoting katas should be weighted less and less.

And, please, spare the pathetic victimism of mentioning hidden agendas or attacks to one's freedom of speech (which was never impeded, as far as I am aware).

**Comment by CliffStamp** [comment] 2019-01-01 17:41
> And the retirement can be educational for the author, too.

It could be, but it won't for newcomers, the literature is clear on that, that isn't even debated. There are numerous katas where the author was actually trying to fix the issues, but the vote spamming preventing them from doing so as it can happen instantly, as in minutes. That is not going to create an environment where newcomers want to learn, it is just going to drive people away. 

When you look at a kata, you see the effort that it would take you to write it, and the effort it would take you to think on/create the concept. For you, those katas are all trivial, and you see authors doing no work at all because that is what it would take for you, no effort. However for a beginner, even the most basic things can be a struggle like trying to sort out why Test.expect is not ok, but Test.assertEquals is, and how to use them and writing random tests is very daunting, especially as there are no examples set up for them to review, adapt, modify. In many languages even the most trivial thing like how to compare numbers isn't even standardized and even PU's debate about it, but yet newcomers are supposed to be able to do that and if they don't out come the spammed downvotes?

Plus when you look at what a new author sees when they look at existing kata, it isn't obvious that 

- the approval conditions are a LOT higher now than in the past
- you don't have nearly as much time to make changes due to the current user base

There are complaints about that as well, people wondering why their kata don't get approved when they see the same type of thing being approved before. How come there are dozens of palindrome katas with only minor changes approved, but I make one kata on X which has only one other X type kata and I get spammed with downvotes and issues? 

The massive increase in user base, and in particular very active users who look for new betas and instantly solve/rank them, makes it a very different environment than the past and this isn't made clear to a newcomer when it talks about making new katas. The reality of spammed downvotes and instant retirement isn't at all noted in the kata creation. If your kata isn't "interesting" then it could be instantly retired without warning - that, if true, deserves a very big and bold red flag in the kata creation documentation.

What is one of the main complaints now - lack of new and interesting content. Well guess what, this mass vote spamming and overly hostile reaction to newcomers is exactly what you want to do to create that problem. People who write new and interesting problems don't just wake up with the ability to do so, it comes with experience, and if you want that, then actually act in a manner which encourages it. Yeah there are very low effort and low yield katas, and there are likely low effort and low yield authors and some that never will be anything more. But you will never find the ones that could generate decent content with the "kill it with fire" approach noted above.

But hey, this is a community site - if the community actually wants this approach well go do it, but I can guarantee that content creation will stagnate because of it, that isn't even debatable, so think about what you want to achieve.

**Comment by Voileexperiments** [comment] 2019-01-01 17:54
> There are numerous katas where the author was actually trying to fix the issues, but the vote spamming

Define "vote spamming".

Votes that you don't like are not "spamming". If your kata has issues, then... your kata has issues? Why should I not downvote just because "author is trying to fix the issues", when *it's not actually fixed at the moment*? (See: raulbc777's katas, where he could say "I'll look into the issue" and then *forgot about it for 3 years*) By next day you might even say "you shouldn't downvote because the kata author's learning how to do it".

> For you, those katas are all trivial, and you see authors doing no work at all because that is what it would take for you, no effort. However for a beginner, even the most basic things can be a struggle

...Yeah, I called it.

It's funny how you're using "downvoting because kata shows no effort" as a strawman, when in the previous paragraph you're talking about "downvoting because kata has issues". Nobody doing the downvotes actually care about who is the one writing the kata, or their skills. We just downvote when the kata has issues.

> this mass vote spamming and overly hostile reaction to newcomers

If you're still trying to use this strawman, please *pull out actual data that supports this claim* before accusing everyone of being elitists, thank you. Your argument is disgusting.

**Comment by Voileexperiments** [comment] 2019-01-01 18:04
@GiacomoSorbi 

> Regardless, I think the correct solution would be to ponder the user story: somebody just blindly approving or downvoting katas should be weighted less and less.

I also think the correct solution would be to revoke kata creation/translation privilege to users who *keeps making problematic katas/translations*, which would mean you'll instantly lose this privilege.

It seems like you're still butthurt about me downvoted on that kata of yours, but really, I don't owe any explanations to you about that, so you can go being salty about it for another months if you wanted. The only thing that I think you ought to know is that my track record is better than yours, I *actually fix stuff that is broken*, and users *who are normal and reasonable* agree about what I do and say. In some sense, you deserved it, so the ball of "reflecting on what's wrong with one self" is on your court.

**Comment by GiacomoSorbi** [comment] 2019-01-01 18:44
Mh, no, sorry: I still trust I am not the more childish of the 2 here and I voiced my concerns more than once, even before that, about katas being downvoted on a whim and (new) user treated like shit for no plausible reason.

I have no problem admitting that you are in all likelihood a better coder than me (and a good chunk of other users), also considering I am relatively new to the game (only a few years ago I was doing something else); yet I do not see how this is relevant, unless you want to push for your own flavour of "might makes right".

I am actually fixing stuff almost every time I get notified about something.

But thanks for admitting a personal bias and thus downvoting, as I stated, on a whim or with very preposterous motivations. Yet again, it is not a matter about me: sorry if not everybody is so self-centered.

**Comment by FArekkusu** [comment] 2019-01-01 19:17
> I am actually fixing stuff almost every time I get notified about something.

Latest 2 translations you were notified about was never fixed properly - you either did *practically* nothing or made everything worse, and closed the issue afterwards. Your 2 katas which I found issues in were never fixed as well, all you did was close my issues and downvote my comments - well done :+1:

> about katas being downvoted on a whim and (new) user treated like shit for no plausible reason

In a year I haven't seen **even once** a kata being downvoted for no reason. Unless it's newbies who couldn't complete the task, forfeited and downvoted the kata (hopefully such users never check Beta kata list, and this bullshit only happens with approved content). Your katas (because obviously you're caring about what **you** make, and talking about your katas solely) get downvoted because they're bad, not because people dislike you after all the terrible experience of interacting with you they have.

**Comment by GiacomoSorbi** [comment] 2019-01-01 19:34
Not really, I just fixed an edge case in the last one yesterday, but then again you think everything is about you; you did stupid remarks multiple times and you just know how to act like a spoiled kid, demanding to fix things which are not broken.

If you care to know more details, I am referring to your demands to fix with specific inputs you want to be tested or claiming my solution which was much more performing than your silly brute-forcish one was the one preventing you from completing a kata, suggesting me how to make tests for another kata while you were just running thousands of them for no plausible reason and much more.

Deal with it: you are no Voile. And probably not even remotely as good as you think you are.

I have done like one kata in the past few months and again: no, it is no about me. Not everybody is like you and your master, you know. I have a live, commitment and plenty of other stuff to do - I am not losing my sleep over it or patrolling CW site and channels 24/7.

Now, back on topic, your role-model has himself admitted of downvoting without giving a reason or just because he does not like a kata (which is a tad different from a wrong kata), so your claims are, yet again, just an ungrounded waste of bytes.

If you like to even deny that katas are downvoted without leaving a single line of feedback - suggestions and that newbies are treated pretty poorly, if not bullied, well, please, go on...

**Comment by Voileexperiments** [comment] 2019-01-02 07:39
I think this SO meta question should be instructive to the problem at hand:

https://meta.stackoverflow.com/questions/366889/can-we-make-it-more-obvious-to-new-users-that-downvotes-on-the-main-site-are-not

**Comment by GiacomoSorbi** [comment] 2019-01-02 07:49
Strawman again: we are discussing being gratuitously rude (with beginners in particular) and downvoting on a whim, not because a kata is bad/duplicated, but because you just happen not to like it.

Is that so hard to face and discuss?

*[On top of that, I would definitely not take SO as an example of how to run things, as they had (have?) lot of issues in people not interacting out of fear and hopelessness - not to mention up/downvoting answers to the same question - thus competing information - it is not the same as building a kata on a specific issue/feature.]*

**Comment by FArekkusu** [comment] 2019-01-02 08:53
> downvoting on a whim

The fact that people don't like your katas and downvote them doesn't mean that this happens to every one. It just so happens that you're one of the users who are authoring duplicates, writing bad tests, and writing bad descriptions which is a red flag to "kill it with fire" ;)

**Comment by GiacomoSorbi** [comment] 2019-01-02 09:35
It is not "people", it is you, your master and occasionally very few others; you can look at my stats for that. Same for your childish downvoting frenzy: I understand that life must be rather grim for you, but most people don't even bother "patrolling" on their "enemies" to spam downvotes on each of their comments, kid.

That said, which part of "it is *not* about me" are you struggling to comprehend? Come on, it is not like Kadane's algorithm that you proved not to grasp/identify - we are conducting a much simpler discussion 😞

**Comment by Blind4Basics** [comment] 2019-01-02 15:14
@CliffStamp :
> But hey, this is a community site - if the community actually wants this approach well go do it, but I can guarantee that content creation will stagnate because of it, that isn't even debatable, ___so think about what you want to achieve___.

Are you seriously saying this to __me__ in particular?!? XD
Amidst all the PU doing betas, I'm surely the one who's giving the most information in the comments...

Anyway. That part is plainly true, tho:
>  If your kata isn't "interesting" _or has conception issues_, then it could be ~~instantly retired without warning~~ _retired very quickly_ - that ~~, if true,~~ deserves a very big and bold red flag in the kata creation documentation.

@kazk : could be of use to put that or some variation of it somewhere appropriate (but where...?)

**Comment by CliffStamp** [comment] 2019-01-05 04:55
> Amidst all the PU doing betas, I'm surely the one who's giving the most information in the comments...

I would not dispute that.  I wasn't speaking to you personally, I was just noting that new kata authors can get an extremely harsh initial response (as noted in the above), and this isn't beneficial to the site at all, it in fact does the opposite of what the goals the people who do it publically say they are trying to achieve. It certainly won't increase the rate of quality kata being made, it will only decrease it.

I can't imagine anyone, anywhere who would even begin to advocate it in a professional situation where newcomers were trying to be integrated into the workforce. Again I would simply ask, what is it you are trying to create/achieve? Are new comers to coding supposed to want to come here to learn, it is supposed to be a place where they build skills or it is only a place where you go when you have them? If it is the former well the kind of behavior noted here certainly isn't the way to make that happen.

**Comment by Voileexperiments** [comment] 2019-01-08 03:34
I'm baffled I actually have to write personal things like this, but here we go:

@CliffStamp: Please stop being a backseat judge that complains about everyone else's judgement while doing nothing useful.

Once upon a time, PUs used to just upvote katas that they feel interesting. Okay, but that leads to lots of katas with very weak tests and lots of iffy solutions passed; also there are lots of duplicates and low quality katas. So then it's advocated to PUs should vote according to kata topic quality and kata test quality. *Okay*, but then there are... some snowflake users that complains very vocally on the comments whenever their katas get downvoted. So we just give them a "very satisfied" anyway to stop them from complaining again and wasting everybody's time. **Okay**, then everyone should be satisfied and nobody will complain about PUs, right?

No, because now *you*'re coming out and complaining about every PU giving "not satisfied" votes for being "elitist to newcomers".

You're more toxic than all the PUs mentioned above: at least we do things actually contributing. We make beta votes. *We curate beta content and raise issues about things that needs to be fixed*. **We fix stuff others have left unfixed**. Meanwhile what you've done in these months is literally just complaining about everything being too strict, then fall back to the usual abstract nonsense whenever being pressed by someone else.

This is why no PUs like you. You talk big but you are unhelpful and disrespectful to everyone else who is actually spending their effort. If you want to beta process to go better, you should inform and encourage the kata authors to make their katas better and so we can all have better beta experience, not [inducing FUD to new kata authors by calling us elitists and trashtalking the entire beta process to make kata authors entitled](https://www.codewars.com/kata/5be0d7b36f74f583ab000109/discuss). By this you're insulting us in a way, and some people like me don't mind fighting back.

(Oh, and don't forget you also prematurely approved a few katas that has problems and never actually fix them either. PUs do remember things, you know, and your track record is not that great.)

Also, it's funny that while every PU feels dubious about ZED making crazy ranking votes, only you are oblivious to this and instead complain about every other PU voting too harshly. At least if you want to pick a target, pick a better one? Then at least some people might agree with you.

@GiacomoSorbi Can you ever stop complaining about everyone else before reflecting on "what should *I* have done" and actually does them?

Have you actually worked on making your katas/translations more correct so that other people such as me, Blind4Basics and CliffStamp don't have to fix your broken code every single time, while you're most likely not gonna fix them?

Why can't you git gud on the kata/translation creation process like, how *I* do? I write katas with almost impeccable tests, resolve possible issues quickly, fixed and approved more katas than anyone else that seldom gets issue complaints of. This is what a good kata author and PU should do. Not one like you've been doing where you keep making dubious katas/translations, gets incredibly butthurt whenever we points out you need to git gud, and then keep pretending nothing happened.

Again, this is for you too: If you keep behaving like someone who talks big and think his opinion is always right but consistently fails to deliver, nobody will like you. You deserve what you got.

**Comment by Voileexperiments** [comment] 2019-01-08 07:30
> but again, as I told to your minion: "it is not about me"
Then why are you still commenting here? Your presence here has been nothing but derailing the topic.

> katas should not be downvoted on a whim
Unless you can read other's minds, all claims that "katas are downvoted on a whim" are unsubstantial.

And in the next sentence you're already claiming "probably venting out frustration from other sources on the people that you like to feel beneath you". So what is your claim actually, is the downvote on a whim or not on a whim?

**Comment by GiacomoSorbiAcuris** [comment] 2019-01-08 07:33
I frankly don't see how one option would exclude the other... Do you want to focus on that for a few exchanges, as a new way to sway the conversation?

**Comment by Voileexperiments** [comment] 2019-01-08 07:34
@kazk I suggest closing this issue as it is right now because it is filled with a biased view that the entire issue is caused by "elitist power users shutting down new kata authors because they don't like everything". If we are going to deal with the underlying issue (how to handle subpar beta katas more gracefully and let new kata authors be more informed about the retire process), this narrative is extremely harmful as it strikes to amplify the confrontation between kata authors and kata curation instead of working together.

In any case, I'll open a new issue that is more instructive and helpful to this matter.

**Comment by kazk** [comment] 2019-01-08 22:55
Please keep the comments on the issues in this repository on topic.
I don't really have the time to read all of this and some potentially useful information gets buried.

Closing this because #1672 is well written, summarizing the problems.

---

@FArekkusu I'll look into the possible bug [you mentioned](https://github.com/Codewars/codewars.com/issues/1645#issuecomment-450751125).

**Closed by kazk** 2019-01-08 22:55 UTC
Labels: area/qa, enhancement
