### ISSUE TITLE
CW-172: "Unpublish on two issues" mechanism causes old betas to become unrecoverable

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#3103] opened 2023-11-18 23:19 UTC
Motivated by [this post](https://www.codewars.com/kata/5e4ee2c17770f20016d52f60/discuss#6558c88f3974cb1378be2a62) (but discovered some time ago already, but I cannot find any report):

To force new authors to curate their kata better, the mechanism has been introduced which causes beta kata to be auto-unpublished when they collect two issues during 24h (?) curation period after being published. The mechanism was meant to reduce the amount of newly published, bad kata, which can be fixed by authors and republished. However, it affects also old kata, when author is long gone, and there is no one to republish them.

To reproduce:

1. Find an old beta kata.
2. Do anything what causes update of its "modified" timestamp: approve a pending translation, create and approve a fork with a fix, edit it with kata editor and republish, etc.
3. Raise an issue or two on it (depending if it already has a pending issue or not), or use the "recalculate stats" mender action (if the kata has at least two issues).

At this point, the kata gets unpublished and moved to draft state. If its author is inactive, the kata cannot be recovered.

The effect is deemed to be undesired, because initially it was meant to handle only new kata, while their authors are still around, ready to react to issues.

**Comment by Blind4Basics** [comment] 2023-11-25 12:33
another case here...: https://www.codewars.com/kata/55a9a6ffd7f21d7d000000e5/discuss

Author gone since 2015 / got unpublished with my issue...

---

edit: on the other hand, [this one](https://www.codewars.com/kata/5597ca93d5b5b37db8000066/discuss#6561c06687ba1844f4ada931) didn't get pushed to draft while dfhwze also raised an issue on it while both kata already add an old issue... => ??

**Comment by VanessaGreene** [comment] 2023-11-28 17:42
Escalated to CW-172

**Comment by kazk** [comment] 2023-12-06 22:11
This was introduced in June 2022:

> Recently published kata (within the past 48h) is now automatically unpublished if it has 2 unresolved issues.
> https://github.com/codewars/codewars.com/discussions/2600#discussioncomment-2969174

We overlooked that the "last published at" timestamp is modified by actions other than the original author publishing the kata. Not sure what's best to do. I don't want to change this and affect other stuff, nor add a new field just to track when the original author published the kata.

> If its author is inactive, the kata cannot be recovered.

Can you (a mod) publish the draft kata from the editor? Maybe I'm overlooking something, but I don't think I see anything preventing that. Note that we don't allow publishing draft kata with unresolved issues, as proposed in #2598, so the "Publish" button should be disabled until the issues are resolved.

**Comment by Kacarott** [comment] 2023-12-06 22:19
Attempting to republish a draft with no issues initially looked like it was working, but then I found myself on a page "You do not have permissions to view this page", and the publish did not work.

**Comment by hobovsky** [comment] 2023-12-06 22:31
> Can you (a mod) publish the draft kata from the editor? Maybe I'm overlooking something, but I don't think I see anything preventing that.

I think it's never been possible?

I just tried and got the same result as Kacarott: the Publish button is clickable, but after clicking it I end up with "You do not have permissions to view this page" and kata state seems to be not changed.

**Comment by kazk** [comment] 2023-12-07 07:00
Thanks for checking. It took me forever to find why mods can save, but not publish a draft kata you don't own :man_facepalming:

I'll make these kata recoverable by allowing the mods to publish them like admins.

**Comment by hobovsky** [comment] 2023-12-07 07:27
Would love to see the `if` which caused this :D

**Comment by Kacarott** [comment] 2023-12-07 07:48
Will this also allow mods to publish even with open issues? This behaviour happens when some recently updated kata gets some new issues, so it would be nice to be able to directly republish without having to close the issues, republish, then re-open the issues. (especially if adding the issues again would revert it back to draft again lol)

**Comment by hobovsky** [comment] 2023-12-07 08:43
When you close the issues, publish the draft, and re-raise the issues, the kata will get unpublished again :D (unless you merge the pending issues into one).

**Comment by kazk** [comment] 2023-12-07 19:31
> Will this also allow mods to publish even with open issues?

No, everything else stays the same. But I'm open to suggestions.

I forgot exactly why we decided to disable publishing with unresolved issues, but can't you confirm that the issue is resolved, close the issue, then republish? Isn't that what the author is doing?

**Comment by Blind4Basics** [comment] 2023-12-07 20:31
> can't you confirm that the issue is resolved, close the issue, then republish? Isn't that what the author is doing?

That's what's currently happening, yes.

> I forgot exactly why we decided to disable publishing with unresolved issues

There were mostly 2 reasons (maybe I forgot some others, tho):
- Most (newbie) authors will insta-republish if they can, even without solving the issues, so the kata will definitely get retired even if it has potential. This "delay" makes the beta process less destructive for authors, and less upsetting for beta testers.
- At some point in the past, this also was an anti-troll-kata/author measure.

**Comment by Kacarott** [comment] 2023-12-07 20:36
In most cases when a kata is unpublished, the original author will still be active, and they have easy access to their own kata and are usually the main person responsible for fixing the issues, so it works out well. But in the case where a kata is old and the author long gone, then theoretically mods can fix the issues and then resolve and republish, but it means that the responsibility for fixing the kata lies mostly on the mods, and in the time until its fixed, no one has easy access to the kata, they have to save the url somewhere.

I think it would be a lot more convenient if mods could republish even with open issues, because it allows old kata to still be accessed by other community members who might be interested in fixing it, and it also allows the kata to be republished quickly, before the link is lost.

**Comment by Blind4Basics** [comment] 2023-12-07 20:41
> I think it would be a lot more convenient if mods could republish even with open issues, because it allows old kata to still be accessed by other community members who might be interested in fixing it, and it also allows the kata to be republished quickly, before the link is lost.

Adding a condition to the unpublishing so that it doesn't happen when _more_ than 2 issues are opened would avoid to auto-unpublish the old ones, maybe?

**Comment by kazk** [comment] 2023-12-07 23:15
The change to allow mods to publish drafts was deployed, but I'm still thinking about republishing with unresolved issues and old betas with inactive authors.

Even if we allow the mods to republish with open issues, the kata will be unpublished whenever the current condition is met. I thought maybe we can check the date when the author last signed in, but that doesn't mean anything if they've lost interest in maintaining the kata.

Maybe we can add a way to flag a kata as "abandoned by author" and use it for special casing. If a kata is flagged as "abandoned", we won't auto-unpublish and allow mods to republish with open issues.

**Comment by hobovsky** [comment] 2023-12-07 23:45
Maybe another metric could be kata age? Not 48h after "last published at", but (for example) 48h or 5 days or a week after "first published"? Kata seem to have such property because it is visible in "STATS" section of kata details? Or after first non-author solution, or attempt? This way, old kata would not get auto-unpublished regardless of the author's activity.

**Comment by kazk** [comment] 2023-12-08 04:12
Good idea. Let's include when the kata was first published, and only consider unpublishing if the kata was first published at most a week ago. I think it still makes sense to only unpublish if the kata was last published within 48 hours. For example, don't unpublish if the kata had survived 3 days before 2 issues were opened.

Current condition:
```ruby
total_unresolved_issues >= 2 && last_published_at >= 2.days.ago
```

New condition:
```ruby
published_at >= 1.week.ago && total_unresolved_issues >= 2 && last_published_at >= 2.days.ago
```

**Comment by kazk** [comment] 2023-12-08 05:37
Deployed the change

**Closed as completed by kazk** 2023-12-08 05:37 UTC
Labels: jira-escalated
