### ISSUE TITLE
WOT extension causes site to not display correctly

### ISSUE THREAD

**Issue by joss-c** [Codewars/codewars.com#1979] opened 2019-12-04 15:04 UTC
#### Describe the bug
It appears there is something wrong with the CSS and the site isn't displaying how it should.

#### To Reproduce
Go to kata detail (see: A), or list of solutions for any kata (see: B).

Screenshot A:

![Screenshot A](https://user-images.githubusercontent.com/3187056/70153486-ec1e1c80-16a6-11ea-89e4-ccf8f5adb266.png)

Screenshot B:

![Annotation 2019-12-04 145801 2](https://user-images.githubusercontent.com/3187056/70153608-212a6f00-16a7-11ea-9db6-38f92ae618fc.png)

#### Contexts

Please complete the following information:

- Codewars username: joss-c
- OS: Windows 10
- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

**Comment by joss-c** [comment] 2019-12-04 19:32
Just to note, I did try doing a hard refresh and the problem persisted.

**Comment by kazk** [comment] 2019-12-04 20:21
I can't reproduce this.
Can you try in Incognito/Private Window with all extensions disabled? Also, is there anything logged in console?

**Comment by Mikhail158** [comment] 2019-12-06 20:19
I have the same issue since the last visit (wasn't present previously (more than one month ago))

Some information:
- OS: Windows 10
- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

**Comment by kazk** [comment] 2019-12-06 21:40
@Mikhail158 can you try in Incognito with all extensions disabled? Also can you check if anything is logged in console?

**Comment by joss-c** [comment] 2019-12-07 13:26
So after some testing I discovered that it was the "[WOT Web of Trust, Website Reputation Ratings](https://chrome.google.com/webstore/detail/wot-web-of-trust-website/bhmmomiinigofkjcapegjjndpbikblnp)" extension causing the problem. Disabling this extension fixed the problem.

Here is the console output for Chrome with _only_ this extension enabled.

![console readout](https://user-images.githubusercontent.com/3187056/70375366-f46b9700-18f4-11ea-8e91-5c8d8f366d51.png)

**Comment by Mikhail158** [comment] 2019-12-08 11:51
WOT Extension adds it's own icon to links. Probably there are some CSS conflicts.

**Comment by kazk** [comment] 2020-02-05 20:59
Closing because it's not actionable by us.

**Closed by kazk** 2020-02-05 20:59 UTC
Labels: tier/front-end
