### ISSUE TITLE
C++ Tests fail showing "true"/0 "false"/1 are not equal.

### ISSUE THREAD

**Issue by askreet** [Codewars/codewars.com#1692] opened 2019-01-24 01:00 UTC
#### Describe the bug
The test framework for C++ kata is not appropriately comparing boolean results to their string form, or something.

#### To Reproduce

Attempt this kata: https://www.codewars.com/kata/path-finder-number-1-can-you-reach-the-exit/train/cpp
(Please let me know if it is OK to post my solution here.

#### Expected Behavior

Passing tests.

#### Screenshots

Test Results:
your_path_finder_function
should_pass_some_fixed_assertions_involving_simple_mazes
Expected: true
Actual: 0
should_work_for_edge_cases_involving_snake_labyrinths
Expected: false
Actual: 1
should_work_for_50_small_randomly_generated_mazes
Expected: true
Actual: 0
should_work_for_10_large_randomly_generated_mazes
Expected: false
Actual: 1

**Comment by FArekkusu** [comment] 2019-01-24 01:03
Those are not strings, but booleans. And your solution returns wrong values.

**Comment by kazk** [comment] 2019-01-24 01:06
It's a known issue from a test framework. See https://github.com/Codewars/codewars-runner-cli/issues/657

I think it's possible to tweak the output by adding stringifier, but that should be done by the author as we don't control that part.

**Comment by kazk** [comment] 2019-01-24 01:08
Just to be clear, this shouldn't affect the result. If your solution is correct, it should pass.

**Comment by kazk** [comment] 2019-01-24 01:40
Closing as a duplicate of https://github.com/Codewars/codewars-runner-cli/issues/657

> **Expected Behavior**
>
> Passing tests.

You should be able to pass if you return the correct `bool` value (`Actual: 0` means your solution returned `false` where `true` was expected).

**Closed by kazk** 2019-01-24 01:40 UTC

**Comment by askreet** [comment] 2019-01-24 02:02
Indeed you're right, my program was wrong. I assumed 0/1 was the inverse and the test framework was to blame. Thanks!
