### ISSUE TITLE
Want notification of invalid solution

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1443] opened 2018-05-23 23:23 UTC
I am seeing more and more Katas which are not well written first time which means method signatures and edge cases get modified after the 1st publish.... Really the "beta" phase of a Kata is for the community to find things you accidentally overlooked after careful consideration - not to do all the work for you just so you can press the Publish button faster.  :frowning: 

But that aside, my main gripe is that the early solutions to Kata then become invalidated without any notification to the solver. And thereby disqualifying them as candidates for future up-votes etc.

Can CW be enhanced to deliver me a notification if ever my solution becomes invalidated due to the Kata being republished? At least that will give me chance to re-submit...

**Comment by kazk** [comment] 2018-05-25 19:10
Closing as duplicate of #57

**Closed by kazk** 2018-05-25 19:10 UTC
Labels: area/notification, kind/feature-request
