### ISSUE TITLE
Rank breakdown "Overall" percentage

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#2245] opened 2020-09-28 06:42 UTC
Since some weeks I have taken back kata I already passed in at least one language and tried to do them in other languages  (for a refresh of my knowledge...). 
Once  successful the corresponding language percentage grows (a bit:-) but the "Overall" one has been stuck for weeks. 
Is there a problem?
Maybe it could be less discouraging if it showed more decimals.

**Comment by Blind4Basics** [comment] 2020-09-28 06:55
the overall % increase only once per kata solved. Hence if you already solved those katas in another language, that's the expected behavior.

**Comment by g964** [comment] 2020-09-28 09:08
> the overall % increases only once per kata solved.

I think I had already seen it increased when a kata is solved in another language than the first one (I can be wrong:-); that would be a normal behavior since if the percentage in one language changes the "overall" - which should be some kind of average of all the languages - should change too...

**Comment by hobovsky** [comment] 2020-09-28 09:17
No, it's not the case here. Overall progress can be increased only once per kata. You cannot advance your rank solving just one kata in all available languages. Overall is not "average for all languages", it does not work this way. I would be 1 dan long time ago if I resubmitted all purples I solved in all available languages :)

Solving kata in more than language will reward you with language progress for all languages you solved it with. But Overall rank will not change.

There used to be a bug (IIRC related issue is #1683) when kata was not correctly marked as completed and you could be rewarded for it twice, but it has not reappeared since long time ago.

**Comment by g964** [comment] 2020-09-28 09:47
OK and thanks! Do you know where it is possible to find explanations about these rather mysterious computations. Nevertheless I think it would be better to have e.g 2 decimals for these percentages... otherwise I feel like a tortoise.

**Comment by Greatlemer** [comment] 2020-09-28 12:03
It mentions it in the [wiki, here](https://github.com/Codewars/codewars.com/wiki/Honor-&-Ranks#leveling-your-rank).

> Every time time you complete a kata, the rank score for the corresponding language of completion will increase. However, if you complete the same kata in more than one language, only the FIRST completion will improve your Overall rank score.

**Comment by hobovsky** [comment] 2020-09-28 12:11
Some hints can be found in [this post](https://github.com/codewars/codewars.com/issues/1510#issuecomment-405440938). When querying for your user information with API call to [this endpoint](https://www.codewars.com/api/v1/users/g964) you can see your exact amount of overall score and how it increases with every solved kata. Table there also shows that you should see visible increase in your rank progress percentage for any kata of rank 5 kyu or better, so when you say that your percents are stuck, you either submit kata you have already solved, or solve only whites :) Solving a new 5 kyu should bump your percentage up by ~0.1%.

**Comment by g964** [comment] 2020-09-28 13:14
Many thanks to both!

**Closed** 2020-09-28 18:44 UTC
Labels: kind/question
