### ISSUE TITLE
Bug with honor(didn't get honor from completed Kata during month)

### ISSUE THREAD

**Issue by Sinelife** [codewars/codewars.com#1796] opened 2019-04-16 15:30 UTC
Nearly month passed from time when I completed 4kyu Kata "Large Factorials". I get 0 points for it and it didn't marked with tick. I tried few more times to send code in this Kata but result didn't change. I register other account  and completed this Kata from it to test if someone can get honor from it. On other account I get 32 points from "Large Factorials" Kata. So I can/t understand why I didn't get honor for "Large Factorials" on my first account.

Same problem I sometimes met with some other 6kyu Katas. Not very often but sometimes have. When I didn't get honor for Kata and Kata didn't mark with tick in list of Katas(all others which I completed marked with tick). And sending code few more times didn't changed anything.

I read that sometimes you didn't get honor immediately and you should wait. But nearly month passed and nothing changed. 
What should I do to get honor from that Katas? Or it is not real to get honor from them now?

**Comment by kazk** [comment] 2020-04-03 02:02
Closing because a lot have changed since this issue was reported.
Please open a new issue if the problem is not fixed.

I can trigger the recalculation of honor points if you include your username.

**Closed by kazk** 2020-04-03 02:02 UTC
Labels: issue/honor
