### ISSUE TITLE
Java System.out.print is affecting Kata tests. Bad solution can be submitted.

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#867] opened 2017-03-22 10:33 UTC
A user encountered some weird problem running one of my Kata.

* His solution fails my test cases
* He included some Java **System.out.print** statements and magigically the Solution "passes". Actually it still fails same as before but CW does not recognize it anymore as failing!

--

I have reproduced his problem and the System.out.print REALLY DO affect the test result in some strange way. 

Futhermore, if I change his System.out.print statements to **println** instead of **print** then the bad Kata solution fails again like it was ought to...

Something weird going on...

PSA screenshot showing the Output window when using System.out.print. 
* Notice the Passed number (1) is plain wrong. 
* Notice the error message shows on the screen but CW still thinks the solutions is a pass.

![cw-print-issue](https://cloud.githubusercontent.com/assets/22114719/24193525/a7bd5444-0f46-11e7-8621-8e17d22faf6e.PNG)

FYI - Here is link to his solution code:
https://www.codewars.com/kata/reviews/56f53a5b6dc4feeaa2000044/groups/58d1e2f7f4080cf53d0000bb

**Comment by kazk** [comment] 2017-03-22 17:52
@jhoffner maybe you figured this out already, but this is probably caused by this?

`System.out.print`:

```
user logged output<FAILED::>
```

`System.out.println`

```
user logged output
<FAILED::>
```

**Comment by blarosen95** [comment] 2017-03-22 18:24
Also the arrays first differed at element [1] according to the array displayed.

**Comment by kazk** [comment] 2017-03-22 18:33
Confirmed this reproducible in multiple languages. If the assertion failure doesn't write to `stderr`, and there's at least one `<PASSED::>` recognized, the test is considered passed.
I think this is essentially the same as Codewars/codewars-runner-cli#127 where the user's output interferes with test result.

---

JavaScript behaves differently when the tests are not inside `describe`.

```js
function add(a, b) {
  if (a != 1) return a + b;
  process.stdout.write(''+a);
  return a - b;
}
```

#### with describe

```javascript
describe("Solution", function() {
  it("should test for something", function() {
    Test.assertEquals(add(1, 1), 2);
    Test.assertEquals(add(2, 1), 3);
  });
});
```
![image](https://cloud.githubusercontent.com/assets/639336/24214416/a95e1486-0ef2-11e7-877e-80aee3379cc4.png)

#### without  describe
```js
Test.assertEquals(add(1, 1), 2);
Test.assertEquals(add(2, 1), 3);
```

![image](https://cloud.githubusercontent.com/assets/639336/24213862/1725bb92-0ef1-11e7-8668-6b9ea3fa9016.png)

**Comment by blarosen95** [comment] 2017-03-22 18:51
If I refactor my submission, will you all still have access to the bug related code?

**Comment by jhoffner** [comment] 2017-03-22 18:55
The best way to handle this across all languages would be to either go through all of them and ensure that `<PASSED::>` and `<FAILED::>` are on their own line (by prefixing with `\n`), or updating the output parser to allow those tokens to exist anywhere in the line. 

The later would be easier to make the change but I'm not certain of what edge cases that could create.

**Comment by kazk** [comment] 2017-03-22 19:27
@jhoffner
How are blank lines handled? I tried in Kumite and it seems to be completely ignored.

```js
console.log(`
a


b
`); // including the leading and the trailing
```
![image](https://cloud.githubusercontent.com/assets/639336/24216544/d09949f6-0ef9-11e7-8238-cf0d47ce1c1f.png)

I don't know if this is intentional, but prefixing with `\n` looks safe.

Changing the output parser might be easier in short term, but I think it should be avoided because of the uncertainty. I also like the idea of "each new STDOUT line is considered a new piece of data" :)

**Comment by jhoffner** [comment] 2017-03-22 19:38
@kazk I agree. 

This change (for Java only) will be fixed within the next Coderunner deployment. 

https://github.com/Codewars/codewars-runner-cli/pull/336

**Comment by kazk** [comment] 2017-03-22 19:46
I can start changing other languages if you'd like.
Updating `lib/runners/X.js` and `test/runners/X_spec.js` and opening a PR per language?

**Comment by kazk** [comment] 2017-03-22 20:25
@blarosen95 I think every distinct solution gets a permalink so no need to worry. Also the cause of this issue is found :)

**Comment by blarosen95** [comment] 2017-03-22 21:20
I figured you guys had the issue pinpointed 👍

**Comment by jhoffner** [comment] 2017-03-22 23:57
Changes are in preview, www is deploying now. 

@kazk sounds good. Thanks!

**Closed by jhoffner** 2017-03-22 23:57 UTC
Labels: bug, cli, high priority

**Comment by ma-za-kpe** [comment] 2019-05-09 20:32
![Screenshot from 2019-05-09 22-32-20](https://user-images.githubusercontent.com/28810111/57484824-56561680-72aa-11e9-8012-334d3cfe6799.png)
log info not being printed.

**Comment by kazk** [comment] 2019-05-09 20:49
@ma-za-kpe that's because you're only allocating `char[]` and not putting anything in it. So your code is basically doing `System.out.println((char)0);`. The output is shown like that because it's not a printable character.

Do `char[] n = str.toCharArray();` or copy the chars into `n`.
