### ISSUE TITLE
Can't translate a kata

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1414] opened 2018-04-25 09:13 UTC
kata : <https://www.codewars.com/kata/floating-point-approximation-i/translations>

When I push "TRANSLATE THIS KATA" I get (the too often...)
```
Kumite

Looks like there was a server error! (500)
We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `name' for nil:NilClass
```
which is very tiring :-(

As a remainder, same thing with:
<https://www.codewars.com/kata/phone-directory/translations>

**Comment by kazk** [comment] 2018-04-25 17:54
Duplicate of #1268.

> Note : the problem fixes itself if someone recreates the original version directly in the edit panel of the kata.

Can you try this workaround?

**Closed by kazk** 2018-04-25 17:54 UTC
Labels: duplicate

**Comment by g964** [comment] 2018-04-26 05:55
I will try, thanks.
