### ISSUE TITLE
5xx: Server Error

### ISSUE THREAD

**Issue by KStasi** [Codewars/codewars.com#1503] opened 2018-07-03 14:48 UTC
Face 5xx: Server Error for the whole day. 
Sometimes I can reach home page but can't open any kata. I had this error few times before but after reloading it usually was solved. 
Could you help me? 

![image](https://user-images.githubusercontent.com/31795791/42227056-46cd1c3c-7ee9-11e8-9ae8-9d8267aa51ef.png)

**Comment by hobovsky** [comment] 2018-07-03 14:51
And you did not read https://github.com/Codewars/codewars.com/issues/1502 by any chance, did you? :)

**Comment by kazk** [comment] 2018-07-03 19:07
Closing as duplicate of #1502

**Closed by kazk** 2018-07-03 19:08 UTC
