### ISSUE TITLE
ISE for get_sum

### ISSUE THREAD

**Issue by syedshazli** [Codewars/codewars.com#3234] opened 2024-05-30 13:54 UTC
Got the right solution and tried to submit in python and java. Got this issue in the past for other katas too. ![image](https://github.com/codewars/codewars.com/assets/146783525/8e404a6d-7d2c-4ff4-921f-7ff34921cd0a)

**Comment by hobovsky** [comment] 2024-05-30 13:56
Duplicate of #3209

**Closed as completed by hobovsky** 2024-05-30 13:56 UTC
Labels: duplicate
