### ISSUE TITLE
White Output Screen in Elixir Translation

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#949] opened 2017-05-05 00:18 UTC
Yesterday, I received an [Elixir Translation](https://www.codewars.com/kumite/590a48360936751bd6000089?sel=590a48360936751bd6000089) to one of my Kata and the test output for it was fine then.  However, since the translator selected the "Sample Test Cases" and executed that instead of the actual "Test Cases" when publishing it, I requested him/her to re-publish the translation again with the "Test Cases" tab on.  Surprisingly, the test output this time is completely white:

![2017-05-05 8 14 09](https://cloud.githubusercontent.com/assets/7777884/25729942/57ad6434-316b-11e7-9ce5-dbecafe06b55.png)

Refreshing the page multiple times has no effect.

**Comment by DonaldKellett** [comment] 2017-05-05 00:20
Just read the Issues page and realized that this Issue is probably inter-related to #948 and appears to be a rather recent bug.

**Comment by AwelEshetu** [comment] 2017-05-05 00:28
actually other test are not also running.
![flaw](https://cloud.githubusercontent.com/assets/4153683/25730121/e5d4ee40-3142-11e7-988a-61f7f68255a9.png)

**Comment by dpleshkov** [comment] 2017-05-05 01:52
![screen shot 2017-05-04 at 6 48 55 pm](https://cloud.githubusercontent.com/assets/22554516/25731371/9622179e-30fa-11e7-9d56-719998814ab2.png)

Tests are also not working with on Mac with macOS Sierra on Chrome. (Tests are for Python)

**Comment by tomb0y** [comment] 2017-05-05 07:26
I experienced this issue as well several times in the past few days.

I found out that if I go into a kata, click output, and run the tests right away (without doing anything else), it works after that just fine. 
But when I didn't do this (eg started to work on the kata, and tried to run the tests later), I encountered the white screen problem quite frequently.

**Comment by jhoffner** [comment] 2017-05-05 16:56
Duplicate of #928

**Closed by jhoffner** 2017-05-05 16:56 UTC
