### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1843] opened 2019-06-14 08:30 UTC
I always get:
```
Server Execution Error:
Internal Server Error
Request Error:
Request failed with status code 500
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.
```

**Comment by Christoph-Harms** [comment] 2019-06-14 08:50
Possible dupe: #1842

**Comment by ArcaNO93** [comment] 2019-06-14 09:02
got the same issue this morning
and no changes so far
is this internal CodeWars problem or what?

**Comment by jerson100** [comment] 2019-06-14 10:03
De igual manera me sale a mí, al parecer es problema de la plataforma.

**Comment by kazk** [comment] 2019-06-14 10:15
Closing as duplicate of #1842.

The outage was caused by Redis service going down. I'm deploying the changes right now so it should go back up soon. See https://status.codewars.com/

**Closed by kazk** 2019-06-14 10:15 UTC
