### ISSUE TITLE
Kata Info Scrolling Up When I Type in the Code Area

### ISSUE THREAD

**Issue by dpleshkov** [Codewars/codewars.com#834] opened 2017-02-20 02:03 UTC
When I am making a translation on a kata, and I scroll down on the left bar(the one that shows description, example tests, tests, user's solution, etc.) and then I type in the code area on the right, the left bar scrolls all the way up. This is really frustrating.

**Comment by kazk** [comment] 2017-05-28 22:17
Duplicate of #353?

**Comment by kazk** [comment] 2017-05-29 19:53
Duplicate of #353.

**Closed by kazk** 2017-05-29 19:53 UTC
Labels: area/editor, area/ux, bug, duplicate
