### ISSUE TITLE
Can't comment or ask questions on Kata solutions

### ISSUE THREAD

**Issue by luluUK** [codewars/codewars.com#2493] opened 2021-09-28 21:42 UTC
Hello, hoping somebody can help me. I can't post a comment or ask a question on Kata solutions. My account has been verified. There are no errors in my console. I've tried on Safari, Chrome and Firefox ... not working on any of those.

**Comment by kazk** [comment] 2021-09-28 22:44
Which solution? I'm guessing this is a duplicate of #2263 (happens for old kata with lots of solutions).

**Comment by luluUK** [comment] 2021-09-29 09:04
Hello Kazk, thank you for your quick response. 

I tried to comment on several of the solutions for the Exes and Ohs challenge https://www.codewars.com/kata/55908aad6620c066bc00002a/solutions/javascript. 
I've read through the page #2263 ...The technical detail was a bit over my head but I think I got the gist. The old way of doing this set some kind of limit on user input for comments and votes etc but to solve this issue is labour intensive and will take some time. I accept that... but I must say I found this frustrating and time consuming trying to figure out what was going on... when you're new, you're already trying to take a lot in familiarising yourself with the site so this is quite annoying.
 It would be great if there was some explicit way of letting the user know that they can't post because it's an old katas rather than give the impression all is fine allowing you to create a comment but stopping short of actually posting on the click. Some kind of indication better than none to avoid frustration so early on. I really like the site and felt quite excited  by what gains I could make in learning but that positivity was soon replaced with frustration spending so long trying to figure out why I couldn't post a comment or question.

**Comment by aninaA** [comment] 2021-11-07 19:27
Hi Lulu, I'm having the same issue on several katas. Can't vote on solutions either and didn't find out why until I found your explanation of #2263. I agree with you that this should be either indicated on the page via a disclaimer and/or the comment and voting feature should be removed for old katas.

**Comment by kazk** [comment] 2022-01-07 06:43
See https://github.com/codewars/codewars.com/issues/2263#issuecomment-1007176572

**Closed by kazk** 2022-01-07 06:43 UTC
