### ISSUE TITLE
Kata translation got approved twice

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#1741] opened 2019-02-25 01:14 UTC
I've made a JS translation of [this kata](https://www.codewars.com/kata/encrypt-this).

**On approval:**

1. I pressed the Approval button twice in a row but nothing happened.
2. I refreshed the page and the translation got approved

**Result:**

- The kata got approved twice and I got the honor points twice
- The translation is displayed twice (see the pictures below)

<img width="887" alt="image" src="https://user-images.githubusercontent.com/11985251/53308580-c9064700-38a2-11e9-83c1-131f9e7426de.png">
<img width="196" alt="image" src="https://user-images.githubusercontent.com/11985251/53308593-e9360600-38a2-11e9-8cce-81e3b9f910e0.png">

**Comment by kazk** [comment] 2019-02-25 01:42
Closing as duplicate of #1189.

**Closed by kazk** 2019-02-25 01:42 UTC
Labels: duplicate
