### ISSUE TITLE
You can add non passing translations

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#2051] opened 2020-03-02 08:48 UTC
#### Describe the bug
When you create a new Kata, not all languages are validated, wich is standard behaviour, however, all the provided translations are saved.

Take for example https://www.codewars.com/kata/5e5cc5aa6760d70036ea6d22/javascript

#### To Reproduce

1. Create a new Kata
2. Add code in one language
3. Switch to another language
4. Make it pass in the second language and it will save the first language without even validating it to pass

#### Expected Behavior

You should be able to save only the current language. And the solution for the second language should not be listed as passing solution for the first language.

#### Screenshots

![image](https://user-images.githubusercontent.com/1063901/75659738-1775c080-5c30-11ea-8e39-fb20b63130e8.png)

#### Contexts

Please complete the following information:

- OS: Windows 10
- Browser: Firefox
- Browser Version: 73.0.1 (64-bit)

**Comment by kazk** [comment] 2020-03-02 18:29
I think this is a duplicate of #764.

**Closed by kazk** 2020-03-02 18:29 UTC
Labels: duplicate
