### ISSUE TITLE
Occasional missing kata honor scores after completion

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1020] opened 2017-06-30 09:07 UTC
I've observed several people encountering this problem since this month.

When they complete a kata (usually blue kata), after completion their honor is shown to only increase by 2 points, which should've been 32 points. Site Events is showing the correct total, but the total honor shown on the top-right and in the profile page is missing the kata difficulty score from the new kata (kata completion score is added properly though, hence the 2 honor).

The missing honor seem to come back after completing another kata with the same color tier.

**Comment by nomennescio** [comment] 2017-08-19 07:54
I have encountered the same problem already for several months.
Occasionally (but yesterday it happened twice) I only get 2 points for solving Katas which should have given much more points. After a day, that still is not corrected by recalculations, so I assume it's a real bug.

**Comment by jhoffner** [comment] 2018-02-28 02:12
Closing since this is a duplicate of https://github.com/Codewars/codewars.com/issues/943

**Closed by jhoffner** 2018-02-28 02:12 UTC
