### ISSUE TITLE
Hard Sudoku Solver  --  I can't access the discussion

### ISSUE THREAD

**Issue by YOEL311** [codewars/codewars.com#2086] opened 2020-04-05 15:19 UTC
Hi
I'm in this kata https://www.codewars.com/kata/5588bd9f28dbb06f43000085/train/python
It looks like there's a bug in the tests
But I can't access the discussion page and report an error
What should I do

this is table
[[4, 0, 5, 0, 1, 0, 7, 0, 8], [0, 0, 7, 0, 0, 5, 0, 0, 0], [0, 3, 0, 7, 0, 0, 0, 5, 0], [0, 0, 3, 0, 0, 0, 0, 0, 5], [0, 4, 0, 2, 0, 8, 0, 6, 0], [5, 0, 0, 0, 0, 0, 1, 0, 0], [0, 7, 0, 0, 2, 3, 0, 1, 0], [0, 0, 0, 4, 0, 0, 2, 0, 0], [9, 0, 6, 0, 7, 0, 4, 0, 3]]

this my result
[[4, 9, 5, 6, 1, 2, 7, 3, 8], [6, 1, 7, 8, 3, 5, 9, 4, 2], [2, 3, 8, 7, 9, 4, 6, 5, 1], [7, 6, 3, 1, 4, 9, 8, 2, 5], [1, 4, 9, 2, 5, 8, 3, 6, 7], [5, 8, 2, 3, 6, 7, 1, 9, 4], [8, 7, 4, 9, 2, 3, 5, 1, 6], [3, 5, 1, 4, 8, 6, 2, 7, 9], [9, 2, 6, 5, 7, 1, 4, 8, 3]]

why I get 
 Invalid grid should raise an error.
![image](https://user-images.githubusercontent.com/39925212/78502439-dfe7c000-7769-11ea-973d-6d2318730383.png)

**Comment by Blind4Basics** [comment] 2020-04-05 15:22
I'll bet you didn't check the solution is unique? because that makes the grid invalid too, according to the requirements.

**Comment by DonaldKellett** [comment] 2020-04-05 15:47
> I can't access the discussion page

Your email account is probably unconfirmed. Go to "Account Settings" and find the button that says "Resend Confirmation Email" (or something to that effect).

**Comment by YOEL311** [comment] 2020-04-05 16:46
> אני בטוח שלא בדקת שהפתרון הוא ייחודי? מכיוון שזה הופך את הרשת גם לא תקף, בהתאם לדרישות.

I chacked

**Comment by Blind4Basics** [comment] 2020-04-05 18:21
you mean "checked"?

**Comment by Blind4Basics** [comment] 2020-04-05 18:27
confirmed: there are several solutions for this input grid. Your code is incorrect/


{(
(4, 9, 5, 6, 1, 2, 7, 3, 8),
(6, 1, 7, 8, 3, 5, 9, 4, 2),
(2, 3, 8, 7, 4, 9, 6, 5, 1), 
(7, 6, 3, 1, 9, 4, 8, 2, 5), <<<
(1, 4, 9, 2, 5, 8, 3, 6, 7), 
(5, 8, 2, 3, 6, 7, 1, 9, 4), 
(8, 7, 4, 9, 2, 3, 5, 1, 6), 
(3, 5, 1, 4, 8, 6, 2, 7, 9), 
(9, 2, 6, 5, 7, 1, 4, 8, 3)),

(
(4, 9, 5, 6, 1, 2, 7, 3, 8), 
(6, 1, 7, 8, 3, 5, 9, 4, 2), 
(2, 3, 8, 7, 9, 4, 6, 5, 1), 
(7, 6, 3, 1, 4, 9, 8, 2, 5), <<<
(1, 4, 9, 2, 5, 8, 3, 6, 7), 
(5, 8, 2, 3, 6, 7, 1, 9, 4), 
(8, 7, 4, 9, 2, 3, 5, 1, 6), 
(3, 5, 1, 4, 8, 6, 2, 7, 9), 
(9, 2, 6, 5, 7, 1, 4, 8, 3))}

**Comment by YOEL311** [comment] 2020-04-05 18:34
But why don't I have chat access

In this kata

![image](https://user-images.githubusercontent.com/39925212/78506804-e46da200-7784-11ea-827d-c8ad42e65e43.png)

**In another kata**


![image](https://user-images.githubusercontent.com/39925212/78506771-a8d2d800-7784-11ea-80cf-a78d45c2dfcb.png)

**Comment by Blind4Basics** [comment] 2020-04-05 20:42
that, on the other hand, is weird, yes...

**Comment by YOEL311** [comment] 2020-04-05 20:48
Yes very weird
I tried to disconnect and connect
Nothing helped

**Comment by kazk** [comment] 2020-04-06 02:14
For some reason, the discuss button in trainer is only shown if you've already completed it or have enough rank to unlock the solution and forfeit. It's been like this for at least 3 years. I'll close this when the fix is deployed.

@YOEL311 For now, you can find the link to the discussion page from the [kata page](https://www.codewars.com/kata/5588bd9f28dbb06f43000085). Or just append `/discuss` to the kata's URL. https://www.codewars.com/kata/5588bd9f28dbb06f43000085/discuss

**Comment by kazk** [comment] 2020-04-06 03:10
Should be fixed now.

**Closed by kazk** 2020-04-06 03:10 UTC
Labels: kind/bug
