### ISSUE TITLE
Please correct the output display bug

### ISSUE THREAD

**Issue by myjinxin2015** [Codewars/codewars.com#499] opened 2016-08-06 13:15 UTC
![!!](https://files.gitter.im/Codewars/codewars.com/gI8s/blob)

Please look at the green output text, the second line always shorter than other lines, in fact, they have same length.

This bug always appear at the output of the first testcase.

[You can test this kata](http://www.codewars.com/kata/t-dot-t-t-dot-21-handle-the-text-alignment/train/javascript)

**Comment by daveee** [comment] 2016-08-27 14:28
yes this is annoying!

looks like the first occurence of two spaces together in a string is being replaced by a single space:

![image](https://cloud.githubusercontent.com/assets/1071096/18028007/dd1b2a82-6c6a-11e6-9670-2e9402f2ae32.png)

**Comment by kazk** [comment] 2017-07-07 17:40
This was caused by a bug sanitizing output, replacing the first occurrence of two consecutive spaces with a space.
Closing this because this was fixed in https://github.com/Codewars/codewars-runner-cli/pull/438.
![image](https://user-images.githubusercontent.com/639336/27969581-3e88b6c2-6300-11e7-935c-4092e965a139.png)

**Closed by kazk** 2017-07-07 17:40 UTC
Labels: area/output
