### ISSUE TITLE
Some profiles show a Twitter icon even though a Twitter account is not connected

### ISSUE THREAD

**Issue by connorkendrick** [Codewars/codewars.com#964] opened 2017-05-13 23:51 UTC
Some profiles on the website show a Twitter icon even if they have not linked their Twitter account to their profile. The icon leads to Twitter's login page if no account is connected. This is a little confusing if you are expecting it to lead to the user's personal Twitter page.

This issue does not seem to occur for the GitHub icon.

[Here's a link to my account as an example of the problem](https://www.codewars.com/users/connorkendrick)

[Some profiles do not have this issue](https://www.codewars.com/users/iRayan7)

**Comment by PilgrimShadow** [comment] 2017-10-05 07:09
My account is one of these. After unlinking my twitter account, the icon remained.

**Comment by e-mihaylin** [comment] 2018-11-06 10:48
same issue for me:
https://www.codewars.com/users/e.mihaylin

**Comment by kazk** [comment] 2018-11-06 19:41
Found the cause and fixed it. I'll close this when it's deployed.

**Comment by kazk** [comment] 2018-11-07 00:49
Fixed. Note that it might take some time for the cache to invalidate.

**Closed by kazk** 2018-11-07 00:49 UTC
Labels: area/account, kind/bug
