### ISSUE TITLE
Allow for deletion of Draft Translations/Forks

### ISSUE THREAD

**Issue by DanL12186** [Codewars/codewars.com#1561] opened 2018-09-03 14:38 UTC
Forks end up in the same place as translation drafts, which personally makes me avoid forking except when totally necessary since I can't delete them.

I've also got a few translations I started and then didn't submit for one reason or another (other translations being accepted is one), and it can make it a chore to find the ones you're actually working on and the ones that are just leftovers littering the space.

Could we have an option to delete these?

**Comment by anter69** [comment] 2018-11-07 13:55
I can totally confirm this: I have multiple translation drafts under [my draft translations](https://www.codewars.com/users/anter69/draft_translations) page, which were created by error or by some CW hiccup, and are now stuck there forever...

![image](https://user-images.githubusercontent.com/12795864/48135295-d02a2a80-e29c-11e8-853e-4a5f41c4f032.png)

**Comment by kazk** [comment] 2019-01-05 07:40
Closing as duplicate of #81.

**Closed by kazk** 2019-01-05 07:40 UTC
Labels: kind/feature-request
