### ISSUE TITLE
Kata page crushes

### ISSUE THREAD

**Issue by sandbox992** [Codewars/codewars.com#1637] opened 2018-11-24 21:08 UTC
#### Describe the bug
https://www.codewars.com/kata
https://www.codewars.com/kata/latest/
https://www.codewars.com/kata/latest/my-languages
crushes when i want reach them

#### To Reproduce

1. Just go to that links
2. 1 sec seems page loads
3. Crush

#### Expected Behavior

Loaded page with list of my katas

#### Contexts

Please complete the following information:

- Codewars username (if account related): sandbox992
- OS: Win7 x64
- Browser: Chrome, Mozilla (both crushed pages)
- Browser Version: [Chrome 70.0.3538.102, Mozilla 63.0.3]

#### P.S.
Mozilla sreenshot - just what i can catch before crush - I mean reload page - take screenshot - page crushed; No errors in console; All extensions turned off; Incognito page already tried
![screenshot_5](https://user-images.githubusercontent.com/38735939/48972951-c98e0800-f03d-11e8-95e9-8a59098c2d8a.png)
![screenshot_6](https://user-images.githubusercontent.com/38735939/48972952-c98e0800-f03d-11e8-94ce-035737aa8650.png)

**Comment by kazk** [comment] 2018-11-24 22:02
Closing as duplicate of #1157. Please look there for more information. Some users have found that it's related to icons and posted workarounds.

**Closed by kazk** 2018-11-24 22:02 UTC
Labels: duplicate
