### ISSUE TITLE
Non-clickable links in a comment summary

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#1625] opened 2018-11-13 08:55 UTC
#### Describe the bug
Some links are rendered without a **href** attribute, what makes them unclickable. Also note the oddly placed quotation marks around the link, but this might be "as intended", although looking a bit off.

#### To Reproduce
Go to Profile/Discourse, and search for comment headers with unclickable links. One kind of such links is in comments titled as `SomeUser commented on ""Some Kata Title" Java Translation"`.

#### Expected Behavior
Link is clickable and redirects to the discussed item.

#### Screenshots

![image](https://user-images.githubusercontent.com/23709795/48401495-a011da00-e729-11e8-8516-536b11351e71.png)

![image](https://user-images.githubusercontent.com/23709795/48401565-c8013d80-e729-11e8-80b1-f0d0f3f61972.png)

**Comment by kazk** [comment] 2018-11-13 09:01
This is probably a duplicate of #68.
I don't know if this is intentional or not at the moment. If it's intentional and it's meant to prevent random users from accessing, then it shouldn't be shown on the dashboard to begin with. But I never know because Codewars has lots of irrational stuff from over the years.

**Comment by hobovsky** [comment] 2018-11-13 10:52
Ah what drove off is a fact that it did not happen on a dashboard but on a "Discourse" view of my profile, and it's a link to my own translation - where I think is no reason to limit this possibility.

But as you say, the reason and logic behind such behavior is probably the same as in case of #68

**Comment by FArekkusu** [comment] 2018-11-13 14:06
I also encountered it yesterday and today, but it was even more strange - `Unnamed commented on "" kata`.

**Comment by error256** [comment] 2018-11-13 15:04
`Unnamed commented on "" kata` seems to be different, but I assume that it's just a weird consequence of timing out. It was supposed to be [here](https://www.codewars.com/kata/bocce/discuss), but it appeared on dashbord and in my profile, but not at the discuss page.

**Closed** 2022-05-26 07:20 UTC
Labels: kind/bug, area/comments
