### ISSUE TITLE
Please remove the broken "smart edit" feature in Code Editor

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#2378] opened 2021-05-11 03:16 UTC
It's broken/annoying in many ways and it's very annoyed to code against it:

1. When typing quotes or parentheses, the code editor might turn it into a full pair of them. The problem is that it sometimes does this and sometimes does not, and I find it often does stupid things like:
    ```python
    ''.join''.join(c) for c in r for r in image)
    ```
    Now when I type `(` between `join` and `''` it fills in `()` instead? Is it not aware that the parenthesis is not complete and so `(` should be matching the dangling `)`?

2. Similarly, the code editor likes to eat the closing quotes/parentheses when the context clearly lacks one to begin with. if I have
    ```python
    add(a,b)
    ```
    And now I want to change it to `add(max(a,c),min(b,c))`, and I typed it to
    ```python
    add(max(a,c),min(b,c)
    ```
    With the cursor just before the last `c` (because I'm typing inside the `add(a,b)`. Now I only need to close the parenthesis. However, when I press `)` it eats my `)` and I have type it again to make the `)` appear. Now imagine if there are multiple nested `)` at the end.

3. When typing quotes or parenthesis while something's selected, they are wrapped around the text instead. This leads to peculiar situations like this: Let's say I have
    ```python
    f'minute{'' if n==1 else 's'}'
    ```
    Oops, now I should probably replace the outer quotes to double quotes. I can either
    - Move cursor to after the `'`, press backspace, then type `"`; but then `""` will appear instead. And no, backspace doesn't work here since it removes *both* double quotes. You need to either delete the right one, or resort to more selecting/moving cursor around
    - Select `'` and type `"`; but then it becomes `"'"` instead of just `"`, so now you realized you fxxked up and immediately want to backspace the extra characters out. But since `'` is still selected, backspace or delete gives you `""` instead, which is the above situation.
    - Copy a `"` with Ctrl+C, Select `'`, Ctrl+V. This works but it is extremely inconvenient.
    - Do some crazy stuff like selecting the whole text, Ctrl+X, backspace once so only `f` is left, then type `"` and Ctrl+V? I just want to change the surrounding chars, why do I have to fiddle with the entire block?

4. Python: Making a new line through `pass` automatically assumes you're ending the block, which is not useful at all. Let's say I have
    ```python
    def f(a, b):
        pass
    def a(a, b):
        pass
    ```
    When I want to finish the function `f` and remove the `pass` there, there are a few possible things I might do:
    - Move cursor to `:`, newline, and except both a indent to appear (hint: it doesn't in some editors, e.g Notepad++), and then try to remove `pass` via some gymnastics? Switching to mouse from a keyboard position or having to quadraple-tap an arrow button is very time-consuming.
    - Move cursor to the end of `pass`, newline, expect a indent to appear, then shift + up, backspace, and start coding! Which doesn't work because the indent is gone after creating a new line. Now I have to press an additional tab.
    - Others? But it's also very time consuming.

5. Also Python: The code editor *really* hates inline `if`/`elif` blocks in Python. Let's say I'm typing this code snippet:
    ```python
    if n%p==0: n /= p
    ```
    And I want to add another `elif`/`else` condition. Because of 3, When adding a newline after `n /= p` an extra indent will *always* be created unless it was `pass`. But then I already have a single-line if condition, why would I ever want an extra indent? I've never seen anyone who mixes inline if condition with multi-line if condition (since it'd be atrocious code style to do so). When I newline in this case, I want to type *outside* the if block, not inside it.
    Seriously, what's the issue of using the old, tried-and-true rule of "just follow the indent of the line being newline-ed out of"? If I already have this:
    ```python
    if n%p==0:
        n /= p
    ```
    Then naturally I might want to still code inside the if block when newlining after `n /= p`. And it has always worked.

6. Probably many more that I can't recall.

---

My general experience with the smart editor features in *this particular code editor* is that they never worked well, and I have to constantly fight against them when typing code.

Also note than all of the above issue doesn't happen in [Monaco](https://microsoft.github.io/monaco-editor/), so I see that I'm not indeed insane and just imagining things.

**Comment by XRFXLP** [comment] 2021-05-11 03:39
Duplicate of https://github.com/codewars/codewars.com/issues/2198 ?

**Comment by kazk** [comment] 2021-05-11 04:44
Yeah, this is a duplicate of #2198. I completely understand the annoyance.

I can add a quick hack without any UI for now. Then you guys can run

```javascript
localStorage.setItem('editorOptions', JSON.stringify({
  autoCloseBrackets: false,
}));
```
in console, and refresh the page.

**Comment by Voileexperiments** [comment] 2021-05-11 09:10
> I can add a quick hack without any UI for now. Then you guys can run
> 
> ```js
> localStorage.setItem('editorOptions', JSON.stringify({
>   autoCloseBrackets: false,
> }));
> ```
> 
> once in console, and refresh the page.

Would this work on all the existing code editor options?

**Comment by kazk** [comment] 2021-05-11 18:44
Deployed.

You can run
```javascript
localStorage.setItem('editorOptions', JSON.stringify({
  autoCloseBrackets: false,
  smartIndent: false
}));
```
in the console once and refresh the page to use that option from there. I'll close this because we already have #2198.

I confirmed this to work, but let me know if it doesn't or if you find anything weird.

---

By the way, thanks for the detailed examples, I honestly didn't realize it was this annoying. Someone asked for these in #2189, and I enabled them because I thought it wasn't too bad after testing. But I admit I didn't test as much using the default keybinding. Here's how I'd edit those with Vim keybinding.

1. Not really annoyed. vim: `fna(` -> `Ctrl-[` -> `lx`. (find next `n`, append `(`, exit insert mode, then remove the right)
2. Mildly annoyed. But I tend to break them up into multiple lines, adjust them, and then use `J` to join lines instead.
    ```python
    add(
        a,
        b
    )
    add(
        max(a),
        min(b)
    )
    add(
        max(a,c),
        min(b,c)
    )
    add(max(a,c),min(b,c))
    ``` 
3. Not annoyed. vim: `f'r"$.` (find next `'`, replace with `"`, jump to the end of line (`$`), then repeat the last change). I had no idea typing `"` when `'` is selected surrounds it! But backspace and `"` works for me without having Vim enabled, so I'm not sure why it doesn't for you.
4. Not annoyed. vim: `fpDa` (find next `p`, delete from there, then start appending). I didn't know newline after `pass` outdents. I guess it makes sense _if_ you had just typed `pass`.
5. Not annoyed because I usually write normal blocks, then use `J` (join lines) when it makes sense.

**Closed as completed** 2021-05-11 18:45 UTC
Labels: duplicate, area/editor
