### ISSUE TITLE
User sessions sometimes get lost while using the site

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#1] opened 2015-03-27 16:58 UTC
While using the site, I will sometimes get logged out. Any attempt to do something fails and I have to reload the page, which then asks me to log in again.

**Comment by e-mihaylin** [comment] 2018-10-30 08:36
Moved here from https://github.com/Codewars/codewars.com/issues/1574

Bunch of related problems:

Every day (I quess every 24 hours) I am logged off the platform.
For example: I can log in at 10am, be online due to 18pm, and next day I'll be logged of at 10am.
May be a feature, not a bug - but better to reroll auth to avoid such problems.

Then I press log in button, do the auth (via github).
And I have other codewars tabs in browser.
If I refresh any (not authed, expired) -> I'll have all of them exprired.
Bugs not all the time, but very often.

If I was working on kata, I can be logged off after succesfull submit.
If I log in and then use browser back button (to kata solutions) -> I am logged off.

When I finally get to the kata solutions/my solution (after that auth mess)
I have 'There are no solutions yet for this kata' instead of my solution (which was submitted correctly)
But in my profile/completed_solutions everything is ok (and the honor comes with some dely)

Sometimes it just logs me off on code submit during daily session.
(Logged in at 11, logged off on code submit at 16 with successfull submit 5 minutes before)

**Comment by kazk** [comment] 2019-03-20 18:31
Closing as fixed.

**Closed by kazk** 2019-03-20 18:31 UTC
Labels: high priority, issue/session, kind/bug
