### ISSUE TITLE
While editing kumite, kata details constantly scroll to top

### ISSUE THREAD

**Issue by bdw429s** [Codewars/codewars.com#2019] opened 2020-01-30 18:45 UTC
#### Describe the bug
If I'm editing a kumite (in this case a language translation) I often times scroll down in the kata information in the far left tab for reference,  But the instant I type into any of the code editors on the right, the left pane scrolls all the way to the top.  This is very annoying and I find myself scrolling back down over and over again.  

#### To Reproduce

1. Edit a kumite translation
2. scroll down halfway in the "kata" information tab
3. Click into the "solution" editor and type a character
4. The left pane will jump up to the top

#### Expected Behavior

I expect the kata tab to stay where I left it last.

#### Screenshots

![image](https://user-images.githubusercontent.com/584009/73479768-372e7600-435e-11ea-9566-3535a686bea6.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): bdw429s
- OS: Windows 7
- Browser: Chrome 
- Browser Version: 79.0.3945.130 (Official Build) (64-bit)

**Comment by kazk** [comment] 2020-01-30 18:49
Thanks for all the details. I'm going to close this because it's a duplicate of #353, but will reference this one when I get to it.

**Closed by kazk** 2020-01-30 18:49 UTC
Labels: duplicate

**Comment by bdw429s** [comment] 2020-01-30 18:57
@kazk Sorry for the duplicate.  I did actually search the issue tracker first before entering but must not have been using the correct keywords as I didn't come across #353
