### ISSUE TITLE
Request failed with status code 500 - timeout when testing and submit solutions.

### ISSUE THREAD

**Issue by qblacksheep** [Codewars/codewars.com#1231] opened 2017-11-23 19:04 UTC
Hello, whole day i have problem with test or submit solution. Every time when i try it i get a timeout error.
Request failed with status code 500. Everyone got this problem or only me? I tried from diffrent PC's with other net connections and still don't working.

**Comment by art-ewantes** [comment] 2017-11-23 19:05
++
Still have the same problem.

**Comment by moealemam** [comment] 2017-11-23 19:19
++
same. trying to show a friend who just started programming :(

**Comment by thecoolster** [comment] 2017-11-23 19:21
main thread is at #1230 check that out as well guys... this is so wierd.. is everyone off for thanksgiving ..... no response at all????

**Comment by lukasowy** [comment] 2017-11-23 19:29
i have the same problem

**Comment by kazk** [comment] 2017-11-23 20:36
Closing as duplicate of #1230, I've reached out to @jhoffner and we're looking into it. Sorry about the delay, everyone is off due to thanksgiving.

**Closed by kazk** 2017-11-23 20:36 UTC
