### ISSUE TITLE
See the performance of solutions

### ISSUE THREAD

**Issue by Tortar** [codewars/codewars.com#2861] opened 2022-11-11 11:44 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have a way to see which are the most performant solutions to a kata (this is interesting for example in relation to katas created with the intent of testing performance)

**Describe the solution you'd like**

I thought about a solution divided in two steps:

- Print above/below the kata solution the ms it took to pass the tests subtracting the setup ms.
- Create a button to let the users order by performance.

**Comment by Blind4Basics** [comment] 2022-11-11 12:13
Duplicate of #2036 #1754 #1133 #959 . See related issues for explanation why it's not as good idea as it might seem.

**Closed by Blind4Basics** 2022-11-11 12:13 UTC

**Comment by Tortar** [comment] 2022-11-11 17:08
Oh, searched badly and didn't found all those issues, it is actually a popular topic as one would expect  :-)
