### ISSUE TITLE
-4 collections

### ISSUE THREAD

**Issue by VityaSchel** [codewars/codewars.com#2340] opened 2021-03-11 11:06 UTC
**Describe the bug**
-4 collections on [this kata](https://www.codewars.com/kata/514a677421607afc99000002)

**To Reproduce**
Go to oldest 7 kyu kata
https://www.codewars.com/kata/514a677421607afc99000002

**Expected behavior**
collections must be 0 or more

**Screenshots**
![image](https://user-images.githubusercontent.com/59040542/110777844-061bb700-827b-11eb-8fd5-897c05c11647.png)

**Browser**
Chrome 89 but it doesn't matter anyway I suppose

- OS: macOS
- Browser chrome
- Version 89

**Additional context**
What else can I say??

**Comment by hobovsky** [comment] 2021-03-11 11:13
Duplicate of #2185

**Closed by hobovsky** 2021-03-11 11:13 UTC
