### ISSUE TITLE
Shell tests: passing an array

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1125] opened 2017-09-08 14:20 UTC
```
def dotest(k, x, exp)
    test1 = (run_shell args: [k, x])
    expect(test1).to eq(exp)
end

dotest(4, [10175, 10185, 10180, 10197], 3)
```
Only the 1st element of the array is passed to bash.

**Comment by kazk** [comment] 2017-09-08 17:19
I don't think Shell can accept array like that.

Your setup sets the arguments `["4", "[10175, 10185, 10180, 10197]"]`:
```shell
echo $@
# 4 [10175, 10185, 10180, 10197]
echo $#
# 2
```

Try
```ruby
dotest("4", "10175 10185 10180 10197", "3")
# or
dotest("4", [10175, 10185, 10180, 10197].join(' '), "3")
```
Then
```shell
echo $@
# 4 10175 10185 10180 10197
# this is hard to see, but $1="4" and $2="10175 10185 10180 10197"
echo $#
# 2
```

The solution can use them like this:
```shell
n=$1
xs=($2)
echo "$n"
# 4
echo "${xs[@]}"
# 10175 10185 10180 10197
```

**Comment by g964** [comment] 2017-09-08 19:23
@kazk: I am very sorry to bother you! This is what I have as a try at CW:
```
fake() {
    echo "All args : $@"
    d=$1
    echo "First arg : $d"
    echo "2nd arg : /$2/"
    xs=( $2 )
    echo "Array : ${xs[@]}"
    arraylength=${#xs[@]}
    echo "Array length : $arraylength"
    for (( i=0; i < ${arraylength}; i++ ));
    do
      echo "$i : ${xs[$i]}"
    done
    echo "elt of endex 1 : ${xs[1]}"
}
fake $1 $2
###########
def dotest(k, x, exp)
    test1 = (run_shell args: [k, x])
    expect(test1).to eq(exp)
end
describe("consec_kprimes") do
    it("Basic tests") do
        dotest("4", "10175 10185 10180 10197", "3")
    end
end
````
When I run the test I get:
```
Shell Output
All args : 4 10175 10185 10180 10197
First arg : 4
2nd arg : /10175/
Array : 10175
Array length : 1
0 : 10175
elt of endex 1 :
```
"All args" seems correct but "2nd arg" is only the first element of the string passed by Ruby. 
The second element of the string will be "$3" for Bash and so on. I must make a mistake somewhere but I don't see it:-(

**Comment by jhoffner** [comment] 2017-09-08 19:38
Closing because this seems to be working as designed. Bash input can only accept strings, when calling `run_shell args: [...]` is just going to result in this happening `args.map(&:to_s)` when sending the input.

**Closed by jhoffner** 2017-09-08 19:38 UTC

**Comment by kazk** [comment] 2017-09-08 20:24
@g964 that's because you're giving `fake` 5 numbers:
```shell
# fake $1 $2 becomes
fake 4 10175 10185 10180 10197
```

Try `echo $#` inside `fake`, it should output `5`.

Do `fake $1 "$2"` (note the `"` around `$2`) instead and you should see:
```
All args : 4 10175 10185 10180 10197
First arg : 4
2nd arg : /10175 10185 10180 10197/
Array : 10175 10185 10180 10197
Array length : 4
0 : 10175
1 : 10185
2 : 10180
3 : 10197
elt of endex 1 : 10185
```

**Comment by g964** [comment] 2017-09-09 07:35
@kazk : thanks, now it works!
