### ISSUE TITLE
Refreshing of "Most Consecutive Days" doesnt work

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#974] opened 2017-05-21 17:29 UTC
Refreshing of "Most Consecutive Days" doesnt work. 
It stays at 18.05.
I did every day at least one kata.

I suppose one service has crashed!?

**Comment by kazk** [comment] 2017-05-21 17:34
Duplicate of #945?

**Comment by SteffenVogel79** [comment] 2017-05-21 18:06
Maybe really the same problem.

**Closed** 2017-05-23 11:25 UTC
