### ISSUE TITLE
JS - String.prototype.repeat doesn't work

### ISSUE THREAD

**Issue by shershen08** [Codewars/codewars.com#216] opened 2015-12-17 19:19 UTC
There's a note - "All code is ran through BabelJS (ES 2015 supported)" but according to https://kangax.github.io/compat-table/es6/ - String.prototype methods are supported by Babel.

**Comment by pborshchahivskyi** [comment] 2016-03-01 14:26
+1

**Comment by kazk** [comment] 2017-03-28 01:05
Duplicate of #195.

**Closed by kazk** 2017-03-28 01:05 UTC
