### ISSUE TITLE
Adapt time limits depending on language

### ISSUE THREAD

**Issue by louischatriot** [Codewars/codewars.com#1448] opened 2018-05-31 19:26 UTC
First, thanks for making Codewars, it's great.

I'm on a kata (insane coloured triangles) which I suspect cannot be done with Python simply due to the language being slow (i.e. my solution is linear which the best class for this problem but finishes in ~20s while the limit seems to be 10s). I have not tried Java yet but I suspect I will easily clear it that way, so it may be a good idea to ask kata submitters to time the correct solution on all languages to adapt accordingly?

**Comment by kazk** [comment] 2018-05-31 19:30
> I suspect cannot be done with Python simply due to the language being slow

If the language is available then that means there's at least one solution (the author's) that can complete in that time limit.

**Comment by kazk** [comment] 2018-05-31 19:34
https://www.codewars.com/kata/insane-coloured-triangles/python has 58 Python solutions at the moment. I tried few and some of them finishes in about 4s.

**Comment by kazk** [comment] 2018-05-31 19:38
I'm going to close this as duplicate of https://github.com/Codewars/codewars-runner-cli/issues/480 for the feature request to allow kata authors to set the maximum allowed time.

**Closed by kazk** 2018-05-31 19:38 UTC

**Comment by louischatriot** [comment] 2018-05-31 21:00
Thanks for the answer @kazk - so if that's the case I'll make it work :)

**Comment by olance** [comment] 2018-06-04 23:00
@kazk my Python solution runs in ~4s on my computer for the [same kata](https://www.codewars.com/kata/insane-coloured-triangles) and a triangle first line of 100k chars :

```
⇒  python -m cProfile /Users/olance/Dev/python-challenges/coloured-triangles/insane_solution.py        

256 function calls in 3.958 seconds
```

Yet it always times out when I attempt to submit it 😕

**Comment by kazk** [comment] 2018-06-04 23:22
> Yet it always times out when I attempt to submit it

Remember that tests used when you attempt are different from the ones you see under sample tests. It shouldn't be possible for you to run the exact tests locally. Sample tests are for you to modify as you need while writing the solution.

For this kata, the following are tested when you submit (it's in the description):

- basic tests
- 100 tests (length between 100 and 1000)
- 100 tests (length between 1000 and 10000)
- 100 tests (length between 10000 and 100000)

**Comment by olance** [comment] 2018-06-04 23:40
@kazk thanks for your reply, and sorry I had deleted my comment quickly because I thought using Discourse to discuss with the kata author might be better than here...

I'm aware of the tests not being the same, of course, but I'm surprised that attempting to submit the exact same code with Python 3.4.3 and then Python 2.7.6 does not show the same result at all:
With Python 3, it times out with no tests passed at all, whereas for Python 2 it does timeout but with the 6 basic, the 100 small and 67 medium tests passed.

Which makes me think performance of the language itself (in setting up the tests and running the solution) does have a potential negative impact

**Comment by kazk** [comment] 2018-06-05 00:06
> using Discourse to discuss with the kata author might be better than here...

Yeah, that will be better :) The author's solution seems to run in about ~3-4s with Python 2 and ~4s with Python 3.4/3.6.

> I'm surprised that attempting to submit the exact same code with Python 3.4.3 and then Python 2.7.6 does not show the same result at all

Yeah, it also depends on the language features being used. But a language version shouldn't be enabled unless it's possible to complete the kata using it. So at least the author's solution runs fast enough in both Python 2 and 3.

> Which makes me think performance of the language itself (in setting up the tests and running the solution) does have a potential negative impact

The difficulty of the kata is not uniform across languages for many reasons. For performance, authors usually makes some adjustments when needed like reducing the number of tests or limiting the size of inputs.

**Comment by olance** [comment] 2018-06-05 09:38
Thanks @kazk, I'll continue on Discourse ;)
I also divided my algorithm's running time by 2, but still not cutting it 😅
