### ISSUE TITLE
Unable to publish new (PHP) Kata

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#559] opened 2016-09-02 16:37 UTC
I just authored a Kata in PHP and was about to publish it but no matter how I reduce the number of assertions in my test cases (from 1000 random assertions per "category" to 100 to 10 only) the kata just won't publish and keeps reporting a timeout error.

![2016-09-03 12 36 42](https://cloud.githubusercontent.com/assets/7777884/18211103/84de1dd0-716e-11e6-95d9-2e69e2a76262.png)

**Comment by jhoffner** [comment] 2016-09-02 21:28
Publishing relies on the background job to handle the code runs, which went down again (I am in a constant struggle to figure out why the background process keeps freezing up).

**Comment by jhoffner** [comment] 2016-09-02 21:30
Related to/duplicate of #558, #475

**Comment by DonaldKellett** [comment] 2016-09-04 14:52
@jhoffner This problem is appearing again.  I just published a new PHP Kata and was in the midst of synchronising the Kata description across all the Kata in my series and this happened.

![screen shot 2016-09-04 at 10 48 44 pm](https://cloud.githubusercontent.com/assets/7777884/18231660/ed9cd17a-72f1-11e6-9c00-5eaee9ef3db3.png)

**Comment by kazk** [comment] 2017-05-31 02:47
See #901

**Closed by kazk** 2017-05-31 02:47 UTC
Labels: duplicate
