### ISSUE TITLE
C# warning ---> unknown error 

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#320] opened 2016-05-21 18:46 UTC
With the new version of C# there are "warnings". Compilation succeeds but the guys passing the kata receive "Unknown error" and they fail. Could you suppress these warnings otherwise lots of kata working with the old version (particularly those abose 500 CW) will not be anymore usable (they are not editable anymore...).

**Comment by jhoffner** [comment] 2016-05-24 18:06
I am unable to reproduce this issue. Is this still happening? If so please provide example kata/repro steps.

**Comment by error256** [comment] 2016-05-24 19:08
Any warning in any kata, for instance, unreachable code:
```csharp
int Foo()
{
    if (false)
        return 0;
    return 42;
}
```

**Comment by kazk** [comment] 2018-04-21 23:44
I think the original issue was caused by warnings printed to stderr which Codewars considers a failure. Closing this because all of the existing C# kata should work with the new runner.

**Closed by kazk** 2018-04-21 23:44 UTC
Labels: needs more info
