### ISSUE TITLE
Where am I within my clan?

### ISSUE THREAD

**Issue by AlexanderZagaynov** [Codewars/codewars.com#1255] opened 2017-12-14 13:12 UTC
I should be visible within my clan, but I'm not. Please see the red arrows on screenshot.
<img width="1347" alt="screen shot 2017-12-14 at 14 02 37" src="https://user-images.githubusercontent.com/7778414/33993886-ab1b503c-e0d8-11e7-96e2-bc19c75dd661.png">

**Comment by Dirtier** [comment] 2017-12-16 08:06
Correct me if I'm wrong, but I'm pretty sure you're looking at your 'Allies', not your clan. You just happen to have a lot of clan members as Allies, because, as it says in the picture, you are automatically given an allegiance with anyone who in the same clan as you.

**Comment by AlexanderZagaynov** [comment] 2017-12-18 10:33
I believe this is the same issue: https://github.com/Codewars/codewars.com/issues/1243

**Comment by kazk** [comment] 2018-01-01 02:53
Closing as duplicate of #1243

**Closed by kazk** 2018-01-01 02:53 UTC
Labels: duplicate
