### ISSUE TITLE
Cannot complete kata and possibility of obtaining points for same kata more than once

### ISSUE THREAD

**Issue by petegg-pja** [Codewars/codewars.com#1834] opened 2019-06-06 08:26 UTC
Hello,
I finished a kata called:
Find the odd int 
https://www.codewars.com/kata/54da5a58ea159efa38000836
in C# language. After providing the correct solution and saving it - kata is still in unresolved state. Moreover I am getting points for solving it. The other interesting thing is that I can submit my code again ("solving" it again). Kata still stays in unresolved mode (cannot see the solutions) and again give me points for solving it. Below just in case I send my solution. Please resolve this issue.

PS. What is interesting is that on the list with all other katas - this one has a check meaning I solved it.
PS2. Thank you for the great site to practice coding : )

Thank you,
Piotr Gago
==========================
        public static int find_it(int[] seq)
        {
            return seq.GroupBy(s => s).First(s => s.Count() % 2 == 0).Key;
        }

**Comment by hobovsky** [comment] 2019-06-06 10:02
#1683 
Just curious, have you actually tried going up to infinity? :)

**Comment by petegg-pja** [comment] 2019-06-06 14:14
> #1683
> Just curious, have you actually tried going up to infinity? :)

Thank you for the link. I admit, pretty bad title for the issue : ) 
Thank you for pointing this out.

**Comment by andrew-qio** [comment] 2019-06-06 20:46
Duplicate of #1683

**Closed by andrew-qio** 2019-06-06 20:46 UTC
