### ISSUE TITLE
Sort by "Performance"

### ISSUE THREAD

**Issue by veernahar** [codewars/codewars.com#2362] opened 2021-04-23 02:20 UTC
I was solving some performance katas recently (such as prime streaming PG-13/NC-17 and The Millionth Fibonacci) and I thought it would be cool if under the 'solutions' tab after you have solved a kata, you can filter by the amount of time the solution took to pass the full test suite. 
Sort of like this: (numbers made up) (excuse the messy-ness)

![image](https://user-images.githubusercontent.com/32236948/115901888-128e5480-a462-11eb-90bd-fab23cdcf3e6.png)

**Comment by bero** [comment] 2021-04-23 16:25
I agree on that. And filter by language. This way you can see how your solution was compared to others with same language. But also globally with all languages.

**Comment by hobovsky** [comment] 2021-04-23 16:37
Duplicate of #2036 #1754 #1133 #959 . See related issues for explanation why it's not as good idea as it might seem.

**Closed by hobovsky** 2021-04-23 16:37 UTC
