### ISSUE TITLE
Solution not showing up in "Solutions"

### ISSUE THREAD

**Issue by joss-c** [Codewars/codewars.com#1936] opened 2019-09-09 19:23 UTC
I will preface this by saying that I can't be sure if this is a problem with the specific kata or a more general problem. As well, codewars was running very slowly for me when this happened.

**The problem**:

I just finished the challenge _[Calculating with Functions](https://www.codewars.com/kata/525f3eda17c7cd9f9e000b39)_, I received honor and then hit "SUBMIT FINAL". Everything seemed normal as I was redirected to the solutions page. As I always do I hit "Newest" to look at my solution alongside the latest submissions. To my surprise I could not see my solution. To ensure that I had actually submitted it, I went to my profile to look at my solutions. I could see my solution there, no problem.

![cw1](https://user-images.githubusercontent.com/3187056/64559687-c7800600-d33e-11e9-8d46-1185feaa1200.png)

I then went back to the solutions page for this kata, clicked on "My Solutions" and it said "There are no solutions yet for this kata."

![cw2](https://user-images.githubusercontent.com/3187056/64559795-fe561c00-d33e-11e9-8ee3-8dc122373178.png)

This has never happened before, but I'm guessing it was a problem caused by the fact that my connection with CW was so weak.

My username on CW is: joss-c
OS: Windows 10
Browser: Chrome (76.0.3809.132)

**Comment by kazk** [comment] 2019-09-09 19:48
Closing as duplicate of other issues like #33.

This seems to happen when something fails when Codewars tries to group the solution. That's why "Discuss" link is missing.

**Closed by kazk** 2019-09-09 19:48 UTC
Labels: duplicate, issue/solution-not-shown, kind/bug
