### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#217] opened 2015-12-22 11:06 UTC
I had already told it many times: it is impossible to re-publish a Java translation of a kata with modifications. You have "Please wait while we publish..." forever... 
I had to delete this Java translation but when I want (with the "+" button) to re-translate it I get "Uh oh! Something went wrong! (500)..." .Can somebody really look at that problem?

**Comment by bkaestner** [comment] 2015-12-24 13:40
Duplicate of #64.

**Comment by g964** [comment] 2015-12-25 09:53
Duplicate of #64, of #209... but never corrected. It's a real pain in the neck to publish and re-publish in Java!

**Comment by brendanvos** [comment] 2017-03-29 18:36
@kazk @jhoffner Listed duplicates are closed, this issue can likely be closed.

**Comment by kazk** [comment] 2017-03-29 18:43
Closing this because @jhoffner commented on Jun 27, 2016 in #209:

> This should have been resolved with all of the recent updates

**Closed by kazk** 2017-03-29 18:43 UTC
