### ISSUE TITLE
There is my solution for kata but system says "you have not yet solved this kata, we have hidden the solutions from you"

### ISSUE THREAD

**Issue by klass-ivan** [Codewars/codewars.com#665] opened 2016-11-03 04:32 UTC
Hi!
I don't think it's related to kata problem itself but some system consistency/integrity issues, so posting it here.
I've completed kata 51646de80fd67f442c000013 in python.
When I review my profile page, it's shown as completed kata, and is presented as "completed" in my "solutions" tab.
However, when I want to check other solutions (https://www.codewars.com/kata/strip-url-params/solutions/python, or (https://www.codewars.com/kata/51646de80fd67f442c000013/solutions/python), it says 

**Solutions have been withheld
Since you have not yet solved this kata we have hidden the solutions from you.**

That's inconsistent, even after more than 15 minutes.

I should note that while solving this kata, "submit final" button was not working first time, so I've reloaded page to paste my solution and complete it.

P.S. Thank you guys for such a project, I really like it :)

**Comment by jhoffner** [comment] 2016-11-30 02:56
This issue was likely caused by a failure to submit the solution correctly (on the system's part). I have a possible fix being deployed to preview.codewars.com now.

**Comment by kazk** [comment] 2017-06-08 20:59
Closing this assuming the changes resolved the issue. Let me know if not.

**Closed by kazk** 2017-06-08 20:59 UTC
Labels: bug, Deployed to preview.codewars.com
