### ISSUE TITLE
Disable spoiler hiding in your own comments

### ISSUE THREAD

**Issue by Haksell** [codewars/codewars.com#2117] opened 2020-05-01 08:01 UTC
#### Is your feature request related to a problem? Please describe.
Most of the comments I post are answers to questions under Kata solutions, and these questions are often the same. So instead of writing the same 10 lines every time, I would prefer being able to copy-paste a past comment and modify it as needed.
However, since these comments are spoilers, they all show as "This comment is hidden because it contains spoiler information about the solution" under the "Discourse" section of my profile, and I can't search the page for keywords.

#### Describe the solution you'd like
I would like to be able to see my comments unaltered under my profile.

**Comment by kazk** [comment] 2020-05-08 03:41
Closing as duplicate of #967

**Closed by kazk** 2020-05-08 03:41 UTC
