### ISSUE TITLE
"Toggle TDD mode" tooltip does not disappear after turning the TDD mode back on

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2281] opened 2020-12-02 00:40 UTC
If you press the "toggle TDD" button in a kumite twice, turning it off and back on, the tooltip gets stuck and never disappears.

When hovering the cursor over it with the TDD mode on, a second tooltip shows up on top of the first one. It seems there're 2 separate tooltips for when the TDD mode is on and when it's off, and the latter one is broken.

Below you can see how there're 2 arrows on top of the tooltip:

![image](https://user-images.githubusercontent.com/31668662/100813190-6fec1f80-3447-11eb-8c58-600b2a2a28fc.png)

**Comment by kazk** [comment] 2020-12-02 00:42
Closing as duplicate of #2115.

**Closed by kazk** 2020-12-02 00:42 UTC
Labels: duplicate
