### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by zachary-mathias** [Codewars/codewars.com#3239] opened 2024-06-05 13:54 UTC
**Describe the bug**
I'm trying to get some practice in as I try to do daily and I have been getting an internal server error! I checked the website status and everything seems to be in the green and running fine. Help! I love this website DX

**Comment by hobovsky** [comment] 2024-06-05 13:58
Duplicate of #3216

**Closed as completed by hobovsky** 2024-06-05 13:58 UTC
Labels: duplicate
