### ISSUE TITLE
Instructions and tests not matching Kata 

### ISSUE THREAD

**Issue by jordanflow** [Codewars/codewars.com#378] opened 2016-06-13 03:29 UTC
There seems to be some issues with the interface on Code Wars.  Instructions aren't matching up with tests...Methods aren't working correctly in their REPL.

**Comment by jhoffner** [comment] 2016-06-15 03:05
This is an odd bug. Possibly a caching issue. Have you seen it again? Do you remember which kata had the invalid description?

**Comment by kazk** [comment] 2017-08-25 07:07
I'm closing this because not enough information was provided to reproduce.

**Closed by kazk** 2017-08-25 07:07 UTC
Labels: bug, more info needed
