### ISSUE TITLE
Solutions don't get unlocked while sending solution

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#395] opened 2016-06-15 16:02 UTC
Can't pass [this Kata](http://www.codewars.com/kata/571c0b707beb0aaa470013e7/) with the following code:
````
def read_ncbi_genetic_code(string)
  data=string.gsub(/(.)+=([^\w\*\-\n]+)/,'').split(/[\n]/)
  aas= data[0]
  starts=data[1]
  base1=data[2]
  base2=data[3]
  base3=data[4]
  
  nucleotidsAtStart = Array.new
  starts.to_enum(:scan,/[^-]/).map do |m,|
    nucleotidsAtStart.push base1[$`.size]+base2[$`.size]+base3[$`.size]
  end
  
 tri_amino = Hash.new
 aas.to_enum(:scan,/./).map do |m,|
   key=base1[$`.size]+base2[$`.size]+base3[$`.size]
   tri_amino.store(key, m)
 end
 
  return [tri_amino,nucleotidsAtStart]
end
````
My solution appears in the past solutions section with formatting altered as
````
def read_ncbi_genetic_code(string)  data=string.gsub(/(.)+=([^\w\*\-\n]+)/,'').split(/[\n]/)  aas= data[0]  starts=data[1]  base1=data[2]  base2=data[3]  base3=data[4]    nucleotidsAtStart = Array.new  starts.to_enum(:scan,/[^-]/).map do |m,|
    nucleotidsAtStart.push base1[$`.size]+base2[$`.size]+base3[$`.size]
  end
  
 tri_amino = Hash.new
 aas.to_enum(:scan,/./).map do |m,|
   key=base1[$`.size]+base2[$`.size]+base3[$`.size]
   tri_amino.store(key, m)
 end
 
  return [tri_amino,nucleotidsAtStart]
end
````

 but solutions don't get shown.

**Comment by jhoffner** [comment] 2016-06-15 16:10
This is related to #391. It was a problem before but may be more common now after the platform transition.

**Comment by javatlacati** [comment] 2016-06-15 16:16
ty :)

**Comment by aryan-firouzian** [comment] 2016-06-15 16:54
Hopefully everything gets fixed soon. Thanks jhoffner, you are doing a great job.

**Comment by jhoffner** [comment] 2016-06-23 05:31
The main cause for this (and #391) has been resolved. There may be some very infrequent data issues caused by other reasons, I'll keep an eye on the exception logs for those. Closing for now.

**Closed by jhoffner** 2016-06-23 05:31 UTC
Labels: bug, high priority

**Comment by javatlacati** [comment] 2016-06-23 22:01
tested again an confirm it's solved thank you :)
