### ISSUE TITLE
Output Compile Window is too small to see executed code and see verified test status

### ISSUE THREAD

**Issue by nellikun** [Codewars/codewars.com#1207] opened 2017-10-30 15:14 UTC
Previously, the output window was large enough to scroll through tests or lines of compiled code to see how the code handled the tests. But since last week, it appears that the window has been resized and appears to not be functioning properly. This occurs independent of the kata, language or account used. I tried creating a new account to see if it was an issue with my account settings, but saw the same problem occur. I have attached a screenshot for reference. 

![image](https://user-images.githubusercontent.com/33227961/32178468-c67a7656-bd5a-11e7-8968-b5e1b581aa6c.png)

**Comment by jhoffner** [comment] 2017-10-30 16:34
Nothing was changed, this seems to be an issue with possibly with a recent release of Chrome. I am working on finding a fix, using FIrefox is the workaround for now.

**Comment by nellikun** [comment] 2017-10-30 16:35
Thank you for the prompt reply!

**Comment by kazk** [comment] 2017-10-30 18:50
Related (or duplicate of) #1202

**Closed** 2017-10-30 21:01 UTC
Labels: bug, high priority
