### ISSUE TITLE
Opening 'Solutions' gives me error: Looks like there was a server error! (500)

### ISSUE THREAD

**Issue by Marcin-Kulik** [Codewars/codewars.com#1241] opened 2017-11-29 11:05 UTC
It looks like my profile has been broken for months. I raised the issue a few months ago but the situation is still the same. Please somebody help me so I can start enjoying Codewars again. No matter which browser I am using whenever I click on 'Solutions' in my profile I get:

Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `code_challenge_review' for nil:NilClass

My nickname on Codewars is Dr. Van Nostrand.

**Comment by kazk** [comment] 2018-05-15 23:54
Sorry for the late response. I'm going to close this as duplicate of your original issue (#1042). Can you post a link to the page you're trying to open? I couldn't find a user with name "Dr. Van Nostrand".

**Closed by kazk** 2018-05-15 23:54 UTC
Labels: issue/server-error-nil

**Comment by kazk** [comment] 2018-05-16 01:25
I'm not sure what was causing the error, but I'm glad that you're able to use Codewars again :) Thanks for letting us know.
