### ISSUE TITLE
JS: Array.fill() not working

### ISSUE THREAD

**Issue by scheffield** [Codewars/codewars.com#194] opened 2015-10-13 11:25 UTC
Hi,

the following code works using `babel-node` on my local machine:

```
var largeArray = Array(1000).fill(0);
```

But on codewars this seems to create an array filled with `undefined`.

**Comment by shershen08** [comment] 2015-12-14 16:53
I am gettting ```TypeError: Object ... has no method 'fill'```

**Comment by GiacomoSorbi** [comment] 2015-12-26 23:08
Not the best workaround, maybe, but try this one instead:

```
new Array(1001).join("a").split("").map(a=>0);
```

**Comment by caycek** [comment] 2016-05-10 14:01
is this still supposed to be happening?? The above helps, but it would be really cool to use fill instead.

**Comment by javatlacati** [comment] 2016-06-09 16:17
@jhoffner  this doesn't has to be on the [codewars runner cli](https://github.com/Codewars/codewars-runner-cli) repo as issue?

**Comment by kazk** [comment] 2017-03-28 00:50
Confirmed this using Node v0.10.33/Babel, but closing because Node v6 is available now.
We should also start looking into removing Node v0.10.x as it reached end-of-life status on 2016-10-31. [nodejs/LTS](https://github.com/nodejs/LTS).

**Closed by kazk** 2017-03-28 00:50 UTC
Labels: enhancement
