### ISSUE TITLE
Receiving "python version python not supported" error after editing a published translation

### ISSUE THREAD

**Issue by ggmoy** [Codewars/codewars.com#918] opened 2017-04-25 14:00 UTC
Good morning guys,

I need some help from you, please. Yesterday, I published a new [Python Translation](https://www.codewars.com/kumite/58fcf1142bffa781c7000133?sel=58fcf1142bffa781c7000133) of the "[Kata Break the pieces](https://www.codewars.com/kata/break-the-pieces)". After I published it, I realized that the name of a function was not complaint with Python naming convention. So, I edited the published translation, fixed the function name and then published again. The problem is that I received a message stating that it was published but without passing the test cases. If you go to the translation link, it said "Failed tests".

The message I'm receiving is "python version python not supported".

Could someone help me, please?

**Comment by jhoffner** [comment] 2017-04-25 17:26
Related to #869, duplicate of #761

**Closed** 2017-04-25 17:26 UTC
Labels: bug, duplicate, high priority
