### ISSUE TITLE
Disable 'Attempt' button after submitting

### ISSUE THREAD

**Issue by ScottWorks** [Codewars/codewars.com#1767] opened 2019-03-16 19:50 UTC
I noticed that clicking the 'Attempt' button twice will actually reset your code wars challenge. This is clearly the case for the antsy programmer but it would be nice to just disable the button while CW's processes the request, that way there is no chance the challenge will be reset.

**Comment by kazk** [comment] 2019-03-16 20:02
Isn't this already done?

![attempt-click-3](https://user-images.githubusercontent.com/639336/54480905-9e494780-47eb-11e9-8ea7-db6cee40b514.gif)


Also, what do you mean by "will actually reset your code wars challenge"?

**Comment by ScottWorks** [comment] 2019-03-16 22:02
@kazk I thought so as well but that was not the case today when I was working on a few challenges. At the moment I can't replicate the problem I had either. 

Basically what happened was: 
1) Finished writing the code challenge
2) Select 'Attempt' 
3) Some time passes, I hit the same button as I did in step 2
4) I am redirected to the solutions page but I am asked if I want to unlock the solution
5) Navigate back to code challenge, all of the code previously written is gone. 

This has happened to me at least 5 times already it seems like its been happening very frequently lately. I will try to be more observant going forward.

**Comment by kazk** [comment] 2019-03-16 22:06
@ScottWorks Thanks for explaining. That makes sense. What you're describing is one of the known bugs (#1683) which is not easy to fix. If you're interested in more details, see https://github.com/Codewars/codewars.com/issues/1683#issuecomment-473416159 .

Closing as duplicate of other issues.

**Comment by kazk** [comment] 2019-03-16 22:07
Actually, can you explain what you mean by "Some time passes, I hit the same button as I did in step 2"?

More specifically, how long is "some time" and do you see "Attempt" again instead of "Submit Final"?

**Comment by ScottWorks** [comment] 2019-03-16 22:19
By "some time" I am only referring to the amount of time that would be expected for the "Attempt" request to resolve. I dont know exactly how much time that actually is. 

The "Attempt" button only appears for a brief moment before "Submit Final" IIRC, I would need to confirm this another time though.

**Comment by kazk** [comment] 2019-03-16 22:36
Yeah, sounds like the same issue so closing as duplicate. Feel free to comment if you have any follow up information.

**Closed by kazk** 2019-03-16 22:36 UTC
Labels: duplicate
