### ISSUE TITLE
When translating a Kata, typing in the description or code window scrolls the description to the top

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars.com#1206] opened 2017-10-29 05:41 UTC
Issue: When translating a Kata, typing in the description or code window scrolls the description to the top

How to reproduce: Create a new Kata translation, scroll the description/Kata specs window to the bottom, and type in the code window.

Temp fix: Replacing `jQuery.style` with a dummy function, e.g. `jQuery.style = () => null`, causes this issue to disappear. The user's scroll position is likely lost when the styles are reset.

Note: This issue is separate from #1202 / #1204 and has been occurring for a while.

**Comment by 10XL** [comment] 2017-10-29 17:02
Duplicate of https://github.com/Codewars/codewars.com/issues/353

**Comment by kazk** [comment] 2018-01-04 21:28
Closing as duplicate of #353

**Closed by kazk** 2018-01-04 21:28 UTC
Labels: duplicate
