### ISSUE TITLE
Margin width too small affecting UI display

### ISSUE THREAD

**Issue by ejini6969** [codewars/codewars.com#2688] opened 2022-05-08 01:06 UTC
As in the figure below, most `_` are hidden except the one in the last line. This only happens in test case section of a kata but not in sample tests. Mostly affected in languages that use `snake_case`, & characters such as `g`, `y`, etc.

![image](https://user-images.githubusercontent.com/65498235/167277355-bf0b472a-1121-45f7-8dc9-d392dabd07e5.png)

**Comment by FArekkusu** [comment] 2022-05-08 08:34
Looks like a duplicate of #2669.

**Comment by Blind4Basics** [comment] 2022-05-08 08:51
yup, closing.

**Closed by Blind4Basics** 2022-05-08 08:51 UTC
