### ISSUE TITLE
Cannot submit kata

### ISSUE THREAD

**Issue by Vadim-pmm** [Codewars/codewars.com#896] opened 2017-04-14 06:03 UTC
Today I did 2 katas and neither of them let me submit the solution. The buton "Attempt" remains as "Attempt" after all tests had passed.
I pushed the button several times, refreshed the page - no effect...
The last kata was - "Unique In Order" in Ruby.

**Comment by kazk** [comment] 2017-04-14 06:06
Closing because this is exact duplicate of #893.

**Closed by kazk** 2017-04-14 06:06 UTC
