### ISSUE TITLE
Internal Server Error while reaching the solutions/discourse

### ISSUE THREAD

**Issue by Roxasch97** [Codewars/codewars.com#3221] opened 2024-05-22 13:24 UTC
**Describe the bug**
I've tried to pass the kata, failed, and decided to peek at the solutions, but received Internal Server Error

**To Reproduce**
Attend a kata, provide partially good response, fail miserably and proceed to check the solutions with heart full of shame, receive an error.

**Expected behavior**
Solutions being shown (with disgust to the person checking them).

**Screenshots**
![image](https://github.com/codewars/codewars.com/assets/85390643/fd79f7c8-c80d-4c0b-9880-e45e312af3ea)

**Browser**
Chrome
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36,gzip(gfe)

- OS: Win11

**Comment by hobovsky** [comment] 2024-05-22 13:25
Duplicate of #3220

**Closed as completed by hobovsky** 2024-05-22 13:25 UTC
Labels: duplicate
