### ISSUE TITLE
Runner error: Overflow sort stage buffered data usage...

### ISSUE THREAD

**Issue by aariza** [Codewars/codewars.com#1186] opened 2017-10-19 07:10 UTC
Hi,
When I try to load the Home page, I always obtain this error message:

 The operation: #<Moped::Protocol::Query @length=14498 @request_id=1002 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="codewars-production.users" @skip=0 @limit=0 @selector={"$query"=>{"$and"=>[{"_id"=>{"$in"=>["5829a977261c2a2ea3000753", "5855b24c36b75bb06900000c", "57ea8c3df330e298460006e9", "582ac01274152e9bfe0000be", "58357ec662ee22150c000176", "57d94ca71a62825a2500012d", "57ecfae85f79f65d7b000201", "57c3dd571170a324810004d6", 
...
"59e7b0d8c596ebb18f00029a", "59e7babaa9542730e60000f4", "59e135c52a7accc19a00002a"]}}]}, "$orderby"=>{"points.xp"=>-1}} @fields=nil> failed with error 17144: "Runner error: Overflow sort stage buffered data usage of 33558697 bytes exceeds internal limit of 33554432 bytes" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error.

My username is aariza and I login with github. This error has started to appear after select new languages to train in my profile, but after deselect them the error continue, then I don't think it is related with.

BR,
Arturo

**Comment by aariza** [comment] 2017-10-21 09:02
I have tried with a different browser and the problem continues, then does not depend on the browser version neither cookies.

**Comment by kazk** [comment] 2018-01-04 21:24
Closing as duplicate of #1220

**Closed by kazk** 2018-01-04 21:24 UTC
Labels: duplicate
