### ISSUE TITLE
Wrong selector to toggle rank assessment

### ISSUE THREAD

**Issue by ZEDCWT** [Codewars/codewars.com#1736] opened 2019-02-18 05:36 UTC
#### To Reproduce
+ Rank any beta kata
+ After responsed, click any `<li>` element of kyu description, like `Defining a simple function (i.e. hello world)`, `Fixing basic syntax issues`, ...
+ Then the rank assessment would be toggled off

#### Fix
Correct the `.assessment-ranks li click` selector in `application.js`

**Comment by kazk** [comment] 2019-02-18 08:04
Most likely a duplicate of #283 if I'm understanding correctly, but I'll close this when I fix it

**Comment by kazk** [comment] 2019-02-22 02:39
Fixed

**Closed by kazk** 2019-02-22 02:39 UTC
Labels: duplicate
