### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by CaptainLiuMing** [Codewars/codewars.com#3220] opened 2024-05-22 13:19 UTC
I encountered an "Internal Server Error" while using Codewars. This error prevents me from submitting my solution to a kata.

**Steps to Reproduce:**
1. Navigate to the kata page: [URL of the kata]
2. Enter my solution code.
3. Click on the "Submit" button.
4. The "Internal Server Error" message appears.

**Expected Behavior:**
The solution should be submitted successfully, and I should receive feedback on my code.

**Actual Behavior:**
An "Internal Server Error" message is displayed, and the submission is not processed.

**Additional Information:**
- Browser: Google Chrome v91.0.4472.124
- Operating System: Windows 10
- Screenshot: [Attach screenshot if available]

Thank you for looking into this issue!

**Comment by hobovsky** [comment] 2024-05-22 13:38
Duplicate of #3216

**Closed as completed by hobovsky** 2024-05-22 13:38 UTC
Labels: duplicate
