### ISSUE TITLE
An (on-going) comprehensive list of published/beta katas that are duplicates/should be retired/edited

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1315] opened 2018-02-26 08:56 UTC
While #1301 is being idle for a while, let's collect all the duplicates/low quality katas out there that should be retired/revamped/de-duplicated.

---

**Duplicates**

Rot-13:
https://www.codewars.com/kata/rot13/
https://www.codewars.com/kata/rot13-1/
https://www.codewars.com/kata/rot13-2/
beta:
https://www.codewars.com/kata/hail-caesar
https://www.codewars.com/kata/caesars-cypher-2
Proposal: Drop all betas, and all but one published katas

Ceasar cipher:
https://www.codewars.com/kata/caeser-encryption
https://www.codewars.com/kata/dbftbs-djqifs
https://www.codewars.com/kata/caesar-cipher-helper
beta:
https://www.codewars.com/kata/caesar-cipher-1
https://www.codewars.com/kata/unofficial-fcc-challenge-basic-algorithm-scripting-caesars-cipher
https://www.codewars.com/kata/cryptography-caesar-cipher
https://www.codewars.com/kata/caesars-cipher
https://www.codewars.com/kata/caesars-cipher-1
https://www.codewars.com/kata/caesar-cipher
https://www.codewars.com/kata/casear-cypher
https://www.codewars.com/kata/caesar-cipher-1
Proposal: **Drop all the betas**, and all but one published katas

Fizzbuzz:
https://www.codewars.com/kata/fizz-buzz
https://www.codewars.com/kata/pre-fizzbuzz-workout-number-1
betas:
https://www.codewars.com/kata/tiy-fizzbuzz
https://www.codewars.com/kata/if-less-fizzbuzz-1
https://www.codewars.com/kata/fizzbuzz-4
https://www.codewars.com/kata/pre-fizzbuzz-workout-number-2
https://www.codewars.com/kata/fizz-buzz-2
https://www.codewars.com/kata/fizz-buzz-1
https://www.codewars.com/kata/your-basic-fizzbuzz-kata
Proposal: **DROP ALL THE BETAS** (Note that there are more of them, I just searched along "fizzbuzz" keyword. I know there are more because I've encountered more disguised ones in beta). Maybe we should only keep one of the published ones, I mean, they're pretty much the same, no? Except for the return type

Church numerals: 
https://www.codewars.com/kata/church-numbers-1
https://www.codewars.com/kata/church-numbers-ii
https://www.codewars.com/kata/church-numbers
https://www.codewars.com/kata/church-numbers-add-multiply-exponents
https://www.codewars.com/kata/church-numbers-find-the-predecessor-and-subtract
Proposal: Only one of `1, 3, 4` should be kept. `2` is the most comprehensive but it's only in JS. Preferably we should have one version that covers all of `2` and are still available in most functional languages (and maaaaybe JS? But I don't think JS is a good idea for this).

Arithmetic expression parser:
https://www.codewars.com/kata/arithmetic-expressions-evaluator
https://www.codewars.com/kata/calculate-the-expression
https://www.codewars.com/kata/evaluate-mathematical-expression
https://www.codewars.com/kata/parsing-and-evaluation-of-mathematical-expressions
https://www.codewars.com/kata/calculator
https://www.codewars.com/kata/no-math-expression-evaluator
https://www.codewars.com/kata/route-calculator
beta:
https://www.codewars.com/kata/advanced-calculator
https://www.codewars.com/kata/my-bedmas-approved-calculator
Proposal: Drop all but one. We already have tons of arithmetic expression parser kata who are all pretty much the same except with a million variations. The problem is, all of them are pretty much the same **and the quickest way to do them is to** `eval` **them via JS/Python/etc**, and it's unstoppable this way (or you can just drop in the standard parser already available and tweak from there). They stop being interesting a long time ago.

Sudoku board validation: 
https://www.codewars.com/kata/did-i-finish-my-sudoku
https://www.codewars.com/kata/sudoku-solution-validator
https://www.codewars.com/kata/validate-sudoku-with-size-nxn
Proposal: Drop 1 and 2, they have incredibly weak tests anyway and is covered by 3. 3 needs to revamped and added better tests and random tests, but that's after 500 limit is lifted.

Sudoku solver: 
https://www.codewars.com/kata/hard-sudoku-solver
https://www.codewars.com/kata/hard-sudoku-solver-1
https://www.codewars.com/kata/sudoku-solver
https://www.codewars.com/kata/finish-this-mini-sudoku
https://www.codewars.com/kata/easy-sudoku (beta)
https://www.codewars.com/kata/sudoku-solver-number-1 (beta)
https://www.codewars.com/kata/sudoku-solver-number-2 (beta)
https://www.codewars.com/kata/sudoku-solver-number-3 (beta)
https://www.codewars.com/kata/sudoku-solver-number-4 (beta)
https://www.codewars.com/kata/sudoku-solver-number-5 (beta)
Proposal: Drop all of them and rewrite one that actually has good tests and random tests. Especially those betas: those 5 betas are duplicate of *themselves*

Fibonacci numbers:
https://www.codewars.com/kata/complete-fibonacci-series
https://www.codewars.com/kata/fibonacci-reloaded
https://www.codewars.com/kata/n-th-fibonacci
https://www.codewars.com/kata/memoized-fibonacci
https://www.codewars.com/kata/fast-fibonacci
https://www.codewars.com/kata/recursion-number-2-fibonacci
https://www.codewars.com/kata/big-fibonacci-numbers-1
betas:
https://www.codewars.com/kata/fibonacci-number
https://www.codewars.com/kata/the-fibonacci-sequence
https://www.codewars.com/kata/fibonacci-numberd
https://www.codewars.com/kata/efficient-recursive-fibonacci
Proposal: Drop all but one

Reverse fibonacci numbers:
https://www.codewars.com/kata/reverse-fibonacci-series
https://www.codewars.com/kata/the-iccanobif-sequence
Proposal: Drop all. They are pretty much the same as the fibonacci numbers katas anyway

Fibonacci number generators: 
https://www.codewars.com/kata/custom-enumerators-fibonacci
https://www.codewars.com/kata/fibonacci-generator
https://www.codewars.com/kata/fibonacci-generator-function
https://www.codewars.com/kata/fibonacci-streaming
Proposal: Drop all but one

Fibonacci rectangle: 
https://www.codewars.com/kata/perimeter-of-squares-in-a-rectangle
https://www.codewars.com/kata/perimeter-of-fibonacci-rectangle
Proposal: Drop the 2nd kata (okay, this was my fault, I approved it)

Sum of even fibonacci numbers:
https://www.codewars.com/kata/sum-even-fibonacci-numbers
https://www.codewars.com/kata/even-fibonacci-sum
https://www.codewars.com/kata/sumfibs
Proposal: Drop all but one

Factorial:
https://www.codewars.com/kata/recursion-number-1-factorial
https://www.codewars.com/kata/factorial-1
https://www.codewars.com/kata/factorial
https://www.codewars.com/kata/factorial-factory
https://www.codewars.com/kata/big-factorial
beta:
https://www.codewars.com/kata/factorializing-a-number
https://www.codewars.com/kata/factorial-fun
https://www.codewars.com/kata/unofficial-fcc-challenge-basic-algorithm-scripting-factorialize-a-number
Proposal: Drop all but one

Pascal triangle:
https://www.codewars.com/kata/pascals-triangle-number-2
https://www.codewars.com/kata/pascal-problem
https://www.codewars.com/kata/simple-fun-number-214-pascal-matrix
https://www.codewars.com/kata/pascals-triangle
beta:
https://www.codewars.com/kata/pascals-triangle-2
Proposal: Drop all but one. The last approved one *must* be dropped though because of its ridiculous requirement (all rows concatenated into one) and early kata overranking

Primality check:
https://www.codewars.com/kata/check-for-prime-numbers
https://www.codewars.com/kata/prime-numbers
https://www.codewars.com/kata/is-a-number-prime
https://www.codewars.com/kata/check-if-number-is-prime-without-loops
https://www.codewars.com/kata/is-a-prime
beta:
https://www.codewars.com/kata/is-it-prime
https://www.codewars.com/kata/is-prime-number
https://www.codewars.com/kata/check-if-a-number-is-prime

Prime counting:
beta:
https://www.codewars.com/kata/count-prime
https://www.codewars.com/kata/count-primes-easy
(Variant: n-th prime):
https://www.codewars.com/kata/prime-number-generator-intermediate-with-inputs-version
https://www.codewars.com/kata/nth-prime-number
(Variant: prime counting in an interval):
https://www.codewars.com/kata/count-primes-easy
https://www.codewars.com/kata/count-primes
https://www.codewars.com/kata/finding-a-prime-number-in-an-interval

Prime generator:
https://www.codewars.com/kata/prime-numbers
https://www.codewars.com/kata/get-n-first-prime-numbers
https://www.codewars.com/kata/simple-prime-number-generator
https://www.codewars.com/kata/array-of-all-primes-up-to-number-n
https://www.codewars.com/kata/prime-number-generator-simple-version
https://www.codewars.com/kata/array-of-primes
https://www.codewars.com/kata/first-n-prime-numbers
beta:
https://www.codewars.com/kata/prime-finder

Sum of primes:
https://www.codewars.com/kata/sum-of-primes-1
beta:
https://www.codewars.com/kata/sum-of-primes

Sieve:
https://www.codewars.com/kata/master-your-primes-sieve-with-memoization
https://www.codewars.com/kata/sieve-of-eratosthenes
beta:
https://www.codewars.com/kata/sieve-of-eratosthenes-1
Proposal: **Revamp and prune all these prime katas**. There are only 3 algorithms involved:
- Trial division
- Sieve
- Sometimes number-theoretic prime check (e.g Miller-Rabin)

So in some sense, *all* of them are boring and kind of a duplicate.

Integer factorization:
https://www.codewars.com/kata/prime-factorization
https://www.codewars.com/kata/prime-factors
https://www.codewars.com/kata/primes-in-numbers
beta:
https://www.codewars.com/kata/prime-factors-1
https://www.codewars.com/kata/prime-factorisation-in-index-notation
https://www.codewars.com/kata/prime-factorisation
https://www.codewars.com/kata/factorization-1
Proposal: Drop all but one

Trailing zeros in factorial:
https://www.codewars.com/kata/number-of-trailing-zeros-of-n
https://www.codewars.com/kata/factorial-tail
https://www.codewars.com/kata/trailing-zeros-in-factorials-in-any-given-integer-base
Proposal: Drop 2 (2 and 3 are exactly the same except 3 is slightly more performance heavy), and maybe 1 since it's a subset of 3.

Goldbach conjecture:
https://www.codewars.com/kata/goldbachs-conjecture-1
https://www.codewars.com/kata/goldbachs-conjecture-prime-numbers
https://www.codewars.com/kata/goldbachs-conjecture
Proposal: Drop all but one

~~Girls are updating, Please wait warmly...~~

---

**Low quality katas**

Base91 encoding: https://www.codewars.com/kata/base91-encoding-and-decoding
...Okay, it was my mistake to approve this. It should really be sent back to beta/retired. (Though one has to wonder *why* beta testers are giving it *very satisfied* in the first place when the kata description is far from adequate and they're just all copying the same piece of code from the web. I was naive back then. If it was me now I'd probably have raised like 3 issues to it.)

Subtract the sum: https://www.codewars.com/kata/subtract-the-sum
Highly controversial for obvious reasons

~~Girls are updating, Please wait warmly...~~

---

**Broken katas**

~~Girls are updating, Please wait warmly...~~

**Comment by Unihedro** [comment] 2018-02-28 09:54
>Trailing zeros in factorial:
>https://www.codewars.com/kata/number-of-trailing-zeros-of-n
>https://www.codewars.com/kata/factorial-tail
>https://www.codewars.com/kata/trailing-zeros-in-factorials-in-any-given-integer-base
>Proposal: Drop 2 (2 and 3 are exactly the same except 3 is slightly more performance heavy), and maybe 1 since it's a subset of 3.

I disagree that 1 is a subset of 3; It covers **a more narrow domain** which can be modeled a lot more simply than the arbitrary base problem and is a **good stepping stone** for the relevant algorithms (another common task is to find largest `k` such that `n! mod p^k == 0` where `p` is some prime number input, which I haven't seen, but I also haven't done many problems on codewars (please link to me if you see it)), not to mention that **it has wider translation coverage** (can't judge if it's *better*, though) which is not matched by either 2 or 3, so it's more readily available to more users to practice.

**Comment by Unihedro** [comment] 2018-03-02 00:45
Proposals for treatment as low quality katas:

https://www.codewars.com/kata/text-align-justify/discuss **28 open issues** nonexistent sample tests, translations are apparently even worse than the source; proposition: clean up needed

https://www.codewars.com/kata/ip-validation/discuss/ **16 open issues** <- although it's not really that bad. 4kyu is vastly overrating it for current standards since it's a simple validation problem, and it's missing sample tests in CoffeeScript, Javascript etc; proposition: rewrite needed, possibly retire old kata in favour of realigning the score

https://www.codewars.com/kata/base64-encoding/discuss **18 open issues** ...

**Comment by Voileexperiments** [comment] 2018-03-02 01:41
@Unihedro those katas can be boiled down to ~3 *unique* issues: others are just people keep raising the same issue again without adding anything new (yes, people like to do that all the time). And the issue boils down to, unsurprisingly, broken translations. If I have time to clean up all those duplicate issues I'd probably have just fixed the translation, but I didn't do the latter, so ;-)

**Comment by docgunthrop** [comment] 2018-03-02 08:55
The following kata can also be retired:
https://www.codewars.com/kata/regular-expression-check-if-divisible-by-0b101-5
It's an exact duplicate of:
https://www.codewars.com/kata/regular-expression-for-binary-numbers-divisible-by-5

**Comment by Blind4Basics** [comment] 2018-03-03 15:33
Low quality kata (still in beta) to retire: https://www.codewars.com/kata/52f5f8757c461de6310001e8 (writing the sum of a and b... / 20 issues / no random tests / ...)

**Comment by Blind4Basics** [comment] 2018-03-05 18:42
in the low quality katas to retire:

* https://www.codewars.com/kata/escape-the-mines/  (fixed tests only, and checking for an exact path instead of A shortest path)

**Comment by anter69** [comment] 2018-03-06 14:50
https://www.codewars.com/kata/factorization/

**Comment by Voileexperiments** [comment] 2018-03-09 03:54
https://www.codewars.com/kata/zero-fill-dot-dot-dot-for-the-queen

This is now obsolete since `padStart` is available.

**Comment by dinglemouse2250** [comment] 2018-03-09 05:26
> This is now obsolete since padStart is available from Node 8.

But not all Kata are applicable for all languages. And on the other side of the coin, just because one language has has a library function does not mean it a bad Kata for other languages....

**Comment by Voileexperiments** [comment] 2018-03-09 07:14
Yes, but my point there is that lots people make katas that are language-specific, and so they're not portable to most other languages and, hence, the status of other languages does not apply to the kata.

**Comment by Voileexperiments** [comment] 2018-03-09 07:15
https://www.codewars.com/kata/grasshopper-debug

Or, in general: all the bs "bugfix" katas that just dumps "code" in alien syntax in the initial code section.

They don't teach anything and are really best described as attempts to shitpost katas.

**Comment by Voileexperiments** [comment] 2018-03-15 02:41
https://www.codewars.com/kata/true-addition

**Comment by kazk** [comment] 2018-03-22 01:31
These kata failed tests when I tested against the new runner. I haven't looked into them much, so some might be caused by the changes in the runner.

It seems like `assertSimilar` is causing lots of issues for JS. I think it's a bad idea to use the output of `util.inspect` for testing... The output isn't standardized as far as I know, so it could've changed over the years. `cw-2.js` needs to be fixed in general.


- ["AURUM RECLUDIT CUNCTA"](https://codewars.com/kata/59bcd995bf10a4206d00004d) with javascript
- ["string".forEachMatch(regex, callback, [context]);](https://codewars.com/kata/52a4545199b32d4074000176) with javascript
  - assertSimilar issue
- [Alphabetize a list by the nth character ](https://codewars.com/kata/54eea36b7f914221eb000e2f) with javascript
  - random test fail
- [An Introduction to DocTesting...](https://codewars.com/kata/58e4033b5600a17be1000103) with python
  - `<FAILED::>'TestResults(failed=0, attempted=0)' should equal 'TestResults(failed=0, attempted=6)'`
- [Arrays are Objects](https://codewars.com/kata/552fc8d81b59b6b4820000a4) with javascript
  - assertSimilar issue. util.inspect changed output?
- [Bad Exception Handling](https://codewars.com/kata/5950eec3a100d72be100003f) with python
- [Ball Launcher Robot](https://codewars.com/kata/575ee86851071bd22c000106) with javascript
  - assertSimilar issue
- [Bar Graph - Graphing #1](https://codewars.com/kata/56cb632fc8cfccc84e0015d9) with javascript
- [Basic Calculator](https://codewars.com/kata/5296455e4fe0cdf2e000059f) with javascript
  - signed zero compared with string comparison
- [better Add Floats](https://codewars.com/kata/5293ef9b6144df008d000147) with javascript
- [Call Center Call Backs](https://codewars.com/kata/55c3e6472605d3f415000060) with javascript
  - the solution relies on system locale
- [Cartesian coordinates from degree angle](https://codewars.com/kata/555f43d8140a6df1dd00012b) with javascript
  - assertSimiar issue. signed zero in array
- [Convert number to reversed array of digits](https://codewars.com/kata/5583090cbe83f4fd8c000051) with javascript
  - assertSimilar issue
- [Count the Ones](https://codewars.com/kata/5519e930cd82ff8a9a000216) with javascript
  - expected 0 got NaN
- [Counting number of ones in an iterable using all() and any().](https://codewars.com/kata/58ed06f0b43ea0e68d000050) with python
  - `Need to use my_any() function`
- [Counting Sort](https://codewars.com/kata/57d287d1900f6e219d00000c) with javascript
  - not reliable test, compares execution speed against builtin sort.
- [Custom sort function](https://codewars.com/kata/52105fab0bd0ce9dd00000fe) with coffeescript
  - assertSimilar issue
- [Data mining #1](https://codewars.com/kata/58f89357d13bab79dc000208) with python
- [Don't rely on luck.](https://codewars.com/kata/5268af3872b786f006000228) with php
  - `<FAILED::>Sorry. Unlucky this time.<:LF:>Failed asserting that 80 matches expected 85.`
- [Find  Cracker.](https://codewars.com/kata/59f70440bee845599c000085) with javascript
  - `<FAILED::>Expected: '[\'John Brown\', \'Bill Webb\', \'Jane Webb\', \'Doe Bradley\', \'Bill Lawrence\', \'Doe Lawrence\', \'Jane Watts\', \'Jane Lawrence\']', instead got: '[\'John Brown\', \'Jane Webb\', \'Doe Bradley\', \'Bill Lawrence\', \'Doe Lawrence\', \'Jane Watts\', \'Jane Lawrence\']'`
- [Find the name of the lucky variable](https://codewars.com/kata/5a47d5ddd8e145ff6200004e) with python
- [Fun with ES6 Classes #1 - People, people, people](https://codewars.com/kata/56f7f8215d7c12c0e7000b19) with coffeescript
- [Grasshopper - if/else review](https://codewars.com/kata/57227b32785220c82b000b93) with python
- [Handy Toolbox for Kata authors](https://codewars.com/kata/56efff4a49cd0c58a0000b8c) with javascript
- [Helper Functions and Recursion - Factorials, Permutations and Combinations](https://codewars.com/kata/56f7996c5d7c121fd6000511) with javascript
  - `TestError: Oops, it seems that you have not used recursion in your function.  Please try again.`
- [Ho Ho Ho with Functions!](https://codewars.com/kata/52af1f150fcae8d33d0009bc) with coffeescript
  - `TestError: Expected: '', instead got: undefined`
- [How many dots are covered](https://codewars.com/kata/590c6a479f4b9f28e6000084) with javascript
  - `TestError: 212.228 × 164.964 ↺ 32° 35043 ̷≈ 35009.979792`
- [Identify Case](https://codewars.com/kata/5819a6fdc929bae4f5000a33) with coffeescript
  - TestError: Expected: 'camel', instead got: 'none'
- [Insert into xml object - xml #3](https://codewars.com/kata/56cf504761603455580012ab) with javascript
  - `Expected: '[{ siddneni: \n   { attributes: {},\n     sub: \n      [ [Object],\n        \'mwrfjwfml    cpwrwp    novymc   qfpeou       llyejcu\',\n        [Object] ] } }, { wmwgs: { attributes: {}, sub: [ [Object], [Object], [Object] ] } }, { code: \n   { sub: \n      [ [Object],\n        \'ktqyfy   obigjppi        idcgc  cfudjj      ejknhr\',\n        [Object] ] } }, \'kpoimx    qtxtxk xufgthgynls   dglid    xumddimsfyw\']', instead got: '[{ siddneni: \n   { attributes: { undefined: undefined },\n     sub: \n      [ [Object],\n        \'mwrfjwfml    cpwrwp    novymc   qfpeou       llyejcu\',\n        [Object] ] } }, { wmwgs: \n   { attributes: { undefined: undefined },\n     sub: [ [Object], [Object], [Object] ] } }, { code: \n   { sub: \n      [ [Object],\n        \'ktqyfy   obigjppi        idcgc  cfudjj      ejknhr\',\n        [Object] ] } }, \'kpoimx    qtxtxk xufgthgynls   dglid    xumddimsfyw\']'`
- [Is there an Arithmetic Progression sequence?](https://codewars.com/kata/57bff6f6b5e2c99387000149) with javascript
- [Kasiski's Test - Breaking the Vigenère Cipher](https://codewars.com/kata/544e5d75908f2d5eb700052b) with javascript
- [Lexicographic Permutations](https://codewars.com/kata/55baa55cf332e67eb000000a) with python
- [List functions of an object  by length](https://codewars.com/kata/57067e00fb3008566300058a) with ruby
  - `<FAILED::>Expected: [:+, :-, :*, :/, :%, :>, :<, :~, :&, :|, :^, :i, :!], instead got: [:%, :&, :*, :+, :-, :/, :<, :>, :^, :|, :~, :i, :!]`
- [Mastermind](https://codewars.com/kata/58a848258a6909dd35000003) with ruby
  - `<FAILED::>Error: you have had more than 60 tries! -  Expected: 2, instead got: 1`
- [Monotone travel](https://codewars.com/kata/54466996990c921f90000d61) with python
  - `<FAILED::>Should work on increasing lists`
- [My Very Own Python's Split Function](https://codewars.com/kata/55e0467217adf9c3690000f9) with python
  - `<FAILED::>No-no! You were asked to create a generator!: False should equal True`
- [Mystery function #2](https://codewars.com/kata/55041210decf057109000277) with javascript
  - `<FAILED::>Something fishy going on. Make sure your solved function is correct.`
- [not So Easy: Count characters](https://codewars.com/kata/57fcedb387b8012b23000023) with javascript
  - `Expected: '36', instead got: '37'`
- [Random Sequence Generator](https://codewars.com/kata/5302b069ad5217ce2d0000f1) with javascript
- [React Flux](https://codewars.com/kata/569c2ee3f16a9857a2000047) with javascript
- [Recursive Replication](https://codewars.com/kata/57547f9182655569ab0008c4) with python
- [Recursive reverse string](https://codewars.com/kata/536a9f94021a76ef0f00052f) with python
  - `<FAILED::>18 should equal 1`
- [Secret knock](https://codewars.com/kata/525f00ec798bc53e8e00004c) with python
  - `<FAILED::>Sorry, that's not the secret knock.`
- [Sequence generator](https://codewars.com/kata/56ba8a9b022c16017d0001f3) with javascript
  - `<FAILED::>what if 2nd parameter is not provided? - Expected: '[null, null]', instead got: '[undefined, undefined]'`
- [Shop Inventory Manager](https://codewars.com/kata/55d1d06def244b18c100007c) with python
- [Shortest Code : Guess the Hat](https://codewars.com/kata/570e6d8576f0cde131000129) with javascript
  - `<FAILED::>Expected: '\'2\'', instead got: '2'`
- [Smart Contracts Introduction: GiftCoin](https://codewars.com/kata/59bc5750460387a5120000ad) with solidity
  - `AssertionError: GiftSent should not be called when funds are insufficient`
- [Sports league table - help your local team!](https://codewars.com/kata/566fd169d39cf89e1e000044) with python
- [Temperature converter](https://codewars.com/kata/54ce9497975ca65e1a0008c6) with javascript
  - `<FAILED::>Convert 54 Re to F - Expected: 154, instead got: 153`
- [To BrainFuck Transpiler](https://codewars.com/kata/59f9cad032b8b91e12000035) with ruby
- [What time is it in Japan ?](https://codewars.com/kata/59c53183aeb2842585000116) with shell
  - `<FAILED::>Test Failed<:LF:>expected: "2018-03-18T16:13+0900"<:LF:>     got: "2018-03-18T16:13+09:00"<:LF:><:LF:>(compared using ==)<:LF:>`

**Comment by kazk** [comment] 2018-03-22 01:54
CoffeeScript kata that just wraps JavaScript with backticks.
These are broken for a while. See https://github.com/Codewars/codewars-runner-cli/issues/406

- [Check and Mate?](https://codewars.com/kata/52fcc820f7214727bc0004b7) with coffeescript
- [Exercise in Summing](https://codewars.com/kata/52cd0d600707d0abcd0003eb) with coffeescript
- [Fancy Schmancy Sort](https://codewars.com/kata/53006ec8c7c0f4f5e00002c3) with coffeescript
- [Friday the 13ths](https://codewars.com/kata/540954232a3259755d000039) with coffeescript
- [IP Address to Number](https://codewars.com/kata/541a354c39c5efa5fa001372) with coffeescript
- [NATO Phonetic Alphabet](https://codewars.com/kata/54530f75699b53e558002076) with coffeescript
- [Node.js Async I/O](https://codewars.com/kata/542106e2dda52658bf00001a) with coffeescript
- [Number-like counter](https://codewars.com/kata/5313b713bb244a0eb20001fe) with coffeescript
- [Pentabonacci](https://codewars.com/kata/55c9172ee4bb15af9000005d) with coffeescript
- [Point in Polygon](https://codewars.com/kata/530265044b7e23379d00076a) with coffeescript
- [Recursive reverse string](https://codewars.com/kata/536a9f94021a76ef0f00052f) with coffeescript
- [Rotate Array (JS)](https://codewars.com/kata/54f8b0c7a58bce9db6000dc4) with coffeescript
- [Streams - endless arrays](https://codewars.com/kata/52744341faf5480173000bc7) with coffeescript
- [Title Case](https://codewars.com/kata/5202ef17a402dd033c000009) with coffeescript
- [Topological Sort](https://codewars.com/kata/55f10facf351f5e236000014) with coffeescript
- [Type Checking](https://codewars.com/kata/54149054c1f3a6675b0009c2) with coffeescript

**Comment by kazk** [comment] 2018-03-22 01:58
[mkdir -p](https://codewars.com/kata/53e248c9af0d91a45b000e71) has a test case that tries to create '/usr/share/man/man1'. This will now fail with `EACCESS: permission denied`.
```
<ERROR::>Error: EACCES: permission denied, mkdir '/usr/share/man/man1'
```
I think this used to work because the directory existed.

**Comment by anter69** [comment] 2018-04-03 10:34
Another FizzBuzz: https://www.codewars.com/kata/multiples/ 

Also, #1342 should be part of this issue (although most of those katas are now retired)

**Comment by Voileexperiments** [comment] 2018-04-06 05:26
@kazk I've mostly fixed the katas you've listed above for those I can.

The problem is: Most of those Python katas are passing through a global object through user code and test fixture (and sometimes preloaded too) and do things on them. Because concatenation is not used anymore there is no way to pass any kind of global variables around *and have changes reflected on all sides*.

**Comment by kazk** [comment] 2018-04-06 07:24
Thanks @Voileexperiments!

@Bubbler-4 do you know any workarounds for global states? Maybe `import setup` (instead of `from setup import *`) and mutate `setup.shared_variable`?

**Comment by Voileexperiments** [comment] 2018-04-06 08:38
@kazk The current problem with [Recursive Replication](https://codewars.com/kata/57547f9182655569ab0008c4) and [Recursive reverse string](https://codewars.com/kata/536a9f94021a76ef0f00052f) is actually still the global scope problem: The tests try to patch the user solution function to include a counter. But since the reference to the user function *within its code* is not pointing to the one in global space anymore, the patching breaks and the counter is always `1`.

Also I've just fixed [Lexicographic Permutations](https://www.codewars.com/kata/55baa55cf332e67eb000000a) (Just came out a fix myself): I deleted `modules['itertools']` in Preloaded. Users trying to import `itertools` will still fail the tests.

**Comment by kazk** [comment] 2018-04-07 06:25
Retired the following:

- [Regular Expression - Check if divisible by 0b101 (5)](https://www.codewars.com/kata/regular-expression-check-if-divisible-by-0b101-5)
- [addition function problem](https://codewars.com/kata/52f5f8757c461de6310001e8)

**Comment by Bubbler-4** [comment] 2018-04-07 07:11
> Because concatenation is not used anymore there is no way to pass any kind of global variables around *and have changes reflected on all sides*.

[I think the way @kazk mentioned is a possible workaround for it.](https://www.codewars.com/kumite/5ac865de52ea7ef42f000072?sel=5ac865de52ea7ef42f000072)

The idea is to mutate the *module object* directly so that the loaded modules can see its own scope changed. `import x` reveals a module object named `x` which acts as a "scope" for the inner objects. Mutating `x.y` then makes the change to `y` visible inside the module `x`.

**Comment by Voileexperiments** [comment] 2018-04-08 15:45
https://www.codewars.com/kata/hypercube-lists

`typing` is not available in the new runner anymore?

**Comment by kazk** [comment] 2018-04-08 17:32
`typing` was introduced in Python 3.5 as far as I know. Sometimes Codewars has incorrect Python version associated with the kata. It should be available if 3.6 is specified.

**Comment by Voileexperiments** [comment] 2018-04-08 17:34
Well, but as far as I know:

- Python 3.6 was not available for *a year*
- It used to work before the new runner (that's why there's one solve)

So I guess that means the previous Python 3.4 version somehow has `typing`?

**Comment by kazk** [comment] 2018-04-08 17:48
I just checked the log and the request has `languageVersion` set to `3.x` meaning `3.4` at the moment.

> So I guess that means the previous Python 3.4 version somehow has `typing`?

That might be possible. The old runner's environment was not isolated well causing lots of issues. The kata should be republished with language version set to 3.6.

**Comment by kazk** [comment] 2018-04-08 20:09
It can't be republished with Python 3.6 at the moment because it sets number `3.6` as version number instead of string `"3.6"` :expressionless:

**Comment by anter69** [comment] 2018-04-13 10:25
Happy numbers:
https://www.codewars.com/kata/happy-numbers-5 (js)
https://www.codewars.com/kata/happy-numbers-6 (haskell, python)
(should be merged?)

betas:
https://www.codewars.com/kata/happy-numbers-3
https://www.codewars.com/kata/happy-numbers-4

drafts (if they matter):
https://www.codewars.com/kata/happy-numbers
https://www.codewars.com/kata/happy-numbers-1

**Comment by Voileexperiments** [comment] 2018-04-23 18:44
@kazk someone reported that the Rust version of [Boolfuck Interpreter is broken under 1.25](https://www.codewars.com/kata/5861487fdb20cff3ab000030) due to unused import, and I fiddled with the code for a long time and didn't come up with a solution (Rust is not my thing ;-)). Can you please take a look?

**Comment by kazk** [comment] 2018-04-23 19:54
Yeah, I'll take a look.

Just for the record, Rust 1.25 is not always compatible with contents written for Rust 1.15 on Codewars. If it was, then we didn't have to wait for the new runner to add it.
I don't know if it's possible to make it work in both versions. I recently learned that Codewars doesn't allow multiple language versions to coexist. This limitation comes from how Codewars stores kata in the database. Languages like JS and Python works because the same code can be used across versions.

**Comment by kazk** [comment] 2018-04-23 21:00
I made that one work with 1.25 and dropped 1.15.1 support. Existing solutions should work as long as it's not using deprecated stuff.

**Comment by Blind4Basics** [comment] 2018-04-26 12:03
strong suspicion of a retirement required: https://www.codewars.com/kata/5452113c699b538c18000b01/discuss

in java at least, this kata is full of shit. It actually test almost nothing (and I don't even talk about the number of tests... See the issue I posted)

**Comment by Voileexperiments** [comment] 2018-04-26 12:05
@Blind4Basics Nah, it's just the Java version that's completely bogus. The translator is long gone so *someone* will have to rewrite the Java version (or nuke it, but only author can do that).

**Comment by Blind4Basics** [comment] 2018-04-28 23:25
https://www.codewars.com/kata/55c353487fe3cc80660001d4

This one is just bullshit: description lacking almost everything, 5 tests only, the "only" way to pass the tests is to implement something that would NEVER be a good idea on the field.... One of the poorest experience a warrior could encounter on CW...

**Comment by kazk** [comment] 2018-04-30 07:32
Yeah, I'll fix it soon.

**Comment by kazk** [comment] 2018-04-30 07:40
Fixed. The auto upgrade script shouldn't have enabled Ruby 2.5 with warning printed to `stderr` :/

**Comment by Voileexperiments** [comment] 2018-04-30 08:02
Can we instead collect all the Ruby versions that has warning printed to `stderr`? Because this is a mild issue (like `xrange`/`range` for Python 2/3) and is easily fixable.

**Comment by Voileexperiments** [comment] 2018-06-05 09:51
Something I just recalled: https://www.codewars.com/kata/data-types-a-la-carte-fork was a fork (aka with the exact same content) of https://www.codewars.com/kata/data-types-a-la-carte which used to be broken a long, long time because we used to couldn't edit approved katas. Since the latter has already been fixed, the former should be retired.

**Comment by Paradoxial-Name** [comment] 2018-06-06 18:29
This has vote ranking of 32% only and has been inactive for over 2 years and was published 4 years ago : 

https://www.codewars.com/kata/binary/discuss/javascript

I think this should be retired. 

---

This has vote ranking 0% of 3 (is not retired for some reason) has been inactive for 3 years and was published 4 years ago : 

https://www.codewars.com/kata/inverse-function

Probably needs to be retired now. 

---

This has 57% vote ranking, has been inactive for 4 years and was published 4 years ago.

https://www.codewars.com/kata/n-queen-problem/javascript

This will now be a duplicate to Kata published after that. Needs to be retired

---

This has 50% vote ranking, inactive for 3 years and was published 4 years ago 

https://www.codewars.com/kata/simple-bbcode-parser/discuss/javascript

Probably best to put it to sleep now. 

---

Great Kata, but duplicate of a million Kata's by now. Inactive for 3 years and was published 4 years ago 

https://www.codewars.com/kata/fool-me-once-jokes-on-you-fool-me-twice-jokes-on-me-fool-me-thrice-fibonacci/discuss/javascript

No more fibonacci Kata's are required. My vote is on retire

**Comment by hobovsky** [comment] 2019-01-03 20:30
- [Maximum subarray sum](https://www.codewars.com/kata/54521e9ec8e60bc4de000d6c) - might stay as it already has 6 language versions and not that many unresolved issues.
- [Maximum Contiguous sum](https://www.codewars.com/kata/52f4261c95d6bff39a003096) - only JS version, possible to copy/paste solution for above kata and just change the function name. IMO candidate to delete.

**Comment by kazk** [comment] 2019-01-28 03:57
For duplicates, please contribute to https://github.com/Codewars/codewars.com/wiki/List-of-Possible-Duplicate-Kata instead of commenting here.

**Comment by kazk** [comment] 2021-05-07 00:35
Closing because we now have <https://github.com/codewars/content-issues>.

**Closed by kazk** 2021-05-07 00:35 UTC
Labels: area/kata-qa, help wanted, kind/discussion
