### ISSUE TITLE
What I get when trying to save (or publish) a translation

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#1608] opened 2018-10-24 15:07 UTC
Saving a translation is most often very very very slow and often I get that:

![cw](https://user-images.githubusercontent.com/12381126/47440727-0badfa80-d7af-11e8-99b7-c7bb67a658a5.jpg)

All tabs are emptied after "SAVE".

**Comment by kazk** [comment] 2018-11-03 01:40
I'm guessing you get this error most often because of the number of languages your kata supports.
Codewars' database is highly inefficient with many embedded documents and it's probably taking too long to gather the information needed to show that page when the number of languages is high.

I've made small optimizations this week, are you still getting this?

**Comment by kazk** [comment] 2020-07-28 03:15
Closing because it's not reproducible. Maybe related to https://github.com/codewars/codewars.com/issues/2017#issuecomment-607512316

**Closed by kazk** 2020-07-28 03:15 UTC
Labels: area/db, area/translation, kind/bug, unreproducible
