### ISSUE TITLE
Typescript translation

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#473] opened 2016-07-23 07:57 UTC
1) When I publish a Typescript translation the first two lines of "Example Test Cases" are modified in the following manner 

```
/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" />
/// <reference path="/runner/typings/main/ambient/chai/index.d.ts" />
```

become

```
/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" ></reference>
/// <reference path="/runner/typings/main/ambient/chai/index.d.ts" ></reference>
```

With that transformation the Codewarrior who wants to "Run" the tests gets an error.

2) In description it was impossible to use examples with ```Typescript. It was replaced long ago by "jscript" and later by ... nothing. Has it been corrected? See issue: #411, #426.

**Comment by jhoffner** [comment] 2016-07-28 15:36
This is a duplicate of #361

**Comment by g964** [comment] 2016-08-02 12:37
Nothing has changed  for Typescript translation. When I try to publish I get
```
 ../tmp/typescript11672-17-100lfo6.k3xvszto6r/spec.ts(1,1): error TS1084: Invalid 'reference' directive syntax.
../tmp/typescript11672-17-100lfo6.k3xvszto6r/spec.ts(2,1): error TS1084: Invalid 'reference' directive syntax.  

/runner/lib/util.js:36
                    else throw error;
                         ^

Error: Command failed: tsc --module commonjs /tmp/typescript11672-17-100lfo6.k3xvszto6r/spec.ts

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by kazk** [comment] 2018-04-19 07:38
Same as #593. The new runner doesn't need it so you can remove them.

**Closed by kazk** 2018-04-19 07:38 UTC
Labels: duplicate, high priority, kind/bug
