### ISSUE TITLE
Characters do not show in a code block in a comment

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1798] opened 2019-04-18 09:31 UTC
The title should be self-explanatory. [Link to the comment](https://www.codewars.com/kata/521c2db8ddc89b9b7a0000c1/discuss#5cb84126459a3300250131d4).

![image](https://user-images.githubusercontent.com/31668662/56351144-19c85b00-61d5-11e9-836f-3913697a5bc9.png)

**Comment by kazk** [comment] 2019-04-18 17:44
Looks like highlightjs is doing something :( I can't reproduce this with Marked by itself. I'll look into it.

**Comment by FArekkusu** [comment] 2020-02-11 20:25
I've just stumbled upon this comment, and it looks correct. Perhaps, this issue could be closed until any similar bugs show up.

**Comment by kazk** [comment] 2020-02-11 21:22
Thanks for letting me know. highlightjs was updated to fix Fortran (https://github.com/Codewars/codewars.com/issues/1436#issuecomment-554595325) so that might have included the fix for this as well.

**Closed by kazk** 2020-02-11 21:22 UTC
Labels: area/markdown, kind/bug
