### ISSUE TITLE
Duplicate entries in available languages list

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#1531] opened 2018-08-15 15:10 UTC
C++ occurs twice on the list of available languages for this kata: https://www.codewars.com/kata/find-the-parity-outlier . Both versions seem to be identical, but did not check exactly.

![image](https://user-images.githubusercontent.com/23709795/44155620-1429d856-a0ae-11e8-8bc5-4cb74d4c8e7a.png)

**Comment by kazk** [comment] 2018-10-31 18:05
Closing as duplicate of #1189

**Closed by kazk** 2018-10-31 18:05 UTC
Labels: area/db, duplicate, kind/bug
