### ISSUE TITLE
kata called Nim

### ISSUE THREAD

**Issue by marbiru** [Codewars/codewars.com#1263] opened 2017-12-25 14:55 UTC
There is a kata called Nim, whose link is:
https://www.codewars.com/kata/nim
But that link now takes users to the kata-search page for the programming language Nim, instead of taking users to the actual kata 

It seems that the slug system for katas and languages is the same, and the later addition of a language by the same name overrode the link for the previously-written kata. It's possible that this problem exists for other kata as well, though possibly this is the only example.

This is not a very high-priority issue, just wanted to pass it along.

**Comment by kazk** [comment] 2017-12-25 18:53
Closing as duplicate of https://github.com/Codewars/codewars.com/issues/1086

**Closed by kazk** 2017-12-25 18:53 UTC
Labels: duplicate

**Comment by marbiru** [comment] 2017-12-25 18:58
ah, my bad, thanks!
