### ISSUE TITLE
Approve Translation button doesn't work

### ISSUE THREAD

**Issue by kittyj27** [Codewars/codewars.com#1389] opened 2018-04-17 14:32 UTC
When trying to approve a translation, the site pops up asking you to confirm if you're sure, but on selecting yes it closes the popup but doesn't do anything else

**Comment by DonaldKellett** [comment] 2018-04-17 14:42
Translation approval *silently* fails if you did not author the Kata but are the author of said translation.  Furthermore, even if you are not the author of the translation, translation approval will still *silently* fail if the Kata author has been active this month and the translation is less than a week old.

Not the desired behavior, I know, but known and perfectly normal.  Feel free to inform CW though if the conditions I mentioned above are not met but the translation approval still silently fails :smile:

**Comment by kittyj27** [comment] 2018-04-17 14:54
Thanks. It will be because the translation in question is less than a week old. Still a bug though, and still incredibly annoying, especially if you're not aware of this behaviour :)

**Comment by kittyj27** [comment] 2018-04-17 14:56
Actually, it says the translation in question is a week old. So I'm not sure.

**Comment by anter69** [comment] 2018-06-05 20:42
Same as #1116 and #1093

**Comment by kazk** [comment] 2018-06-05 21:11
Closing as duplicate of #1093

**Closed by kazk** 2018-06-05 21:11 UTC
