### ISSUE TITLE
Suggest to add a filter, solved/not-solved by specific language

### ISSUE THREAD

**Issue by ekailia** [Codewars/codewars.com#887] opened 2017-04-11 03:28 UTC
In the list of Kata, there are ticks before some headings, saying "You have already solved this kata".

They were solved by some languages that I already know, But I am looking for Kata to practice a new language. I am not able to distinguish if a kata is solved by **which language**.

Suggest to add a filter against specific language. For example, I'd like to select Kata that have not been solved with Haskell.

**Comment by kazk** [comment] 2017-04-11 04:57
Possible duplicate of #790 which requests to filter by currently selected language.

**Comment by kazk** [comment] 2018-01-06 19:00
Closing as duplicate of #790

**Closed by kazk** 2018-01-06 19:00 UTC
Labels: area/search, area/ux, enhancement
