### ISSUE TITLE
Handling duplicate katas: a "Duplicate of..." flag

### ISSUE THREAD

**Issue by MMMAAANNN** [codewars/codewars.com#128] opened 2015-07-15 11:15 UTC
There are certain programming exercises that are annoyingly popular and they tend to appear as new katas over and over again, especially if published by newbies. Some examples may include palindromes, fibonacci, factorials etc. When I was a newbie, I wrote almost a duplicate myself.

There is a dilemma what to do with such katas. In most cases, those duplicates are not completely equivalent. I see several options:

1) Merge such katas into one, re-formulating the description accordingly. This can be complicated, as functions may have different names, some solutions may become broken, etc. So this is hardly a good way out, at least not an easy way.

2) Flag all similar katas that are almost equivalent as duplicates. And for katas that have this flag, do not add progress and honour when warrior already solved the same kata in the same language. (or add only half honour).

Now for option 2, there can be a question of what we consider 'almost equivalent'. My suggestion would be to consider kata X equivalent to kata Y for a certain user if user's solution published for X fully passes all tests for kata Y (please note that the opposite may not be true, i.e. there can be a situation where kata X is equivalent to Y, but not vice versa).

The issue of different function names is easily manageable in this case. There can, however, be another issue with different order of arguments - for this case, switching the order of arguments up to a certain number of them (e.g. 3) can be attempted.

Also, such duplicate katas should not reside as beta forever, as this generates a lot of false honour (especially for the author of such kata, which is nonsense - doing an easy duplicate kata brings more honour than doing an unique hard kata). Once this flag is put on a beta kata, this should be brought to the attention of a moderator, and he should make a decision and retire the kata if appropriate.

**Comment by jhoffner** [comment] 2015-07-15 16:18
We have the ability to "retire" a kata, which takes it out of the catalog. It is a start but the system needs to be fleshed out a little more. The problem is that we have a lot of kata with issues and there needs to be a special flag so that admins will take notice so that we, as you said, take it out of beta faster.

**Comment by jhoffner** [comment] 2015-07-15 16:20
I'm thinking a quick fix for this is to just check if the word "duplicate" exists in a comment that is an issue. If it does, then a message can be sent into one of the teams slack channels for a quicker response.

**Comment by MMMAAANNN** [comment] 2015-07-15 17:02
Well, that may serve as a quick fix for flagging, but what will happen after that? My idea was that flag can automatically modify honour and experience points awarded when solving the kata. But if this is going to send a message to some team, what will that team do? Retire one of the katas? Which one? What if one of the katas is just a part of another one (like with Roman numerals set of katas)?

**Comment by bkaes** [comment] 2015-07-15 18:18
Why don't we simply follow StackOverflow's approach? You can _vote to close_ questions there. Given that Codewars has something similar to reputation, that could be a valid way to handle things.

By the way, I don't really see a problem with your remark:

> The issue of different function names is easily manageable in this case. There can, however, be another issue with different order of arguments - for this case, switching the order of arguments up to a certain number of them (e.g. 3) can be attempted.

The solution-passes-all-given-test should be done by hand either way. A human can see rather easily whether two solutions are isomorphic; any script we can come up with will probably get screwed over by a imaginative user.

**Comment by jhoffner** [comment] 2015-07-15 18:19
Yeah at that point we would just have to decide if the kata really is a duplicate or not, and resolve the issue if it isnt and retire it if it is. When a kata is retired the honor is still kept. Thats fine. So they solved the same kata again with the same solution as another kata. They earn 3 honor for completing a beta kata and hopefully providing us feedback that its the same thing. Beta kata already dont count towards rank progression until they are approved, and 3 honor in the grand scheme of things for the handful of duplicate kata are not going to make a difference - but to try to prevent it will make an already complex system (on the backend) even more complex.

**Comment by MMMAAANNN** [comment] 2015-07-15 18:30
I'm not concerned about the honour people get from solving betas, it is okay with me, just as you said.

But look at how kata sensei honour can be distorted - write a simple duplicate and you get lots of it!

Example:
http://www.codewars.com/kata/palindromes - 163 upvotes, how much honour does it bring?

**Comment by jhoffner** [comment] 2015-07-15 18:43
@MMMAAANNN Right but isnt that large upvote count an issue of it falling through the cracks? If it was a notification in my slack (which I pretty much use for all of my team communication and notifications these days) then I would have seen it within the day that it was marked as a duplicate, which in this case would have been 5 months ago.

Granted this keeps a dependency on me personally as an admin to take care of such things, which more and more I'm trying to find ways of opening this functionality up to power users such as yourself and @bkaes. I'm just thinking quick solution here for the time being.

**Comment by bkaes** [comment] 2015-07-15 18:45
You keep mentioning slack, but that's probably Codewars staff only, right? Or does it have a connection to the "Feedback" tab?

**Comment by jhoffner** [comment] 2015-07-15 21:43
You can give anyone access to a specific channel, so we can include moderators within it. But yeah the Slack channel would mostly be used by Codewars staff. The one issue with public channels in slack is that I think we can only give access to a single channel for free.

**Comment by bkaestner** [comment] 2016-01-11 19:50
Any progress here? [This kata has been approved](http://www.codewars.com/kata/prime/discuss#5693efa80404a3729e000044), although its (beside a type check) a duplicate of [this one](http://www.codewars.com/kata/is-a-number-prime). [This one](http://www.codewars.com/kata/prime-numbers-are-prime/discuss/java) is also a duplicate, where I've posted a duplicate issue 10 months ago.

**Comment by g964** [comment] 2016-01-12 05:14
Another one <http://www.codewars.com/kata/check-if-a-number-is-prime>
Another one <http://www.codewars.com/kata/check-for-prime-numbers>

**Comment by bkaestner** [comment] 2016-01-12 08:04
@g964 Five. There's also an instant method to close questions as duplicates, but I wouldn't recommend that for Codewars.

**Comment by kazk** [comment] 2022-05-27 00:15
Duplicates are now discussed and handled in https://github.com/codewars/content-issues

**Closed by kazk** 2022-05-27 00:15 UTC
Labels: area/kata-qa, kind/feature-request, topic/duplicate-kata
