### ISSUE TITLE
Add additional filter for kata progress

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#333] opened 2016-05-27 07:53 UTC
The current progress filter on katas only provides the following three options:

> - All
> - Katas I have not trained on
> - Katas I have not completed

However, this hinders searching for duplicates. The negations of the latter filters (e.g. katas I **have** completed) would make the search a lot easier.

**Comment by DonaldKellett** [comment] 2016-05-27 09:15
Great suggestion, I have thought about this before.  I understand why Codewars might not have this filter option (as most users just want to complete more Kata to gain rank/honor) but adding this filter option could greatly improve the Kata approval process for Moderators.

**Comment by javatlacati** [comment] 2016-06-09 15:36
[Filter Katas not yet completed](https://codewars.ideas.aha.io/ideas/CW-I-55)

**Comment by javatlacati** [comment] 2016-06-09 15:40
https://codewars.ideas.aha.io/ideas/CW-I-90

**Comment by javatlacati** [comment] 2016-06-09 15:40
[Filter Katas not yet trained on](https://codewars.ideas.aha.io/ideas/CW-I-90)

**Comment by bkaestner** [comment] 2016-06-09 16:01
@javatlacati The joy of #226.

**Comment by javatlacati** [comment] 2016-06-09 16:14
Yup. But since @jhoffner started closing my github issues that were enhacement proposals since they had to be on the ideas site I wanted to help and because who doesn't love to have thousands of notifications with duplicity :smile:

**Comment by jhoffner** [comment] 2016-06-09 16:29
Yeah BTW for clarification why we have the enhancement tag in Github. If the enhancement is for functionality that seems incomplete or broken, but is working as designed, and is a small feature, it can make sense here as an enhancement. However there has been an explosion of issues being logged recently so I was hoping to redirect any "wouldnt it be cool if..." type enhancements out of this list, since A: aha is a better place for tracking votes, B: realistically between all of the bugs, small enhancements and a few important strategic initiatives that we have, I don't have any bandwidth for adding new complex features and this list is starting to get hard to manage. I can only focus on quick wins right now.

**Comment by bdw429s** [comment] 2020-02-12 18:23
@bkaestner The kata search seems to have a "Katas I have completed" option now.  Can this ticket be closed?

**Closed** 2020-02-12 18:59 UTC
Labels: area/search, kind/feature-request
