### ISSUE TITLE
URL hash anchor in kata discourse doesn't work if the comment is a reply

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2121] opened 2020-05-04 02:30 UTC
Example:

Works: https://www.codewars.com/kata/59568be9cc15b57637000054/discuss#5bf49e8cd0253f57ef0002bd

![image](https://user-images.githubusercontent.com/14909989/80932419-e19cb600-8df1-11ea-872a-2adf13586181.png)

Doesn't work: https://www.codewars.com/kata/59568be9cc15b57637000054/discuss#5a933940b1710121fc000101

![image](https://user-images.githubusercontent.com/14909989/80932432-eeb9a500-8df1-11ea-9ff8-f7067b2d63d0.png)

Expected behaviour:

![image](https://user-images.githubusercontent.com/14909989/80932497-3b9d7b80-8df2-11ea-958f-6aef8c36a4ae.png)

**Comment by Voileexperiments** [comment] 2020-05-04 02:35
Also, a hash change in kata discourse triggers a refresh, which is *not* expected behaviour.

**Comment by Voileexperiments** [comment] 2020-05-04 07:20
Related: #2063

**Comment by FArekkusu** [comment] 2020-05-04 07:39
Looks like a duplicate of #2060

**Comment by kazk** [comment] 2020-08-04 18:04
Fixed

**Closed by kazk** 2020-08-04 18:04 UTC
