### ISSUE TITLE
Codewars STDOUT

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#844] opened 2017-02-25 20:17 UTC
Codewars stdout doesn't print part of a string when between < and >

**Comment by kazk** [comment] 2017-02-25 23:24
Which language?
When I was adding Go, I encountered this problem and I had to use a special tag to prevent the output from interpreted as HTML. See [this comment](https://github.com/Codewars/codewars-runner-cli/pull/305#issuecomment-278226045) and the reply.
I'd suggest opening an issue in [codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli). Manually escaping before outputting might work as a workaround for now.

**Comment by kazk** [comment] 2017-02-25 23:34
I think #831 is the same issue in C.
This seems to happen when the character following `<` is `[a-zA-Z]`.

**Comment by dinglemouse2250** [comment] 2017-02-26 04:20
Sounds similar to my #765 too...

**Comment by nomennescio** [comment] 2017-03-09 23:11
There's AT LEAST one Kata that uses this as a feature to display inline images:
https://www.codewars.com/kata/image-processing/c

**Comment by kazk** [comment] 2017-03-09 23:41
HTML output is a feature and there are many kata using it. This issue needs more info, but the renderer does need improvements on checking whether the string contains HTML fragment or not.

The example in #831 is probably mistaking `<em>`.

```
                            <EM[^>]*>
<~1I4T&>9Z0Y6[EH-:*h&<,bD_-$<EM;d=<a<CLh<@lZ/,3(HGC~>
                            ^^^
<~1I4T&>9Z0Y6[EH-:*h&<,bD_-$
```

**Comment by jhoffner** [comment] 2017-03-10 00:17
If you are a kata author running into this issue, you can specifically escape the output by prefixing it with `<LOG:ESC:>`

**Comment by jhoffner** [comment] 2017-04-26 15:27
It was a mistake of the original site design to allow for HTML by default within the log output. As a way to try to deal with that design flaw in a way that is backwards compatible with older content, I'm adding some auto-detection to try to determine if content contains any HTML and if not, it will render the content as text. 

I will be releasing this change today, I already have it up on preview.codewars.com for you guys to test. @g964 @kazk @dinglemouse2250 @dinglemouse2250 @OverZealous @Dan-Nolan I would like to hear your feedback. Here are the basic rules in place. 

#### Basic HTML Detection Regex
`/<[a-z]*( [a-z-]*=.*)*( ?\/)?>/` will be used to auto-detect if HTML is present within the content. It does not require matching closing elements to be present but it does require that all elements and attributes by lower cased. 

#### Already Escaped Detection Regex
Some content has already been created which escapes characters on its own, so we want to render them as HTML. Right now I am using `/(&lt;|&gt;|&#\d{4,6};)/` to detect escaped `<`, `>` and char codes.

#### Passed/Failed/It/Describe statements:
These statements use HTML detection only since char codes may in fact by part of the description and and its not likely that someone has intentionally escaped < or > (though I could be wrong). 

#### Log Output:
For log output (console.log, puts, etc) I am using both HTML and Escape detection


Have I missed anything? Is this a terrible idea? If you guys have any content that you think might be affected by this would you mind testing on preview?

My next step towards this is think of how best to configure a default MIME type for the kata. Once this is determined and implemented, then we would consider all legacy content to be a special "auto-detect" value, where as all future (or updated legacy) content could be specifically set to HTML. 

In the meantime I've also added a HTML log type so now you can use:
`<LOG:HTML:>This code will always be <b>HTML</b>`
`<LOG:ESC:>This code will always be <b>escaped</b>`

> if you decide to use the <LOG> prefixed messages, remember that line breaks need to be replaced with `<:LF:>`

BTW I've also fixed scripts not running and the issue where sometimes encoding characters  would randomly be re-encoded to something else.

**Comment by OverZealous** [comment] 2017-04-26 15:34
I like it in general. It all makes sense to me.

I might suggest adjusting the already escaped test. I'm not sure I'd bother checking for explicit char codes (`&#\d{4,6};`), but you might want to add in `&quot;` and `&amp;` for your already escaped detection.

The "only lowercase HTML" could possibly cause minor issues, but there aren't too many cases where people still type tags in all `<UPPERCASE>`, so I think that's a good choice.

**Comment by Dan-Nolan** [comment] 2017-04-26 16:21
Would this affect markdown parsing? Example Challenge: https://preview.codewars.com/kata/simple-fun-number-1-seats-in-theater/train/javascript
**Preview**:
![image](https://cloud.githubusercontent.com/assets/4423365/25444892/b3f60932-2a7a-11e7-82fd-a813f1d30556.png)
**Production**:
![image](https://cloud.githubusercontent.com/assets/4423365/25444959/defc4222-2a7a-11e7-88bb-344f11be801e.png)

**Comment by OverZealous** [comment] 2017-04-26 16:24
That looks like an issue I've seen on Qualified, I'm guessing CW has the updated markdown parser, too, where it won't render headers without a space between the `#` and the first character.

i.e.: This works:
```
# Hello
```

But this doesn't:

```
#Hello
```

**Comment by jhoffner** [comment] 2017-04-26 16:27
That is caused by how myjinxin2015 likes to setup his markdown, using `- #Header`. I've been manually correcting it as I find them but I need to get a hold of him and ask him to use something like `# Header` instead.

**Comment by Dan-Nolan** [comment] 2017-04-26 16:28
Cool, totally unrelated then. So far I haven't seen it break any content in preview 👍

**Comment by Dan-Nolan** [comment] 2017-04-26 16:31
Actually it looks like my solution is no longer working for Image Processing like @nomennescio mentioned. 
**STDERR**:
```
[eval]:376
   <canvas id="cvs_${displayID}"
    ^
SyntaxError: Unexpected token <
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at 
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```

**Comment by jhoffner** [comment] 2017-04-26 16:35
For the markdown issue, I upgraded markedjs. That seems to be why `- #Header` no longer works. I'll look into image processing (I had just fixed the script issue on that, but due to content size restrictions it looks like the last 2 tests don't render properly)

**Comment by kazk** [comment] 2017-04-26 16:36
Add `&#x[\da-fA-F]+;` for already escaped. And do `&#\d+;` instead. I think the spec allows any number of digits digits.

---

For my opinion about this, I don't think this is *terrible*, but really hard to do this well.

**Comment by Dan-Nolan** [comment] 2017-04-26 16:36
Cool, if it helps it looks like it works when you send it to CodeRunner without ciphered test cases, like within the Kata Editor versus the Kata Trainer

**Comment by kazk** [comment] 2017-04-26 16:40
> Decimal numeric character reference
The ampersand must be followed by a "#" (U+0023) character, followed by one or more ASCII digits, representing a base-ten integer that corresponds to a Unicode code point that is allowed according to the definition below. The digits must then be followed by a ";" (U+003B) character.
>
> Hexadecimal numeric character reference
The ampersand must be followed by a "#" (U+0023) character, which must be followed by either a "x" (U+0078) character or a "X" (U+0058) character, which must then be followed by one or more ASCII hex digits, representing a base-sixteen integer that corresponds to a Unicode code point that is allowed according to the definition below. The digits must then be followed by a ";" (U+003B) character.
> https://www.w3.org/TR/html5/syntax.html#character-references

**Comment by Dan-Nolan** [comment] 2017-04-26 16:44
Looks like Image Processing works on Node v6, for some reason training again reverted it to v0.10 without me realizing.

**Comment by kazk** [comment] 2017-04-26 16:55
I think it's less work in long term to make HTML opt-in. Introduce `<LOG:HTML:>` then escape by default and fix the existing kata that intentionally uses HTML.
Majority of the kata doesn't use HTML and I'm sure there will be lots of edge cases doing HTML detection. Trying to fix all that will be painful.

**Comment by kazk** [comment] 2017-04-26 16:58
I don't know how kata is stored in the database, but is it possible to do HTML detection on them to see the number of affected katas?

**Comment by OverZealous** [comment] 2017-04-26 17:09
That's a good point, if it's only a few dozen kata, we'd be able to scan & fix it once, rather than every time the result is rendered.

The only uncertain aspect to that is some kata (and Qualified challenges) don't necessarily have the raw HTML visible within the code. For example, it might look like this:

```js
var output = '<span';
if(something) { output += ' class="error">' }
output += value
...
```

Or they might only render the solution, which is HTML. So there might not be any HTML at all.

And a third scenario, there might only be HTML rendered if the solution fails (I've written one like that, where failed results are rendered in a `pre` block, but successes are not rendered at all).

**Comment by jhoffner** [comment] 2017-04-26 17:22
Yeah it will be hard to detect like @OverZealous said. We would have to check for things like `.toCharCode` in various different languages. If we stored the output of the reference solution this would be a lot easier. Also adding `<LOG:HTML:>` would have to be manually done per each language, especially since if multi-lines are used we would also need to replace `/n` with `<:LF:>`. Like you said though, its probably not more than 50 kata that are affected.

@kazk I agree though that this is going to be a tricky thing to keep up with. My biggest concern is the poor guy who is trying desperately to do something and can't for the life of him/her figure out why the hell sometimes code is escaped and sometimes it isn't. 

My hope is that we can at least cover the common cases that affect our existing content as a quick stop-gap, then introduce maybe either a preloaded config (i.e. `// @config: mime-type auto-detect`) or output token (ie. `<CONFIG::MIME>auto-detect`), then one by one identify the content that needs this behavior and add those tokens to it, then once those tokens are pretty well added to our content base, switch the default so that auto-detection is no longer the default (`text/plain` would be).

**Comment by kazk** [comment] 2017-04-26 17:39
For Codewars, is it possible to pick one valid and one invalid solution and run to inspect the output? Kind of similar to doing solution invalidation, but not running every solution.

> My biggest concern is the poor guy who is trying desperately to do something and can't for the life of him/her figure out why the hell sometimes code is escaped and sometimes it isn't.

I agree, and this is why I'd prefer not to HTML detect. This poor guy might be doing something unexpected but completely valid.
For the amount of work, I still think it's less even with language variations in *long term*.
But I now see the difficulties detecting :(
If you decide to do HTML detection, I found [is-html](https://www.npmjs.com/package/is-html) doing quick `npm` search. He might also have a package for this problem. 😆

**Comment by kazk** [comment] 2017-04-26 17:52
@jhoffner I don't know if I'm understanding your last paragraph. Is this intended to be temporary and are you planning to gradually shift to defaulting to plain text?

**Comment by jhoffner** [comment] 2017-04-26 18:16
> Is this intended to be temporary and are you planning to gradually shift to defaulting to plain text?

Yes

> is-html

Interesting. The html-tags dependency this package uses would be very helpful. Whitelisting the tags that can be considered html would probably go a long way in preventing false positives. I'll add this in.

**Comment by kazk** [comment] 2017-04-26 18:23
Ok, then I don't see a problem in this approach :+1:

**Comment by dinglemouse2250** [comment] 2017-04-27 12:28
Some random thoughts:

* HTML detection - wondered why only lower case tags detected

* Escapes - I use this one fairly often ```&nbsp;```

* It's not just the Kata/tests that have HTML - sometimes I use HTML tags in my solution for output/debugging even when it was not used by the Kata.

* I'm confused - is all this effort only fix the problem of things between ```<``` and ```>``` not rendering properly because they get mis-interpreted as HTML? (like sometimes happens with "view solution" in discourse comments). If so - maybe it is easier if CW just embeds ```<LOG:ESC:>``` for those few known cases instead of overhead to attempt HTML detect everywhere else.

* Stdout font - A related problem seems a recent change to variable width fonts in the stdout. That ruined a lot of output for tables and pictures drawn with chars for me. I don't want to have to use HTML to enforce the fixed font when it previous did this by default (earlier today I saw it making bad output - now it seems ok again - maybe this is already being modified as I type?)

eof

**Comment by jhoffner** [comment] 2017-04-27 16:06
> wondered why only lower case tags detected

Valid HTML is supposed to be lower-case. From what I've seen everyone so far has used lower-case, and not supporting uppercase may help prevent content that looks like HTML but isn't from getting detected.

> I use this one fairly often &nbsp;

Good point, I'm just going to use `&[a-z]{2,6};` to test for character entities

> is all this effort only fix the problem of things between < and > not rendering properly because they get mis-interpreted as HTML

Yeah pretty much. adding <LOG:ESC>s all over the place is a manual process of adding and I'm trying to get a fix that solves the problem now. We can deprecate auto-detection later once we have cleaned the content up. 

> Stdout font

I've got this fix queued up for today, should already be on preview.

**Comment by Voileexperiments** [comment] 2017-04-28 05:46
The new markdown parser seems to be choking some katas which have descriptions with single line code blocks using 3 backticks because it picks up the whole line as if it's a language while it's not, which result in a parse error. e.g:

https://www.codewars.com/kata/a-simple-music-decoder/

If you enter the train screen it's put to a halt while loading, with error message:

![image](https://cloud.githubusercontent.com/assets/14909989/25515704/fe6e018c-2c18-11e7-8a51-57a52d1c643e.png)

(Incidentally, that kata also has improper headers without spaces between # and the actual text. Goes on to show that how easy it is for someone to write non-conformal markdown!)

**Comment by Voileexperiments** [comment] 2017-04-28 09:31
I found another kata that causes problem to test output:

https://www.codewars.com/kata/calculate-the-function-f-x-for-a-simple-linear-sequence-easy/train/javascript

(Try submitting the code and observe the test output. No errors from console this time but the test comes out completely unformatted.)

**Closed** 2017-04-28 16:10 UTC
Labels: bug, cli

**Comment by jhoffner** [comment] 2017-05-01 21:45
> **Passed/Failed/It/Describe statements:**
These statements use HTML detection only since char codes may in fact by part of the description and and its not likely that someone has intentionally escaped < or > (though I could be wrong).

Update, I've had to change this behavior as it was causing issues with certain content. I believe I had come across other content that needed this behavior but has been broken for a while. 

It makes a lot more sense to not render describe/it blocks as HTML as most typical use cases would be more likely something along the lines of `"should render <b>bold</b>"`.

**Comment by Voileexperiments** [comment] 2017-05-03 05:50
@jhoffner I think you should also update this kumite demonstrating the use of AngularJS on test output you wrote a long time ago:

http://www.codewars.com/kumite/56d7779373b8348def00023b?sel=56d7779373b8348def00023b

**Comment by Voileexperiments** [comment] 2017-05-03 09:23
Another kata that has invalid headers (no whitespaces between `#` and actual text) in the description:

https://www.codewars.com/kata/deficiently-abundant-perfect-amicable-numbers

**Comment by dinglemouse2250** [comment] 2017-05-09 12:16
What's the latest with this HTML tag auto-detect for STDOUT? 

I used to be able to do Java ```System.out.println("<hr>something")``` but today it is just printing the ```<hr>``` as text instead of a horizontal line like it used to and like I want it to.
