### ISSUE TITLE
In the solutions of finished kata does not appear my solution

### ISSUE THREAD

**Issue by KonstantinModin** [Codewars/codewars.com#1975] opened 2019-11-14 18:48 UTC
#### Describe the bug
In the solutions of finished kata does not appear my solution.
In some rare cases when I finish kata, then in solutions I click "My Solutions" but there is no solutions.
If I submit solution for the second time or wait some time it does not help.
But I still can see my solution in my Profile-->Solutions.

#### To Reproduce

1. Solve kata.
2. Click on 'My Solutions' in Solutions
3. Can't see my solution.

#### Expected Behavior

Normally I should see my solution in "solution" section or in "My Solutions" section.

#### Screenshots
![kata](https://user-images.githubusercontent.com/45493372/68886202-05225600-0717-11ea-8da1-d4b2056fefa6.jpg)
![kata2](https://user-images.githubusercontent.com/45493372/68886209-081d4680-0717-11ea-8421-77bb333d8daa.jpg)

#### Contexts

Please complete the following information:

- Codewars username (if account related): [Konstantin%20Modin]
- OS: [Win10 Pro 64]
- Browser: [chrome]
- Browser Version: [78.0.3904.87]

**Comment by kazk** [comment] 2019-11-14 22:55
Closing as duplicate of #1598 and others with the same label.

**Closed by kazk** 2019-11-14 22:55 UTC
Labels: duplicate
