### ISSUE TITLE
I have completed some's excercises but they are still marked as not completed.

### ISSUE THREAD

**Issue by Mateusz-p** [Codewars/codewars.com#1820] opened 2019-05-10 15:10 UTC
I have finished 2 kata's:
"Super Duper Easy" (8kyu - PHP)
"Pre-FizzBuzz Workout #1" (8kyu - PHP)

I have submitted my solution. I can see other solutions, but those 2 kata's are still marked as not completed. I have also completed every other 8kyu kata's with PHP and they are ok (marked as completed).

username: Tersh
OS: Windows 10
Browser version:  Google Chrome 74.0.3729.131 64bit, Firefox Quantum 66.0.5 64bit (I have tried on both browsers, and still my solution passes as correct, then i have submitted my solution, but those kata's are still marked as not completed.)

I also remember that i have changed my nickname on codewars before this bug occured.

**Comment by kazk** [comment] 2019-05-10 18:37
Closing as duplicate of #1739

**Closed by kazk** 2019-05-10 18:37 UTC
Labels: area/search, duplicate, kind/bug

**Comment by kazk** [comment] 2019-05-10 21:23
I've just deployed a fix for #1739. Can you confirm that it's now marked as completed?

**Comment by Mateusz-p** [comment] 2019-05-13 08:38
Yes, it's marked as completed now, thank You. I'm not 100% if I received
points for those 2 kata's, but it's not a big deal for me. I also want to
say that i have changed my email (this is my previous email), but i'm still
receiving messages from Codewars here.

Have a nice day.

pt., 10 maj 2019 o 23:23 kazk <notifications@github.com> napisał(a):
