### ISSUE TITLE
5xx: Server Error after login

### ISSUE THREAD

**Issue by Balkoth** [Codewars/codewars.com#1964] opened 2019-10-31 09:35 UTC
#### Describe the bug
After I login, every page displays 5xx: Server Error. 

I have no issue before login so this must be related to my account.
I tried removing cookies and local storage but the errors are still there when I login again.

Note that this issue is not new, this is at least several months old.

#### Contexts
- Codewars username: Balkoth
- OS: Ubuntu
- Browser: reproduced in Chrome and Firefox

**Comment by kazk** [comment] 2019-11-01 03:11
I've fixed one data issue I found. Can you try again and let me know if that helped?

**Comment by Balkoth** [comment] 2019-11-01 08:57
Thanks for looking into this.
Sadly I still have those errors, even after cleaning cookies and local storage.

**Comment by kazk** [comment] 2019-11-01 21:38
I found the cause. It's the notifications component. Some of the notifications about someone commenting on your solution are failing to look up relevant resources in time. The notification component is loaded on all pages when you're logged in so it's causing to timeout.

I don't know why it's written this way and the code is very inefficient :(
I'll try fixing the underlying issue eventually, but for now I removed the problematic notifications for you so you can at least load the pages.

Can you try again? If this wasn't enough, I'll remove all of the notifications.

**Comment by Balkoth** [comment] 2019-11-01 21:58
It works !! Thanks a lot :)

**Closed** 2019-11-01 23:41 UTC
Labels: area/account, kind/bug
