### ISSUE TITLE
Can't change Kata description due to publishing time out 

### ISSUE THREAD

**Issue by treffynnon** [Codewars/codewars.com#1325] opened 2018-03-14 13:44 UTC
This ticket relates to the following kata: https://www.codewars.com/kata/5701e43f86306a615c001868/

I want to update the description of a kata I wrote to make use of the [markdown language conditional blocks](https://github.com/Codewars/codewars.com/wiki/Markdown-Formatting#optional-section-formatting). Unfortunately, I keep getting:

<img width="646" alt="screen shot 2018-03-14 at 23 40 28" src="https://user-images.githubusercontent.com/65215/37405742-2bea5a60-27e1-11e8-85d5-f703e28cd43e.png">

so I cannot republish the kata with the improved description - please see below for the desired description:

    Given a credit card number we can determine who the issuer/vendor is with a few basic knowns.

    ```if:python
    Complete the function `get_issuer()` that will use the values shown below to determine the card issuer for a given card number. If the number cannot be matched then the function should return the string `Unknown`.
    ```
    ```if-not:python
    Complete the function `getIssuer()` that will use the values shown below to determine the card issuer for a given card number. If the number cannot be matched then the function should return the string `Unknown`.
    ```
    ```if:typescript
    Where `Issuer` is defined with the following enum type.
    ~~~typescript
    enum Issuer {
      VISA = 'VISA',
      AMEX = 'AMEX',
      Mastercard = 'Mastercard',
      Discover = 'Discover',
      Unknown = 'Unknown',
    }
    ~~~
    ```

    ```markdown
    | Card Type  | Begins With          | Number Length |
    |------------|----------------------|---------------|
    | AMEX       | 34 or 37             | 15            |
    | Discover   | 6011                 | 16            |
    | Mastercard | 51, 52, 53, 54 or 55 | 16            |
    | VISA       | 4                    | 13 or 16      |
    ```

    ```if:c,cplusplus
    **C/C++ note:** in C/C++ the input is a numeric string. The return value in C is not freed.
    ```

    ## Examples

    ```if-not:python
    ~~~js
    getIssuer(4111111111111111) == "VISA"
    getIssuer(4111111111111) == "VISA"
    getIssuer(4012888888881881) == "VISA"
    getIssuer(378282246310005) == "AMEX"
    getIssuer(6011111111111117) == "Discover"
    getIssuer(5105105105105100) == "Mastercard"
    getIssuer(5105105105105106) == "Mastercard"
    getIssuer(9111111111111111) == "Unknown"
    ~~~
    ```
    ```if:python
    ~~~py
    get_issuer(4111111111111111) == "VISA"
    get_issuer(4111111111111) == "VISA"
    get_issuer(4012888888881881) == "VISA"
    get_issuer(378282246310005) == "AMEX"
    get_issuer(6011111111111117) == "Discover"
    get_issuer(5105105105105100) == "Mastercard"
    get_issuer(5105105105105106) == "Mastercard"
    get_issuer(9111111111111111) == "Unknown"
    ~~~
    ```

**Comment by anter69** [comment] 2018-03-15 09:06
Try to do the update via https://preview.codewars.com

**Comment by cyril-lemaire** [comment] 2018-03-15 12:59
Had the same problem.
@anter69 updating via the preview worked! That's a good fix until the problem is solved! 👍

**Comment by treffynnon** [comment] 2018-03-15 13:16
Yep, that worked for me too. Think this issue can probably be closed.

**Comment by anter69** [comment] 2018-03-15 13:17
@treffynnon I think you can close it yourself, as you created the issue.

**Closed** 2018-03-15 13:25 UTC
