### ISSUE TITLE
Solution not showing up

### ISSUE THREAD

**Issue by ouroborus** [codewars/codewars.com#2282] opened 2020-12-05 08:27 UTC
I completed [Rummy: Find Lowest Scoring Hand](https://www.codewars.com/kata/5b75aa794eb8801bd0000033) for Python but my answer only shows up in [my profile](https://www.codewars.com/users/ouroborus/completed_solutions) and in the "Compare with your solution" link under each solution in the kata's solution list. Switching to the kata's "My solutions" filter comes up empty.

**Comment by Steffan153** [comment] 2020-12-05 13:55
Duplicate of #33, #41, #691, and #1598.

**Closed by Steffan153** 2020-12-05 13:55 UTC

**Comment by Blind4Basics** [comment] 2020-12-13 13:00
@ouroborus : submit it again, but switching two lines somewhere (comments or spaces won't change anything)

**Comment by hobovsky** [comment] 2020-12-13 13:05
Hi @ouroborus , to answer your questions:

> Have a solution still not showing up after a week with same symptoms as [comment above](https://github.com/codewars/codewars.com/issues/1598#issuecomment-430661558). (Specific details in issue #2282.) From the tickets this sort of thing has been a problem for years. How do I properly report these such that they get fixed and what's the time to wait before reporting them?

Generally, there's no good process established for this yet, but you can report such cases if your solution does not appear after a couple of hours. Your solution is recognized by the system correctly, your points are there, it's just not visible in some places. It can be forced to appear manually, but unfortunately this option is not available yet to moderators. They can see that your solution is invisible, but actual handling has to be performed by admins, who can easily miss such reports. There's a plan to handle this operation out to moderators, so things will be easier to process.

The bug itself used to be much more severe, currently it does not occur very often, but still happens sometimes.

**Comment by hobovsky** [comment] 2020-12-15 11:31
@ouroborus , just to let you know: it should be possible now for moderators to address single cases of such issue manually and force the missing solution to appear. But since you resubmitted your solution to the kata in question, there's nothing to do there anymore.
