### ISSUE TITLE
New API endpoint to get katas

### ISSUE THREAD

**Issue by darthzyklus** [codewars/codewars.com#1708] opened 2019-01-31 12:31 UTC
I'm trying to make a telegram bot to get a number of katas from codewars but there is no such endpoint .

#### Description about the solution I'd like
It would be great if exist an endpoint like /api/v1/code-challenges/ to get a certain number of katas. Also It would be awesome if your can paginate the results or filter them with query parameters like language and kyu.

**Comment by kazk** [comment] 2021-04-09 21:54
Closing as a duplicate of #2302 (This was filed before, but that one has more info.)

**Closed by kazk** 2021-04-09 21:54 UTC
Labels: area/api, duplicate, kind/feature-request
