### ISSUE TITLE
''Failed to update the output theme. Please reload the page.''

### ISSUE THREAD

**Issue by sstanchev94** [codewars/codewars.com#2268] opened 2020-11-13 04:14 UTC
I get this message whenever I open a kata. Reloading the page changes nothing. And if I try to test my code I get another message: ''Failed to connect to the runner. Please reload the page.'' I had no such issue until this morning. I tried using a different browser.. I also tried deleting my cache and all that. Nothing fixes it. I appreciate the help in advance.

**Comment by kazk** [comment] 2020-11-13 04:24
Thanks for reporting. This is caused by a new deployment.
Are you using the light theme? I forgot to test with it and was able to reproduce it.

**Comment by sstanchev94** [comment] 2020-11-13 04:29
No.. I use the default dark theme. But i tried in light theme now.. same problem still there.

**Comment by kazk** [comment] 2020-11-13 04:31
Thanks, I'm unable to reproduce it with the dark theme, but #2269 was also reported so it seems like the connection in general is buggy. I'll close this one because it's a subset of #2269.

**Closed by kazk** 2020-11-13 04:31 UTC
