### ISSUE TITLE
Search for 8 or 7 kyu Clojure kata incorrectly displays 66 results instead of 92

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#325] opened 2016-05-24 12:45 UTC
I was searching for some easy Clojure kata to get warmed up on, and discovered this bug.

**How to reproduce:** Search for [8 or 7 kyu Clojure kata](http://www.codewars.com/kata/search/clojure?q=&r%5B%5D=-8&r%5B%5D=-7).  

**Expected Behavior:** There are 26 [8 kyu Clojure kata](http://www.codewars.com/kata/search/clojure?q=&r%5B%5D=-8) and 66 [7 kyu Clojure kata](http://www.codewars.com/kata/search/clojure?q=&r%5B%5D=-7), so the search for both should display 26 + 66 = 92 results.

**Buggy Behavior:** The heading is (92 kata found) but only the first 66 are displayed.  Since they are ordered from latest to oldest, this means older kata like Multiply and Broken Greetings are not listed even though there is a Clojure translation available.

I am guessing it's probably not a coincidence that there are 66 kata at 7kyu and the search for either 8 or 7 kyu is wrongly limited to 66 kata.  That may be a clue as to what is happening.

**Comment by kazk** [comment] 2019-03-20 06:35
Closing as duplicate of #936.

**Closed by kazk** 2019-03-20 06:35 UTC
Labels: area/search, duplicate, kind/bug
